force-app/main/default/objects/Business_Entity__c/Business_Entity__c.object-meta.xml
<CustomObject>
    <description>Business Entity connected to an Account</description>
    <label>Business Entity</label>
    <nameField>
        <label>Business Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Not being used</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Property__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/Deal_Field_Validations__mdt.object-meta.xml
<CustomObject>
    <label>Deal Field Validation</label>
    <pluralLabel>Deal Field Validations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/FieldLabels__c.field-meta.xml
<CustomField>
    <fullName>FieldLabels__c</fullName>
    <label>Field Labels</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/FieldNames__c.field-meta.xml
<CustomField>
    <fullName>FieldNames__c</fullName>
    <label>Field Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <label>Filter Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/FromStage__c.field-meta.xml
<CustomField>
    <fullName>FromStage__c</fullName>
    <label>From Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved by Committee</fullName>
                <default>true</default>
                <label>Approved by Committee</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Data Tape Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Issue Term Sheet/Order Appraisal</fullName>
            </value>
            <value>
                <fullName>Loan Processing</fullName>
            </value>
            <value>
                <fullName>Matured</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted to Underwriting</fullName>
            </value>
            <value>
                <fullName>Term Sheet Issued</fullName>
            </value>
            <value>
                <fullName>Term Sheet Signed/Deposit Collected</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>UW Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>RecordType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bridge_Loan_Closed_Lost</fullName>
                <default>true</default>
                <label>Bridge_Loan_Closed_Lost</label>
            </value>
            <value>
                <fullName>LOC_Loan</fullName>
            </value>
            <value>
                <fullName>Model_Home_Lease</fullName>
            </value>
            <value>
                <fullName>Single_Asset_Bridge_Loan</fullName>
            </value>
            <value>
                <fullName>Single_Asset_Loan</fullName>
            </value>
            <value>
                <fullName>Term_Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/ToStage__c.field-meta.xml
<CustomField>
    <fullName>ToStage__c</fullName>
    <label>To Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved by Committee</fullName>
                <default>true</default>
                <label>Approved by Committee</label>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Data Tape Received</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Issue Term Sheet/Order Appraisal</fullName>
            </value>
            <value>
                <fullName>Loan Processing</fullName>
            </value>
            <value>
                <fullName>Matured</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted to Underwriting</fullName>
            </value>
            <value>
                <fullName>Term Sheet Issued</fullName>
            </value>
            <value>
                <fullName>Term Sheet Signed/Deposit Collected</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>UW Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Field_Validations__mdt/fields/Validation_Type__c.field-meta.xml
<CustomField>
    <fullName>Validation_Type__c</fullName>
    <label>Validation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required Fields</fullName>
                <default>true</default>
                <label>Required Fields</label>
            </value>
            <value>
                <fullName>Record Exists</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appraisal_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAB Use</description>
    <inlineHelpText>The Appraisal has been ordered and paid for by the Borrower</inlineHelpText>
    <label>Appraisal Ordered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Background_Check_Completed__c.field-meta.xml
<CustomField>
    <fullName>Background_Check_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAB Use</description>
    <inlineHelpText>Background Check has been completed and uploaded to the Deal</inlineHelpText>
    <label>Background Check Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Check_Completed__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAB Use</description>
    <inlineHelpText>The Credit Check has been completed</inlineHelpText>
    <label>Credit Check Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data.  Record Type Developer Name</inlineHelpText>
    <label>Record Type Developer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>IF(  
 CONTAINS(RecordType.DeveloperName, &apos;LOC&apos;),
 &apos;Bridge&apos;,
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Term&apos;), 
 &apos;Term&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Loan&apos;), 
 &apos;Single Asset Rental&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Investor_DSCR&apos;), 
 &apos;Investor DSCR&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Bridge&apos;), 
 &apos;Bridge&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Acquired_Bridge_Loan&apos;), 
 &apos;Acquired Bridge Loan&apos;, 
 &apos;&apos;
 ) 
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Term Use</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>Formula based on the Record Type</description>
    <formula>IF( 
OR(CONTAINS(RecordType.DeveloperName, &quot;No_Renovation&quot;), 
CONTAINS(RecordType.DeveloperName, &quot;LOC&quot;) 
), &quot;Bridge&quot;, 
IF( 
CONTAINS(RecordType.DeveloperName, &quot;Term&quot;), 
&quot;Term&quot;, 
IF(
OR(
CONTAINS(RecordType.DeveloperName, &quot;Bridge_Renovation&quot;),
CONTAINS(RecordType.DeveloperName, &quot;Ground_Up_Construction&quot;)),
&quot;Renovation&quot;,
&quot;&quot;
)
 
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula based on the Record Type</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DealFieldValidationHelper.cls
public without sharing class DealFieldValidationHelper {
  public static Map<String, Map<String, Deal_Field_Validations__mdt>> dealFieldValidationMapRF;
  public static Map<String, Map<String, Deal_Field_Validations__mdt>> dealFieldValidationMapRE;

  public static void compileDFVMap() {
    dealFieldValidationMapRF = new Map<String, Map<String, Deal_Field_Validations__mdt>>();
    dealFieldValidationMapRE = new Map<String, Map<String, Deal_Field_Validations__mdt>>();

    for (Deal_Field_Validations__mdt mdt : [
      SELECT
        ObjectName__c,
        RecordType__c,
        FromStage__c,
        ToStage__c,
        FieldLabels__c,
        FieldNames__c,
        Active__c,
        Validation_Type__c,
        Filter_Criteria__c
      FROM Deal_Field_Validations__mdt
      WHERE Active__c = TRUE
    ]) {
      if (mdt.Active__c || (!mdt.Active__c && Test.isRunningTest())) {
        if (mdt.Validation_Type__c == 'Required Fields') {
          if (
            dealFieldValidationMapRF.containsKey(
              mdt.RecordType__c +
              '|' +
              mdt.ObjectName__c
            )
          ) {
            dealFieldValidationMapRF.get(
                mdt.RecordType__c +
                '|' +
                mdt.ObjectName__c
              )
              .put(mdt.FromStage__c + '~~' + mdt.ToStage__c, mdt);
          } else {
            dealFieldValidationMapRF.put(
              mdt.RecordType__c +
              '|' +
              mdt.ObjectName__c,
              new Map<String, Deal_Field_Validations__mdt>{
                mdt.FromStage__c +
                '~~' +
                mdt.ToStage__c => mdt
              }
            );
          }
        } else if (mdt.Validation_Type__c == 'Record Exists') {
          if (
            dealFieldValidationMapRE.containsKey(
              mdt.RecordType__c +
              '|' +
              mdt.ObjectName__c
            )
          ) {
            dealFieldValidationMapRE.get(
                mdt.RecordType__c +
                '|' +
                mdt.ObjectName__c
              )
              .put(mdt.FromStage__c + '~~' + mdt.ToStage__c, mdt);
          } else {
            dealFieldValidationMapRE.put(
              mdt.RecordType__c +
              '|' +
              mdt.ObjectName__c,
              new Map<String, Deal_Field_Validations__mdt>{
                mdt.FromStage__c +
                '~~' +
                mdt.ToStage__c => mdt
              }
            );
          }
        }
      }
    }
  }

  public static String validateDeals(
    Map<Id, Opportunity> oldDealMap,
    Map<Id, Opportunity> newDealMap,
    Map<Id, List<Property__c>> dealPropertyMap,
    Map<Id, List<Business_Entity__c>> businessEntityMap,
    Map<Id, List<Deal_Document__c>> dealDocumentMap
  ) {
    //String errorMsg = '';

    if (dealFieldValidationMapRF == null || dealFieldValidationMapRE == null) {
      compileDFVMap();
    }

    // system.debug(JSON.serialize(dealFieldValidationMap));
    String invalidDealId = '';
    String errorMsg = '';
    String returnVal = '';
    for (Opportunity deal : newDealMap.values()) {
      String dealId = deal.Id;
      // system.debug(deal.StageName);
      // system.debug(oldDealMap.get(deal.Id).StageName);

      // system.debug(
      //   String.isNotBlank(invalidDealId) &&
      //   deal.StageName != oldDealMap.get(deal.Id).StageName
      // );

      String recordType = deal.Record_Type_Name__c;
      String stageName = deal.StageName;
      String oldStageName = oldDealMap.get(deal.Id).StageName;

      system.debug('validator');
      system.debug(recordType);
      system.debug(stageName);
      system.debug(oldStageName);

      if (String.isBlank(invalidDealId) && stageName != oldStageName) {
        String initialRecordTypeDealKey = recordType + '|Deal';
        String initialRecordTypePropertyKey = recordType + '|Property';
        String initialRecordTypeBusinessEntityKey =
          recordType + '|Business Entity';

        String initialRecordTypeDealDocument = recordType + '|Deal_Document__c';
        String stageNameChangeKey = oldStageName + '~~' + stageName;
        system.debug(
          'String.isBlank(invalidDealId)==' + String.isBlank(invalidDealId)
        );
        system.debug('initialRecordTypeDealKey' + initialRecordTypeDealKey);
        system.debug(
          'dealFieldValidationMapRF.containsKey(initialRecordTypeDealKey)==' +
          dealFieldValidationMapRF.containsKey(initialRecordTypeDealKey)
        );
        system.debug('stageNameChangeKey==' + stageNameChangeKey);
        system.debug('dealFieldValidationMapRF==' + dealFieldValidationMapRF);
        system.debug('initialRecordTypeDealKey==' + initialRecordTypeDealKey);
        system.debug('stageNameChangeKey==' + stageNameChangeKey);
        if (
          String.isBlank(invalidDealId) &&
          dealFieldValidationMapRF.containsKey(initialRecordTypeDealKey) &&
          dealFieldValidationMapRF.get(initialRecordTypeDealKey)
            .containsKey(stageNameChangeKey)
        ) {
          Deal_Field_Validations__mdt fieldValidation = dealFieldValidationMapRF.get(
              initialRecordTypeDealKey
            )
            .get(stageNameChangeKey);
          system.debug('validateFields deal');
          errorMsg = validateFields(fieldValidation, deal);

          if (String.isNotBlank(errorMsg)) {
            invalidDealId = dealId;
          }
        }
        system.debug(
          'String.isBlank(invalidDealId)==' + String.isBlank(invalidDealId)
        );
        system.debug(
          'initialRecordTypePropertyKey==' + initialRecordTypePropertyKey
        );
        system.debug('dealFieldValidationMapRF==' + dealFieldValidationMapRF);
        system.debug(
          'dealFieldValidationMapRF.containsKey(initialRecordTypePropertyKey)==' +
          dealFieldValidationMapRF.containsKey(initialRecordTypePropertyKey)
        );
        system.debug(
          'dealPropertyMap.containsKey(dealId)==' +
          dealPropertyMap.containsKey(dealId)
        );
        system.debug('dealId==' + dealId);
        if (
          String.isBlank(invalidDealId) &&
          dealFieldValidationMapRF.containsKey(initialRecordTypePropertyKey) &&
          dealFieldValidationMapRF.get(initialRecordTypePropertyKey)
            .containsKey(stageNameChangeKey) &&
          dealPropertyMap.containsKey(dealId)
        ) {
          Deal_Field_Validations__mdt fieldValidation = dealFieldValidationMapRF.get(
              initialRecordTypeDealKey
            )
            .get(stageNameChangeKey);

          for (Property__c property : dealPropertyMap.get(dealId)) {
            system.debug('validateFields property');
            errorMsg = validateFields(fieldValidation, property);

            if (String.isNotBlank(errorMsg)) {
              invalidDealId = dealId;
              break;
            }
          }
        }

        if (
          String.isNotBlank(invalidDealId) &&
          dealFieldValidationMapRF.containsKey(
            initialRecordTypeBusinessEntityKey
          ) &&
          dealFieldValidationMapRF.get(initialRecordTypeBusinessEntityKey)
            .containsKey(stageNameChangeKey) &&
          businessEntityMap.containsKey(dealId)
        ) {
          Deal_Field_Validations__mdt fieldValidation = dealFieldValidationMapRF.get(
              initialRecordTypeBusinessEntityKey
            )
            .get(stageNameChangeKey);

          for (
            Business_Entity__c businessEntity : businessEntityMap.get(dealId)
          ) {
            system.debug('validateFields businessEntity');
            errorMsg = validateFields(fieldValidation, businessEntity);

            if (String.isNotBlank(errorMsg)) {
              invalidDealId = dealId;
              break;
            }
          }
        }

        if (
          String.isNotBlank(invalidDealId) &&
          dealFieldValidationMapRF.containsKey(initialRecordTypeDealDocument) &&
          dealFieldValidationMapRF.get(initialRecordTypeDealDocument)
            .containsKey(stageNameChangeKey) &&
          dealDocumentMap.containsKey(dealId)
        ) {
          Deal_Field_Validations__mdt fieldValidation = dealFieldValidationMapRF.get(
              initialRecordTypeDealDocument
            )
            .get(stageNameChangeKey);

          for (Deal_Document__c dealDoc : dealDocumentMap.get(dealId)) {
            system.debug('validateFields businessEntity');
            errorMsg = validateFields(fieldValidation, dealDoc);

            if (String.isNotBlank(errorMsg)) {
              invalidDealId = dealId;
              break;
            }
          }
        }

        if (
          String.isBlank(invalidDealId) &&
          dealFieldValidationMapRE.containsKey(initialRecordTypeDealDocument) &&
          dealFieldValidationMapRE.get(initialRecordTypeDealDocument)
            .containsKey(stageNameChangeKey)
        ) {
          Deal_Field_Validations__mdt fieldValidation = dealFieldValidationMapRE.get(
              initialRecordTypeDealDocument
            )
            .get(stageNameChangeKey);

          List<Deal_Document__c> dealDocs = dealDocumentMap.get(dealId);

          system.debug(dealDocs);
          system.debug('in record exists');

          errorMsg = validateRecordExists(
            fieldValidation,
            dealDocs,
            'Deal Document'
          );

          if (String.isNotBlank(errorMsg)) {
            invalidDealId = dealId;
            break;
          }
        }
      }
    }

    if (String.isNotBlank(invalidDealId)) {
      returnVal = errorMsg = invalidDealId + '~~' + errorMsg;
    }

    return returnVal;
  }

  public static String validateRecordExists(
    Deal_Field_Validations__mdt mtdt,
    List<Sobject> records,
    String sobjectType
  ) {
    String errorMsg = '';

    try {
      List<String> filterCriterias = String.isNotBlank(mtdt.Filter_Criteria__c)
        ? ((String) mtdt.Filter_Criteria__c).split(',')
        : new List<String>();

      // String allCriteriasValidated = true;

      system.debug('--filter criterias--');
      system.debug(filterCriterias);

      for (String criteria : filterCriterias) {
        List<String> criteriaSplit = criteria.split('=');
        String fieldName = criteriaSplit[0];
        String fieldValue = criteriaSplit[1];

        system.debug(fieldName);
        system.debug(fieldValue);

        Boolean criteriaValidated = false;

        system.debug(records);

        if (records != null) {
          for (Sobject record : records) {
            system.debug('record value');
            system.debug(record.get(fieldName));

            if ((String) record.get(fieldName) == fieldValue) {
              criteriaValidated = true;
            }
          }
        }

        system.debug(criteriaValidated);
        if (!criteriaValidated) {
          // allCriteriasValidated = false;

          errorMsg += fieldValue + ' ' + sobjectType + ' is missing. ';
        }

        system.debug('--------');
      }

      return errorMsg;
    } catch (Exception ex) {
      system.debug('Error ==>' + ex.getMessage());
      system.debug('Error ==>' + ex.getLineNumber());
      system.debug('Error ==>' + ex.getStacktraceString());
      return 'Error Occurred';
    }
  }

  public static string validateFields(
    Deal_Field_Validations__mdt mtdt,
    Sobject sobj
  ) {
    system.debug('sobj==' + sobj);
    String errorMsg = '';

    try {
      String objectname = String.valueOf(mtdt.ObjectName__c);
      system.debug('INSIDE validateDealFields' + objectname);
      if (objectname == 'Deal') {
        objectname = 'Opportunity';
      }
      List<String> fieldLabels = !String.isEmpty(mtdt.FieldLabels__c)
        ? ((String) mtdt.FieldLabels__c).split(',')
        : new List<String>();
      System.debug(
        'fieldLabels size: ' +
        fieldLabels.size() +
        ' , ' +
        fieldLabels
      );

      List<String> fieldNames = !String.isEmpty(mtdt.FieldNames__c)
        ? ((String) mtdt.FieldNames__c).split(',')
        : new List<String>();
      System.debug(
        'fieldNames szie: ' +
        fieldNames.size() +
        ' , ' +
        fieldNames
      );

      if (
        fieldLabels.size() > 0 &&
        fieldNames.size() > 0 &&
        fieldLabels.size() == fieldNames.size()
      ) {
        System.debug('Inside fieldLabels and fieldNames if condition....');
        for (String fldName : fieldNames) {
          System.debug(
            'sobj.getSObjectType().getDescribe().getName()=====' +
            sobj.getSObjectType().getDescribe().getName()
          );
          System.debug(
            sobj.getSObjectType().getDescribe().getName() != 'Opportunity'
          );
          //system.debug('String.valueOf(sobj.get(fldName)=='+String.valueOf(sobj.get(fldName)));
          if (fldName.indexOf('__r') > -1) {
            String[] flds = fldName.split('\\.');

            // System.debug('FieldsTest===='+flds[0]+'==='+flds[1]);
            if (sobj.getSObject(flds[0]) != null) {
              if (
                String.isEmpty(
                  String.valueOf(sobj.getSObject(flds[0]).get(flds[1]))
                )
              ) {
                errorMsg = String.isEmpty(errorMsg)
                  ? fieldLabels[fieldNames.indexOf(fldName)]
                  : errorMsg + ', ' + fieldLabels[fieldNames.indexOf(fldName)];
              }
            }
          } else if (
            objectname == sobj.getSObjectType().getDescribe().getName()
          ) {
            if (
              String.isEmpty(String.valueOf(sobj.get(fldName))) ||
              (String.valueOf(fldName) == 'Appraisal_Ordered__c' &&
              String.valueOf(sobj.get(fldName)) != 'true') ||
              (String.valueOf(fldName) == 'Background_Check_Completed__c' &&
              String.valueOf(sobj.get(fldName)) != 'true') ||
              (String.valueOf(fldName) == 'Credit_Check_Completed__c' &&
              String.valueOf(sobj.get(fldName)) != 'true')
            ) {
              System.debug('fldName errorMsg' + fldName);
              errorMsg = String.isEmpty(errorMsg)
                ? fieldLabels[fieldNames.indexOf(fldName)]
                : errorMsg + ', ' + fieldLabels[fieldNames.indexOf(fldName)];
            }
          }
        }
      }
      system.debug('errorMsg ==>' + errorMsg);
      return errorMsg;
    } catch (Exception ex) {
      system.debug('Error ==>' + ex.getMessage());
      system.debug('Error ==>' + ex.getLineNumber());
      system.debug('Error ==>' + ex.getStacktraceString());
      return 'Error Occurred';
    }
  }
}