force-app/main/default/objects/Business_Entity__c/Business_Entity__c.object-meta.xml
<CustomObject>
    <description>Business Entity connected to an Account</description>
    <label>Business Entity</label>
    <nameField>
        <label>Business Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Borrower_Entity__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Borrowing Entity</inlineHelpText>
    <label>Borrower Entity</label>
    <referenceTo>Business_Entity__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Line_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Line_Maturity_Date__c</fullName>
    <description>Bridge Use
Previously - ADDMONTHS(Loan_Effective_Date__c, LOC_Term_Number__c)</description>
    <formula>ADDMONTHS(Loan_Effective_Date__c, 
  VALUE( SUBSTITUTE(TEXT(LOC_Term__c), &quot; Months&quot;, &quot;&quot;)))</formula>
    <inlineHelpText>Loan Effective Date + Term</inlineHelpText>
    <label>Original Loan Maturity date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stated_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Stated_Maturity_Date__c</fullName>
    <description>The Original Stated Loan Level Maturity Date</description>
    <inlineHelpText>The Original Stated Loan Level Maturity Date</inlineHelpText>
    <label>Original Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Yardi_ID__c.field-meta.xml
<CustomField>
    <fullName>Yardi_ID__c</fullName>
    <description>Loan ID used by Accounting and Servicers</description>
    <inlineHelpText>Loan ID used by Accounting and Servicers</inlineHelpText>
    <label>Yardi ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Approved_Advance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Advance_Amount__c</fullName>
    <description>Bridge Use
Previous formula:
IF(Override_Advance_Amount__c = 0, 
        Initial_Disbursement_Remaining__c + Reno_Advance_Amount__c,
    Override_Advance_Amount__c
)</description>
    <formula>IF(OR(
 TEXT(Status__c) = &apos;Active&apos;,
 TEXT(Status__c) = &apos;Sold&apos;,
 TEXT(Status__c) = &apos;Paid Off&apos;),
  Approved_Advance_Amount_Used__c,
Initial_Disbursement_Remaining__c + Reno_Advance_Amount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If the Status is &quot;Pending&quot; or &quot;In Process&quot;, then this will be the Approved Advance Amount for the next Advance.  If the Status is &quot;Active&quot;, then this will be the amount funded.</inlineHelpText>
    <label>Approved Advance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ConstructionManagementLoanId__c.field-meta.xml
<CustomField>
    <fullName>ConstructionManagementLoanId__c</fullName>
    <description>The Land Gorilla Loan ID that coms back from the API</description>
    <externalId>true</externalId>
    <label>Land Gorilla Loan ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Yardi_Id__c.field-meta.xml
<CustomField>
    <fullName>Yardi_Id__c</fullName>
    <description>From Servicer after Accounting assigns value.</description>
    <inlineHelpText>Updated by Statebridge Servicer Integration after on-boarding.</inlineHelpText>
    <label>Yardi ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/Settings__mdt.object-meta.xml
<CustomObject>
    <description>This will give us the ability to enable/disable certain actions/triggers in the system</description>
    <label>Settings</label>
    <pluralLabel>Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Settings__mdt/fields/Enable_LandGorilla_API__c.field-meta.xml
<CustomField>
    <fullName>Enable_LandGorilla_API__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable LandGorilla API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/LandGorilla_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>LandGorilla_Endpoint__c</fullName>
    <label>LandGorilla Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/LandGorilla_Password__c.field-meta.xml
<CustomField>
    <fullName>LandGorilla_Password__c</fullName>
    <label>LandGorilla Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/LandGorilla_Username__c.field-meta.xml
<CustomField>
    <fullName>LandGorilla_Username__c</fullName>
    <label>LandGorilla Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/LandGorllia_ApiName__c.field-meta.xml
<CustomField>
    <fullName>LandGorllia_ApiName__c</fullName>
    <label>LandGorllia ApiName</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LandGorillaAPI.cls
public without sharing class LandGorillaAPI {
  public static final String BASE_URL = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .LandGorilla_Endpoint__c;
  public static final String API_NAME = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .LandGorllia_ApiName__c;
  public static final String USERNAME = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .LandGorilla_Username__c;
  public static final String PASSWORD = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .LandGorilla_Password__c;
  public static final Boolean IS_API_ENABLED = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .Enable_LandGorilla_API__c;

  public class TokenResponse {
    public String id { get; set; }
    public String token { get; set; }
    public DateTime expired { get; set; }
  }

  public class PostResponse {
    public String id { get; set; }
    public String message { get; set; }
  }

  public static TokenResponse currentToken {
    get {
      if (
        !IS_API_ENABLED ||
        String.isEmpty(BASE_URL) ||
        String.isEmpty(API_NAME) ||
        String.isEmpty(USERNAME) ||
        String.isEmpty(PASSWORD)
      ) {
        return null;
      }

      if (
        currentToken != null &&
        currentToken.expired < System.now().dateGmt()
      ) {
        return currentToken;
      }

      return requestToken();
    }
    private set;
  }

  public static TokenResponse requestToken() {
    String token = '';
    HttpRequest req;
    HttpResponse resp;
    String tokenEndpoint = BASE_URL + '/api/token&api_name=' + API_NAME;
    try {
      req = new HttpRequest();
      req.setEndpoint(tokenEndpoint);
      req.setMethod('GET');
      req.setHeader('USER', USERNAME);
      req.setHeader('PASSWORD', PASSWORD);

      String payload = 'api_name=' + API_NAME;

      req.setTimeout(120000);
      Integer statusCode = 200;
      String respBody = '';

      if (!Test.isRunningTest()) {
        resp = new Http().send(req);
        statusCode = resp.getStatusCode();
        respBody = resp.getBody();
        if (statusCode == 200) {
          Map<String, Object> respMap = (Map<String, Object>) JSON.deserializeUntyped(
            respBody
          );
          TokenResponse retVal = new TokenResponse();
          retVal.id = String.valueOf(respMap.get('id'));
          retVal.token = String.valueOf(respMap.get('token'));
          // 2021-09-27 13:44:52
          String dateString = String.valueOf(respMap.get('expired'));
          // Integer year = Integer.valueOf(dateString.substring(0, 4));
          // Integer month = Integer.valueOf(dateString.substring(5, 7));
          // Integer day = Integer.valueOf(dateString.substring(8, 10));
          // Integer hour = Integer.valueOf(dateString.substring(11, 13));
          // Integer minute = Integer.valueOf(dateString.substring(14, 16));
          // Integer second = Integer.valueOf(dateString.substring(17, 19));
          retVal.expired = Datetime.valueOf(dateString);
          System.debug(retVal);
          return retVal;
        } else {
          return null;
        }
      } else {
        TokenResponse respMap = new TokenResponse();
        respMap.id = '1';
        respMap.token = '12345';
        respMap.expired = System.now().addHours(1);
        return respMap;
      }
    } catch (Exception err) {
      System.debug(err.getMessage());
      return null;
    }
  }

  public static void processPropertiesForPostLoan(Set<Id> propertyIds) {
    List<Property__c> props = [
      SELECT
        Id,
        Name,
        City__c,
        ZipCode__c,
        Approved_Advance_Amount__c,
        County__c,
        State__c,
        Yardi_Id__c,
        Deal__r.Borrower_entity__r.Name,
        Deal__r.Original_Line_Maturity_Date__c,
        Deal__r.CloseDate,
        Deal__r.Stated_Maturity_Date__c
      FROM Property__c
      WHERE
        Id = :propertyIds
        AND ((Deal__r.LOC_Loan_Type__c = 'Credit Line'
        AND Deal__r.Product_Sub_Type__c = 'Renovation')
        OR Deal__r.LOC_Loan_Type__c = 'Multifamily/CRE'
        OR (Deal__r.LOC_Loan_Type__c = 'Single Asset (1-4 Unit)'
        AND Deal__r.Product_Sub_Type__c IN ('Renovation', 'Construction'))
        OR (Deal__r.LOC_Loan_Type__c = 'Single Asset (5-10 Unit)'
        AND Deal__r.Product_Sub_Type__c IN ('Renovation', 'Construction'))
        OR Deal__r.LOC_Loan_Type__c = 'Build to Rent')
        AND Deal__r.StageName IN ('Approved by Committee', 'Closed Won')
        AND RecordType.Name IN (
          'Bridge Renovation',
          'Bridge Renovation Special Asset',
          'Ground Up Construction',
          'Ground Up Construction Special Asset'
        )
    ];

    if (props.size() > 0) {
      List<Property__c> updatedProperties = new List<Property__c>();
      for (Property__c prop : props) {
        PostResponse res = postLoan(prop);
        if (res != null && String.isNotBlank(res.id)) {
          updatedProperties.add(
            new Property__c(
              Id = prop.Id,
              ConstructionManagementLoanId__c = res.id
            )
          );
        }
      }

      if (updatedProperties.size() > 0) {
        update updatedProperties;
      }
    }
  }

  public static PostResponse postLoan(Property__c p) {
    if (
      !IS_API_ENABLED ||
      String.isEmpty(BASE_URL) ||
      String.isEmpty(API_NAME) ||
      String.isEmpty(USERNAME) ||
      String.isEmpty(PASSWORD)
    ) {
      return null;
    }

    String postLoanEndpoint = BASE_URL + '/api/clm/loan';
    HttpRequest req;
    HttpResponse resp;
    try {
      TokenResponse tokenData = currentToken;
      String token = tokenData.token;
      PostResponse returnStatement = new PostResponse();
      req = new HttpRequest();
      req.setMethod('POST');
      Map<String, String> headers = new Map<String, String>();
      req.setHeader('Authorization', 'Bearer ' + token);

      req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
      req.setEndpoint(postLoanEndpoint);
      Map<String, String> payload = new Map<String, String>();
      payload.put('Loan File Number', p.Yardi_Id__c);
      // payload.put('Loan Type', 'Commercial');
      // payload.put('Loan Program', 'Test');
      // payload.put('Loan Purpose', 'Purchase');
      // payload.put('Loan Term in Days', '' + (p.Deal__r.CloseDate.daysBetween(p.Deal__r.Original_Line_Maturity_Date__c)));
      // payload.put('Loan Funded Date', String.valueOf(p.Deal__r.CloseDate));
      payload.put('Subject property address', p.Name);
      payload.put('Zip', p.ZipCode__c);
      payload.put('City', p.City__c);
      payload.put('State', p.State__c);
      payload.put('County', p.County__c);
      // payload.put('Borrower First Name', p.Deal__r.Borrower_entity__r.Name.substringBefore(' '));
      // payload.put('Borrower Last Name', p.Deal__r.Borrower_entity__r.Name.substringAfterLast(' '));
      // payload.put('Loan Amount', String.valueOf(p.Approved_Advance_Amount__c));

      // payload.put('Loan File Number', '1234ABC');
      // payload.put('Loan Type', 'Commercial');
      // payload.put('Loan Program', 'Test');
      // payload.put('Loan Purpose', 'Purchase');
      // payload.put('Loan Term in Days', '10950');
      // payload.put('Loan Funded Date', '5/11/2022');
      // payload.put('Subject property address', '1600 Pennsylvania Ave NW');
      // payload.put('Zip', '20500');
      // payload.put('City', 'Washington');
      // payload.put('State', 'DC');
      // payload.put('County', 'DC');
      // payload.put('Borrower First Name', 'John');
      // payload.put('Borrower Last Name', 'Doe');
      // payload.put('Loan Amount', '2000000');

      req.setBody(getBodyString(payload));
      req.setTimeout(120000);

      if (!Test.isRunningTest()) {
        resp = new Http().send(req);
        if (resp.getStatusCode() == 200) {
          String respval = resp.getBody();
          returnStatement = (PostResponse) JSON.deserialize(
            respval,
            PostResponse.class
          );
        } else {
          System.debug(resp.getBody());
        }
      }

      return returnStatement;
    } catch (Exception err) {
      System.debug(err.getMessage() + ' on line ' + err.getLineNumber());
      return null;
    }
  }

  public static String getBodyString(Map<String, String> parameters) {
    String bodyStr = '';
    if (parameters != null) {
      for (String key : parameters.keySet()) {
        bodyStr +=
          key +
          '=' +
          EncodingUtil.urlEncode(parameters.get(key), 'UTF-8') +
          '&';
      }
    }
    return bodyStr;
  }
}