force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Advance_Fee_Total__c.field-meta.xml
<CustomField>
    <fullName>Advance_Fee_Total__c</fullName>
    <formula>Advance_Fee_Subtotal__c + Advance_Fee_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Advance Fee Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Approved_Advance_Amount_Max_Total__c.field-meta.xml
<CustomField>
    <fullName>Approved_Advance_Amount_Max_Total__c</fullName>
    <label>Approved Advance Amount Max Total</label>
    <summarizedField>Property_Advance__c.Approved_Advance_Amount_Max__c</summarizedField>
    <summaryForeignKey>Property_Advance__c.Advance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Broker_Advance_Fee_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Broker_Advance_Fee_Subtotal__c</fullName>
    <description>Bridge Use</description>
    <label>Broker Advance Fee Subtotal</label>
    <summarizedField>Property_Advance__c.Broker_Advance_Fee__c</summarizedField>
    <summaryForeignKey>Property_Advance__c.Advance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Daily_Interest_Rate_Total__c.field-meta.xml
<CustomField>
    <fullName>Daily_Interest_Rate_Total__c</fullName>
    <formula>Daily_Interest_Rate_Subtotal__c + Daily_Interest_Rate_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Daily Interest Rate Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Inspection_Fee_Total__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Fee_Total__c</fullName>
    <formula>Inspection_Fee_Adjustment__c + Inspection_Fee_Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inspection Fee Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Origination_Fee_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee_Subtotal__c</fullName>
    <label>Origination Fee Subtotal</label>
    <summarizedField>Property_Advance__c.Origination_Fee__c</summarizedField>
    <summaryForeignKey>Property_Advance__c.Advance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Advance__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/APN__c.field-meta.xml
<CustomField>
    <fullName>APN__c</fullName>
    <label>APN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Approved_Advance_Amount_Max__c.field-meta.xml
<CustomField>
    <fullName>Approved_Advance_Amount_Max__c</fullName>
    <description>Bridge Use
Previous formula:
IF(Override_Advance_Amount__c = 0, 
        Initial_Disbursement__c + Reno_Advance_Amount__c,
    Override_Advance_Amount__c
)</description>
    <formula>Initial_Disbursement__c + Approved_Renovation_Holdback__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Max that can be funded for the Initial Disbursement and the Renovation Advances</inlineHelpText>
    <label>Approved Advance Amount Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Asset ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Escrow_Agent__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escrow Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties (Escrow Agent)</relationshipLabel>
    <relationshipName>Properties1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Lender_Comments__c.field-meta.xml
<CustomField>
    <fullName>Lender_Comments__c</fullName>
    <label>Lender Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Rehab_Budget__c.field-meta.xml
<CustomField>
    <fullName>Rehab_Budget__c</fullName>
    <description>Bridge Reno Use</description>
    <label>Renovation Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title_Company__c.field-meta.xml
<CustomField>
    <fullName>Title_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Title Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Title_Contact_Name__c</fullName>
    <label>Title Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Yardi_Id__c.field-meta.xml
<CustomField>
    <fullName>Yardi_Id__c</fullName>
    <description>From Servicer after Accounting assigns value.</description>
    <inlineHelpText>Updated by Statebridge Servicer Integration after on-boarding.</inlineHelpText>
    <label>Yardi ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/Property_Advance__c.object-meta.xml
<CustomObject>
    <description>The Individual Property for which a Bridge Advance was made</description>
    <label>Property Advance</label>
    <nameField>
        <label>Property Advance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Approved_Advance_Amount_Max__c.field-meta.xml
<CustomField>
    <fullName>Approved_Advance_Amount_Max__c</fullName>
    <description>The maximum that can be funded for both the Initial Disbursement and Renovation Advances for the life of this loan</description>
    <inlineHelpText>The maximum that can be funded for both the Initial Disbursement and Renovation Advances for the life of this loan</inlineHelpText>
    <label>Approved Advance Amount Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Daily_Interest_Rate_Total__c.field-meta.xml
<CustomField>
    <fullName>Daily_Interest_Rate_Total__c</fullName>
    <formula>IF(AND(
Name == &apos;1&apos;,
 Property__r.Deal__r.RecordType.Name   == &apos;Single Asset Bridge Loan&apos;),
Daily_Interest_Rate__c *  Days_Between_Wire_and_Last_Day_Month__c,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Daily Interest Rate Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Escrow_Agent__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escrow Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Wire__c.field-meta.xml
<CustomField>
    <fullName>Wire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wire</label>
    <referenceTo>Wire__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wire__c/Wire__c.object-meta.xml
<CustomObject>
    <label>Wire</label>
    <nameField>
        <displayFormat>W-{000000000}</displayFormat>
        <label>Wire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Wires</relationshipLabel>
    <relationshipName>Wires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wire__c/fields/Escrow_Agent__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escrow Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wires</relationshipLabel>
    <relationshipName>Wires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wire__c/fields/Wire_Number__c.field-meta.xml
<CustomField>
    <fullName>Wire_Number__c</fullName>
    <label>Wire #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/advancePrint_Extension.cls
public with sharing class advancePrint_Extension {
  public static List<String> OPTIONALFIELDS = new List<String>{
    'Advance_Fee_Total__c',
    'Origination_Fee_Subtotal__c',
    'Broker_Advance_Fee_Subtotal__c',
    'Daily_Interest_Rate_Total__c'
  };
  public Advance__c record { get; set; }
  public List<Property_Advance__c> properties { get; set; }
  public List<Wire__c> wires { get; set; }
  public Boolean approvedAdvanceAmountCondition { get; set; }
  public advancePrint_Extension(
    ApexPages.standardController standardController
  ) {
    this.record = (Advance__c) standardController.getRecord();
    this.approvedAdvanceAmountCondition = false;
    if (record.Id != null) {
      // record = (Advance__c)util.queryRecord(record.Id);
      List<String> propertyFieldsList = new List<String>{
        'Property__r.Asset_ID__c',
        'Wire__r.Wire_Number__c',
        'Property__r.APN__c',
        'Property__r.Name',
        'Property__r.City__c',
        'Property__r.State__c',
        'Property__r.ZipCode__c',
        'Property__r.County__c',
        'Property__r.Rehab_Budget__c',
        'Property__r.Yardi_Id__c',
        'Escrow_Agent__r.Name',
        'Property__r.Title_Company__r.Name',
        'Property__r.Title_Contact_Name__c',
        'Property__r.Title_Company__r.BillingStreet',
        'Property__r.Title_Company__r.BillingCity',
        'Property__r.Title_Company__r.BillingState',
        'Property__r.Title_Company__r.BillingPostalCode',
        'Property__r.Lender_Comments__c',
        'Property__r.Approved_Advance_Amount_Max__c'
      };
      List<String> wireFieldsList = new List<String>{ 'Escrow_Agent__r.Name' };
      properties = (List<Property_Advance__c>) queryChildren(
        'Property_Advance__c',
        propertyFieldsList,
        'Advance__c',
        record.Id
      );
      

      //   system.debug(this.record.Approved_Advance_Amount_Max_Total__c);
      Decimal advanceAmountMaxSum = 0;
      for (Property_Advance__c pAdvance : properties) {
        advanceAmountMaxSum += pAdvance.Property__r.Approved_Advance_Amount_Max__c;
      }
      //   system.debug(advanceAmountMaxSum);
      this.approvedAdvanceAmountCondition =
        advanceAmountMaxSum == this.record.Approved_Advance_Amount_Max_Total__c;
      // query property advances and fields
      wires = (List<Wire__c>) queryChildren(
        'Wire__c',
        wireFieldsList,
        'Advance__c',
        record.Id
      );
    }
  }

  public Integer renoColspan {
    get {
      Integer val = 14;
      List<String> privateOptFields = new List<String>{'Inspection_Fee_Total__c'};
      privateOptFields.addAll(OPTIONALFIELDS);
      for(String field : privateOptFields) {
        if(record.get(field) != null && record.get(field) != 0) {
          val += 1;
        }
      }

      return val;
    } 
    private set;
  }

  public Integer nonRenocolspan { 
    get {
      Integer val = 16;

      if(record != null) {
        for(String field : OPTIONALFIELDS) {
          if(record.get(field) != null && record.get(field) != 0) {
            val += 1;
          }
        }
      }

      return val;
    } 
    private set; }


  public static List<sObject> queryChildren(
    String objectName,
    List<String> additionalFields,
    String lookupField,
    Id recordId
  ) {
    Set<String> fieldNamesSet = util.getAllFieldNamesForObject(objectName);
    List<String> fieldNames = new List<String>();
    fieldNames.addAll(fieldNamesSet);

    String qs = 'SELECT ';
    for (Integer i = 0; i < fieldNames.size(); i++) {
      qs += fieldNames[i];
      if (i < fieldNames.size() - 1) {
        qs += ', ';
      }
    }

    if (additionalFields != null) {
      for (String s : additionalFields) {
        qs += ', ' + s;
      }
    }

    qs +=
      ' FROM ' +
      objectName +
      ' WHERE ' +
      lookupField +
      ' = \'' +
      recordId +
      '\'';

    List<sObject> l = Database.query(qs);

    return l;
  }

  public PageReference goBack() {
    PageReference pg = new PageReference('/' + this.record.Id);
    pg.setRedirect(true);

    return pg;
  }
}