force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Inspection</fullName>
            </value>
            <value>
                <fullName>Pending Inspection Report Revision</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Capital Partner Release</fullName>
            </value>
            <value>
                <fullName>Pending Release</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>Property Details Section</description>
    <label>Property Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Multi-unit (5+)</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
                <default>true</default>
                <label>SFR</label>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Condo - Detached</fullName>
            </value>
            <value>
                <fullName>Condo - High Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Low Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Mid Rise</fullName>
            </value>
            <value>
                <fullName>Condo - NonWarrantable</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>Multi-unit (1-4)</fullName>
                <isActive>false</isActive>
                <label>Multi-unit (1-4)</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
                <isActive>false</isActive>
                <label>Student Housing</label>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
                <isActive>false</isActive>
                <label>Vacation Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/BPO_Appraisal_Firm__c.field-meta.xml
<CustomField>
    <fullName>BPO_Appraisal_Firm__c</fullName>
    <description>Firm of the most recent Appraisal</description>
    <inlineHelpText>Firm of the most recent Appraisal</inlineHelpText>
    <label>Current Appraisal Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interior_Access_POC_Email__c.field-meta.xml
<CustomField>
    <fullName>Interior_Access_POC_Email__c</fullName>
    <description>Email to contact the person/company regarding internal access to this Property</description>
    <inlineHelpText>Email to contact the person/company regarding internal access to this Property</inlineHelpText>
    <label>Interior Access POC Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label># of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <label>Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/Property_Advance__c.object-meta.xml
<CustomObject>
    <description>The Individual Property for which a Bridge Advance was made</description>
    <label>Property Advance</label>
    <nameField>
        <label>Property Advance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <description>Deal Name of the related Advance</description>
    <formula>Advance__r.Deal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Deal Name of the related Advance</inlineHelpText>
    <label>Deal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PropertyTriggerExtensionsTest.cls
@isTest
public with sharing class PropertyTriggerExtensionsTest {
  @TestSetup
  static void makeData() {
    Account a = Test_Helper.createAccount();
    Contact c = Test_Helper.createContact(a);
    Opportunity o = Test_Helper.createBridgeDeal(a, c);
    List<Property__c> properties = new List<Property__c>();
    for (Integer i = 0; i < 10; i++) {
      properties.add(
        new Property__c(
          Deal__c = o.Id,
          Name = i + ' Test',
          Property_Name__c = i + ' Test',
          Property_Type__c = 'SFR',
          Number_of_Units__c = 1,
          Interior_Access_POC_Email__c = 'test@test.com',
          Security_Deposit__c = 800,
          BPO_Appraisal_Firm__c = 'Test',
          Status__c = 'Inactive'
        )
      );
    }
    insert properties;
  }
  @isTest
  public static void testStatusChanges() {
    Opportunity deal = [SELECT Id FROM Opportunity LIMIT 1];
    List<Property__c> props = [
      SELECT Id, Status__c
      FROM Property__c
      WHERE Deal__c = :deal.Id
    ];

    Test.startTest();
    Advance__c adv = new Advance__c(Deal__c = deal.Id);
    insert adv;

    List<Property_Advance__c> padv = new List<Property_Advance__c>{
      new Property_Advance__c(Property__c = props[0].Id, Advance__c = adv.Id),
      new Property_Advance__c(Property__c = props[1].Id, Advance__c = adv.Id)
    };
    insert padv;

    Map<Id, Property__c> oldPropMap = new Map<Id, Property__c>{
      props[0].Id => new Property__c(Id = props[0].Id, Status__c = 'Inactive')
    };
    Map<Id, Property__c> newPropMap = new Map<Id, Property__c>{
      props[0].Id => new Property__c(Id = props[0].Id, Status__c = 'Cancelled')
    };

    PropertyTriggerExtensions.checkStatusChanges(oldPropMap, newPropMap);
    List<Property_Advance__c> padv2 = [
      SELECT Id
      FROM Property_Advance__c
      WHERE Advance__c = :adv.Id
    ];
    System.assertNotEquals(
      padv.size(),
      padv2.size(),
      'Property_Advance__c records were not deleted'
    );

    Map<Id, Property__c> oldPropMap1 = new Map<Id, Property__c>{
      props[1].Id => new Property__c(Id = props[1].Id, Status__c = 'Inactive')
    };
    Map<Id, Property__c> newPropMap1 = new Map<Id, Property__c>{
      props[1].Id => new Property__c(Id = props[1].Id, Status__c = 'Active')
    };
    update newPropMap1.values();
    PropertyTriggerExtensions.checkStatusChanges(oldPropMap1, newPropMap1);
    Map<Id, Advance__c> adv2 = new Map<Id, Advance__c>(
      [SELECT Id, Property_Count__c, Name FROM Advance__c WHERE Id = :adv.Id]
    );
    System.assertEquals(
      '1',
      adv2.values()[0].Name,
      'Advance__c record was not updated'
    );
    Test.stopTest();
  }

  @isTest
  public static void testAdvanceDeletion() {
    Opportunity deal = [SELECT Id FROM Opportunity LIMIT 1];
    List<Property__c> props = [
      SELECT Id, Status__c
      FROM Property__c
      WHERE Deal__c = :deal.Id
      LIMIT 2
    ];
    Test.startTest();
    Advance__c adv = new Advance__c(Deal__c = deal.Id);
    insert adv;
    List<Property_Advance__c> padv = new List<Property_Advance__c>{
      new Property_Advance__c(Property__c = props[0].Id, Advance__c = adv.Id),
      new Property_Advance__c(Property__c = props[1].Id, Advance__c = adv.Id)
    };
    insert padv;

    Map<Id, Advance__c> oldMap = new Map<Id, Advance__c>(
      [SELECT Id, Property_Count__C FROM Advance__c WHERE Id = :adv.Id]
    );

    delete padv;
    Map<Id, Advance__c> newMap = new Map<Id, Advance__c>(
      [SELECT Id, Property_Count__C FROM Advance__c WHERE Id = :adv.Id]
    );

    PropertyTriggerExtensions.checkAdvancesPropertyCount(oldMap, newMap);

    List<Advance__c> advsExpectedEmpty = [
      SELECT Id
      FROM Advance__c
      WHERE Id = :adv.Id
    ];
    System.assertEquals(
      0,
      advsExpectedEmpty.size(),
      'Advance__c record was not deleted'
    );
    Test.stopTest();
  }

  @isTest
  public static void testPropAdvanceStatuses() {
    Opportunity deal = [SELECT Id FROM Opportunity LIMIT 1];
    List<Property__c> props = [
      SELECT Id, Status__c
      FROM Property__c
      WHERE Deal__c = :deal.Id
      LIMIT 2
    ];
    Test.startTest();

    for(Property__c p : props ){ 
        p.Status__c = 'Active';
    }
    update props;

    Advance__c adv = new Advance__c(Deal__c = deal.Id);
    insert adv;
    List<Property_Advance__c> padv = new List<Property_Advance__c>{
      new Property_Advance__c(Property__c = props[0].Id, Advance__c = adv.Id),
      new Property_Advance__c(Property__c = props[1].Id, Advance__c = adv.Id)
    };
    insert padv;

    Map<Id,Property_Advance__c> propAdvMap = new Map<Id, Property_Advance__c>([
        SELECT Id, Advance__c, Property__c FROM Property_Advance__c WHERE Advance__c = :adv.Id
    ]);

    PropertyTriggerExtensions.checkAdvancePropertyStatuses(propAdvMap);
    Advance__c advWithName = [SELECT Id, Name FROM Advance__c WHERE Id = :adv.Id];
    System.assertEquals('1', advWithName.Name, 'Advance__c record was not updated');
    Test.stopTest();
  }

  // @isTest
  // public static void testAdvNameChange() {
  //   Opportunity deal = [SELECT Id FROM Opportunity LIMIT 1];
  //   List<Property__c> props = [
  //     SELECT Id, Status__c
  //     FROM Property__c
  //     WHERE Deal__c = :deal.Id
  //     LIMIT 2
  //   ];
  //   Test.startTest();

  //   Advance__c adv = new Advance__c(Deal__c = deal.Id, Name = 'TBD');
  //   insert adv;
  //   List<Property_Advance__c> padv = new List<Property_Advance__c>{
  //     new Property_Advance__c(Property__c = props[0].Id, Advance__c = adv.Id),
  //     new Property_Advance__c(Property__c = props[1].Id, Advance__c = adv.Id)
  //   };
  //   insert padv;

  //   Map<Id,Advance__c> advMap = new Map<Id, Advance__c>{
  //       adv.Id => new Advance__c(Id = adv.Id, Name = '1')
  //   };

  //   Boolean hasException = false;

  //   try {
  //       PropertyTriggerExtensions.validateAdvanceNames(advMap);
  //   } catch (Exception err) {
  //       hasException = true;
  //   }
  //   System.assertEquals(true, hasException, 'Exception was not thrown');

  //   Test.stopTest();
  // }
}