force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <formula>text( Deal__r.Index__c)</formula>
    <label>Index</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Index_Floor__c.field-meta.xml
<CustomField>
    <fullName>Index_Floor__c</fullName>
    <formula>text( Deal__r.Floor__c )</formula>
    <label>Index Floor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Index_Margin__c.field-meta.xml
<CustomField>
    <fullName>Index_Margin__c</fullName>
    <formula>Deal__r.Index_Margin__c</formula>
    <label>Index Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <formula>Text(Deal__r.Interest_Rate_Type__c)</formula>
    <label>Interest Rate Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apex_Context__c.field-meta.xml
<CustomField>
    <fullName>Apex_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for development work only</description>
    <label>Apex Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Draw_Period__c.field-meta.xml
<CustomField>
    <fullName>Draw_Period__c</fullName>
    <description>Bridge model pricing request field for Draw Period Term,</description>
    <inlineHelpText>Requested Advance Period = &apos;Draw Period&apos; in Pricing Model</inlineHelpText>
    <label>Requested Advance Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>Secured Overnight Financing Rate (SOFR)</description>
    <label>Index</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Rate_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1M SOFR</fullName>
            </value>
            <value>
                <fullName>3M SOFR</fullName>
            </value>
            <value>
                <fullName>6M SOFR</fullName>
            </value>
            <value>
                <fullName>1Y SOFR</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Index_Floor__c.field-meta.xml
<CustomField>
    <fullName>Index_Floor__c</fullName>
    <label>Index Floor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Rate_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.00%</fullName>
            </value>
            <value>
                <fullName>0.15%</fullName>
            </value>
            <value>
                <fullName>0.25%</fullName>
            </value>
            <value>
                <fullName>0.50%</fullName>
            </value>
            <value>
                <fullName>0.75%</fullName>
            </value>
            <value>
                <fullName>1.00%</fullName>
            </value>
            <value>
                <fullName>1.25%</fullName>
            </value>
            <value>
                <fullName>1.50%</fullName>
            </value>
            <value>
                <fullName>1.55%</fullName>
            </value>
            <value>
                <fullName>1.60%</fullName>
            </value>
            <value>
                <fullName>1.65%</fullName>
            </value>
            <value>
                <fullName>1.70%</fullName>
            </value>
            <value>
                <fullName>1.75%</fullName>
            </value>
            <value>
                <fullName>1.80%</fullName>
            </value>
            <value>
                <fullName>1.85%</fullName>
            </value>
            <value>
                <fullName>1.90%</fullName>
            </value>
            <value>
                <fullName>1.95%</fullName>
            </value>
            <value>
                <fullName>2.00%</fullName>
            </value>
            <value>
                <fullName>2.25%</fullName>
            </value>
            <value>
                <fullName>2.30%</fullName>
            </value>
            <value>
                <fullName>2.50%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Index_Margin__c.field-meta.xml
<CustomField>
    <fullName>Index_Margin__c</fullName>
    <description>Floating Index Margin field set back to percentage, user who enters basis points will need to use percent instead.</description>
    <label>Margin</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <label>Interest Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Line_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Line_Expiration__c</fullName>
    <description>Bridge model pricing request field for Line Expiration</description>
    <inlineHelpText>Requested Term = &apos;Line Expiration&apos;&apos; in Pricing Model</inlineHelpText>
    <label>Requested Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Repayment_Period__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Period__c</fullName>
    <description>Bridge model pricing request field for Repayment Period</description>
    <label>Requested Repayment Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Draw_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Draw_Fee__c</fullName>
    <description>Bridge model pricing request field for Draw Fee
Requested Advance Fee = &apos;Draw Fee&apos; in Pricing Model</description>
    <inlineHelpText>This is the Advance Fee reflected in a Term Sheet</inlineHelpText>
    <label>Requested Advance Fee</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Draw_Fee_Cap__c.field-meta.xml
<CustomField>
    <fullName>Requested_Draw_Fee_Cap__c</fullName>
    <description>Bridge model pricing request values for Draw Fee Cap</description>
    <inlineHelpText>Requested Advance Fee Cap = &apos;Draw Fee Cap&apos; in Pricing Model</inlineHelpText>
    <label>Requested Advance Fee Cap</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Initial Line Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Exit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Exit_Fee__c</fullName>
    <description>Bridge model pricing request field for Exit Fee</description>
    <label>Requested Exit Fee</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>Requested_Interest_Type__c</fullName>
    <description>Bridge model pricing request values for Requested Interest Type</description>
    <label>Requested Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_LTC_Max__c.field-meta.xml
<CustomField>
    <fullName>Requested_LTC_Max__c</fullName>
    <description>Bridge model pricing request field for Requested LTC Max</description>
    <label>Requested Initial LTC</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_LTV_Max__c.field-meta.xml
<CustomField>
    <fullName>Requested_LTV_Max__c</fullName>
    <description>Bridge model pricing request field for Requested LTV Max</description>
    <label>Requested Initial LTV</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Origination_Fee__c</fullName>
    <description>Bridge model pricing request field for Origination Fees</description>
    <label>Requested Origination Fee</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Rate_1_9_Months__c.field-meta.xml
<CustomField>
    <fullName>Requested_Rate_1_9_Months__c</fullName>
    <description>Bridge model pricing request values for Requested Rates</description>
    <label>Requested Rate</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Revolving__c.field-meta.xml
<CustomField>
    <fullName>Requested_Revolving__c</fullName>
    <description>Bridge model pricing request values for Requesting Revolvoing t</description>
    <label>Requested Revolving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/globalValueSets/LOC_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6 Months</fullName>
    </customValue>
    <customValue>
        <fullName>9 Months</fullName>
    </customValue>
    <customValue>
        <fullName>12 Months</fullName>
    </customValue>
    <customValue>
        <fullName>15 Months</fullName>
    </customValue>
    <customValue>
        <fullName>18 Months</fullName>
    </customValue>
    <customValue>
        <fullName>20 Months</fullName>
    </customValue>
    <customValue>
        <fullName>21 Months</fullName>
    </customValue>
    <customValue>
        <fullName>24 Months</fullName>
    </customValue>
    <customValue>
        <fullName>30 Months</fullName>
    </customValue>
    <customValue>
        <fullName>36 Months</fullName>
    </customValue>
    <customValue>
        <fullName>540 Days</fullName>
    </customValue>
    <customValue>
        <fullName>630 Days</fullName>
    </customValue>
    <customValue>
        <fullName>720 Days</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>33 Months</fullName>
        <isActive>false</isActive>
        <label>33 Months</label>
    </customValue>
    <customValue>
        <fullName>27 Months</fullName>
        <isActive>false</isActive>
        <label>27 Months</label>
    </customValue>
    <customValue>
        <fullName>3 Months</fullName>
        <isActive>false</isActive>
        <label>3 Months</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <description>Terms for LOC Loans</description>
    <masterLabel>LOC Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Wire_TriggerTest.cls
@isTest
private class Wire_TriggerTest {

    //static List<Account> testAccounts = testDataFactory.createTestRecords(new Account[10]);

    static TestMethod void advance_Tests_UnitTest()
    {
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity opp = test_Helper.createOpportunity( acc, cont );
        opp.Apex_Context__c = true;
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE sobjecttype = 'Opportunity' and DeveloperName = 'LOC_Loan'].Id;
        opp.StageName = 'Hold';
        opp.Draw_Period__c = '12 Months';
        opp.Repayment_Period__c = '9 Months';
        opp.LOC_Loan_Type__c = 'Credit Line';
        opp.Loan_Size__c = 3000000;
        opp.Line_Expiration__c = '18 Months';
        opp.Requested_LTC_Max__c = 70;
        opp.Requested_LTV_Max__c = 80;
        opp.Requested_Origination_Fee__c = 0;
        opp.Requested_Draw_Fee__c = 2;
        opp.Requested_Exit_Fee__c = 0;
        opp.Requested_Interest_Type__c = 'Fixed';
        opp.Requested_Rate_1_9_Months__c = 10;
        opp.Requested_Revolving__c = 'Yes';
        opp.Requested_Draw_Fee_Cap__c = 'None';
        opp.Product_Sub_Type__c = 'Renovation';
        opp.Interest_Rate_Type__c = 'Floating';
        opp.Index__c = '1M LIBOR';
        opp.Index_Floor__c = '1.00%';
        opp.Index_Margin__c = 1.50;
        opp.Deal_Intro_Source__c = 'Hotline';
        opp.Deal_Intro_Sub_source__c = 'Main';
        update opp;

        List<Property__c> property = new List<Property__c>();
        for(Integer i = 0; i < 20; i++){
            property.add(
                new Property__c(
                    Name='Test + ' + i, 
                    Property_Name__c = 'Test ' + i, 
                    Deal__c = opp.Id, 
                    Escrow_Company_text__c = 'ESCROW', 
                    Insurance_Company_text__c = 'INSURANCE', 
                    Status__c = 'Pending',
                    RecordTypeId = [SELECT Id FROM RecordType WHERE sobjecttype = 'Property__c' and DeveloperName = 'Bridge_No_Renovation'].Id
                )
            );
        }

        property[0].Status__c = 'Cancelled';
        property[1].Status__c = 'Active';
        property[2].Payoff_Received_Date__c = system.today();
        insert property;
        Test.startTest();

        Advance__c adv = new Advance__c(Deal__c = opp.Id);
        insert adv;

        Wire__c wire = new Wire__c(Advance__c = adv.Id, Wire_Number__c=123456);
        insert wire;

        Wire__c wire1 = new Wire__c(Advance__c = adv.Id, Wire_Number__c=123456);
        insert wire1;
        
        wire.Wire_Date__c=Date.Today();
        update wire;
        
        delete wire;
        
        undelete wire;

        Test.stopTest();
    }
}