force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Advance__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/Property_Advance__c.object-meta.xml
<CustomObject>
    <description>The Individual Property for which a Bridge Advance was made</description>
    <label>Property Advance</label>
    <nameField>
        <label>Property Advance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <description>Deal Name of the related Advance</description>
    <formula>Advance__r.Deal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Deal Name of the related Advance</inlineHelpText>
    <label>Deal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AdvanceFundingMemoControllerTests.cls
@isTest
public with sharing class AdvanceFundingMemoControllerTests {
    @TestSetup
    static void makeData(){
        Test_Helper.createDealLoanNumber();
        Account a = Test_Helper.createAccount();
        Contact c = Test_Helper.createContact(a);
        Opportunity o = Test_Helper.createBridgeDeal(a, c);
        List<Property__c> props = Test_Helper.createProperties(o);

        Advance__c adv =  new Advance__c(Deal__c = o.Id);
        insert adv;
        insert new Property_Advance__c(Advance__c = adv.Id, Property__c = props[0].Id);
        
    }

    @isTest
    public static void unitTest1() {
        Advance__c adv =[SELECT Id FROM Advance__c];

        Map<String,String> details = new Map<String,String>{
            'actualDscr' => '1x',
            'actualLtv' => '2',
            'actualDebtYield' => '2',
            'proformaRent' => '3321',
            'recordId' => adv.Id
        };

        AdvanceFundingMemoController.downloadFile(JSON.serialize(details)); 

        ApexPages.currentPage().getParameters().put('id', details.get('recordId'));
        ApexPages.currentPage().getParameters().put('actualDscr', details.get('actualDscr'));
        ApexPages.currentPage().getParameters().put('actualLtv', details.get('actualLtv'));
        ApexPages.currentPage().getParameters().put('actualDebtYield', details.get('actualDebtYield'));
        ApexPages.currentPage().getParameters().put('proformaRent', details.get('proformaRent'));
        
        ApexPages.StandardController sc = new ApexPages.StandardController(adv);
        AdvanceFundingMemoController afmc = new AdvanceFundingMemoController(sc);
        AdvanceFundingMemoController.PropertyDetails pd = afmc.propertyDetails;
    }
}