force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{00000000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Callout_Failed__c.field-meta.xml
<CustomField>
    <fullName>Callout_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Callout Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Request_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Request_Endpoint__c</fullName>
    <label>Request Endpoint</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Yardi</fullName>
            </value>
            <value>
                <fullName>Clear Capital</fullName>
            </value>
            <value>
                <fullName>Clarocity</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>CoreLogic</fullName>
            </value>
            <value>
                <fullName>Beekin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appraisal__c/Appraisal__c.object-meta.xml
<CustomObject>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Property__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/Settings__mdt.object-meta.xml
<CustomObject>
    <description>This will give us the ability to enable/disable certain actions/triggers in the system</description>
    <label>Settings</label>
    <pluralLabel>Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Settings__mdt/fields/Enable_BOX_API_Response_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_BOX_API_Response_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will enable the logging of the API response for BOX in the API Log Object</description>
    <inlineHelpText>This will enable the logging of the API response for BOX in the API Log Object</inlineHelpText>
    <label>Enable BOX API Response Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/Enable_Clear_API_Response_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Clear_API_Response_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will enable the logging of the API response for Clear background check in the API Log Object</description>
    <inlineHelpText>This will enable the logging of the API response for Clear background check in the API Log Object</inlineHelpText>
    <label>Enable Clear API Response Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/Enable_CoreLogic_API_Response_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_CoreLogic_API_Response_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will enable the logging of the API response for CoreLogic in the API Log Object</description>
    <inlineHelpText>This will enable the logging of the API response for CoreLogic in the API Log Object</inlineHelpText>
    <label>Enable CoreLogic API Response Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/Enable_Valuation_API_Response_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Valuation_API_Response_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will enable the logging of the API response for Valuation Vendors in the API Log Object</description>
    <inlineHelpText>This will enable the logging of the API response for Valuation Vendors in the API Log Object</inlineHelpText>
    <label>Enable Valuation API Response Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/Enable_Yardi_API_Response_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Yardi_API_Response_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will enable the logging of the API response for Yardi integration in the API Log Object</description>
    <inlineHelpText>This will enable the logging of the API response for Yardi integration in the API Log Object</inlineHelpText>
    <label>Enable Yardi API Response Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/APILoggerQueueable.cls
public without sharing class APILoggerQueueable implements Queueable {
  API_Log__c log;
  Id parentId;
  Boolean error;
  APILoggerQueueable next;

  public APILoggerQueueable(
    HttpRequest request,
    HttpResponse response,
    Id parentId,
    Boolean error
  ) {
    this.parentId = parentId;
    this.error = error;
    this.log = new APILogger(request, response).getLog();
  }

  public APILoggerQueueable(
    HttpRequest request,
    HttpResponse response,
    Id parentId,
    APILoggerQueueable nextQueue
  ) {
    this.parentId = parentId;
    this.error = false;
    this.next = nextQueue;
    this.log = new APILogger(request, response).getLog();
  }

  public APILoggerQueueable(
    HttpRequest request,
    HttpResponse response,
    Id parentId,
    Exception e
  ) {
    this.parentId = parentId;
    this.error = true;
    this.log = new APILogger(request, response, e).getLog();
  }

  public void execute(QueueableContext qc) {
    log.Callout_Failed__c = error;

    String endpoint = log.Request_Endpoint__c;

    List<Settings__mdt> settings = [
      SELECT
        Enable_Yardi_API_Response_Logging__c,
        Enable_BOX_API_Response_Logging__c,
        Enable_Valuation_API_Response_Logging__c,
        Enable_Clear_API_Response_Logging__c,
        Enable_CoreLogic_API_Response_Logging__c
      FROM Settings__mdt
      WHERE DeveloperName = 'Universal_Settings'
    ];

    Clarocity_API_Settings__c clarocitySettings = Clarocity_API_Settings__c.getInstance();
    Appraisal_Nation_API__c appraisalSettings = Appraisal_Nation_API__c.getInstance();
    Valuation_Services_API__c valuationSettings = Valuation_Services_API__c.getInstance();
    String appraisalBaseEndPoint = appraisalSettings.Endpoint__c;
    String clarocityBaseEndpoint = clarocitySettings.Endpoint__c;
    String valuationBaseEndpoint = valuationSettings.Endpoint__c;

    if (Test.isRunningTest()) {
      clarocityBaseEndpoint = 'cvs';
      appraisalBaseEndPoint = 'appraisal';
      valuationBaseEndpoint = 'valuation';
    }

    Boolean enableLogging = true;

    if (endpoint.contains('yardi')) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_Yardi_API_Response_Logging__c
        : true;
      log.Type__c = 'Yardi';
    } else if (endpoint.contains('box.com')) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_BOX_API_Response_Logging__c
        : true;
      log.Type__c = 'Box';
    } else if (endpoint.contains('clearcapital')) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_Valuation_API_Response_Logging__c
        : true;
      log.Type__c = 'Clear Capital';
    } else if (endpoint.contains(clarocityBaseEndpoint)) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_Valuation_API_Response_Logging__c
        : true;
      log.Type__c = 'Clarocity';
    } else if (endpoint.contains(appraisalBaseEndPoint)) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_Valuation_API_Response_Logging__c
        : true;
      log.Type__c = 'Appraisal';
    } else if (endpoint.contains(valuationBaseEndpoint)) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_Valuation_API_Response_Logging__c
        : true;
      log.Type__c = 'Valuation';
    } else if (endpoint.contains('thomsonreuters')) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_Clear_API_Response_Logging__c
        : true;
      log.Type__c = 'Clear';
    } else if (endpoint.contains('corelogic')) {
      enableLogging = settings.size() > 0
        ? settings[0].Enable_CoreLogic_API_Response_Logging__c
        : true;
      log.Type__c = 'CoreLogic';
    }

    if (enableLogging) {
      if (parentId != null) {
        String sobjectType = parentId.getSObjectType().getDescribe().getName();

        switch on sobjectType {
          when 'Opportunity' {
            log.Deal__c = parentId;
          }
          when 'Property__c' {
            log.Property__c = parentId;
          }
          when 'Advance__c' {
            log.Advance__c = parentId;
          }
          when 'Deal_Document__c' {
            log.Deal_Document__c = parentId;
          }
          when 'Appraisal__c' {
            log.Appraisal__c = parentId;
          }
          when 'Deal_Contact__c' {
            log.Deal_Contact__c = parentId;
          }
          when 'Clear_Result__c' {
            log.Clear_Result__c = parentId;
          }
          when 'Contact__c' {
            log.Contact__c = parentId;
          }
        }
      }

      insert log;

      if (next != null && !Test.isRunningTest()) {
        System.enqueueJob(next);
      }
    }
  }

  class APILogger {
    API_Log__c log;

    public APILogger(HttpRequest request, HttpResponse response) {
      if (request == null) {
        request = new HttpRequest();
      }

      if (response == null) {
        response = new HttpResponse();
      }

      log = new API_log__c();
      log.Request_Endpoint__c = request.getEndpoint();
      log.Request_Method__c = request.getMethod();

      String requestContentType = request.getHeader('Content-Type');
      if (requestContentType == 'application/json') {
        Map<String, Object> body = (Map<String, Object>) JSON.deserializeUntyped(
          request.getBody()
        );
        log.Request_Body__c = JSON.serializePretty(body);
      } else {
        //    else if (requestContentType.contains('text/xml')) {
        //     Dom.Document domDoc = new Dom.Document(); //new Dom.Document(request.getBody());
        //     domDoc.load(request.getBody());
        //     dom.Xmlnode root = domDoc.getRootElement();
        //     if (root != null) {
        //       String body = util.prettyPrint(root, 4);
        //       log.Request_Body__c = body;
        //     } else {
        //       log.Request_Body__c = request.getBody();
        //     }
        //   }
        log.Request_Body__c = request.getBody();
      }

      log.Response_Status__c = response.getStatus();
      log.Response_Status_Code__c = response.getStatusCode();

      Map<String, String> responseHeaders = new Map<String, String>();
      for (String key : response.getHeaderKeys()) {
        responseHeaders.put(key, response.getHeader(key));
      }
      log.Response_Headers__c = JSON.serializePretty(responseHeaders);

      String responseContentType = response.getHeader('Content-Type');
      if (responseContentType == 'application/json') {
        Map<String, Object> body = (Map<String, Object>) JSON.deserializeUntyped(
          response.getBody()
        );
        String resBody = String.valueOf(JSON.serializePretty(body));

        if (resBody.length() > 32700) {
          resBody = resBody.substring(0, 32700);
          resBody += ' ... (truncated)';
        }

        log.Response_Body__c = resBody;

      } else {
        //   else if (responseContentType.contains('text/xml')) {
        //     Dom.Document domDoc = new Dom.Document(); //new Dom.Document(request.getBody());
        //     domDoc.load(response.getBody());
        //     dom.Xmlnode root = domDoc.getRootElement();
        //     if (root != null) {
        //       String body = util.prettyPrint(root, 4);
        //       log.Response_Body__c = body;
        //     } else {
        //       log.Response_Body__c = request.getBody();
        //     }
        //   }

        String resBody = response.getBody();

        if (resBody.length() > 32700) {
          resBody = resBody.substring(0, 32700);
          resBody += ' ... (truncated)';
        }

        log.Response_Body__c = resBody;
      }
    }

    public APILogger(HttpRequest request, HttpResponse response, Exception e) {
      this(request, response);
      this.log.Exception_Line_Number__c = e.getLineNumber();
      this.log.Exception_Message__c = e.getMessage();
      this.log.Exception_Stack_Trace__c = e.getStackTraceString();
      this.log.Exception_Type__c = e.getTypeName();
      this.log.Callout_Failed__c = true;
    }

    public API_Log__c getLog() {
      return this.log;
    }
  }
}