force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact this Document is related to</description>
    <inlineHelpText>Contact this Document is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Structure_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Structure_Id__c</fullName>
    <externalId>true</externalId>
    <label>Document Structure Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FileMoveBatch.cls
global with sharing class FileMoveBatch implements Database.Batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    String queryString = 'SELECT';
    queryString += ' Id, latestpublishedversion.firstpublishlocationid, LatestPublishedVersionId, LatestPublishedVersion.Title, LatestPublishedVersion.FileExtension FROM ContentDocument';
    queryString += ' WHERE LatestPublishedVersion.Migrated_File__c = TRUE AND LatestPublishedVersion.Linked_To_Record__c = FALSE';
    return Database.getQueryLocator(queryString);
  }

  global void execute(Database.BatchableContext bc, List<sObject> scope) {
    List<Deal_Document__c> dealDocs = new List<Deal_Document__c>();

    //Id docStructureId = 'm005b0000010wJK';
    List<ContentVersion> contentVersions = new List<ContentVersion>();

    Set<Id> advanceIds = new Set<Id>();
    for (ContentDocument contentDoc : (List<ContentDocument>) scope) {
      if (
        contentDoc.LatestPublishedVersion.FirstPublishLocationId.getSObjectType()
          .getDescribe()
          .getName() == 'Account' ||
        contentDoc.LatestPublishedVersion.FirstPublishLocationId.getSObjectType()
          .getDescribe()
          .getName() == 'Contact'
      ) {
        contentVersions.add(
          new ContentVersion(
            Id = contentDoc.LatestPublishedVersionId,
            Linked_To_Record__c = true
          )
        );
        Deal_Document__c dealDocument = new Deal_Document__c();
        //dealDocument.Advance__c = contentDoc.LatestPublishedVersion.FirstPublishLocationId;
        if (
          contentDoc.LatestPublishedVersion.FirstPublishLocationId.getSObjectType()
            .getDescribe()
            .getName() == 'Account'
        ) {
          dealDocument.Account__c = contentDoc.LatestPublishedVersion.FirstPublishLocationId;
        } else if (
          contentDoc.LatestPublishedVersion.FirstPublishLocationId.getSObjectType()
            .getDescribe()
            .getName() == 'Contact'
        ) {
          dealDocument.Contact__c = contentDoc.LatestPublishedVersion.FirstPublishLocationId;
        }
        dealDocument.File_Name__c =
          contentDoc.LatestPublishedVersion.Title +
          '.' +
          contentDoc.LatestPublishedVersion.FileExtension;
        dealDocument.COntentVersion_Id__c = contentDoc.LatestPublishedVersionId;
        dealDocument.Attachment_Id__c = contentDoc.Id;
        dealDocument.Document_Loaded__c = true;
        //dealDocument.Document_Structure_Id__c = docStructureId;
        dealDocument.Type__c = 'Miscellaneous';
        dealDocument.Document_Type__c = 'Miscellaneous';
        dealDocs.add(dealDocument);
      }
    }

    insert dealDocs;
    update contentVersions;
    Set<Id> ids = new Set<Id>();

    List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();
    for (Deal_Document__c dealDoc : dealDOcs) {
      ContentDocumentLink cdl = new ContentDocumentLink();
      cdl.ContentDocumentId = dealDoc.Attachment_Id__c;
      cdl.LinkedEntityId = dealDoc.Id;
      cdl.ShareType = 'V';
      cdl.Visibility = 'AllUsers';
      contentDOcumentLinks.add(cdl);

      ids.add(dealDoc.Account__c);
      ids.add(dealDoc.Contact__c);
      ids.add(dealDoc.Attachment_Id__c);
    }

    delete [
      SELECT Id
      FROM COntentDocumentLInk
      WHERE LinkedEntityId IN :ids AND ContentDocumentId IN :ids
    ];

    insert contentDocumentLinks;
  }

  global void finish(Database.BatchableContext bc) {
  }
}