force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact_Type__c</fullName>
    <label>Deal Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Loan Application Entity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Portal Access</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>EscrowAgent</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>TitleCompany</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/Loan_Fee__c.object-meta.xml
<CustomObject>
    <description>Fees associated to Loans</description>
    <label>Loan Fee</label>
    <nameField>
        <displayFormat>LF-{000000}</displayFormat>
        <label>Loan Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fee__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Deal associated with this fee</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Deal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Deal Contact</label>
    <referenceTo>Deal_Contact__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The Amount of this Fee</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property that this Fee is related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Reference Number for this Fee</description>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vendor this fee is paid to</description>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Active_States__c.field-meta.xml
<CustomField>
    <fullName>Active_States__c</fullName>
    <description>Bridge Use</description>
    <inlineHelpText>States that the Properties reside in</inlineHelpText>
    <label>Active States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Advance__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/Property_Advance__c.object-meta.xml
<CustomObject>
    <description>The Individual Property for which a Bridge Advance was made</description>
    <label>Property Advance</label>
    <nameField>
        <label>Property Advance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <description>Deal Name of the related Advance</description>
    <formula>Advance__r.Deal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Deal Name of the related Advance</inlineHelpText>
    <label>Deal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SABAdvanceMemoExtensionTest.cls
@isTest
private class SABAdvanceMemoExtensionTest {
  static testMethod void testMethod1() {
    Account acc = Test_Helper.createAccount();
    Contact cont = Test_Helper.createContact(acc);
    Opportunity opp = Test_Helper.createBridgeDeal(acc, cont);
    List<Property__c> properties = Test_Helper.createProperties(opp);

    Loan_Fee__c Loan_Fee = new Loan_Fee__c(
      Deal__c = opp.Id,
      Fee_Amount__c = 1000,
      Reference__c = '121212',
      Vendor__c = acc.Id
    );

    Advance__c adv = new Advance__c(Name = 'Tesst', Deal__c = opp.Id);
    insert adv;

    Property_Advance__c propAdv = new Property_Advance__c(
      Name = 'test',
      Advance__c = adv.Id,
      Property__C = properties[0].Id
    );
    insert propAdv;

    Test.startTest();
    SABAdvanceMemoExtension obj = new SABAdvanceMemoExtension();
    obj.filtersJSON =
      '{"recordId":"' +
      adv.Id +
      '","loantype":"1211","liquidcashreserves":"111","corevestapprovalmanager":"111","otheradjustments":"111","priorcvloans":"1111","everdeliquent":"11"}';
    obj.getData();
    SABAdvanceMemoExtension.getUrlAndInstance();
    Test.stopTest();
  }

  static testMethod void testMethodSuccess() {
    Account acc = Test_Helper.createAccount();
    Contact cont = Test_Helper.createContact(acc);
    Opportunity opp = Test_Helper.createBridgeDeal(acc, cont);
    opp.Active_States__c = 'California;Nevada';
    update opp;

    insert new deal_contact__c(
      Deal__c = opp.Id,
      Contact__c = cont.Id,
	  Deal_Contact_Type__c = 'Individual',
      Entity_Type__c = 'Sponsor'
    );
    insert new deal_contact__c(
      Deal__c = opp.Id,
      Contact__c = cont.Id,
	  Deal_Contact_Type__c = 'Individual',
      Entity_Type__c = 'Guarantor'
    );
    List<Property__c> properties = Test_Helper.createProperties(opp);
    Loan_Fee__c Loan_Fee = new Loan_Fee__c(
      Deal__c = opp.Id,
      Fee_Amount__c = 1000,
      Reference__c = '121212',
      vendor__c = acc.Id
    );

    Advance__c adv = new Advance__c(Name = 'Test', Deal__c = opp.Id);
    insert adv;
    Test.startTest();
    Property_Advance__c propAdv = new Property_Advance__c(
      Name = 'test',
      Advance__c = adv.Id,
      Property__c = properties[0].Id
    );
    insert propAdv;

    SABAdvanceMemoExtension obj = new SABAdvanceMemoExtension();
    obj.filtersJSON =
      '{"recordId":"' +
      adv.Id +
      '","loantype":"1211","liquidcashreserves":"111","corevestapprovalmanager":"111","otheradjustments":"111","priorcvloans":"1111","everdeliquent":"11"}';
    obj.getData();
    SABAdvanceMemoExtension.getUrlAndInstance();
    Test.stopTest();
  }

  static testMethod void testMethodFail() {
    Test.startTest();
    SABAdvanceMemoExtension obj = new SABAdvanceMemoExtension();
    obj.filtersJSON = '{"recordId":"1234","loantype":"1211","liquidcashreserves":"111","corevestapprovalmanager":"111","otheradjustments":"111","priorcvloans":"1111","everdeliquent":"11"}';
    obj.getData();

    SABAdvanceMemoExtension.WrapperData wd = new SABAdvanceMemoExtension.WrapperData();

    wd.corevestapprovalmanager = '1000';
    wd.priorcvloans = '1000';
    wd.everdeliquent = '1000';
    wd.loantype = '1000';

    Test.stopTest();
  }
}