force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Acquisition_Date__c.field-meta.xml
<CustomField>
    <fullName>Acquisition_Date__c</fullName>
    <label>Acquisition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Advance__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/BPO_Appraisal_Date__c.field-meta.xml
<CustomField>
    <fullName>BPO_Appraisal_Date__c</fullName>
    <description>Date of the most recent Appraisal</description>
    <inlineHelpText>Date of the most recent Appraisal</inlineHelpText>
    <label>Current Appraisal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label># of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Occupancy_Pct__c.field-meta.xml
<CustomField>
    <fullName>Occupancy_Pct__c</fullName>
    <formula>Number_of_Occupied_Units__c / Deal__r.Total_Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Occupancy %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Refinance_Acquisition__c.field-meta.xml
<CustomField>
    <fullName>Refinance_Acquisition__c</fullName>
    <label>Refinance Acquisition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <label>Year Built</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/Property_Advance__c.object-meta.xml
<CustomObject>
    <description>The Individual Property for which a Bridge Advance was made</description>
    <label>Property Advance</label>
    <nameField>
        <label>Property Advance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Advance__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Advances</relationshipLabel>
    <relationshipName>Property_Advances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AdvanceFundingMemoController.cls
public without sharing class AdvanceFundingMemoController {
  public String actualDscr { get; set; }
  public Decimal actualLtv { get; set; }
  public Decimal actualDebtYield { get; set; }
  public Decimal proformaRent { get; set; }
  public Advance__c record { get; set; }

  public AdvanceFundingMemoController(
    ApexPages.standardController standardController
  ) {
    this.record = (Advance__c) standardController.getRecord();
    this.actualLtv = ApexPages.currentPage().getParameters().containsKey('actualLtv') && String.isNotBlank(ApexPages.currentPage().getParameters().get('actualLtv')) ? Decimal.valueOf(
      ApexPages.currentPage().getParameters().get('actualLtv')
    ) : null;
    this.actualDebtYield = ApexPages.currentPage().getParameters().containsKey('actualDebtYield') && String.isNotBlank(ApexPages.currentPage().getParameters().get('actualDebtYield')) ? Decimal.valueOf(
      ApexPages.currentPage().getParameters().get('actualDebtYield')
    ) : null;
    this.actualDscr = ApexPages.currentPage().getParameters().containsKey('actualDscr') &&  String.isNotBlank(ApexPages.currentPage().getParameters().get('actualDscr')) ? ApexPages.currentPage().getParameters().get('actualDscr') : 'N/A';
    this.proformaRent = ApexPages.currentPage().getParameters().containsKey('proformaRent') && String.isNotBlank(ApexPages.currentPage().getParameters().get('proformaRent')) ? Decimal.valueOf(ApexPages.currentPage().getParameters().get('proformaRent')) : null;
  }

  public PropertyDetails propertyDetails {
    get {
      PropertyDetails pd = new PropertyDetails();

      if (this.record != null) {
        Set<String> transacTypes = new Set<String>();
        Set<String> propTypes = new Set<String>();
        pd.unitCount = 0;
        pd.propertyCount = 0;
        pd.occupancy = 0;
        Decimal occupancyTotal = 0;
        Decimal validOccCount = 0;
        Decimal yearBuiltTotal = 0;
        Decimal validYearBuiltCount = 0;
        Decimal totalDaysBetween = 0;
        Decimal validTotalDays = 0;
        Decimal totalAppraisalDays = 0;
        Decimal validAppraisalDays = 0;

        for (Property__c p : [
            SELECT Id, Refinance_Acquisition__c,Acquisition_Date__c, Property_Type__c,Number_of_Units__c,Occupancy_Pct__c,Year_Built__c,BPO_Appraisal_Date__c
            FROM Property__c
            WHERE Id IN (SELECT Property__c FROM Property_Advance__c WHERE Advance__c = :this.record.Id)
        ]) {
          pd.propertyCount++;
          if (String.isNotBlank(p.Refinance_Acquisition__c)) {
            transacTypes.add(p.Refinance_Acquisition__c);
          }
          if (String.isNotBlank(p.Property_Type__c)) {
            propTypes.add(p.Property_Type__c);
          }

          if (p.Number_of_Units__c != null) {
            pd.unitCount += p.Number_of_Units__c;
          }

          if (p.Occupancy_Pct__c != null) {
            occupancyTotal += p.Occupancy_Pct__c;
            validOccCount++;
          }

          if (String.isNotBlank(p.Year_Built__c)) {
            yearBuiltTotal += Decimal.valueOf(p.Year_Built__c);
            validYearBuiltCount++;
          }

          if(p.Acquisition_Date__c != null) {
            totalDaysBetween = p.Acquisition_Date__c.daysBetween(System.today());
            validTotalDays++;
          }

          if(p.BPO_Appraisal_Date__c != null) {
            totalAppraisalDays = p.BPO_Appraisal_Date__c.daysBetween(System.today());
            validAppraisalDays++;
          }
        }

        pd.transactionType = String.join(new List<String>(transacTypes), ', ');
        pd.propertyType = String.join(new List<String>(propTypes), ', ');
        if(validOccCount > 0) {
            pd.occupancy = occupancyTotal / validOccCount;

        }
        if( validYearBuiltCount > 0) {
            pd.avgYearBuilt = yearBuiltTotal / validYearBuiltCount;
        }

        if (validTotalDays > 0) {
          pd.acquisitionDate = System.today().addDays(0 - (Integer.valueOf(totalDaysBetween / validTotalDays)));
        }

        if(validAppraisalDays > 0) {
          pd.appraisalDate = System.today().addDays(0 - (Integer.valueOf(totalAppraisalDays / validAppraisalDays)));
        }
      }

      return pd;
    }
    private set;
  }

  public class PropertyDetails {
    public String transactionType {get; set;}
    public String propertyType {get; set;}
    public Decimal propertyCount {get; set;}
    public Decimal unitCount {get; set;}
    public Decimal occupancy {get; set;}
    public Decimal avgYearBuilt {get; set;}
    public Date acquisitionDate { get; set; }
    public Date appraisalDate { get; set; }
  }

  @AuraEnabled
  public static string downloadFile(String jsonDetails){
    try {
      Map<String, Object> details = (Map<String,Object>) JSON.deserializeUntyped(jsonDetails);

      PageReference pageRef = Page.advanceFundingMemo;
      pageRef.getParameters().put('id', String.valueOf(details.get('recordId')));
      pageRef.getParameters().put('actualDscr', String.valueOf(details.get('actualDscr')));
      pageRef.getParameters().put('actualLtv', String.valueOf(details.get('actualLtv')));
      pageRef.getParameters().put('actualDebtYield', String.valueOf(details.get('actualDebtYield')));
      pageRef.getParameters().put('proformaRent', String.valueOf(details.get('proformaRent')));

      return !Test.isRunningTest() ? EncodingUtil.base64Encode(pageRef.getContentAsPdf()) : '';

    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}