force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Closing_Funds_Checked_By__c.field-meta.xml
<CustomField>
    <fullName>Closing_Funds_Checked_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Funds Checked By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Closing_Funds_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Closing_Funds_Checklist__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closing Funds Checklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Closing_Funds_Checklist_Comments__c.field-meta.xml
<CustomField>
    <fullName>Closing_Funds_Checklist_Comments__c</fullName>
    <label>Closing Funds Checklist Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Closing_Funds_Checklist_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Funds_Checklist_Date__c</fullName>
    <label>Closing Funds Checklist Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Evidence_of_Insurance_Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Evidence_of_Insurance_Approval_Comments__c</fullName>
    <label>Evidence of Insurance Approval Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Evidence_of_Insurance_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Evidence_of_Insurance_Approval_Date__c</fullName>
    <label>Evidence of Insurance Approval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Evidence_of_Insurance_Approved__c.field-meta.xml
<CustomField>
    <fullName>Evidence_of_Insurance_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Evidence of Insurance Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Evidence_of_Insurance_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Evidence_of_Insurance_Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evidence of Insurance Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advances2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Flood_Certificate_Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Flood_Certificate_Approval_Comments__c</fullName>
    <label>Flood Certificate Approval Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Flood_Certificate_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Flood_Certificate_Approval_Date__c</fullName>
    <label>Flood Certificate Approval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Flood_Certificate_Approved__c.field-meta.xml
<CustomField>
    <fullName>Flood_Certificate_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flood Certificate Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Flood_Certificate_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Flood_Certificate_Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flood Certificate Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advances3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Manager_Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Manager_Approval_Comments__c</fullName>
    <label>Manager Approval Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Manager_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Manager_Approval_Date__c</fullName>
    <label>Manager Approval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Manager_Approved__c.field-meta.xml
<CustomField>
    <fullName>Manager_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Manager_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Manager_Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advances1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Doc_String__c.field-meta.xml
<CustomField>
    <fullName>Doc_String__c</fullName>
    <formula>Folder_String__c + &apos;|&apos; + TEXT(Document_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Doc String</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Reviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Document has been reviewed</description>
    <label>Reviewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/Document_Information__c.object-meta.xml
<CustomObject>
    <description>Deal Document Information / Loan Status Tab etc...</description>
    <label>Document Information</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Document Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Information__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Document Information</relationshipLabel>
    <relationshipName>Document_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Information</relationshipLabel>
    <relationshipName>Document_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Doc_String__c.field-meta.xml
<CustomField>
    <fullName>Doc_String__c</fullName>
    <label>Doc String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/Document_Structure__mdt.object-meta.xml
<CustomObject>
    <label>Document Structure</label>
    <pluralLabel>Document Structures</pluralLabel>
</CustomObject>

force-app/main/default/objects/Document_Structure__mdt/fields/Folder_Structure_String__c.field-meta.xml
<CustomField>
    <fullName>Folder_Structure_String__c</fullName>
    <label>Folder Structure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
                <default>true</default>
                <label>Opportunity</label>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Advance__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data.  Record Type Developer Name</inlineHelpText>
    <label>Record Type Developer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Single_Asset_Bridge_Loan.recordType-meta.xml
<RecordType>
    <fullName>Single_Asset_Bridge_Loan</fullName>
    <active>true</active>
    <businessProcess>SAB Process</businessProcess>
    <label>Single Asset Bridge Loan</label>
</RecordType>

force-app/main/default/classes/AdvanceClearToFundController.cls
public without sharing class AdvanceClearToFundController {
  public static List<String> docStructures = new List<String>{
    'Pro_Forma_MUC', //pro forma or muc
    //'Evidence_of_Insurance', //evidence of insurance
    'Advance_Funding_Request_for_Advance', //request for advance
    'LOC_Closing_Instructions', //closing instructions
    'Advance_Funding_Security_Instrument', //security instrument
    'Vesting_Deed', //executed vesting deed
    'Settlement_Statement', //settlement statement
    'Advance_Funding_Funding_Approval_Package', //corevest funding package
    //'Advance_Flood_Certificate', //Flood Certificate
    'Flood_Insurance_if_applicable', //flood insurance (if applicable)
    'HOA_Policy_if_applicable', // HOA Policy (if applicable)
    'LOC_Renovation_Cert' // Renovation Certificate (if applicable)
  };
  @AuraEnabled
  public static String init(Id advanceId) {
    Advance__c advance = [
      SELECT
        Id,
        Deal__c,
        Deal__r.Record_Type_Name__c,
        Closing_Funds_Checklist__c,
        Closing_Funds_Checklist_Date__c,
        Closing_Funds_Checklist_Comments__c,
        Closing_Funds_Checked_By__r.Name,
        Closing_Funds_Checked_By__c,
        Manager_Approval_Comments__c,
        Manager_Approval_Date__c,
        Manager_Approved__c,
        Manager_Approved_By__c,
        Manager_Approved_By__r.Name,
        Evidence_of_Insurance_Approval_Comments__c,
        Evidence_of_Insurance_Approval_Date__c,
        Evidence_of_Insurance_Approved__c,
        Evidence_of_Insurance_Approved_By__r.Name,
        Evidence_of_Insurance_Approved_By__c,
        Flood_Certificate_Approval_Comments__c,
        Flood_Certificate_Approval_Date__c,
        Flood_Certificate_Approved__c,
        Flood_Certificate_Approved_By__c,
        Flood_Certificate_Approved_By__r.Name
      FROM Advance__c
      WHERE Id = :advanceId
      LIMIT 1
    ];

    if(advance.Deal__r.Record_Type_Name__c == 'Single_Asset_Bridge_Loan') {
      List<String> newDocstructures = new List<String>();
      for(String ds : docStructures) {
        newDocstructures.add(ds + '_sab');
      }
      docStructures = newDocstructures;
    }

    Map<String, Map<String, Object>> response = new Map<String, Map<String, Object>>();

    Map<String, String> docStringMap = new Map<String, String>();
    for (Document_Structure__mdt docStructure : [
      SELECT Id, Folder_Structure_String__c, Document_Type__c, DeveloperName
      FROM Document_Structure__mdt
      WHERE sObject__c = 'Advance__c' AND DeveloperName IN :docStructures
    ]) {
      String docString =
        docStructure.Folder_Structure_String__c +
        '|' +
        docStructure.Document_Type__c;

      docStringMap.put(docString, docStructure.DeveloperName);

      response.put(docString, new Map<String, Object>());
      response.get(docString).put('files', new List<Deal_Document__c>());
      response.get(docString).put('docInfoId', '');
    }

    Map<String, Document_Information__c> docInfoMap = new Map<String, Document_Information__c>();
    for (Document_Information__c docInfo : [
      SELECT Id, Doc_String__c, Internal_Comments__c
      FROM Document_Information__c
      WHERE Doc_String__c IN :docStringMap.keySet() AND Advance__c = :advanceId
    ]) {
      String docString = docInfo.Doc_String__c;
      response.get(docString).put('documentInformation', docInfo);
      response.get(docString).put('docInfoId', docInfo.Id);
    }

    system.debug('--docStringMap--');
    system.debug(docStringMap.keySet());

    for (Deal_Document__c dealDoc : [
      SELECT
        Id,
        Doc_String__c,
        Reviewed__c,
        Reviewed_By__r.Name,
        Reviewed_By__c,
        File_Name__c,
        Attachment_Id__c,
        Reviewed_On__c
      FROM Deal_Document__c
      WHERE advance__c = :advanceId AND Doc_String__C IN :docStringMap.keySet()
      ORDER BY CreatedDate DESC
    ]) {
      String docString = dealDoc.Doc_String__c;
      Map<String, Object> castedMap = (Map<String, Object>) response.get(
        docString
      );
      List<Deal_Document__c> castedList = (List<Deal_Document__C>) castedMap.get(
        'files'
      );
      castedList.add(dealDoc);
    }

    List<Document_Information__c> docInfosToInsert = new List<Document_Information__c>();
    for (String docString : response.keySet()) {
      String docInfoId = (String) response.get(docString).get('docInfoId');

      if (String.isBlank(docInfoId)) {
        docInfosToInsert.add(
          new Document_Information__c(
            Advance__c = advance.Id,
            Deal__c = advance.Deal__c,
            Doc_String__c = docString,
            Internal_Comments__c = ''
          )
        );
      }
      // if(response.get(docString).get(''))
    }

    insert docInfosToInsert;

    for (Document_Information__c docInfo : docInfosToInsert) {
      response.get(docInfo.Doc_String__c).put('docInfoId', docInfo.Id);
      response.get(docInfo.Doc_String__c).put('documentInformation', docInfo);
    }

    Map<String, Map<String, Object>> finalResponse = new Map<String, Map<String, Object>>();

    for (String docString : response.keySet()) {
      String devName = docStringMap.get(docString).replace('_sab', '');
      finalResponse.put(devName, response.get(docString));

      List<Deal_Document__c> dealDocs = (List<Deal_Document__c>) (finalResponse.get(
          devName
        )
        .get('files'));
      finalResponse.get(devName).put('uploaded', dealDocs.size() > 0);
      finalResponse.get(devName).put('reviewed', false);
      finalResponse.get(devName).put('lastReviewed', '');
      finalResponse.get(devName).put('reviewedById', null);
      finalResponse.get(devName).put('reviewedBy', null);
      finalResponse.get(devName).put('filesLength', dealDocs.size());
      if (dealDocs.size() > 0) {
        Boolean allReviewed = true;
        DateTime lastReviewed = null;
        String reviewedBy = null;
        Id reviewedById = null;
        for (Deal_Document__c doc : dealDocs) {
          if (!doc.Reviewed__c) {
            allReviewed = false;
            lastReviewed = null;
          } else {
            reviewedBy = doc.Reviewed_By__r.Name;
            reviewedById = doc.Reviewed_By__c;
          }
          if (lastReviewed == null && allReviewed && doc.Reviewed__c) {
            lastReviewed = doc.Reviewed_On__c;
          }
        }

        if (reviewedBy != null) {
          finalResponse.get(devName).put('reviewedBy', reviewedBy);
          finalResponse.get(devName).put('reviewedById', reviewedById);
        }

        if (lastReviewed != null) {
          finalResponse.get(devName).put('lastReviewed', lastReviewed);
        }
        finalResponse.get(devName).put('reviewed', allReviewed);
      }
    }

    Map<String, Object> advanceObj = new Map<String, Object>();
    advanceObj.put('checklist', advance.Closing_Funds_Checklist__c);
    advanceObj.put('lastReviewed', advance.Closing_Funds_Checklist_Date__c);
    advanceObj.put('comments', advance.Closing_Funds_Checklist_Comments__c);
    advanceObj.put('reviewedById', advance.Closing_Funds_Checked_By__c);
    advanceObj.put('reviewedBy', advance.Closing_Funds_Checked_By__r.Name);
    finalResponse.put('advance', advanceObj);
    Map<String, Object> managerObj = new Map<String, Object>();
    managerObj.put('checklist', advance.Manager_Approved__c);
    managerObj.put('lastReviewed', advance.Manager_Approval_Date__c);
    managerObj.put('comments', advance.Manager_Approval_Comments__c);
    managerObj.put('reviewedById', advance.Manager_Approved_By__c);
    managerObj.put('reviewedBy', advance.Manager_Approved_By__r.Name);
    finalResponse.put('manager', managerObj);
    Map<String, Object> evidenceOfInsuranceObj = new Map<String, Object>();
    evidenceOfInsuranceObj.put(
      'checklist',
      advance.Evidence_of_Insurance_Approved__c
    );
    evidenceOfInsuranceObj.put(
      'lastReviewed',
      advance.Evidence_of_Insurance_Approval_Date__c
    );
    evidenceOfInsuranceObj.put(
      'comments',
      advance.Evidence_of_Insurance_Approval_Comments__c
    );
    evidenceOfInsuranceObj.put(
      'reviewedById',
      advance.Evidence_of_Insurance_Approved_By__c
    );
    evidenceOfInsuranceObj.put(
      'reviewedBy',
      advance.Evidence_of_Insurance_Approved_By__r.Name
    );
    finalResponse.put('evidenceOfInsurance', evidenceOfInsuranceObj);
    Map<String, Object> floodCertificateObj = new Map<String, Object>();
    floodCertificateObj.put('checklist', advance.Flood_Certificate_Approved__c);
    floodCertificateObj.put(
      'lastReviewed',
      advance.Flood_Certificate_Approval_Date__c
    );
    floodCertificateObj.put(
      'comments',
      advance.Flood_Certificate_Approval_Comments__c
    );
    floodCertificateObj.put(
      'reviewedById',
      advance.Flood_Certificate_Approved_By__c
    );
    floodCertificateObj.put(
      'reviewedBy',
      advance.Flood_Certificate_Approved_By__r.Name
    );
    finalResponse.put('floodCertificate', floodCertificateObj);

    //

    return JSON.serialize(finalResponse);
  }
}