force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Inspection</fullName>
            </value>
            <value>
                <fullName>Pending Inspection Report Revision</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Capital Partner Release</fullName>
            </value>
            <value>
                <fullName>Pending Release</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact_Type__c</fullName>
    <label>Deal Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Loan Application Entity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Portal Access</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>EscrowAgent</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>TitleCompany</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Title</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borrower Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Diligence Review</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Escrow Agent</fullName>
            </value>
            <value>
                <fullName>Flood Check</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Insurance Review</fullName>
            </value>
            <value>
                <fullName>Lease/Purchase Review</fullName>
            </value>
            <value>
                <fullName>Lender Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Lender Local Legal Counsel</fullName>
            </value>
            <value>
                <fullName>PCA &amp; ESA</fullName>
            </value>
            <value>
                <fullName>Reserves</fullName>
            </value>
            <value>
                <fullName>Securitization Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Servicer</fullName>
            </value>
            <value>
                <fullName>Tax Verification</fullName>
            </value>
            <value>
                <fullName>Title and Escrow</fullName>
            </value>
            <value>
                <fullName>Title and Escrow 2</fullName>
            </value>
            <value>
                <fullName>Title Company</fullName>
            </value>
            <value>
                <fullName>Title Review</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Valuations Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Advance_Period__c.field-meta.xml
<CustomField>
    <fullName>Advance_Period__c</fullName>
    <description>Bridge Use</description>
    <label>Advance Period Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Term__c.field-meta.xml
<CustomField>
    <fullName>LOC_Term__c</fullName>
    <businessOwnerGroup>Bridge_Ops</businessOwnerGroup>
    <description>Bridge Use</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>15 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>21 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>30 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>540 Days</fullName>
            </value>
            <value>
                <fullName>630 Days</fullName>
            </value>
            <value>
                <fullName>720 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maturity_Date_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date_Calculation_Type__c</fullName>
    <description>This controls when the Loan Maturity Date is set</description>
    <inlineHelpText>This controls when the Loan Maturity Date is set</inlineHelpText>
    <label>Maturity Date Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed at Closing</fullName>
            </value>
            <value>
                <fullName>Fixed at First Advance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Modified_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Modified_Expiration_Date__c</fullName>
    <description>This Date is populated when a Loan Modification is completed/approved.  This date will populate the Expiration Date via a formula</description>
    <inlineHelpText>This Date is populated when a Loan Modification is completed/approved</inlineHelpText>
    <label>Modified Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stated_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Stated_Maturity_Date__c</fullName>
    <description>The Original Stated Loan Level Maturity Date</description>
    <inlineHelpText>The Original Stated Loan Level Maturity Date</inlineHelpText>
    <label>Original Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Updated_Loan_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Updated_Loan_Maturity_Date__c</fullName>
    <description>This is used to override the Loan Maturity Date for overrides and Loan Modifications</description>
    <label>Current Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <formula>TEXT(Contact.Account.Non_Borrower_Account_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdvanceDealTriggerHelper.cls
public with sharing class AdvanceDealTriggerHelper {
  static final string VALIDADVSTATUS = 'Completed';
  static final string VALIDCALCULATIONTYPE = 'Fixed at First Advance';
  static final string FIRSTCONTACTTYPE = 'Individual';
  static final string ENTITYTYPE = 'Guarantor';
  static final string SECONDCONTACTTYPE = 'Vendor';
  static final string VENDORTYPE = 'Lender Legal Counsel';
  static final List<String> TEAMROLES = new List<String>{
    'Closer',
    'Originator',
    'Sales Analyst'
  };
  static final List<String> USERROLES = new List<String>{
    'Post Closing',
    'Post Closing Manager'
  };
  static final String EMAILDEVNAME = 'Maturity_Date_Set_on_Advance_Completion_1629747645098';
  static final string SENDEREMAIL = 'integrations@cvest.com';

  private static Opportunity getOpportunityForEmail(Id oppId) {
    return [
      SELECT
        Id,
        Contact__c,
        (
          SELECT
            Id,
            Contact__r.Email,
            Contact__c,
            Deal_Contact_Type__c,
            Entity_Type__c,
            Vendor_Type__c
          FROM Deal_Contacts__r
          WHERE
            (Deal_Contact_Type__c = :FIRSTCONTACTTYPE
            AND Entity_Type__c = :ENTITYTYPE
            AND Contact__c != NULL)
            OR (Deal_Contact_Type__c = :SECONDCONTACTTYPE
            AND Vendor_Type__c = :VENDORTYPE
            AND Contact__c != NULL)
        ),
        (
          SELECT
            Id,
            TeamMemberRole,
            UserId,
            User.ContactId,
            User.Email,
            User.FirstName,
            User.LastName
          FROM OpportunityTeamMembers
          WHERE TeamMemberRole IN :TEAMROLES
        )
      FROM Opportunity
      WHERE Id = :oppId
      LIMIT 1
    ];
  }

  public static void sendEmailForDealTrigger(Id dealId, Id templateId) {
    Opportunity opp = getOpportunityForEmail(dealId);

    List<Id> contactIds = new List<Id>();
    List<Id> userIds = new List<Id>();
    List<Id> toIds = new List<Id>();
    List<String> ccEmails = new List<String>();
    List<String> bccEmails = new List<String>();
    // List<Id> allIds = new List<Id>();
    // List<Messaging.SingleEmailMessage> allEmails = new List<Messaging.SingleEmailMessage>();

    Messaging.SingleEmailMessage dealEmail = new Messaging.SingleEmailMessage();

    dealEmail.setTemplateId(templateId);
    dealEmail.setWhatId(opp.Id);
    dealEmail.setSaveAsActivity(false);
    dealEmail.setTargetObjectId(opp.Contact__c);
    dealEmail.setTreatTargetObjectAsRecipient(false);
    bccEmails.add('bryon.harland@cvest.com');

    for (User user : [
      SELECT
        Id,
        FirstName,
        LastName,
        Email,
        isActive,
        Profile.Name,
        UserRole.Name,
        UserType
      FROM User
      WHERE UserRole.Name IN :USERROLES AND isActive = TRUE AND Email != NULL
    ]) {
      // userIds.add(user.Id);
      // allIds.add(user.Id);
      ccEmails.add(user.Email);
    }

    if (opp.Deal_Contacts__r.size() > 0) {
      for (integer i = 0; i < opp.Deal_Contacts__r.size(); i++) {
        Deal_Contact__c dealContact = opp.Deal_Contacts__r[i];
        // allIds.add(dealContact.Contact__c);
        if (
          dealContact.Deal_Contact_Type__c == FIRSTCONTACTTYPE &&
          dealContact.Entity_Type__c == ENTITYTYPE
        ) {
          if (i == 0) {
            dealEmail.setTargetObjectId(dealContact.Contact__c);
          } else {
            toIds.add(dealContact.Contact__c);
          }
        } else {
          // contactIds.add(dealContact.Contact__c);
          ccEmails.add(dealContact.Contact__r.Email);
        }
      }
    }

    if (opp.OpportunityTeamMembers.size() > 0) {
      for (OpportunityTeamMember teamMember : opp.OpportunityTeamMembers) {
        // userIds.add(teamMember.UserId);
        // allIds.add(teamMember.UserId);
        ccEmails.add(teamMember.User.Email);
      }
    }

    dealEmail.setToAddresses(toIds);
    dealEmail.setCcAddresses(ccEmails);
    dealEmail.setBccAddresses(bccEmails);
    dealEmail.setUseSignature(false);

    List<OrgWideEmailAddress> owea = [
      SELECT Id
      FROM OrgWideEmailAddress
      WHERE Address = :SENDEREMAIL
    ];
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    if (owea.size() > 0) {
      dealEmail.setOrgWideEmailAddressId(owea.get(0).Id);
    }

    // for (Id id : allIds) {
    //   Messaging.SingleEmailMessage newEmail = Messaging.renderStoredEmailTemplate(
    //     templateId,
    //     id,
    //     opp.Id
    //   );
    //   // String emailSubject = newEmail.getSubject();
    //   // String emailTextBody = newEmail.getPlainTextBody();

    //   newEmail.setTargetObjectId(id);
    //   // newEmail.setSubject(emailSubject);
    //   // newEmail.setPlainTextBody(emailTextBody);
    //   newEmail.saveAsActivity = false;

    //   allEmails.add(newEmail);
    // }

    List<Messaging.SendEmailResult> results = Messaging.sendEmail(
      new List<Messaging.SingleEmailMessage>{ dealEmail }
    );

    // List<Messaging.SendEmailResult> results = Messaging.sendEmail(allEmails);

    if (results[0].success) {
      System.debug('The email was sent successfully : ' + results);
    } else {
      System.debug(
        'The email failed to send:  ' + results[0].errors[0].message
      );
    }
  }

  public static void advanceDealTriggerHelperMethod(
    Advance__c triggerNew,
    Advance__c triggerOld
  ) {
    Boolean shouldProceed = true;

    if (triggerOld != null && triggerNew.Status__c == triggerOld.Status__c) {
      shouldProceed = false;
    }

    if (
      shouldProceed &&
      triggerNew.Status__c == VALIDADVSTATUS &&
      triggerNew.Deal__c != null
    ) {
      List<Opportunity> deals = [
        SELECT
          Id,
          Maturity_Date_Calculation_Type__c,
          Stated_Maturity_Date__c,
          Advance_Period__c,
          LOC_Term__c,
          CloseDate
        FROM Opportunity
        WHERE
          Id = :triggerNew.Deal__c
          AND Maturity_Date_Calculation_Type__c = :VALIDCALCULATIONTYPE
          AND Stated_Maturity_Date__c = NULL
      ];

      System.debug('advance trigger for deal has started');

      if (deals.size() > 0) {
        System.debug('advance trigger for deal has returned the query');
        Opportunity updatedDeal = deals[0];
        System.debug('deal from trigger : ' + updatedDeal);

        if (updatedDeal.Advance_Period__c != null) {
          updatedDeal.Modified_Expiration_Date__c = updatedDeal.CloseDate
            .addDays(Integer.valueOf(updatedDeal.Advance_Period__c));
        }

        if (!string.isBlank(updatedDeal.LOC_Term__c)) {
          List<String> locTerm = updatedDeal.LOC_Term__c.split(' ');
          Integer locTermNumber = Integer.valueOf(locTerm[0]);
          updatedDeal.Stated_Maturity_Date__c = updatedDeal.CloseDate
            .addDays(locTermNumber);
          updatedDeal.Updated_Loan_Maturity_Date__c = updatedDeal.CloseDate
            .addDays(locTermNumber);
        }

        EmailTemplate tpl = [
          SELECT Id
          FROM EmailTemplate
          WHERE DeveloperName = :EMAILDEVNAME
          LIMIT 1
        ];

        try {
          update updatedDeal;
          sendEmailForDealTrigger(updatedDeal.Id, tpl.Id);
        } catch (DmlException err) {
          System.debug('deal update on trigger error: ' + err);
        }
      }
    }
  }
}