force-app/main/default/objects/Advance__c/Advance__c.object-meta.xml
<CustomObject>
    <label>Advance</label>
    <nameField>
        <label>Advance #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>dsfs__DocuSign_Status__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Batch_Approval__c.field-meta.xml
<CustomField>
    <fullName>Batch_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance Approval</label>
    <referenceTo>Batch_Approval__c</referenceTo>
    <relationshipLabel>Advances</relationshipLabel>
    <relationshipName>Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Inspection</fullName>
            </value>
            <value>
                <fullName>Pending Inspection Report Revision</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Capital Partner Release</fullName>
            </value>
            <value>
                <fullName>Pending Release</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <inlineHelpText>The Type of Approval Process</inlineHelpText>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Review</fullName>
            </value>
            <value>
                <fullName>Submission into UW</fullName>
            </value>
            <value>
                <fullName>GLC Approval</fullName>
            </value>
            <value>
                <fullName>Term Sheet Approval</fullName>
            </value>
            <value>
                <fullName>Approved By GLC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <label>Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Batch_Approval__c.field-meta.xml
<CustomField>
    <fullName>Batch_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Approval</label>
    <referenceTo>Batch_Approval__c</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Approval__c/Batch_Approval__c.object-meta.xml
<CustomObject>
    <label>Batch Approval</label>
    <nameField>
        <displayFormat>B-{MMDDYYYY}-{000}</displayFormat>
        <label>Batch Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Approval__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance</label>
    <referenceTo>Advance__c</referenceTo>
    <relationshipLabel>Advance Approvals</relationshipLabel>
    <relationshipName>Advance_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Approval__c/fields/Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approval_Comments__c</fullName>
    <label>Approval Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Approval__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance IC Approval</fullName>
            </value>
            <value>
                <fullName>Advance Batch Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Approval__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Approver__c/Batch_Approver__c.object-meta.xml
<CustomObject>
    <label>Advance Approver</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Batch Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advance Approvers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Approver__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch_Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Approver__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <formula>Approver__r.FirstName + &quot; &quot; + Approver__r.LastName</formula>
    <label>Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Approver__c/fields/Batch_Approval__c.field-meta.xml
<CustomField>
    <fullName>Batch_Approval__c</fullName>
    <label>Batch Approval</label>
    <referenceTo>Batch_Approval__c</referenceTo>
    <relationshipName>Batch_Approvers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch_Approver__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Approver__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Batch_Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchApproverHelper.cls
public without sharing class BatchApproverHelper {
  public static void beforeUpdate(
    Map<Id, Batch_Approver__c> oldMap,
    Map<Id, Batch_Approver__c> newMap
  ) {
    for (Batch_Approver__c newBa : newMap.values()) {
      Batch_Approver__c oldBa = oldMap.get(newBa.Id);

      if (newBa.Status__c == 'Approved' && oldBa.Status__c != newBa.Status__c) {
        newBa.Approval_Date__c = System.today();
      }
    }
  }

  public static void afterUpdate(
    Map<Id, Batch_Approver__c> oldMap,
    Map<Id, Batch_Approver__c> newMap
  ) {
    List<Batch_Approver__c> updateComments = new List<Batch_Approver__c>();
    Map<Id, Map<Id, Batch_Approver__c>> updateStatusMap = new Map<Id, Map<Id, Batch_Approver__c>>();
    Map<Id, String> approvedMap = new Map<Id, String>();
    for (Batch_Approver__c newBa : newMap.values()) {
      Batch_Approver__c oldBa = oldMap.get(newBa.Id);

      if (oldBa.Status__c != newBa.Status__c && newBa.Status__c == 'Approved') {
        approvedMap.put(newBa.Batch_Approval__c, newBa.Approver_Name__c);
      }

      if (
        oldBa.Comments__c != newBa.Comments__c &&
        String.isNotEmpty(newBa.Comments__c)
      ) {
        updateComments.add(newBa);
      }

      if (oldBa.Status__c != newBa.Status__c) {
        if (!updateStatusMap.containsKey(newBa.Batch_Approval__c)) {
          updateStatusMap.put(
            newBa.Batch_Approval__c,
            new Map<Id, Batch_Approver__c>{ newBa.Approver__c => newBa }
          );
        } else {
          Map<Id, Batch_Approver__c> subMap = updateStatusMap.get(
            newBa.Batch_Approval__c
          );
          subMap.put(newBa.Approver__c, newBa);
          updateStatusMap.put(newBa.Batch_Approval__c, subMap);
        }
      }
    }

    if (approvedMap.size() > 0) {
      postApprovalChatter(approvedMap);
    }

    if (updateComments.size() > 0) {
      updateCommentsOnParent(updateComments);
    }

    if (updateStatusMap.size() > 0) {
      updateApprovalHistories(updateStatusMap);
    }
  }

  public static void postApprovalChatter(Map<Id, String> appMap) {
    List<ConnectApi.BatchInput> feedElements = new List<ConnectApi.BatchInput>();

    for (Batch_Approval__c ba : [
      SELECT
        Id,
        Submitted_By__c,
        Approval_Type__c,
        Advance__c,
        (
          SELECT Id, Approver__c, Approver_Name__c, Comments__c, Status__c
          FROM Batch_Approvers__r
        )
      FROM Batch_Approval__c
      WHERE Id IN :appMap.keySet()
    ]) {
      List<Id> mentionIds = new List<Id>();
      mentionIds.add(ba.Submitted_By__c);
      String comment = 'Approver comment: ';
      if (ba.Batch_Approvers__r != null && ba.Batch_Approvers__r.size() > 0) {
        for (Batch_Approver__c bapp : ba.Batch_Approvers__r) {
          mentionIds.add(bapp.Approver__c);
          if (
            appMap.get(ba.Id) == bapp.Approver_Name__c &&
            bapp.Status__c == 'Approved'
          ) {
            comment += bapp.Comments__c;
          }
        }
      }

      feedElements.add(
        BatchApprovalHelper.constructBatchChatterPost(
          'This ' + ba.Approval_Type__c + ' has been approved by ' +
          appMap.get(ba.Id) +
          '.\n' +
          comment,
          (ba.Approval_Type__c == 'Advance Batch Approval'
            ? ba.Id
            : ba.Advance__c),
          mentionIds
        )
      );
    }

    if (!test.isRunningTest()) {
      BatchApprovalHelper.postChatterBatch(feedElements);
    }
  }

  public static void updateApprovalHistories(
    Map<Id, Map<Id, Batch_Approver__c>> objMap
  ) {
    List<Approval_History__c> appHistories = new List<Approval_History__c>();

    for (Approval_History__c appHis : [
      SELECT Id, Batch_Approval__c, Status__c, Actor__c, Comments__c
      FROM Approval_History__c
      WHERE Batch_Approval__c IN :objMap.keySet()
    ]) {
      Map<Id, Batch_Approver__c> actorMap = objMap.get(
        appHis.Batch_Approval__c
      );
      if (actorMap.containsKey(appHis.Actor__c)) {
        Batch_Approver__c ba = actorMap.get(appHis.Actor__c);
        appHistories.add(
          new Approval_History__c(
            Id = appHis.Id,
            Status__c = ba.Status__c,
            Comments__c = ba.Comments__c
          )
        );
      }
    }

    if (appHistories.size() > 0) {
      update appHistories;
    }
  }

  public static void updateCommentsOnParent(
    List<Batch_Approver__c> batchApprovers
  ) {
    Map<Id, Batch_Approval__c> bApprovals = new Map<Id, Batch_Approval__c>(
      [
        SELECT Id, Approval_Comments__c
        FROM Batch_Approval__c
        WHERE
          Id IN (
            SELECT Batch_Approval__c
            FROM Batch_Approver__c
            WHERE Id IN :batchApprovers
          )
        FOR UPDATE
      ]
    );

    for (Batch_Approver__c ba : batchApprovers) {
      Batch_Approval__c b = bApprovals.get(ba.Batch_Approval__c);
      b.Approval_Comments__c =
        (String.isEmpty(b.Approval_Comments__c)
          ? ''
          : b.Approval_Comments__c + '\n\n') +
        System.today().format() +
        ': ' +
        ba.Approver_Name__c +
        ' : "' +
        ba.Comments__c +
        '"';
      bApprovals.put(ba.Batch_Approval__c, b);
    }

    update bApprovals.values();
  }
}