force-app/main/default/objects/Appraisal__c/Appraisal__c.object-meta.xml
<CustomObject>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal__c/fields/Appraisal_Fee__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Fee__c</fullName>
    <description>Fee associated with the Appraisal performed</description>
    <inlineHelpText>Fee associated with the Appraisal performed</inlineHelpText>
    <label>Appraisal Fee</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Estimated_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Completion_Date__c</fullName>
    <description>Estimated date that the Appraisal Firm will have completed the Appraisal</description>
    <inlineHelpText>Estimated date that the Appraisal Firm will have completed the Appraisal</inlineHelpText>
    <label>Estimated Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Appraisal_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Due_Date__c</fullName>
    <description>Date that the Appraisal ordered is due</description>
    <label>Appraisal Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/BPO_Appraisal_Fee__c.field-meta.xml
<CustomField>
    <fullName>BPO_Appraisal_Fee__c</fullName>
    <label>Appraisal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AppraisalTriggerHelper.cls
public with sharing class AppraisalTriggerHelper {
    public static void afterUpdate(List<Appraisal__c> oldList, List<Appraisal__c> newList) {
        List<Property__c> props = new List<Property__c>();
        for(Integer i = 0; i < newList.size(); i++) {
            Property__c prop = new Property__c();
            Boolean shouldUpdate = false;
            if(oldList[i].Appraisal_Fee__c != newList[i].Appraisal_Fee__c && newList[i].Property__c != null) {
                prop.BPO_Appraisal_Fee__c = newList[i].Appraisal_Fee__c;
                shouldUpdate = true;
            }
            if(oldList[i].Estimated_Completion_Date__c != newList[i].Estimated_Completion_Date__c && newList[i].Property__c != null) {
                prop.Appraisal_Due_Date__c = newList[i].Estimated_Completion_Date__c.date();
                shouldUpdate = true;
            }

            if(shouldUpdate) {
                prop.Id = newList[i].Property__c;
                props.add(prop);
            }
        }

        if(props.size() > 0) {
            updatePropertyFields(props);
        }
        //Property__c
    }

    public static void updatePropertyFields(List<Property__c> props) {
        Database.update(props, false);
    }
}