force-app/main/default/objects/Appraisal__c/Appraisal__c.object-meta.xml
<CustomObject>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Deal_Document__c.field-meta.xml
<CustomField>
    <fullName>Deal_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Document</label>
    <referenceTo>Deal_Document__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Appraisal Order</description>
    <inlineHelpText>Status of the Appraisal Order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Order</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Ordered - Appraiser Accepted</fullName>
            </value>
            <value>
                <fullName>With Vendor</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Vendor Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Revision Required</fullName>
            </value>
            <value>
                <fullName>Revision Sent</fullName>
            </value>
            <value>
                <fullName>Revision Received</fullName>
            </value>
            <value>
                <fullName>In Revision</fullName>
            </value>
            <value>
                <fullName>Reviewed - Remargin Required</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Reassignment Required</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete-Delivered</fullName>
            </value>
            <value>
                <fullName>Complete-Undelivered</fullName>
            </value>
            <value>
                <fullName>Verbal Pending Final</fullName>
            </value>
            <value>
                <fullName>Other Pending Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Appraisal__c.field-meta.xml
<CustomField>
    <fullName>Appraisal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Appraisal Record that this Deal Document is related</description>
    <label>Appraisal</label>
    <referenceTo>Appraisal__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Property__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/AppraisalTests.cls
@isTest
private class AppraisalTests {
    static testmethod void mergeTest(){
        Account acc = Test_Helper.createAccount();
        Contact cont = Test_Helper.createContact( acc );
        Opportunity opp = Test_Helper.createOpportunity( acc, cont );
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Term_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = Test_Helper.createProperties(opp);
        Appraisal__c appraisal = Test_Helper.createAppraisal(opp, properties[0]);
        appraisal.Status__c = 'Complete-Delivered';
        update appraisal;
        Test.startTest();
            AppraisalMergeController.initMergeScreen(opp.Id);
        Test.stopTest();
        
    }

    static testmethod void parserTest(){
        StaticResource xml = [SELECT Id, Body FROM StaticResource WHERE Name = 'AppraisalXMLTest' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.xml',
            VersionData = xml.Body,
            IsMajorVersion = true
        );

        insert cv;
        Id docId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id LIMIT 1].ContentDocumentId;
        Account acc = Test_Helper.createAccount();
        Contact cont = Test_Helper.createContact( acc );
        Opportunity opp = Test_Helper.createOpportunity( acc, cont );
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Term_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = Test_Helper.createProperties(opp);

        Deal_Document__c doc = new Deal_Document__c(
            Deal__c = opp.Id,
            Property__c = properties[0].Id,
            Document_Type__c = 'Valuations'
        );

        insert doc;

        Test.startTest();
            doc.Attachment_Id__c = docId;
            update doc;
            // system.assert(xml != null);
        Test.stopTest();    

        
    }

    static testmethod void parserTestBBG(){
        StaticResource xml = [SELECT Id, Body FROM StaticResource WHERE Name = 'AppraisalBBGXMLTest' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.xml',
            VersionData = xml.Body,
            IsMajorVersion = true
        );

        insert cv;
        Id docId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id LIMIT 1].ContentDocumentId;
        Account acc = Test_Helper.createAccount();
        Contact cont = Test_Helper.createContact( acc );
        Opportunity opp = Test_Helper.createOpportunity( acc, cont );
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Term_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = Test_Helper.createProperties(opp);

        Deal_Document__c doc = new Deal_Document__c(
            Deal__c = opp.Id,
            Property__c = properties[0].Id,
            Document_Type__c = 'Valuations'
        );

        insert doc;

        Test.startTest();
            doc.Attachment_Id__c = docId;
            update doc;
            // system.assert(xml != null);
        Test.stopTest();    

        
    }


}