force-app/main/default/objects/Appraisal__c/Appraisal__c.object-meta.xml
<CustomObject>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <label>Year Built</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Loan_Number__c/Deal_Loan_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Deal Loan Number</label>
</CustomObject>

force-app/main/default/objects/EBI_API_Setting__c/EBI_API_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>EBI API  Connection details</description>
    <label>EBI API Setting</label>
</CustomObject>

force-app/main/default/objects/EBI_API_Setting__c/fields/EBI_AccountC__c.field-meta.xml
<CustomField>
    <fullName>EBI_AccountC__c</fullName>
    <description>EBI Account Construction Loan Monitoring</description>
    <inlineHelpText>EBI Account Construction Loan Monitoring</inlineHelpText>
    <label>EBI_AccountC</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBI_API_Setting__c/fields/EBI_AccountT__c.field-meta.xml
<CustomField>
    <fullName>EBI_AccountT__c</fullName>
    <description>EBI Account Traditional Payload</description>
    <inlineHelpText>EBI Account Traditional Payload</inlineHelpText>
    <label>EBI AccountT</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBI_API_Setting__c/fields/EBI_API_KeyC__c.field-meta.xml
<CustomField>
    <fullName>EBI_API_KeyC__c</fullName>
    <description>EBI API Key Construction</description>
    <inlineHelpText>EBI API Key Construction</inlineHelpText>
    <label>EBI API KeyC</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBI_API_Setting__c/fields/EBI_API_KeyT__c.field-meta.xml
<CustomField>
    <fullName>EBI_API_KeyT__c</fullName>
    <description>EBI API Key Traditional</description>
    <inlineHelpText>EBI API Key Traditional</inlineHelpText>
    <label>EBI API KeyT</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBI_API_Setting__c/fields/EBI_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EBI_EndPoint__c</fullName>
    <description>EBI EndPoint</description>
    <inlineHelpText>EBI End Point URL</inlineHelpText>
    <label>EBI EndPoint</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>This will replace the manual auto assignment</description>
    <displayFormat>{00000}</displayFormat>
    <label>Deal Loan Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>The Loan Number of the Deal associated to this Property</description>
    <label>Deal Loan Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interior_Access_POC__c.field-meta.xml
<CustomField>
    <fullName>Interior_Access_POC__c</fullName>
    <description>Interior Access Point of Contact</description>
    <inlineHelpText>Name of person/company to contact for internal access to this Property</inlineHelpText>
    <label>Interior Access POC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interior_Access_POC_Email__c.field-meta.xml
<CustomField>
    <fullName>Interior_Access_POC_Email__c</fullName>
    <description>Email to contact the person/company regarding internal access to this Property</description>
    <inlineHelpText>Email to contact the person/company regarding internal access to this Property</inlineHelpText>
    <label>Interior Access POC Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interior_Access_POC_Phone__c.field-meta.xml
<CustomField>
    <fullName>Interior_Access_POC_Phone__c</fullName>
    <description>Phone Number to contact the person/company regarding internal access to this Property</description>
    <inlineHelpText>Phone Number to contact the person/company regarding internal access to this Property</inlineHelpText>
    <label>Interior Access POC Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Square_Feet_value__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet_value__c</fullName>
    <formula>VALUE(Square_Feet__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Square Feet value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <label>Year Built</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EBIAPI.cls
public class EBIAPI {

   public static string submitOrder(
    List<Property__c> listProperties,
    String comments,
    Boolean rushOrder,
    List<Appraisal__c> listAppraisal
  ) {

   EBI_API_Setting__c apiSettings = EBI_API_Setting__c.getInstance();
   String EndPoint = apiSettings.EBI_EndPoint__c;
   String APIKeyT = apiSettings.EBI_API_KeyT__c;
   String APIKeyC = apiSettings.EBI_API_KeyC__c;
   String AccountT = apiSettings.EBI_AccountT__c;
   String AccountC = apiSettings.EBI_AccountC__c; 

    System.debug('RS999 APIKeyT :' +APIKeyT);      
	System.debug('RS999 APIKeyC :' +APIKeyC);      
	System.debug('RS999 AccountT :' +AccountT);      
	System.debug('RS999 AccountC :' +AccountC);   
      
    Map<String, String> reqBody = new Map<String, String>();
    String bodyString = '[';
    for (Property__c property : listProperties)
    {
	string 	account_id = AccountT;
    //account_id = AccountC;
	reqBody.put('account_id',account_id);   
    reqBody.put('zip', property.ZipCode__c);      
   // reqBody.put('construction_date', null); 
	reqBody.put('rush order', rushOrder ? 'True' : 'False');      
    reqBody.put('number_of_tenants', '1');      
    reqBody.put('rentable_square_footage', String.Valueof(property.Square_Feet_value__c));      
    reqBody.put('year_built', property.Year_Built__c);       
    reqBody.put('address', property.Name);
    reqBody.put('city', property.City__c);
    reqBody.put('state', property.State__c);
   // reqBody.put('county', property.County__c);
   // reqBody.put('transaction_manager_email','?????');
	reqBody.put('site_contact_number', property.Interior_Access_POC_Phone__c);
	reqBody.put('site_contact_email', property.Interior_Access_POC_Email__c);
	reqBody.put('site_contact', property.Interior_Access_POC__c);
	reqBody.put('seller_name', Null);
    String property_type = 'Other';      
    reqBody.put('property_type', property_type); 
    String project_type = 'Other'; 
    reqBody.put('project_type', project_type);         
	String project_scope = '["ESA AAI-ASTM2021", "PCS", "Zoning Report",  "RDNSMP" ]';
	//project_scope = '[{"name":"CMR", "quantity":"1",  "number_of_services": "6"},{"name":"CPCR", "quantity":"1"}]';     
	project_scope = '["ESA AAI-ASTM2013", "PCS" ]';
    reqBody.put('project_scope', project_scope); 
    reqBody.put('order_number', property.Deal__r.Deal_Loan_Number__c);       
    reqBody.put('order_owner_email', UserInfo.getUserEmail());
    reqBody.put('order_owner_name', UserInfo.getFirstName() + ' ' + UserInfo.getLastName());
    reqBody.put('b2b_opportunity_owner_email', UserInfo.getUserEmail());
   // reqBody.put('operations_manager_email', property.Deal__r.Deal_Loan_Number__c);
    reqBody.put('notes', comments);
    reqBody.put('asset_due_diligence_folder', comments);
    reqBody.put('name', 'RK_QA B2B Holiday skip 0330022 01');
    reqBody.put('external_object_id', listAppraisal[0].id);
    reqBody.put('delivery_request', '15');  
	String generatedBody = generateBody(reqBody);   
    System.debug('RS999 generatedBody : ' +generatedBody);        
    bodyString += generatedBody + ',';
	}
            
    bodyString = bodyString.removeEnd(',');      
    bodyString += ']';
    String generatedBody  = base64URLencode(Blob.valueOf(bodyString));
    System.debug('RS999 bodyString : ' +bodyString);     
      
    Map<String, String> reqHeader = new Map<String, String>();
    reqHeader.put('alg', 'HS256'); 
	reqHeader.put('typ', 'JWT');   
    //reqHeader.put('Content-Type','application/json');
	String generatedHeader = generateBody(reqHeader); 
    generatedHeader = base64URLencode(Blob.valueOf(generatedHeader));
    String encodedString = generatedHeader + '.' + generatedBody;
	Blob hash = Crypto.generateMac('HmacSHA256', Blob.valueOf(bodyString),blob.valueof(APIKeyT));
    encodedString += '.' + base64URLencode(hash); 
    encodedString = '{"jwtString":"' + encodedString + '"}'; 
    System.debug('RS999 encodedString : ' +encodedString); 
    callout(encodedString,EndPoint);     
    return 'sucess';
  }

@future(callout = true)
public static void callout(string encodedString,String EndPoint)
{
	System.debug('RS999 EndPoint : ' +EndPoint);
	System.debug('RS999 encodedString : ' +encodedString);    
    HttpRequest req = new HttpRequest();
    req.setEndpoint(EndPoint);
    req.setMethod('POST');      
    req.setTimeout(120000);
    req.setHeader('alg', 'HS256');
	req.setHeader('typ', 'JWT');   
    req.setHeader('Content-Type','application/json');
    req.setBody(encodedString); //(body);
   // String body = '{"success":true,"appraisal_id":7967,"sequence_number":"1", "file_number":"xyz293", "loan_number":"LN12345678"}';
    if (!Test.isRunningTest()) 
    {
     HttpResponse resp = new Http().send(req);
     String retBody = resp.getBody();
     System.debug('RS999 retBody : ' +retBody);  
    }
 
   /* Map<String, Object> respMap = (Map<String, Object>) JSON.deserializeUntyped(
      body
    );
    if (!(Boolean) respMap.get('success')) {
      system.debug((String) respMap.get('error_code'));
      system.debug((String) respMap.get('error_msg'));
      throw new AuraHandledException(
        'Error: ' +
        (String) respMap.get('error_code') +
        ' ' +
        (String) respMap.get('error_msg')
      );
    }*/    
}
    
public static string generateBody(
    Map<String, String> reqMap
  ) {
      String body = '{';
    for (String key : reqMap.keySet()) {
      if (key == 'project_scope' || key == 'delivery_request' || key == 'year_built' || key == 'number_of_tenants')
      {
       body += '"' + key + '"'  + ':' + reqMap.get(key) +',' ;   
      }
      Else
      {
      body += '"' + key + '"'  + ':' + '"' + reqMap.get(key) +'",' ;
      }
    }
      body = body.removeEnd(',') + '}';
      
    System.debug('RS999 body :' +body);
	//String output = base64URLencode(Blob.valueOf(body));      
    //System.debug('RS999 output(base64Encode) :' +output);
    return body;
  }

public static String base64URLencode(Blob input){ 
    String output = encodingUtil.base64Encode(input);
    output = output.replace('+', '-');
    output = output.replace('/', '_');
    while ( output.endsWith('=')){
        output = output.subString(0,output.length()-1);
    }
    return output;
}    
 
} //class