force-app/main/default/objects/Appraisal__c/Appraisal__c.object-meta.xml
<CustomObject>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal__c/fields/Appraisal_Firm_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Firm_Transaction_ID__c</fullName>
    <description>Transaction ID from the Appraisal Firm</description>
    <inlineHelpText>Transaction ID from the Appraisal Firm</inlineHelpText>
    <label>Appraisal Firm Transaction ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Prevent_Auto_Refresh__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Auto_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will prevent this Property from being refreshed through API during the auto refresh</description>
    <inlineHelpText>This will prevent this Property from being refreshed through API during the auto refresh</inlineHelpText>
    <label>Prevent Auto Refresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Appraisal Order</description>
    <inlineHelpText>Status of the Appraisal Order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Order</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Ordered - Appraiser Accepted</fullName>
            </value>
            <value>
                <fullName>With Vendor</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Vendor Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Revision Required</fullName>
            </value>
            <value>
                <fullName>Revision Sent</fullName>
            </value>
            <value>
                <fullName>Revision Received</fullName>
            </value>
            <value>
                <fullName>In Revision</fullName>
            </value>
            <value>
                <fullName>Reviewed - Remargin Required</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Reassignment Required</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete-Delivered</fullName>
            </value>
            <value>
                <fullName>Complete-Undelivered</fullName>
            </value>
            <value>
                <fullName>Verbal Pending Final</fullName>
            </value>
            <value>
                <fullName>Other Pending Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Vendor_Ordered_From__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Ordered_From__c</fullName>
    <description>This is the Appraisal Vendor that this order was submitted through</description>
    <inlineHelpText>This is the Appraisal Vendor that this order was submitted through</inlineHelpText>
    <label>Vendor Ordered From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appraisal Nation</fullName>
            </value>
            <value>
                <fullName>BBG</fullName>
            </value>
            <value>
                <fullName>Clarocity Valuation Services</fullName>
            </value>
            <value>
                <fullName>Clear Capital</fullName>
            </value>
            <value>
                <fullName>CoreVest Finance</fullName>
            </value>
            <value>
                <fullName>EBI</fullName>
            </value>
            <value>
                <fullName>Individual Licensed Appraiser</fullName>
            </value>
            <value>
                <fullName>Martin Montserrat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>ServiceLink</fullName>
            </value>
            <value>
                <fullName>ServiceLink-Bofi</fullName>
            </value>
            <value>
                <fullName>US RES</fullName>
            </value>
            <value>
                <fullName>Valuation Services AMC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClarocityBatch.cls
global class ClarocityBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public ClarocityBatch() {
    }
  
    global Database.QueryLocator start(Database.BatchableContext BC) {
      String queryString = 'SELECT Id FROM Appraisal__c';
  
      queryString += ' WHERE Appraisal_Firm_Transaction_ID__c != null AND Vendor_Ordered_From__c = \'Clarocity Valuation Services\'';
      queryString += ' AND CreatedDate = LAST_N_DAYS:30 AND Property__c != null';
      queryString += ' AND Status__c != \'Complete-Delivered\' AND Status__c != \'Cancelled\' AND Prevent_Auto_Refresh__c = false';
  
      return Database.getQueryLocator(queryString);
    }
  
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
      for (sobject s : scope) {
        AppraisalMergeController.checkStatus((Id) s.get('Id'));
      }
    }
  
    global void finish(Database.BatchableContext BC) {
    }
  }