force-app/main/default/objects/Out_of_Office__c/Out_of_Office__c.object-meta.xml
<CustomObject>
    <label>Out of Office</label>
    <nameField>
        <label>Out of Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Out of Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Out_of_Office__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Last day user will out of office</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Out_of_Office__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>First day user will out of office</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Out_of_Office__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who will be out of office</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Out_of_Offices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OutOfOfficeHelper.cls
public class OutOfOfficeHelper {
  public static void afterInsert(List<Out_of_Office__c> newList) {
    Set<Id> ids = new Set<Id>();

    final Date TOMORROW = System.today().addDays(1);
    final Date YESTERDAY = System.today().addDays(-1);
    final Date TODAY = System.today();
    for (Out_Of_Office__c oof : newList) {
      if (oof.Start_Date__c <= TODAY && oof.End_Date__c >= YESTERDAY) {
        ids.add(oof.User__c);
      }
    }

    if (ids.size() > 0) {
      updateUsers(ids);
    }
  }

  public static void updateUsers(Set<Id> userIds) {
    List<Janati_RR__Round_Robin_Group_Member__c> toUpdate = new List<Janati_RR__Round_Robin_Group_Member__c>();

    for (Janati_RR__Round_Robin_Group_Member__c rrMember : [
      SELECT Id, Janati_RR__Assignment_Active__c, Janati_RR__User_Rep__c
      FROM Janati_RR__Round_Robin_Group_Member__c
      WHERE Janati_RR__User_Rep__c IN :userIds
    ]) {
      rrMember.Janati_RR__Assignment_Active__c = false;

      toUpdate.add(rrMember);
    }

    if (toUpdate.size() > 0) {
      update toUpdate;
    }
  }
}