force-app/main/default/objects/Out_of_Office__c/Out_of_Office__c.object-meta.xml
<CustomObject>
    <label>Out of Office</label>
    <nameField>
        <label>Out of Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Out of Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Out_of_Office__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Last day user will out of office</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Out_of_Office__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>First day user will out of office</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Out_of_Office__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who will be out of office</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Out_of_Offices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OutOfOfficeSchedulableTests.cls
@isTest
private class OutOfOfficeSchedulableTests {

    @TestSetup
    static void makeData(){
        // Janati_RR__Round_Robin_Assignment__c assignment = new Janati_RR__Round_Robin_Assignment__c();
        // assignment.Name = 'test';
        // insert assignment;



        // Janati_RR__Round_Robin_Group_Member__c gm = new Janati_RR__Round_Robin_Group_Member__c();
        // gm.Janati_RR__User_Rep__c = UserInfo.getUserId();
        // gm.Janati_RR__Assignment_Active__c = true;
        // gm.Janati_RR__Round_Robin_Assignment__c = assignment.Id;

        // insert gm;
    }

    @IsTest
    static void methodName(){
        User u = [SELECT Id FROM User WHERE Profile.Name = 'Relationship Manager' LIMIT 1];
        Test.startTest();
            Out_of_Office__c oof = new Out_Of_Office__c();
            oof.Start_Date__C = system.today();
            oof.End_Date__c = system.today().addDays(1);
           oof.User__c = u.Id;
            insert oof;

        Test.stopTest();
        
    }
@IsTest
    static void unitTest2(){
        User u = [SELECT Id FROM User WHERE Profile.Name = 'Relationship Manager' LIMIT 1];
        Test.startTest();
            Out_of_Office__c oof = new Out_Of_Office__c();
            oof.Start_Date__C = system.today().addDays(-1);
            oof.End_Date__c = system.today().addDays(-1);
            oof.User__c = u.Id;
            insert oof;

            OutOfOfficeSchedulable.checkOOF();

        Test.stopTest();
    }
@IsTest
    static void unitTest1(){
        User u = [SELECT Id FROM User WHERE Profile.Name = 'Relationship Manager' LIMIT 1];
        Test.startTest();
            Out_of_Office__c oof = new Out_Of_Office__c();
            oof.Start_Date__C = system.today().addDays(1);
            oof.End_Date__c = system.today().addDays(1);
            oof.User__c = u.Id;
            insert oof;

            OutOfOfficeSchedulable.checkOOF();

        Test.stopTest();
    }
}