force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/DealID__c.field-meta.xml
<CustomField>
    <fullName>DealID__c</fullName>
    <description>Deal Loan Number from the Deal</description>
    <formula>Deal__r.Deal_Loan_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field to show the Deal Loan Number</inlineHelpText>
    <label>Deal Loan number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Parent__c.field-meta.xml
<CustomField>
    <fullName>Is_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this property is a parent in a multi unit property</description>
    <label>Is Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/Validated_Property_Address__c.object-meta.xml
<CustomObject>
    <description>This is the Object that gets created when a Property record is created and an API (currently Smartystreets) is called</description>
    <label>Validated Property Address</label>
    <nameField>
        <displayFormat>VPA-{0000000}</displayFormat>
        <label>Validated Property Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Validated Property Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Validated_Property_Address__c/fields/DealId__c.field-meta.xml
<CustomField>
    <fullName>DealId__c</fullName>
    <formula>CASESAFEID(Property__r.Deal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DealId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/Has_Same_Name__c.field-meta.xml
<CustomField>
    <fullName>Has_Same_Name__c</fullName>
    <description>Checked is the Street Address, City Name and Zipcode are the same on the Property as they are on the Validated Property Address record</description>
    <formula>AND(LOWER(VAddress1__c) == LOWER(Property__r.Name),  LOWER(Vcity_name__c)  == LOWER(Property__r.City__c),  Vzipcode__c == Property__r.ZipCode__c, LOWER(Vcounty_name__c) == LOWER(Property__r.County__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Checked is the Street Address, City Name and Zipcode are the same on the Property as they are on the Validated Property Address record</inlineHelpText>
    <label>Has Same Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Validated Property Addresses</relationshipLabel>
    <relationshipName>Validated_Property_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/VAddress1__c.field-meta.xml
<CustomField>
    <fullName>VAddress1__c</fullName>
    <label>Verified First Address Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/Vcity_name__c.field-meta.xml
<CustomField>
    <fullName>Vcity_name__c</fullName>
    <description>The USPS-preferred city name for this particular address, or an acceptable alternate if provided by the user.</description>
    <inlineHelpText>The USPS-preferred city name for this particular address, or an acceptable alternate if provided by the user</inlineHelpText>
    <label>Verified city name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/Vcounty_name__c.field-meta.xml
<CustomField>
    <fullName>Vcounty_name__c</fullName>
    <description>The name of the county the address is in.</description>
    <label>Verified county name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/Vstate_abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Vstate_abbreviation__c</fullName>
    <description>The two-letter state abbreviation.</description>
    <inlineHelpText>The two-letter state abbreviation.</inlineHelpText>
    <label>Verified state abbreviation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validated_Property_Address__c/fields/Vzipcode__c.field-meta.xml
<CustomField>
    <fullName>Vzipcode__c</fullName>
    <description>The 5-digit ZIP Code.</description>
    <inlineHelpText>The 5-digit ZIP Code</inlineHelpText>
    <label>Verified zipcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ValidatedAddressController.cls
public with sharing class ValidatedAddressController {
  public static Map<String, String> MERGE_MAP = new Map<String, String>{
    'VAddress1__c' => 'Name',
    'Vcity_name__c' => 'City__c',
    'Vstate_abbreviation__c' => 'State__c',
    'Vzipcode__c' => 'ZipCode__c',
    'Vcounty_name__c' => 'County__c'
  };

  public static Map<String, Schema.SObjectField> VALIDATEDADDRESS_FIELD_MAP = Schema.SObjectType.Validated_Property_Address__c.fields.getMap();
  public static Map<String, Schema.SObjectField> PROPERTY_FIELD_MAP = Schema.SObjectType.Property__c.fields.getMap();

  @AuraEnabled
  public static List<List<MergeWrapper>> initMergeScreen(String recordId) {
    String queryString = compileQueryString(recordId);

    List<MergeWrapper> wrappers = new List<MergeWrapper>();
    for (
      Validated_Property_Address__c validatedAddress : (List<Validated_Property_Address__c>) database.query(
        queryString
      )
    ) {
      wrappers.add(new MergeWrapper(validatedAddress));
    }

    Map<Id, List<MergeWrapper>> mergeMap = new Map<Id, List<MergeWrapper>>();
    for (MergeWrapper wrapper : wrappers) {
      if (!mergeMap.containsKey(wrapper.propertyId)) {
        mergeMap.put(wrapper.propertyId, new List<MergeWrapper>());
      }
      mergeMap.get(wrapper.propertyId).add(wrapper);
    }

    for (
      Property__c p : (List<Property__c>) database.query(
        compilePropertyQueryString(recordId)
      )
    ) {
      mergeMap.put(p.Id, new List<MergeWrapper>{ new MergeWrapper(p) });
    }

    return mergeMap.values();
  }

  public static string compileQueryString(String dealId) {
    String queryString = 'SELECT Id, ';
    for (String validatedAddressField : MERGE_MAP.keySet()) {
      queryString += validatedAddressField + ', ';
      if (String.isNotBlank(MERGE_MAP.get(validatedAddressField))) {
        queryString +=
          'Property__r.' +
          MERGE_MAP.get(validatedAddressField) +
          ', ';
      }
    }

    queryString += 'Property__c';

    //queryString = queryString.substringBeforeLast(',');

    queryString +=
      ' FROM Validated_Property_Address__c WHERE DealId__c =\'' +
      dealId +
      '\'';
    //queryString += ' AND Property__r.Is_Parent__c = false';
    queryString += ' AND Property__c != null';
    queryString += ' AND Property__r.Status__c NOT IN (\'Rescinded\',\'Cancelled\',\'Sold\',\'Inactive\')';
    queryString += ' AND Property__r.Is_Parent__c = false';
    queryString += ' AND Has_Same_Name__c = false';
    queryString += ' Order By CreatedDate DESC';
    //system.debug('--query string--');
    //system.debug(queryString);
    return queryString;
  }

  public static string compilePropertyQueryString(String dealId) {
    String queryString = 'SELECT Id, ';
    for (String validatedAddressField : MERGE_MAP.keySet()) {
      //queryString += validatedAddressField + ', ';
      if (String.isNotBlank(MERGE_MAP.get(validatedAddressField))) {
        queryString += MERGE_MAP.get(validatedAddressField) + ', ';
      }
    }

    //queryString += 'Property__c';

    queryString = queryString.substringBeforeLast(',');

    queryString += ' FROM Property__c WHERE Deal__c =\'' + dealId + '\'';
    queryString += ' AND ID NOT IN (select property__c from Validated_Property_Address__c) ';
    // queryString += ' AND Property__c != null';
    // queryString += ' AND Status__c = "Active"';
    queryString += ' AND Is_Parent__c = false';
    // queryString += ' AND Has_Same_Name__c = false';
    queryString += ' Order By CreatedDate DESC';
    return queryString;
  }

  public class MergeField {
    @AuraEnabled
    public String propertyFieldLabel;
    @AuraEnabled
    public String propertyAPIFieldName;
    @AuraEnabled
    public String propertyFieldType;
    @AuraEnabled
    public Object propertyValue;

    @AuraEnabled
    public String validatedAddressFieldLabel;
    @AuraEnabled
    public String validatedAddressAPIFieldName;
    @AuraEnabled
    public Object validatedAddressValue;
    @AuraEnabled
    public String validatedAddressFieldType;
  }

  public class MergeWrapper {
    @AuraEnabled
    public Boolean isEmpty = true;
    @AuraEnabled
    public List<MergeField> fields;
    @AuraEnabled
    public Boolean checked;
    @AuraEnabled
    public String validatedAddressId;
    @AuraEnabled
    public String propertyId;

    @AuraEnabled
    public String formId;

    MergeWrapper(Property__c invalidProperty) {
      // validatedAddressId = validatedAddress.Id;
      propertyId = invalidProperty.Id;
      checked = false;
      fields = new List<MergeField>();
      isEmpty = true;
      for (String validatedAddressField : MERGE_MAP.keySet()) {
        MergeField field = new MergeField();

        Schema.DescribeFieldResult validatedAddressDFR = VALIDATEDADDRESS_FIELD_MAP.get(
            validatedAddressField
          )
          .getDescribe();
        field.validatedAddressFieldType = validatedAddressDFR.getType().name();
        field.validatedAddressAPIFieldName = validatedAddressField;
        field.validatedAddressFieldLabel = validatedAddressDFR.getLabel();
        // field.validatedAddressValue = validatedAddress.get(validatedAddressField);

        if (String.isNotBlank(MERGE_MAP.get(validatedAddressField))) {
          Schema.DescribeFieldResult propertyDFR = PROPERTY_FIELD_MAP.get(
              MERGE_MAP.get(validatedAddressField)
            )
            .getDescribe();
          field.propertyFieldType = propertyDFR.getType().name();
          field.propertyAPIFieldName = MERGE_MAP.get(validatedAddressField);
          field.propertyFieldLabel = propertyDFR.getLabel();
          field.propertyValue = invalidProperty.get(
            MERGE_MAP.get(validatedAddressFIeld)
          );
        }

        if (field.validatedAddressFieldLabel == 'Created Date') {
          field.validatedAddressFieldLabel = 'Uploaded Date';
        }

        fields.add(field);
      }
    }

    MergeWrapper(Validated_Property_Address__c validatedAddress) {
      validatedAddressId = validatedAddress.Id;
      propertyId = validatedAddress.Property__c;
      checked = false;
      fields = new List<MergeField>();
      isEmpty = false;
      for (String validatedAddressField : MERGE_MAP.keySet()) {
        MergeField field = new MergeField();

        Schema.DescribeFieldResult validatedAddressDFR = VALIDATEDADDRESS_FIELD_MAP.get(
            validatedAddressField
          )
          .getDescribe();
        field.validatedAddressFieldType = validatedAddressDFR.getType().name();
        field.validatedAddressAPIFieldName = validatedAddressField;
        field.validatedAddressFieldLabel = validatedAddressDFR.getLabel();
        field.validatedAddressValue = validatedAddress.get(
          validatedAddressField
        );

        if (String.isNotBlank(MERGE_MAP.get(validatedAddressField))) {
          Schema.DescribeFieldResult propertyDFR = PROPERTY_FIELD_MAP.get(
              MERGE_MAP.get(validatedAddressField)
            )
            .getDescribe();
          field.propertyFieldType = propertyDFR.getType().name();
          field.propertyAPIFieldName = MERGE_MAP.get(validatedAddressField);
          field.propertyFieldLabel = propertyDFR.getLabel();
          field.propertyValue = validatedAddress.getSobject('Property__r')
            .get(MERGE_MAP.get(validatedAddressFIeld));
        }

        if (field.validatedAddressFieldLabel == 'Created Date') {
          field.validatedAddressFieldLabel = 'Uploaded Date';
        }

        fields.add(field);
      }
    }
  }

  @AuraEnabled
  public static void callSmartyStreets(List<Id> propertyIds) {
    system.debug('hit here?');
    List<Validated_Property_Address__c> validatedAddressess = SmartyStreetsAPI.doCallout(
      propertyIds
    );
    insert validatedAddressess;

    return;
  }
}