force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Estimated_Rent__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Rent__c</fullName>
    <description>Estimated Rent Retrieved from Beekin Interface</description>
    <label>Estimated Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Invalid_Address__c.field-meta.xml
<CustomField>
    <fullName>Invalid_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invalid Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Bath__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Beds__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Beds__c</fullName>
    <label>Beds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <label>Pool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet__c</fullName>
    <label>Square Feet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <label>Year Built</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_AVM__c/Property_AVM__c.object-meta.xml
<CustomObject>
    <description>Automated valuation model (AVM) is the name given to a service that can provide real estate property valuations using mathematical modelling combined with a database. Most AVMs calculate a property&apos;s value at a specific point in time by analyzing values of comparable properties.</description>
    <label>Property AVM</label>
    <nameField>
        <displayFormat>PAVM-{0000000}</displayFormat>
        <label>Property AVM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property AVMs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_AVM__c/fields/Estimated_Rent__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Rent__c</fullName>
    <description>Estimated Rent Retrieved from Beekin API</description>
    <label>Estimated Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_AVM__c/fields/pool__c.field-meta.xml
<CustomField>
    <fullName>pool__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the property has a pool</description>
    <inlineHelpText>Whether the property has a pool</inlineHelpText>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_AVM__c/fields/property_type__c.field-meta.xml
<CustomField>
    <fullName>property_type__c</fullName>
    <description>Type of property. One of [Single Family Residential, Townhouse, Condominium, Manufactured/Mobile Home, Multi-Family, Land, Timeshare, Commercial, Other]</description>
    <inlineHelpText>Type of property. One of [Single Family Residential, Townhouse, Condominium, Manufactured/Mobile Home, Multi-Family, Land, Timeshare, Commercial, Other]</inlineHelpText>
    <label>Property type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BeekinAPI.cls
public class BeekinAPI {
    public static Red_Bell_Settings__c BeekinSettings = Red_bell_Settings__c.getInstance();
    static String USERNAME = BeekinSettings.Username__c;
    static String PASSWORD = BeekinSettings.Password__c;
    static String GRANT_TYPE = BeekinSettings.Grant_Type__c;
    static String BASE_URL = BeekinSettings.Endpoint__c;
    static String ACCESS_TOKEN;
    static Boolean RETRIED_AUTH = False;

    @auraEnabled
    public static Map<String, Object> getProperties(Id recordId) {
        Map<String, Object> response = new Map<String, Object>();
        
        List<Property__c> properties = [SELECT Id, Name, City__c, State__c, ZipCode__c, Status__c, Number_of_Beds__c, Number_of_Bath__c
                                        , Square_Feet__c, Year_Built__c, Pool__c, Property_Type__c, Invalid_Address__c,
											(Select Estimated_Rent__c,Estimated_Min_Rent__c,Estimated_Max_Rent__c
											from Property_AVMs__r where recordtypeid = '012780000008V3MAAU')
                                        FROM Property__c
                                        WHERE
                                            Property__c.Deal__c = :recordId AND Status__c NOT IN ('Inactive','Cancelled','Rescinded')
                                        AND
                                            Property__c.ZipCode__c != null AND 
                                            (Property__c.Property_Type__c = null OR Property__c.Property_Type__c = 'SFR' 
                                             OR Property__c.Property_Type__c = 'Condo' OR Property__c.Property_Type__c = 'Townhome' 
                                             OR (Property__c.Property_Type__c = '2-4 Unit' AND Property__c.Is_Parent__c = true))
                                        ORDER BY Property_Name__c
                                        ];

        System.debug('RS999 property :' +properties);
        response.put('properties', properties);
        return response;
    }

    public class TokenResponse {
        String access_token;
        String token_type;
        Integer expires_in;
        String error;
        String error_description;
    }

    public class AveResponse {
        AveData ave;
        Integer status;
        String message;
    }

    public class AveData {
        AveSubjectData subject;
        AveCompData comps;
    }

    public class AveSubjectData {
        String address;
        String city;
        String state;
        String zip;
        Decimal bed;
        Decimal bath;
        Decimal sqft;
        String propertyType;
        Boolean Pool;
    }

    public class AveCompData {
        Integer estimatedRent;
        Integer estimatedMinRent;
        Integer estimatedMaxRent;
        }

    public static void throwError(String errorMsg) {
        AuraHandledException ex = new AuraHandledException(errorMsg);
        ex.setMessage(errorMsg);
        throw ex;
    }

    @auraEnabled
    public static Map<String, Object> callBeekin(List<Property__c> properties, Id recordId) {
        System.debug(properties);
        AveResponse aveResponse;

        getAccessToken();
        for (Property__c prop : properties) {
            getAveData(prop);
        }
        System.debug(998);
        update properties;
        System.debug(999);
        return getProperties(recordId);
    }

    @auraEnabled
    public static Map<String, Object> callBeekinSingle(Property__c property, Id recordId) {
        System.debug(property);
        AveResponse aveResponse;

        getAccessToken();
        getAveData(property);
        System.debug(998);
        update property;
        System.debug(999);
        return getProperties(recordId);
    }

    public static void getAccessToken() {
        Map<String, String> parameters;
        Map<String, String> headers;
        String endpoint;
        String method;
        String body;
        String rawJSON;
        TokenResponse tokenResponse;

        parameters = new Map<String, String>();
        parameters.put('grant_type', GRANT_TYPE);
        parameters.put('username', USERNAME);
        parameters.put('password', PASSWORD);

        body = getBodyString(parameters);

        headers = new Map<String, String>();
        headers.put('Content-Type', 'application/x-www-form-urlencoded');
        headers.put('Content-Length', String.valueOf(body.length()));
        headers.put('Accept', 'application/json');

        endpoint = BASE_URL + '/token';

        method = 'POST';

        System.debug('body:');
        System.debug(body);
        System.debug(endpoint);

        rawJSON = callOut(method, endpoint, body, headers);

        System.debug(444);
        System.debug(rawJSON);

        TokenResponse = (TokenResponse)JSON.deserialize(rawJSON, TokenResponse.class);

        if (TokenResponse.error != null && TokenResponse.error_description != null) {
            throwError(TokenResponse.error_description);
        }
        else if (TokenResponse.error != null) {
            throwError(TokenResponse.error);
        }
        else {
            ACCESS_TOKEN = TokenResponse.access_token;
        }
    }

    public static void getAveData(Property__c prop) {
        Map<String, String> parameters;
        Map<String, String> headers;
        String endpoint;
        String method;
        String body;
        String rawJSON;
        AveResponse aveResponse;

        string noofbeds = string.valueof(prop.Number_of_Beds__c);
        string noofbath = string.valueof(prop.Number_of_Bath__c);
        string sqft = string.valueof(prop.Square_Feet__c);
        
        String pool = 'false';
        
        if (prop.pool__c == 'Y')
        {
           pool = 'true'; 
        }
        
        string propertytype;
      
        switch on  prop.Property_Type__c
         {
             when 'a' {
                 propertytype = '0';
             }
             when 'b' {
                 propertytype = '1';
             }
             when 'c' {
                 propertytype = '2';
             }
             when 'd' {
                 propertytype = '3';
             }             
        }
            
        parameters = new Map<String, String>{'Address'=>prop.Name, 'Sqft'=>sqft, 'beds'=>noofbeds, 'bath'=>noofbath, 'pool'=>pool, 'property_type'=>propertytype};
        body = JSON.serialize(parameters);
        System.debug(body);

        headers = new Map<String, String>();
        headers.put('Authorization', 'bearer ' + ACCESS_TOKEN);
        headers.put('Content-Type', 'application/json');
        headers.put('Content-Length', String.valueOf(body.length()));
        headers.put('Accept', 'application/json');

        endpoint = BASE_URL + '/upload/ave';

        method = 'POST';

        rawJSON = callOut(method, endpoint, body, headers);
        System.debug('123');
        System.debug(rawJSON);
        aveResponse = (AveResponse)JSON.deserialize(rawJSON, AveResponse.class);
        System.debug(aveResponse);
        if (aveResponse.message == 'Authorization has been denied for this request.' && RETRIED_AUTH == True) {
            System.debug(555);
            throwError(aveResponse.message);
        }
        else if (aveResponse.message == 'Authorization has been denied for this request.') {
            System.debug(666);
            RETRIED_AUTH = True;
            getAccessToken();
            getAveData(prop);
        }
        else if (aveResponse.status != 0) {
            System.debug(777);
            throwError(aveResponse.message);
        }
        else {
            System.debug(888);
            RETRIED_AUTH = False;
            populatePropertyWithFields(prop, aveResponse);
        }
    }

    public static void populatePropertyWithFields(Property__c prop, AveResponse aveResponse) {

        System.debug(aveResponse);

       // prop.Estimated_Max_Rent__c = aveResponse.ave.subject.estimatedMaxRent ;
       // prop.Estimated_Min_Rent__c =  aveResponse.ave.subject.estimatedMinRent;
       // prop.Estimated_Rent__c =  aveResponse.ave.subject.estimatedRent;
       
        
        Property_AVM__c avm=new Property_AVM__c();
        if(prop.Property_AVMs__r.size()>0){
            avm.Id=prop.Property_AVMs__r[0].Id;
        }else{
			avm.RelatedProperty__c=prop.Id;
		}
     
           
        if(avm.Id==null){
            insert avm;
        }else{
            update avm;
        }
        
    }


    public static String getBodyString(Map<String, String> parameters) {
        String bodyStr = '';
        if (parameters != null) {
            for (String key : parameters.keySet()) {
                bodyStr += key + '=' + EncodingUtil.urlEncode(parameters.get(key), 'UTF-8') + '&';
            }
        }
        return bodyStr;
    }

    public static String callOut(String method, String endpoint, String body, Map<String, String> headers) {
        HttpResponse response = new HttpResponse();

        HttpRequest request = new httpRequest();
        request.setTimeout(60000);
    request.setMethod(method);
        request.setEndpoint(endpoint);
        if (headers != null) {
            for (String key : headers.keySet()) {
                request.setHeader(key, headers.get(key));
            }
        }
        if (body != null) {
            request.setBody(body);
        }
        response = new Http().send(request);
        return response.getBody();
    }
   
 }