force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Extension__c/Property_Extension__c.object-meta.xml
<CustomObject>
    <label>Property Extension</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Property Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Extension__c/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Extension Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_Extension__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Extensions</relationshipLabel>
    <relationshipName>Property_Extensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PropertyExtensionHelperTests.cls
@isTest
public with sharing class PropertyExtensionHelperTests {
    @testSetup
    static void makeData(){
        Test_Helper.createDealLoanNumber();
        Account a = Test_Helper.createAccount();
        Contact c = Test_Helper.createContact(a);
        Opportunity o = Test_Helper.createOpportunity(a, c);

        List<Property__c> props = Test_Helper.createProperties(o);
    }
    @isTest
    public static void testPropExtension() {
        Property__c prop = [SELECT Id FROM Property__c LIMIT 1];

        Property_Extension__c pe = new Property_Extension__c(
            Property__c = prop.Id,
            Extension_Date__c = System.today()
        );

        insert pe;

        Property_Extension__c newPe = new Property_Extension__c(
            Property__c = prop.Id
        );

        insert newPe;


        List<Property_Extension__c> propExts = new List<Property_Extension__c>{
            new Property_Extension__c(
                Id = newPe.Id,
                Extension_Date__c = System.today()
            ),
            new Property_Extension__c(
            Id = pe.Id,
            Extension_Date__c = System.today().addDays(-1)
             )
        };

        update propExts;
    }
}