force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>From Servicer</description>
    <inlineHelpText>Updated by Statebridge Servicer Integration.</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Premium__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Premium__c</fullName>
    <formula>Premium_Amount__c/12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Amount__c</fullName>
    <label>Premium Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Reserve_on_Closing_Statement__c.field-meta.xml
<CustomField>
    <fullName>Reserve_on_Closing_Statement__c</fullName>
    <formula>Monthly_Premium__c * Total_Monthly_Reserve_Required__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reserve on Closing Statement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Monthly_Reserve_Required__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Reserve_Required__c</fullName>
    <formula>ROUND(ROUND(12 - Round( (Renewal_Date__c -  Deal__r.First_Payment_Due_Date__c + 1)/31, 1),1)+2,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Monthly Reserve Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InsuranceReserveCalcExtension.cls
public with sharing class InsuranceReserveCalcExtension {

    public Opportunity record {get;set;}
    public List<Property__c> properties {get;set;}
    public Decimal premiumRollup {get;set;}
    public Decimal reserveOnClosingRollup {get;set;}

    public InsuranceReserveCalcExtension(){
        
    }

    public InsuranceReserveCalcExtension(ApexPages.standardController standardController) {

        this.record = (Opportunity)standardController.getRecord();
        this.properties = new List<Property__c>();
        this.premiumRollup = 0;
        this.reserveOnClosingRollup = 0;

        if(this.record.Id != null) {

            this.properties = getProperties(this.record.Id);
        }

        for(Property__c prop : this.properties) {

            this.premiumRollup += prop.Premium_Amount__c != null ? prop.Premium_Amount__c : 0;
            this.reserveOnClosingRollup += prop.Reserve_On_Closing_Statement__c != null ? prop.Reserve_On_Closing_Statement__c : 0;
        }
        System.debug('Premium and reserve rollups');
        System.debug(this.premiumRollup);
        System.debug(this.reserveOnClosingRollup);
    }

    @AuraEnabled(cacheable=true)
    public static List<Property__c> getProperties(Id recordId){

        return [SELECT Id, Name, Premium_Amount__c, Renewal_Date__c, Total_Monthly_Reserve_Required__c, Monthly_Premium__c, Reserve_On_Closing_Statement__c 
                    FROM Property__c 
                    WHERE Deal__c =: recordId];
    }

    @AuraEnabled(cacheable=true)
    public static Opportunity getDeal(Id recordId){
        return [SELECT Id, Name, First_Payment_Date__c
                FROM Opportunity
                WHERE Id =: recordId];
    }

    @AuraEnabled
    public static List<sObject> upsertData(List<sObject> records){
        return lightning_Controller.upsertRecords(records);
    }

}