force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/REO__c.field-meta.xml
<CustomField>
    <fullName>REO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REO</label>
    <referenceTo>REO__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REO__c/REO__c.object-meta.xml
<CustomObject>
    <label>REO</label>
    <nameField>
        <label>REO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/REO__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>REOs</relationshipLabel>
    <relationshipName>REOs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/REOHelperTest.cls
@isTest
public with sharing class REOHelperTest {
    @TestSetup
    static void makeData(){
        Test_Helper.createDealLoanNumber();
        Account a = Test_Helper.createAccount();
        Contact c = Test_Helper.createContact(a);
        Opportunity o = Test_Helper.createBridgeDeal(a, c);
        List<Property__c> props = Test_Helper.createProperties(o);
    }

    @isTest
    public static void testReoTrigger() {
        Property__c prop = [SELECT Id FROM Property__c LIMIT 1];
        REO__c reo = new REO__c(
            Property__c = prop.Id
        );

        insert reo;

        Property__c updatedProp = [SELECT REO__c FROM Property__c WHERE Id = :prop.Id];

        System.assertEquals(reo.Id, updatedProp.REO__c, 'REO Id should be assigned to REO__c field on property.');
    }
}