force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Parent_Property__c.field-meta.xml
<CustomField>
    <fullName>Parent_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Property</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Property__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Child Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Special_Asset_Associate__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset_Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Asset Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title_Company__c.field-meta.xml
<CustomField>
    <fullName>Title_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Title Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title_Company_Contact__c.field-meta.xml
<CustomField>
    <fullName>Title_Company_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Title Company Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/util_Tests.cls
@isTest
private class util_Tests {

    //static List<Account> testAccounts = testDataFactory.createTestRecords(new Account[10]);

    static TestMethod void util_Tests_UnitTest(){
        Account acc = test_Helper.createAccount();
		Contact cont = test_Helper.createContact( acc );
        Opportunity opp = test_Helper.createOpportunity( acc, cont );
        List<Property__c> props = test_Helper.createProperties( opp );

        Test.startTest();
            util.queryOppAndChildren(opp.Id, 'Opportunity', 'Property__c', 'Properties__r');
            util.queryRecordAndChildren(opp.Id, 'Opportunity', 'Property__c', 'Properties__r');
            util.getFieldTypeMap('Opportunity');
            util.getFieldDescribeMap('Opportunity');
            // util.getMappedObjectById('Opportunity',opp.id);
            util.getFullObjectById('Opportunity',opp.Id);
            util.queryRecords('SELECT Id FROM User LIMIT 1');
            util.queryRecords('Opportunity', 'Name != null', 'CreatedDate ASC');
            util.queryRecordAllFields(opp.Id);
            util.queryRecordsAllFields(new Set<Id>{opp.Id});
            util.idToSObject(opp.Id);
            Decimal d;
            util.fixNull(d);
            util.compileRecordTypeMap('Opportunity');
            util.getAllFieldNamesForObject('Opportunity');
            util.getActiveMappedFieldNamesForObject('Opportunity');
            util.getActiveMappingsForObject('Opportunity');
            util.getActiveMappedSelectFields('Opportunity');
        Test.stopTest();
    }

}