force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Asset ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/Title_Order__c.object-meta.xml
<CustomObject>
    <label>Title Order</label>
    <nameField>
        <label>Title Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Title Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Title_Order__c/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <label>Asset ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Title Orders</relationshipLabel>
    <relationshipName>Title_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TitleOrderHelper.cls
public without sharing class TitleOrderHelper {
  public static void beforeInsert(List<Title_Order__c> newList) {
    Set<Id> propIds = new Set<Id>();

    for (Title_Order__c to : newList) {
      if (String.isEmpty(to.Asset_ID__c)) {
        propIds.add(to.Property__c);
      }
    }

    Map<Id, Property__c> propMap = new Map<Id, Property__c>(
      [
        SELECT Id, Asset_ID__c
        FROM Property__c
        WHERE Id IN :propIds AND Asset_ID__c != NULL
      ]
    );

    for (Title_Order__c to : newList) {
      if (propMap.containsKey(to.Property__c)) {
        to.Asset_ID__c = propMap.get(to.Property__c).Asset_ID__c;
      }
    }
  }
}