force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Not being used</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>Carries the Deal Loan Number over from the related Deal</description>
    <formula>Deal__r.Deal_Loan_Number__c</formula>
    <label>Deal Loan Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
            <value>
                <fullName>CAF Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Loan_Number__c/Deal_Loan_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Deal Loan Number</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>This will replace the manual auto assignment</description>
    <displayFormat>{00000}</displayFormat>
    <label>Deal Loan Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/CAFTestingClass.cls
public without sharing class CAFTestingClass {
  public static final List<String> VALID_DOCTYPES = new List<String>{
    'Application',
    'CAF Application'
  };

  public static void checkUploadedDocs(Map<Id, Deal_Document__c> oldDocs, Map<Id, Deal_Document__c> dealDocs) {
    List<Id> applicationDocs = new List<Id>();
    List<String> cvIds = new List<String>();
    for (Deal_Document__c doc : dealDocs.values()) {
      Deal_Document__c oldDoc = oldDocs.get(doc.Id);
      if (VALID_DOCTYPES.contains(doc.Document_Type__c) && doc.ContentVersion_Id__c != null && doc.ContentVersion_Id__c != oldDoc.ContentVersion_Id__c) {
        applicationDocs.add(doc.Id);
        cvIds.add(doc.ContentVersion_Id__c);
      }
    }

    if (applicationDocs.size() > 0) {
      sendEmails(applicationDocs, cvIds);
    }
  }

  public static void sendEmails(List<Id> docIds, List<String> cvIds) {
    List<Deal_Document__c> dealdocs = [
      SELECT
        Id,
        CreatedById,
        CreatedBy.UserRole.DeveloperName,
        CreatedBy.Name,
        Deal__c,
        Deal__r.StageName,
        Deal__r.Name,
        Deal__r.OwnerId,
        Deal__r.Owner.Name,
        Deal__r.CloseDate,
        Deal__r.Deal_Loan_Number__c,
        ContentVersion_Id__c
      FROM Deal_Document__c
      WHERE Id IN :docIds
    ];

    List<ContentVersion> cvs = [
      SELECT Id, Title, PathOnClient, FileType, VersionData
      FROM ContentVersion
      WHERE Id IN :cvIds
    ];
    System.debug('cvs: ' + cvs);
    List<OrgWideEmailAddress> owas = [
      SELECT Id, Address, DisplayName
      FROM OrgWideEmailAddress
      WHERE Address = 'caf-apps@cvest.com'
    ];

    Map<Id, Messaging.EmailFileAttachment> attachmentsMap = new Map<Id, Messaging.EmailFileAttachment>();

    for (ContentVersion c : cvs) {
      Blob data = c.VersionData;
      Messaging.EmailFileAttachment efa1 = new Messaging.EmailFileAttachment();
      if (data.size() > 0) {
        efa1.setBody(data);
        efa1.setFileName(c.Title);
        attachmentsMap.put(c.Id, efa1);
      }
    }

    Map<String, CAFTestSetting__mdt> settingsMap = new Map<String, CAFTestSetting__mdt>{
      'Bridge' => CAFTestSetting__mdt.getInstance('Bridge'),
      'Term' => CAFTestSetting__mdt.getInstance('Term'),
      'Origination' => CAFTestSetting__mdt.getInstance('Origination'),
      'SandboxTester' => CAFTestSetting__mdt.getInstance('SandboxTester')
    };

    List<EmailServicesAddress> esas = [
      SELECT Id, LocalPart, EmailDomainName
      FROM EmailServicesAddress
      WHERE DeveloperName = 'Deal_Email_Handler'
    ];

    String emailServiceEmail;

    if (esas.size() > 0) {
      emailServiceEmail = esas[0].LocalPart + '@' + esas[0].EmailDomainName;
    }

    List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

    for (Deal_Document__c doc : dealdocs) {
      CAFTestSetting__mdt setting = new CAFTestSetting__mdt();
      if(Test.isRunningTest()) {
        setting.Active__c = true;
        setting.RecipientEmail__c = 'test@domain.ua';
      }
      else if (settingsMap.get('SandboxTester') != null && settingsMap.get('SandboxTester').Active__c == true) {
        setting = settingsMap.get('SandboxTester');
      } else {
        setting = settingsMap.get(
          doc.CreatedBy.UserRole.DeveloperName.replace('_Manager', '')
        );
      }
      if (
        setting != null &&
        setting.Active__c &&
        String.isNotEmpty(setting.RecipientEmail__c)
      ) {
        String subject =
          'CAF Application Uploaded for Deal: #' +
          doc.Deal__r.Deal_Loan_Number__c +
          ' ' +
          doc.Deal__r.Name;
        String dealLink =
          URL.getOrgDomainUrl().toExternalForm() +
          '/' +
          doc.Deal__c;

        DateTime dt = doc.Deal__r.CloseDate;
        Date myDate;
        String dateString = 'N/A';
        if(dt != null) {
            myDate = date.newInstance(dt.year(), dt.month(), dt.day());
            dateString = String.valueOf(myDate);
        }

        String htmlBody =
          '<p>A CAF Application was uploaded in Salesforce. Please run a Clear Background Check, if needed.</p>' +
          '<p><a href="' +
          dealLink +
          '">' +
          doc.Deal__r.Name +
          '</a>' +
          '<span>&nbsp;|&nbsp;Deal Stage: ' +
          doc.Deal__r.StageName +
          ' | Deal Close Date: ' +
          dateString +
          ' | CAF Originator: ' +
          doc.Deal__r.Owner.Name +
          '</span>' +
          '</p>' +
          '<p> Uploaded By: ' +
          doc.CreatedBy.Name +
          '</p>';

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        email.setToAddresses(new List<String>{ setting.RecipientEmail__c });

        email.setFileAttachments(
          new List<Messaging.EmailFileAttachment>{
            attachmentsMap.get(doc.ContentVersion_Id__c)
          }
        );
        email.setSubject(subject);
        email.setHtmlBody(htmlBody);
        if (owas.size() > 0) {
          email.setOrgWideEmailAddressId(owas[0].Id);
        }
        if (String.isNotEmpty(emailServiceEmail)) {
          email.setBccAddresses(new List<String>{ emailServiceEmail });
        }
        emails.add(email);
      } else {
        continue;
      }
    }

    if (emails.size() > 0) {
      Messaging.sendEmail(emails);
    }
  }
}