force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Closer from the related Deal</description>
    <inlineHelpText>Closer from the related Deal</inlineHelpText>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Loan_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Coordinator from the related Deal</description>
    <inlineHelpText>Loan Coordinator from the related Deal</inlineHelpText>
    <label>Loan Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Underwriter from the related Deal</description>
    <inlineHelpText>Underwriter from the related Deal</inlineHelpText>
    <label>Underwriter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Closer on this Deal</description>
    <label>Closer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Closer</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Closer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Closer)</relationshipLabel>
    <relationshipName>Deals2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IC_Approval__c.field-meta.xml
<CustomField>
    <fullName>IC_Approval__c</fullName>
    <label>IC Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Loan Coordinator</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Loan Coordinator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Loan Coordinator)</relationshipLabel>
    <relationshipName>Deals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Program_Type__c</fullName>
    <description>Bridge Use
Custom or Standard Pricing</description>
    <inlineHelpText>Indicates if the pricing is Standard or Custom</inlineHelpText>
    <label>Bridge Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data.  Record Type Developer Name</inlineHelpText>
    <label>Record Type Developer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Term and Bridge Use</description>
    <label>Underwriter</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Bridge Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Term Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>SAB Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Underwriter)</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/YardiEmailSubmissionController.cls
public without sharing class YardiEmailSubmissionController {
  public static List<String> fields = new List<String>{
    'Opportunity.Owner.Email',
    'Name',
    'Record_Type_Name__c',
    'LOC_Program_Type__c',
    'Product_Sub_Type__c',
    'Amount',
    'Underwriter__r.Email',
    'Loan_Coordinator__r.Email',
    'Closer__r.Email',
    'IC_Approval__c',
    'StageName'
  };

  public static final List<String> DOCTYPES = new List<String>{
    'DS Funding Package'
  };

  public static List<EmailTemplate> queryEmailTemplate(String templateName) {
    return [
      SELECT Id, Body
      FROM EmailTemplate
      WHERE DeveloperName = :templateName
      LIMIT 1
    ];
  }

  @AuraEnabled
  public static String returnDeal(Id recordId) {
    Map<String, Object> m = new Map<String, List<Object>>();
    String qs = 'SELECT ';
    qs += String.join(fields, ', ');
    qs += ' FROM Opportunity WHERE Id = :recordId LIMIT 1';

    List<Opportunity> deal = [
      SELECT Id, StageName
      FROM Opportunity
      WHERE Id = :recordId
    ];

    system.debug(deal);
    system.debug(recordId);
    if (deal.size() > 0) {
      Id dealId = deal[0].Id;
      if (deal[0].StageName != 'Approved by Committee') {
        m.put(
          'Error',
          new List<Object>{ 'Deal needs to be in Approved by Committee.' }
        );
        return JSON.serialize(m);
      }
    } else {
      m.put('Error', new List<Object>{ 'Unable to process Deal.' });
      return JSON.serialize(m);
    }

    Integer versionNumber = 0;
    List<Deal_Document__c> ddList = [
      SELECT ContentVersion_Id__c, Attachment_Id__c, Type__c, Document_Type__c
      FROM Deal_Document__c
      WHERE
        Deal__c = :recordId
        AND ContentVersion_Id__c != NULL
        AND Document_Loaded__c = TRUE
        AND Is_Deleted__c = FALSE
        AND Type__c IN :DOCTYPES
    ];

    List<Id> ddCvIds = new List<Id>();
    Set<Id> icMemoIds = new Set<Id>();
    if (null != ddList && ddList.size() > 0) {
      for (Deal_Document__c ddc : ddList) {
        if (null != ddc.ContentVersion_Id__c) {
          ddCvIds.add(ddc.ContentVersion_Id__c);
        }
      }
    }

    List<ContentVersion> cvList = [
      SELECT Id, PathOnClient, Description
      FROM ContentVersion
      WHERE Id IN :ddCvIds
    ];

    // String oRecordType;
    List<Person> p = new List<Person>{ new Person().currentUser() };
    EmailTemplate e;

    List<EmailTemplate> eList = queryEmailTemplate('Send_to_Accounting');
    m.put('eList', eList);
    if (eList.size() > 0) {
      e = eList[0];
    }

    if (deal.size() > 0 && null != e) {
      Messaging.SingleEmailMessage mail;
      mail = Messaging.renderStoredEmailTemplate(
        e.Id,
        null,
        (Id) deal[0].get('Id')
      );
      m.put('EmailContents', new List<Object>{ mail.getHTMLBody() });
      m.put('Subject', new List<Object>{ mail.getSubject() });
    }
    m.put('Recipients', new List<Object>{ 'cafaccounting@cvest.com' });
    m.put('CC', new List<Object>{ 'kaitlyn.vuong@cvest.com' });

    // m.put('Recipients', new List<Object>{ 'jonathan.lay@cvest.com' });
    // m.put('CC', new List<Object>{ 'mcastillo@mkpartners.com' });

    m.put('ContentVersions', cvList);
    m.put('CurrentUser', p);
    return JSON.serialize(m, true);
  }

  @AuraEnabled
  public static String sendEmail(String s, String attachIds) {
    Map<String, String> m = (Map<String, String>) JSON.deserialize(
      s,
      Map<String, String>.class
    );

    List<String> recipientEmails = m.get('recipients').split(';');
    List<String> ccEmails = String.isNotEmpty(m.get('cc'))
      ? m.get('cc').split(';')
      : new List<String>();

    List<Id> aIds = (List<Id>) JSON.deserialize(attachIds, List<Id>.class);
    List<Messaging.EmailFileAttachment> attachmentsList = new List<Messaging.EmailFileAttachment>();
    for (ContentVersion a : queryContentVersions(aIds)) {
      attachmentsList.add(constructFileAttachment(a));
    }

    List<String> addresses = new List<String>();
    addresses.addAll(recipientEmails);

    String body = m.get('emailBody');

    // body += ;

    try {
      sendMail(
        addresses,
        m.get('subject'),
        body,
        attachmentsList,
        ccEmails,
        m.get('user'),
        null,
        null,
        null,
        null,
        m.get('recordId')
      );
    } catch (Exception err) {
      Map<String, String> e = new Map<String, String>{
        'Error' => 'FROM SEND MAIL' + err.getMessage()
      };
      return JSON.serialize(e);
    }
    Map<String, String> r = new Map<String, String>{
      'Success' => 'Email Sent'
    };
    return JSON.serialize(r);
  }

  public static Messaging.EmailFileAttachment constructFileAttachment(
    ContentVersion cv
  ) {
    Messaging.EmailFileAttachment file = new Messaging.EmailFileAttachment();
    if (cv != null) {
      file.setFileName(cv.PathOnClient);
      if (null != cv.FileType) {
        file.setContentType('application/' + cv.FileType.toLowerCase());
      }
      file.setBody(cv.VersionData);
    }

    return file;
  }

  public static Messaging.SingleEmailMessage sendMail(
    List<String> toAddresses,
    String subject,
    String htmlBody,
    List<Messaging.EmailFileAttachment> fileAttachments,
    List<String> ccAddresses,
    String senderDislayName,
    Boolean useSignature,
    Boolean saveAsActivity,
    Id targetObjectId,
    Id templateId,
    Id whatId
  ) {
    Messaging.reserveSingleEmailCapacity(1);
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    if (toAddresses != null && toAddresses.size() > 0) {
      mail.setToAddresses(toAddresses);
    }
    if (String.isNotblank(subject)) {
      mail.setSubject(subject);
    }
    if (String.isNotBlank(htmlBody)) {
      mail.setHtmlBody(htmlBody);
    }
    if (fileAttachments != null && fileAttachments.size() > 0) {
      mail.setFileAttachments(fileAttachments);
    }
    if (ccAddresses != null && ccAddresses.size() > 0) {
      mail.setCcAddresses(ccAddresses);
    }
    if (String.isNotBlank(senderDislayName)) {
      mail.setSenderDisplayName(senderDislayName);
    }
    if (useSignature != null) {
      mail.setUseSignature(false);
    }
    if (saveAsActivity != null) {
      mail.setSaveAsActivity(saveAsActivity);
    }
    // if (targetObjectId != null) {
    //   mail.setTargetObjectId(targetObjectId);
    // }
    if (templateId != null) {
      mail.setTemplateId(templateId);
    }
    if (whatId != null) {
      mail.setWhatId(whatId);
    }
    System.debug('this is the mail being sent');
    System.debug(mail);

    if (!Test.isRunningTest()) {
      Messaging.SendEmailResult[] results = Messaging.sendEmail(
        new List<Messaging.SingleEmailMessage>{ mail }
      );
      system.enqueueJob(new YardiQueueable('termXML', new List<Id>{ whatId }));
    }

    return mail;
  }

  public static List<ContentVersion> queryContentVersions(List<Id> cIds) {
    return [
      SELECT PathOnClient, VersionData, FileType
      FROM ContentVersion
      WHERE Id IN :cIds
    ];
  }

  public class Person {
    public Id Id;
    public String Name;
    public String Email;

    public Person currentUser() {
      Id = UserInfo.getUserId();
      Name = UserInfo.getUserId();
      Email = UserInfo.getUseremail();
      return this;
    }
  }
}