force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>Carries the Deal Loan Number over from the related Deal</description>
    <formula>Deal__r.Deal_Loan_Number__c</formula>
    <label>Deal Loan Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Loan_Number__c/Deal_Loan_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Deal Loan Number</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Current_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Amount__c</fullName>
    <label>Current Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>This will replace the manual auto assignment</description>
    <displayFormat>{00000}</displayFormat>
    <label>Deal Loan Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/ServiceLinkAPI.cls
public without sharing class ServiceLinkAPI {
    public class TitleDocument {
        public String DocumentType { get; set; }
        public String DocumentName { get; set; }
        public String Format { get; set; }
        public Long Size { get; set; }
        public String Base64FileData { get; set; }
    }
    public class QuoteRequest {
        public String SourcePartyID { get; set; }
        public String DestinationPartyID { get; set; }
        public String QuoteID { get; set; } // CV unique ID for quote request
        public String LoanNumber { get; set; } // CV Loan Number
        public String LoanPortfolioName { get; set; } // CV Loan Portfolio Name
        public Decimal LoanAmount { get; set; } 
        public String Comments { get; set; }
        public TitleDocument Document { get; set; } // type is QUOTEREQUEST and send XLSX format. "Data Tape" of properties for the quote request

        public void generateRequest(Opportunity deal, Deal_Document__c doc, ContentVersion cv) {
            this.SourcePartyID = 'COREVEST-SFR';
            this.DestinationPartyID = 'COREVEST-QUOTE';
            this.QuoteID = deal.id;
            this.LoanNumber = deal.Deal_Loan_Number__c;
            this.LoanAmount = deal.Current_Loan_Amount__c;
            this.LoanPortfolioName = deal.Name;
            this.Comments = '';
            this.Document.DocumentType = 'QUOTEREQUEST';
            this.Document.DocumentName = doc.File_Name__c;
            this.Document.Format = 'XLSX';
            this.Document.Size = cv.ContentSize; 
            this.Document.Base64FileData = EncodingUtil.base64Encode(cv.VersionData);
        }
    }
}