force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Property__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Title_Order__c.field-meta.xml
<CustomField>
    <fullName>Title_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Title Order</label>
    <referenceTo>Title_Order__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Asset ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Title_Order__c/Title_Order__c.object-meta.xml
<CustomObject>
    <label>Title Order</label>
    <nameField>
        <label>Title Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Title Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Title_Order__c/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <label>Asset ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Bulk_Project_Order_Num__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Project_Order_Num__c</fullName>
    <label>Bulk Project Order Num</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Title Orders</relationshipLabel>
    <relationshipName>Title_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Order_Opened_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Opened_Date__c</fullName>
    <label>Order Opened Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Title Orders</relationshipLabel>
    <relationshipName>Title_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Quote_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID__c</fullName>
    <label>Quote ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote Requested</fullName>
            </value>
            <value>
                <fullName>Quote Received Success</fullName>
            </value>
            <value>
                <fullName>Quote Received Failed</fullName>
            </value>
            <value>
                <fullName>Quote Response Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancel Requested</fullName>
            </value>
            <value>
                <fullName>Cancel Request Failed</fullName>
            </value>
            <value>
                <fullName>Quote Accepted</fullName>
            </value>
            <value>
                <fullName>Quote Accepted Confirmed</fullName>
            </value>
            <value>
                <fullName>Quote Accepted Failed</fullName>
            </value>
            <value>
                <fullName>Order Confirmed</fullName>
            </value>
            <value>
                <fullName>Loan Portfolio Change Submitted</fullName>
            </value>
            <value>
                <fullName>Loan Portfolio Change Confirmed</fullName>
            </value>
            <value>
                <fullName>Loan Portfolio Change Failed</fullName>
            </value>
            <value>
                <fullName>All Titles Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceLinkEndpoint.cls
@RestResource(urlMapping='/servicelink/*')
global without sharing class ServiceLinkEndpoint {
  public class ServiceLinkException extends Exception {
  }

  @HttpPost
  global static void postMethod() {
    RestRequest req = RestContext.request;
    RestResponse res = RestContext.response;
    Blob body = req.requestBody;
    String requestString = body.toString();
    res.addHeader('Content-Type', 'application/json');
    Map<String, String> resMap = new Map<String, String>();
    try {
      Map<String,ServiceLinkResponse> respMap = (Map<String,ServiceLinkResponse>) JSON.deserialize(requestString, Map<String,ServiceLinkResponse>.class);
      if (respMap.containsKey('QuoteReceivedConfirm')) {
        resMap.put(
          'LoanNumber',
          processQuoteReceivedConfirm(respMap.values()[0])
        );
      } else if (respMap.containsKey('QuoteResponse')) {
        resMap.put(
          'LoanNumber',
          processQuoteResponse(respMap.values()[0])
        );
      } else if (respMap.containsKey('OrderInquiryResponse')) {

      } else if (respMap.containsKey('OrderConfirmation')) {
        resMap.put('LoanNumber', processOrderConfirmation(respMap.values()[0]));
      }
      res.statusCode = 201;
      resMap.put('status', 'success');
      res.responseBody = Blob.valueOf(JSON.serialize(resMap));
    } catch (Exception err) {
      res.statusCode = 400;
      res.responseBody = Blob.valueOf(
        JSON.serialize(
          new Map<String, String>{
            'status' => 'error',
            'message' => err.getMessage()
          }
        )
      );
    }
    // List<String> params = Restcontext.request.requestURI.split('/');
  }

  public static String processOrderConfirmation(ServiceLinkResponse ordConf) {
    List<Title_Order__c> titleOrders = [
      SELECT Id
      FROM Title_Order__c
      WHERE Asset_ID__c = :ordConf.AssetID AND
      Bulk_Project_Order_Num__c = :ordConf.BulkProjectOrderNum
      FOR UPDATE
    ];
    if(titleOrders.size() == 0) {
      ServiceLinkException err = new ServiceLinkException();
      err.setMessage('Unable to locate orders.');
      throw err;
    }
    
    for(Title_Order__c to : titleOrders) {
      to.Order_Opened_Date__c = DateTime.valueOf(ordConf.OrderOpenedDate.replace('T', ' '));
      if(ordConf.Status == 'SUCCESS') {
        to.Order_Number__c = ordConf.OrderNumber;
        to.Status__c = 'Order Confirmed';
      } else {
        to.Status__c = 'Order Failed';
        to.Error_Message__c = ordConf.ErrorMessage;
      }
    }

    update titleOrders;

    return ordConf.LoanNumber;
  }

  public static String processQuoteResponse(ServiceLinkResponse qteRes) {
    List<Title_Order__c> titleOrders = [
      SELECT Id, Deal__c, Property__c
      FROM Title_Order__c
      WHERE Quote_ID__c = :qteRes.QuoteID
    ];
    if (titleOrders.size() > 0) {
      ContentVersion cv = createContentVersion(
        new List<ServiceLinkAPI.TitleDocument>{ qteRes.Document },
        titleOrders[0].Deal__c
      )[0];
      List<Deal_Document__c> dealDocs = new List<Deal_Document__c>();
      for (Title_Order__c tos : titleOrders) {
        ServiceLinkAPI.TitleDocument doc = qteRes.Document;
        Deal_Document__c dd = new Deal_Document__c(
          File_Name__c = cv.Title,
          ContentVersion_Id__c = cv.Id,
          Attachment_Id__c = cv.ContentDocumentId,
          Type__c = doc.DocumentType,
          Section__c = 'Title Orders',
          Document_Type__c = doc.DocumentType,
          Document_Loaded__c = true,
          Added_By__c = userInfo.getUserId(),
          Other_Document_Type__c = 'Title Order Documents',
          Deal__c = titleOrders[0].Deal__c,
          Property__c = titleOrders[0].Property__c
        );
        dealDocs.add(dd);
      }
      insert dealDocs;
    } else {
      ServiceLinkException err = new ServiceLinkException();
      err.setMessage('No existing order found for QuoteID ' + qteRes.QuoteID);
      throw err;
    }
    return qteRes.LoanNumber;
  }

  public static List<ContentVersion> createContentVersion(
    List<ServiceLinkAPI.TitleDocument> docs,
    Id parentId
  ) {
    List<ContentVersion> contentVersions = new List<ContentVersion>();

    for (ServiceLinkAPI.TitleDocument doc : docs) {
      ContentVersion cv = new ContentVersion();
      cv.VersionData = EncodingUtil.base64Decode(doc.Base64FileData);
      cv.Title = doc.DocumentName;
      cv.PathOnClient = doc.DocumentName;
      cv.Type__c = doc.DocumentType;
      contentVersions.add(cv);
    }

    insert contentVersions;

    List<ContentVersion> cvsQueried = [
      SELECT Id, VersionData, Title, PathOnClient, Type__c, ContentDocumentId
      FROM ContentVersion
      WHERE Id IN :contentVersions
    ];
    List<ContentDocumentLink> cdLinks = new List<ContentDocumentLink>();

    for (ContentVersion cv : cvsQueried) {
      ContentDocumentLink cdl = new ContentDocumentLink(
        ShareType = 'I',
        Visibility = 'AllUsers',
        LinkedEntityId = parentId,
        ContentDocumentId = cv.ContentDocumentId
      );
      cdLinks.add(cdl);
    }

    insert cdLinks;
    return cvsQueried;
  }

  public static void createDocument(
    List<ServiceLinkAPI.TitleDocument> docs,
    Id dealId,
    Id propId
  ) {
  }

  public static String processQuoteReceivedConfirm(ServiceLinkResponse reqObj) {
    List<Title_Order__c> titleOrders = [
      SELECT Bulk_Project_Order_Num__c
      FROM Title_Order__c
      WHERE Quote_ID__c = :reqObj.QuoteID
      FOR UPDATE
    ];
    if (titleOrders.size() > 0) {
      for (Title_Order__c tO : titleOrders) {
        tO.Order_Opened_Date__c = DateTime.valueOf(reqObj.OrderOpenedDate.replace('T', ' '));
        tO.Bulk_Project_Order_Num__c = reqObj.BulkProjectOrderNum;
      }
      update titleOrders;
    } else {
      ServiceLinkException err = new ServiceLinkException();
      err.setMessage('No existing order found for QuoteID ' + reqObj.QuoteID);
      throw err;
    }

    return reqObj.LoanNumber;
  }

  public virtual class ServiceLinkResponse {
    public String LoanNumber { get; set; }
    public String QuoteID { get; set; }
    public String BulkProjectOrderNum { get; set; }
    public String OrderOpenedDate { get; set; }
    public String Comments { get; set; }
    public ServiceLinkAPI.TitleDocument Document { get; set; }
    public String AssetID { get; set; }
    public String OrderNumber { get; set; }
    public String Status { get; set; }
    public String ErrorMessage { get; set; }
  }

}