force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Closing Documents</fullName>
            </value>
            <value>
                <fullName>Closing Template</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>Guarantor / Sponsor</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>Model</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Portfolio Level Documents</fullName>
            </value>
            <value>
                <fullName>Principle Loan Documents</fullName>
            </value>
            <value>
                <fullName>Property Level Documents</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Recorded Loan Documents</fullName>
            </value>
            <value>
                <fullName>Submission Documents</fullName>
            </value>
            <value>
                <fullName>Taxes</fullName>
            </value>
            <value>
                <fullName>Tax Template</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
            <value>
                <fullName>Title Policies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5 Arch Funding</fullName>
            </value>
            <value>
                <fullName>5 Arch Funding Corp.</fullName>
            </value>
            <value>
                <fullName>A&amp;S Capital</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>Bellevue</fullName>
            </value>
            <value>
                <fullName>Best Lending Co Inc</fullName>
            </value>
            <value>
                <fullName>CAF Bridge Lending</fullName>
            </value>
            <value>
                <fullName>CoreVest American Finance Lender LLC, a Delaware limited liability company</fullName>
                <default>true</default>
                <label>CoreVest American Finance Lender LLC, a Delaware limited liability company</label>
            </value>
            <value>
                <fullName>Dominion Financial Services, LLC</fullName>
            </value>
            <value>
                <fullName>Easy Street Capital</fullName>
            </value>
            <value>
                <fullName>Great Lakes Financing</fullName>
            </value>
            <value>
                <fullName>iFundCities</fullName>
            </value>
            <value>
                <fullName>Navigator Private Capital, LLC</fullName>
            </value>
            <value>
                <fullName>Paradyme Funding</fullName>
            </value>
            <value>
                <fullName>Patch of Land Lending</fullName>
            </value>
            <value>
                <fullName>Pimlico Refinance, LLC</fullName>
            </value>
            <value>
                <fullName>Revolution Realty Capital LLC</fullName>
            </value>
            <value>
                <fullName>Riverbend Lending</fullName>
            </value>
            <value>
                <fullName>Sundae</fullName>
            </value>
            <value>
                <fullName>Sunset Equity</fullName>
            </value>
            <value>
                <fullName>Third Party Originator</fullName>
            </value>
            <value>
                <fullName>YouLand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/lightningUtil_Tests.cls
@isTest
private class lightningUtil_Tests {

    @testSetup static void setup(){
        List<Account> testAccts = new List<Account>();
        for(Integer i=0;i<2;i++) {
            testAccts.add(new Account(Name = 'TestAcct'+i, BillingCountry = 'United States', BillingState='California',Phone='1122334455'));
        }
        insert testAccts; 
    }

    static TestMethod void queryTests(){
        String queryString = 'SELECT Id FROM Account';
        Test.startTest();
        List<sObject> records = lightning_Util.query(queryString);
        lightning_Util.queryJSON(queryString);
        Test.stopTest();
        system.assertEquals(records.size(), 2);
        
        // Code Added By Trivikram : Start
        lightning_Util.getPicklistValues('Opportunity','Lender__c');
        lightning_Util.TPicklistEntry picklistEntryInstance = new lightning_Util.TPicklistEntry();
        picklistEntryInstance.active = 'true';
        picklistEntryInstance.defaultValue = 'test';
        picklistEntryInstance.value = 'test';
        // Code Added By Trivikram : End
    }

    static TestMethod void upsertTests(){
        List<sobject> accounts = database.query('select id,Name,Phone from account');
        
        // Code Added By Trivikram : Start
        List<sobject> listTestAccount = new List<sobject>();
        Account testAccount2 =  (Account)accounts[1];
        testAccount2.Name = 'TestAcct0';
        testAccount2.BillingCountry = 'United States';
        testAccount2.BillingState = 'California';
        testAccount2.Phone = '1122334455';
        
        listTestAccount.add(testAccount2);
        listTestAccount.add(new Account(Name = 'Test'));
        listTestAccount.add(new Account(Name = 'TestAcct0',BillingCountry = 'United States', BillingState='California',Phone='1122334455'));

        Test.startTest();
        try {
            List<sObject> records = lightning_Util.upsertRecords(listTestAccount);
        }
        catch(Exception ex) {
        
        }
        // Code Added By Trivikram : End
        Test.stopTest();
    }

    static TestMethod void deleteTests(){
        List<sobject> accounts = database.query('select id from account');
        accounts.add(new Account(Name = 'Test'));
        Test.startTest();
        lightning_Util.deleteRecords(new List<sObject>{accounts[0]} );
        Test.stopTest();
        List<sObject> records = database.query('select id from account');
        system.assertEquals(records.size(), 1);
        
        // Code Added By Trivikram : Start
        try {
            lightning_Util.deleteRecords(new List<sObject>{accounts[0]} );
        }
        catch(Exception ex) {
        
        }
        // Code Added By Trivikram : End
    }

    static TestMethod void queryTest(){
        String sObjectType = 'Account';
        String whereClause = 'WHERE Id != null';
        String orderBy = 'ORDER BY CreatedDate';
        String lim = 'LIMIT 10';
        List<String> fields = new List<String>{'Id', 'Name'};
        Test.startTest();
        List<sObject> records = lightning_Util.queryRecords(sobjectType, whereClause, OrderBy, lim, fields);
        Test.stopTest();
        system.assertEquals(records.size(), 2);
    }

    static testmethod void userTest(){
        Test.startTest();
        lightning_Util.getUserId();
        lightning_Util.getUser();
        lightning_Util.getDependentOptions('Deal_Document__c', 'Type__c', 'Section__c');
        Test.stopTest();
    }

    static testmethod void getFileTest(){
        Test.startTest();
        lightning_util.getFileFromStaticResource('AdvanceDocuments', 'test');
        Test.stopTest();
    }
    static testmethod void getAppnameTypeTest(){
           Account acc = test_Helper.createAccount();
           Contact cont = test_Helper.createContact( acc );
           Opportunity opp = test_Helper.createOpportunity( acc, cont );
           //lightning_util.getAppName();
           lightning_util.getType(opp.id);
       
    }


}