force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Structure_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Structure_Id__c</fullName>
    <externalId>true</externalId>
    <label>Document Structure Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
            <value>
                <fullName>CAF Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/Document_Structure__mdt.object-meta.xml
<CustomObject>
    <label>Document Structure</label>
    <pluralLabel>Document Structures</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Approved_Term_Sheet_Name__c.field-meta.xml
<CustomField>
    <fullName>Approved_Term_Sheet_Name__c</fullName>
    <label>Approved Term Sheet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Program_Type__c</fullName>
    <description>Bridge Use
Custom or Standard Pricing</description>
    <inlineHelpText>Indicates if the pricing is Standard or Custom</inlineHelpText>
    <label>Bridge Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CAFTestingClassTest.cls
@isTest
public with sharing class CAFTestingClassTest {
  @isTest
  public static void testCAFEmail() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    Id termLoanRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get('Bridge Loan')
      .getRecordTypeId();
    opp.RecordTypeId = termLoanRecordTypeId;
    opp.LOC_Program_Type__c = 'Custom';
    opp.Approved_Term_Sheet_Name__c = null;
    update opp;

    Document_Structure__mdt docStruct = [
      SELECT Id
      FROM Document_Structure__mdt
      LIMIT 1
    ];
    Deal_Document__c doc = new Deal_Document__c(
      Deal__c = opp.Id,
      Document_Structure_Id__c = docStruct.Id,
      Document_Type__c = 'CAF Application'
    );

    insert doc;

    ContentVersion cv = new Contentversion();
    cv.title = 'ABC';
    cv.PathOnClient = 'test';
    Blob b = Blob.valueOf('Unit Test Attachment Body');
    cv.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
    insert cv;

    doc.ContentVersion_Id__c = cv.Id;

    update doc;
  }
}