force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
            <value>
                <fullName>Credit Report</fullName>
            </value>
            <value>
                <fullName>Executed Term Sheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <label>Deposit Amount Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Collected__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Collected__c</fullName>
    <label>Deposit Collected Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Fed_Reference__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Fed_Reference__c</fullName>
    <label>Deposit Fed Reference #</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Foreign_National_picklist__c.field-meta.xml
<CustomField>
    <fullName>Foreign_National_picklist__c</fullName>
    <description>Identifies if deal is associated with a foreign national. A foreign national is any person who is not a national of the United States. A national of the United States is an individual that is a U.S. citizen, Lawful permanent resident (green card holder), or “Protected Person” i.e. political asylum holder. Any individual who is present in the U.S. on a temporary immigration visa is considered a Foreign National.</description>
    <inlineHelpText>Please confirm whether a foreign national is associated with this deal. A foreign national is any person who is not a national of the United States. A national of the United States is an individual that is a U.S. citizen, lawful permanent resident (green card holder), or “Protected Person” i.e. political asylum holder. Any individual who is present in the U.S. on a temporary immigration visa is considered a foreign national.</inlineHelpText>
    <label>Foreign National</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Sheet_Issued__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet_Issued__c</fullName>
    <description>The Date that the Term Sheet is issued to the borrowing party for signature</description>
    <inlineHelpText>The Date that the Term Sheet is issued to the borrowing party for signature</inlineHelpText>
    <label>Term Sheet Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Sheet_Signed__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet_Signed__c</fullName>
    <label>Term Sheet Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/UnderwritingApprovalTests.cls
@isTest
private class UnderwritingApprovalTests {
  @isTest(SeeAllData=true)
  static void UnderwritingApprovalTests_UnitTest() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    opp.StageName = 'Term Sheet Signed/Deposit Collected';
    update opp;
    Opportunity opp2 = test_Helper.createOpportunity(acc, cont);
    Test.startTest();
    UNderwritingApproval_LightningController.validateRecord(opp.Id);

    UnderWritingApproval_LightningController.startApproval(
      'comments',
      (String) opp2.Id,
      'Term_Loan'
    );

    Test.stopTest();
  }

  @isTest(SeeAllData=true)
  static void UnderwritingApprovalTests_UnitTest2() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    opp.StageName = 'Term Sheet Signed/Deposit Collected';
    opp.RecordTypeId = opp.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
    ]
    .Id;
    update opp;
    Opportunity opp2 = test_Helper.createOpportunity(acc, cont);
    Test.startTest();
    UNderwritingApproval_LightningController.validateRecord(opp.Id);

    UnderwritingApproval_LightningController.startApproval(
      'comments',
      (String) opp.Id,
      'LOC_Loan'
    );

    Test.stopTest();
  }

  @isTest(SeeAllData=true)
  static void UnderwritingApprovalTests_UnitTest3() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    cont.MailingPostalCode = '11111';
    cont.Email = 'test@cvest.com';
    cont.MailingStreet = '111 test rd';
    cont.MailingCity = 'Testville';
    update cont;
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    opp.StageName = 'Term Sheet Signed/Deposit Collected';
    opp.RecordTypeId = opp.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
    ]
    .Id;
    opp.Deposit_Amount__c = 100000;
    opp.Deposit_Collected__c = System.today();
    opp.Deposit_Fed_Reference__c = 'fsdf';
    opp.Term_Sheet_Issued__c = System.today();
    opp.Term_Sheet_Signed__c = System.today();
    opp.Foreign_National_picklist__c = 'No';
    update opp;
    List<Deal_Document__c> dealDocs = new List<Deal_Document__c>{new Deal_Document__c(
      Document_Loaded__c = true,
      Is_Deleted__c = false,
      Deal__c = opp.Id,
      Document_Type__c = 'Executed Term Sheet'
    ), new Deal_Document__c(
      Document_Loaded__c = true,
      Is_Deleted__c = false,
      Deal__c = opp.Id,
      Document_Type__c = 'Credit Report'
    )};
    insert dealDocs;

    Opportunity opp2 = test_Helper.createOpportunity(acc, cont);
    Test.startTest();
    String resp = UnderwritingApproval_LightningController.validateRecord(opp.Id);
    System.debug(resp);
    UnderwritingApproval_LightningController.startApproval(
      'comments',
      (String) opp.Id,
      'LOC_Loan'
    );

    Test.stopTest();
  }
}