force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who uploaded this Document</description>
    <label>Added By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents_Added</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Added_On__c.field-meta.xml
<CustomField>
    <fullName>Added_On__c</fullName>
    <description>The Date the Document was uploaded</description>
    <label>Added On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Borrower_Term_Sheet_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Term_Sheet_Signature_Date__c</fullName>
    <label>Borrower Term Sheet Signature Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Structure_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Structure_Id__c</fullName>
    <externalId>true</externalId>
    <label>Document Structure Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
            <value>
                <fullName>Executed Term Sheet</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Executive_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Executive_Approval_Date__c</fullName>
    <description>Date that this Document was approved by an Executive member of CoreVest</description>
    <inlineHelpText>Date that this Document was approved by an Executive member of CoreVest</inlineHelpText>
    <label>Executive Approval Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Closing Documents</fullName>
            </value>
            <value>
                <fullName>Closing Template</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>Guarantor / Sponsor</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>Model</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Portfolio Level Documents</fullName>
            </value>
            <value>
                <fullName>Principle Loan Documents</fullName>
            </value>
            <value>
                <fullName>Property Level Documents</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Recorded Loan Documents</fullName>
            </value>
            <value>
                <fullName>Submission Documents</fullName>
            </value>
            <value>
                <fullName>Taxes</fullName>
            </value>
            <value>
                <fullName>Tax Template</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
            <value>
                <fullName>Title Policies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Sheet_Signed__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet_Signed__c</fullName>
    <label>Term Sheet Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/PortalAPITermsheet.cls
@RestResource(urlMapping='/portal/termsheet/*')
global with sharing class PortalAPITermsheet {
  @HttpGet
  global static void doGet() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');

    if (params[3] != 'executed') {
      Id dealId = params[3];
      system.debug(dealId);
      Deal_Document__c dealDoc = [
        SELECT
          Id,
          Added_On__c,
          Added_By__r.Name,
          File_Name__c,
          ContentVersion_Id__c,
          Document_Type__c
        FROM Deal_Document__c
        WHERE Deal__c = :dealId AND Document_Type__c = 'Term Sheet'
        ORDER BY CreatedDate DESC
        LIMIT 1
      ];

      ContentVersion cv = [
        SELECT Id, VersionData
        FROM ContentVersion
        WHERE Id = :dealDoc.ContentVersion_Id__c
        LIMIT 1
      ];

      Map<String, Object> body = new Map<String, Object>();
      body.put('fileName', dealDoc.File_Name__c);
      body.put('uploadedDate', dealDoc.Added_On__c);
      body.put('dealDocumentId', dealDoc.Id);
      body.put('uploadBy', dealDoc.Added_By__r.Name);
      body.put('base64', EncodingUtil.base64Encode(cv.VersionData));
      res.responseBody = Blob.valueOf(JSON.serialize(body));
      res.addHeader('Content-Type', 'application/json');
    } else {
      Id dealId = params[4];

      system.debug(dealId);
      Deal_Document__c dealDoc = [
        SELECT
          Id,
          Added_On__c,
          Added_By__r.Name,
          File_Name__c,
          ContentVersion_Id__c,
          Document_Type__c
        FROM Deal_Document__c
        WHERE Deal__c = :dealId AND Document_Type__c = 'Executed Term Sheet'
        ORDER BY CreatedDate DESC
        LIMIT 1
      ];

      ContentVersion cv = [
        SELECT Id, VersionData
        FROM ContentVersion
        WHERE Id = :dealDoc.ContentVersion_Id__c
        LIMIT 1
      ];

      Map<String, Object> body = new Map<String, Object>();
      body.put('fileName', dealDoc.File_Name__c);
      body.put('uploadedDate', dealDoc.Added_On__c);
      body.put('dealDocumentId', dealDoc.Id);
      body.put('uploadBy', dealDoc.Added_By__r.Name);
      body.put('base64', EncodingUtil.base64Encode(cv.VersionData));
      res.responseBody = Blob.valueOf(JSON.serialize(body));
      res.addHeader('Content-Type', 'application/json');
    }
  }
  @HttpPost
  global static void doPost() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    String jsonBody = req.requestBody.toString();
    //system.debug(jsonBody);
    Map<String, Object> body = (Map<String, Object>) System.JSON.deserializeUntyped(
      jsonBody
    );

    Id dealId = (Id) body.get('dealId');
    String fileName = (String) body.get('fileName');

    List<Opportunity> opp = [
      SELECT Id, RecordType.DeveloperName
      FROM Opportunity
      WHERE Id = :dealId
    ];

    if (opp.size() > 0) {
      ContentVersion cv = new ContentVersion();
      cv.VersionData = EncodingUtil.base64Decode(
        (String) body.get('base64String')
      );
      cv.Title = fileName;
      cv.pathOnClient = fileName;
      insert cv;

      Id contentDocumentId = [
        SELECT Id, ContentDocumentId
        FROM ContentVersion
        WHERE Id = :cv.Id
      ]
      .ContentDocumentId;

      Deal_Document__c dealDoc = new Deal_Document__c();
      dealDoc.Attachment_Id__c = contentDocumentId;
      dealDoc.ContentVersion_Id__c = cv.Id;
      dealDoc.File_Name__c = fileName;
      dealDoc.Deal__c = opp[0].Id;
      dealDoc.Added_On__c = system.now();
      dealDoc.Added_By__c = UserInfo.getUserId();

      dealDoc.Document_Loaded__c = true;

      if (opp[0].RecordType.DeveloperName == 'LOC_Loan') {
        //dealDoc.Document_Type__c = 'Executed Term Sheet';
        //dealDoc.
        dealDoc.Document_Structure_Id__c = 'm000a000000c2N4';
      } else if (opp[0].RecordType.DeveloperName == 'Term_Loan') {
        dealDoc.Document_Structure_Id__c = 'm000a000000c2OY';
      } else if (opp[0].RecordType.DeveloperName == 'm000a000000c2b9') {
        dealDoc.Document_Structure_Id__c = 'm000a000000c2b9';
      }
      dealDoc.Document_Type__c = 'Executed Termsheet';
      dealDoc.Type__c = 'Executed Termsheet';
      dealDoc.Section__c = 'Executed Termsheet';
      system.debug(body.get('executiveSignedDate'));
      if (body.containsKey('executiveSignedDate')) {
        String s = (String) body.get('executiveSignedDate');

        s = s.replace(' ', 'T');
        s = s.substringBefore('.');
        s = '"' + s + 'Z"';
        dealDoc.Executive_Approval_Date__c = (Datetime) JSON.deserialize(
          s,
          Datetime.class
        );
      }
      system.debug(body.get('borrowerSignedDate'));

      if (body.containsKey('borrowerSignedDate')) {
        // Opportunity deal = new Opportunity(Id = dealId);
        String s = (String) body.get('borrowerSignedDate');
        // deal.Term_Sheet_Signed__c = Date.valueOf(s);
        // update deal;
        s = s.replace(' ', 'T');
        s = s.substringBefore('.');
        s = '"' + s + 'Z"';
        dealDOc.Borrower_Term_Sheet_Signature_Date__c = (Datetime) JSON.deserialize(
          s,
          Datetime.class
        );
      }

      insert dealDoc;

      insert new ContentDocumentLink(
        LinkedEntityId = dealDoc.Id,
        ContentDocumentId = contentDocumentId,
        ShareType = 'I',
        Visibility = 'AllUsers'
      );

      Map<String, String> respBody = new Map<String, String>();
      res.addHeader('Content-Type', 'application/json');
      respBody.put('status', 'success');
      respBody.put('message', 'Executed Term Sheet created');
      res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    } else {
      Map<String, String> respBody = new Map<String, String>();
      res.addHeader('Content-Type', 'application/json');
      respBody.put('status', 'error');
      respBody.put('message', 'Deal Id Not Found');
      res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    }
  }
  @HttpPatch
  global static void doPatch() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    String jsonBody = req.requestBody.toString();
    //system.debug(jsonBody);
    Map<String, Object> body = (Map<String, Object>) System.JSON.deserializeUntyped(
      jsonBody
    );

    Id dealId = (Id) body.get('dealId');
    String fileName = (String) body.get('fileName');

    List<Opportunity> opp = [
      SELECT Id, RecordType.DeveloperName
      FROM Opportunity
      WHERE Id = :dealId
    ];

    if (opp.size() > 0) {
      ContentVersion cv = new ContentVersion();
      cv.VersionData = EncodingUtil.base64Decode(
        (String) body.get('base64String')
      );
      cv.Title = fileName;
      cv.pathOnClient = fileName;
      insert cv;

      Id contentDocumentId = [
        SELECT Id, ContentDocumentId
        FROM ContentVersion
        WHERE Id = :cv.Id
      ]
      .ContentDocumentId;

      Deal_Document__c dealDoc = new Deal_Document__c();
      dealDoc.Attachment_Id__c = contentDocumentId;
      dealDoc.ContentVersion_Id__c = cv.Id;
      dealDoc.Deal__c = opp[0].Id;
      if (opp[0].RecordType.DeveloperName == 'LOC_Loan') {
        //dealDoc.Document_Type__c = 'Executed Term Sheet';
        //dealDoc.
        dealDoc.Document_Structure_Id__c = 'm000a000000c2N4';
      } else if (opp[0].RecordType.DeveloperName == 'Term_Loan') {
        dealDoc.Document_Structure_Id__c = 'm000a000000c2OY';
      } else if (opp[0].RecordType.DeveloperName == 'm000a000000c2b9') {
        dealDoc.Document_Structure_Id__c = 'm000a000000c2b9';
      }

      insert dealDoc;

      insert new ContentDocumentLink(
        LinkedEntityId = dealDoc.Id,
        ContentDocumentId = contentDocumentId,
        ShareType = 'I',
        Visibility = 'AllUsers'
      );

      Map<String, String> respBody = new Map<String, String>();
      res.addHeader('Content-Type', 'application/json');
      respBody.put('status', 'success');
      respBody.put('message', 'Executed Term Sheet created');
      res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    } else {
      Map<String, String> respBody = new Map<String, String>();
      res.addHeader('Content-Type', 'application/json');
      respBody.put('status', 'error');
      respBody.put('message', 'Deal Id Not Found');
      res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    }
  }
}