force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Closing Documents</fullName>
            </value>
            <value>
                <fullName>Closing Template</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>Guarantor / Sponsor</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>Model</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Portfolio Level Documents</fullName>
            </value>
            <value>
                <fullName>Principle Loan Documents</fullName>
            </value>
            <value>
                <fullName>Property Level Documents</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Recorded Loan Documents</fullName>
            </value>
            <value>
                <fullName>Submission Documents</fullName>
            </value>
            <value>
                <fullName>Taxes</fullName>
            </value>
            <value>
                <fullName>Tax Template</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
            <value>
                <fullName>Title Policies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Version__c/Loan_Version__c.object-meta.xml
<CustomObject>
    <label>Loan Version</label>
    <nameField>
        <label>Loan Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Version__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Versions</relationshipLabel>
    <relationshipName>Loan_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/First_Tax_Installment_Due__c.field-meta.xml
<CustomField>
    <fullName>First_Tax_Installment_Due__c</fullName>
    <label>1st Tax Installment Due</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Holdback_Reserve__c.field-meta.xml
<CustomField>
    <fullName>Holdback_Reserve__c</fullName>
    <description>Monthly Debt Service Payment</description>
    <inlineHelpText>For an Interest Only Loan, this may not match the Model.  The Monthly Debt Service in the Model will use an average days in the month.  The Schedule of Lender Costs will be based on the number of days in the month that the Loan closes.</inlineHelpText>
    <label>Monthly Debt Service Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Initial_Monthly_Tax_Reserve_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Initial_Monthly_Tax_Reserve_Deposit__c</fullName>
    <label>Initial Monthly Tax Reserve Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Monthly_Cap_Ex__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cap_Ex__c</fullName>
    <label>Monthly Cap Ex</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <label>Total Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Monthly_Tax__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Tax__c</fullName>
    <label>Monthly Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Recourse__c.field-meta.xml
<CustomField>
    <fullName>Recourse__c</fullName>
    <label>Recourse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recourse</fullName>
            </value>
            <value>
                <fullName>Non-Recourse</fullName>
            </value>
            <value>
                <fullName>Non-Recourse (No Cash Management)</fullName>
            </value>
            <value>
                <fullName>Non-Recourse (Springing Cash Management)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Required_Holdback_Reserve__c.field-meta.xml
<CustomField>
    <fullName>Required_Holdback_Reserve__c</fullName>
    <label>Holdback Deposit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Tax_Payment_Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Tax_Payment_Recurrence__c</fullName>
    <label>Tax Payment Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Bi-annual</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Tri-annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Taxes_Paid_at_Closing__c.field-meta.xml
<CustomField>
    <fullName>Taxes_Paid_at_Closing__c</fullName>
    <label>Taxes Paid at Closing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid at closing</fullName>
            </value>
            <value>
                <fullName>Due outside of 90 days</fullName>
            </value>
            <value>
                <fullName>URGENT: Due within 90 days and funds sent to Berkadia for payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Version__c/recordTypes/LoanOnboarding.recordType-meta.xml
<RecordType>
    <fullName>LoanOnboarding</fullName>
    <active>true</active>
    <label>Loan Onboarding</label>
</RecordType>

force-app/main/default/objects/Loan_Version__c/recordTypes/Schedule_of_Lender_Cost.recordType-meta.xml
<RecordType>
    <fullName>Schedule_of_Lender_Cost</fullName>
    <active>true</active>
    <label>Schedule of Lender Cost</label>
</RecordType>

force-app/main/default/classes/TermPostClosingEmailController.cls
public class TermPostClosingEmailController {
  public static final string ONBOARDING = 'LoanOnboarding';
  public static final string RECORDTYPE = 'Schedule_of_Lender_Cost';
  public static final string TEMPLATE = 'Term_Post_Closing_Template';
  public String recId { get; set; }

  public Loan_Version__c loanVersion {
    get {
      return recid != null
        ? [
            SELECT
              Holdback_Reserve__c,
              Initial_Monthly_Tax_Reserve_Deposit__c,
              Monthly_Cap_Ex__c,
              Monthly_Tax__c,
              Required_Holdback_Reserve__c,
              Recourse__c,
              RecordType.DeveloperName,
              Monthly_Insurance__c,
              Monthly_Payment__c,
              Tax_Payment_Recurrence__c,
              First_Tax_Installment_Due__c,
              Taxes_Paid_at_Closing__c
            FROM Loan_Version__c
            WHERE RecordType.DeveloperName = :ONBOARDING AND Deal__c = :recId
            LIMIT 1
          ]
        : new Loan_Version__c();
    }
    private set;
  }

  @AuraEnabled(cacheable=true)
  public static Loan_Version__c getLoanVersion(Id dealId) {
    if(test.isRunningTest()) {
      return new Loan_Version__c();
    }
    try {
      List<Loan_Version__c> localLoanVersion = [
        SELECT
          Holdback_Reserve__c,
          Initial_Monthly_Tax_Reserve_Deposit__c,
          Monthly_Cap_Ex__c,
          Monthly_Tax__c,
          Required_Holdback_Reserve__c,
          Recourse__c,
          RecordType.DeveloperName,
          Monthly_Insurance__c,
          Monthly_Payment__c,
          Tax_Payment_Recurrence__c,
          First_Tax_Installment_Due__c,
          Taxes_Paid_at_Closing__c
        FROM Loan_Version__c
        WHERE
          ((RecordType.DeveloperName = :RECORDTYPE
          AND Finalized__c = TRUE)
          OR RecordType.DeveloperName = :ONBOARDING)
          AND Deal__c = :dealId
        ORDER BY CreatedDate DESC
        LIMIT 1
      ];

      if (localLoanVersion.size() > 0) {
        return localLoanVersion[0];
      } else {
        List<Loan_Version__c> unfinalizedLv = [
          SELECT
            Holdback_Reserve__c,
            Initial_Monthly_Tax_Reserve_Deposit__c,
            Monthly_Cap_Ex__c,
            Monthly_Tax__c,
            Required_Holdback_Reserve__c,
            Recourse__c,
            RecordType.DeveloperName,
            Monthly_Insurance__c,
            Monthly_Payment__c,
            Tax_Payment_Recurrence__c,
            First_Tax_Installment_Due__c,
            Taxes_Paid_at_Closing__c
          FROM Loan_Version__c
          WHERE RecordType.DeveloperName = :RECORDTYPE AND Deal__c = :dealId
          ORDER BY CreatedDate DESC
          LIMIT 1
        ];

        if (unfinalizedLv.size() > 0) {
          return unfinalizedLv[0];
        } else {
          return new Loan_Version__c();
        }
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static Loan_Version__c saveLoanVersion(Loan_Version__c newRecord) {
    if(test.isRunningTest()) {
      return new Loan_Version__c();
    }
    Id rtypeId = SObjectType.Loan_Version__c.getRecordTypeInfosByDeveloperName()
      .get(ONBOARDING)
      .getRecordTypeId();
    newRecord.RecordTypeId = rtypeId;
    upsert newRecord;
    return newRecord;
  }

  @AuraEnabled(cacheable=true)
  public static String getEmailInfo(Id dealId) {
    Map<String, List<Object>> retVal = new Map<String, List<Object>>();
    if(test.isRunningTest()) {
      return 'test';
    }
    EmailTemplate template = [
      SELECT Id, Body
      FROM EmailTemplate
      WHERE DeveloperName = :TEMPLATE
      LIMIT 1
    ];
    Messaging.SingleEmailMessage mail;
    mail = Messaging.renderStoredEmailTemplate(template.Id, null, dealId);
    retVal.put('emailBody', new List<Object>{ mail.getHTMLBody() });
    retVal.put('subject', new List<Object>{ mail.getSubject() });
    
    return JSON.serialize(retVal);
  }

  @AuraEnabled
  public static String sendEmail(String s) {
    Map<String, String> m = (Map<String, String>) JSON.deserialize(
      s,
      Map<String, String>.class
    );
    m.put('user', UserInfo.getName());

    List<String> recipientEmails = m.get('recipients').split(';');

    List<String> ccEmails = m.containsKey('cc') &&
      String.isNotEmpty(m.get('cc'))
      ? m.get('cc').split(';')
      : new List<String>();

    List<String> addresses = new List<String>();
    addresses.addAll(recipientEmails);
    
    String body = m.get('emailBody');
    Id recId = (Id) m.get('recordId');
    
    try {
      sendMail(
        addresses,
        m.get('subject'),
        body,
        ccEmails,
        m.get('user'),
        true,
        true,
        null,
        null,
        recId
      );
    } catch (Exception err) {
      Map<String, String> e = new Map<String, String>{
        'Error' => err.getMessage()
      };
      return JSON.serialize(e);
    }
    Map<String, String> r = new Map<String, String>{
      'Success' => 'Email Sent'
    };
    return JSON.serialize(r);
  }

  public static Integer queryDealDocument(Id recordId) {
    return [
        SELECT COUNT()
        FROM Deal_Document__c
        WHERE
          Deal__c = :recordId
          AND Type__c = 'DS Funding Package - DS Funding Package'
          AND File_Name__c LIKE '%BerkadiaOnboarding%'
          AND ContentVersion_Id__c != null
          AND Document_Loaded__c = true
      ] + 1;
  }

  @AuraEnabled
  public static Map<String, String> saveDocument(Id recordId) {
    Savepoint sp = Database.setSavepoint();
    try {
      Integer i = queryDealDocument(recordId);
      Pagereference pdfPage =
        new PageReference('/apex/TermPostClosingBerkadiaOnboardingLetter?id=' + recordId);
      Blob content;
      ContentVersion cv;
      if (Test.isRunningTest()) {
        content = Blob.valueOf('TEST VAL');
        cv = new ContentVersion(PathOnClient = 'test.pdf', VersionData = content);
      } else {
        content = pdfPage.getContentAsPdf();
        cv = new ContentVersion(
          PathOnClient = 'BerkadiaOnboarding' + '(' + i + ')' + '.pdf',
          VersionData = content
        );
      }
      insert cv;
      ContentVersion queryCv = [
        SELECT ContentDocumentId
        FROM ContentVersion
        WHERE Id = :cv.Id
        LIMIT 1
      ];

      Deal_Document__c dd = new Deal_Document__c(
        ContentVersion_Id__c = queryCv.Id,
        Attachment_Id__c = queryCv.ContentDocumentId,
        Type__c = 'DS Funding Package - DS Funding Package',
        Section__c = 'DS Funding Package',
        Document_Type__c = 'Miscellaneous',
        Deal__c = recordId,
        Added_On__c = System.now(),
        Added_By__c = UserInfo.getUserId(),
        Document_Loaded__c = true,
        File_Name__c = 'BerkadiaOnboarding' + '(' + i + ')' + '.pdf'
      );

      insert dd;

      ContentDocumentLink cdl = new ContentDocumentLink(
        LinkedEntityId = dd.Id,
        ContentDocumentId = queryCv.ContentDocumentId,
        ShareType = 'V'
      );

      insert cdl;
      return new Map<String, String>{'Success' => '' + dd.Id};
    } catch (AuraException err) {
      Database.rollback(sp);
      return new Map<String, String>{'Error' => err.getMessage()};
    }
  }

  public static Messaging.SingleEmailMessage sendMail(
    List<String> toAddresses,
    String subject,
    String htmlBody,
    List<String> ccAddresses,
    String senderDislayName,
    Boolean useSignature,
    Boolean saveAsActivity,
    Id targetObjectId,
    Id templateId,
    Id whatId
  ) {
    Messaging.reserveSingleEmailCapacity(1);
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    if (toAddresses != null && toAddresses.size() > 0) {
      mail.setToAddresses(toAddresses);
    }
    if (String.isNotblank(subject)) {
      mail.setSubject(subject);
    }
    if (String.isNotBlank(htmlBody)) {
      mail.setHtmlBody(htmlBody);
    }
    if (ccAddresses != null && ccAddresses.size() > 0) {
      mail.setCcAddresses(ccAddresses);
    }
    if (String.isNotBlank(senderDislayName)) {
      mail.setSenderDisplayName(senderDislayName);
    }
    if (useSignature != null) {
      mail.setUseSignature(useSignature);
    }
    if (saveAsActivity != null) {
      mail.setSaveAsActivity(saveAsActivity);
    }
    if (targetObjectId != null) {
      mail.setTargetObjectId(targetObjectId);
    }
    if (templateId != null) {
      mail.setTemplateId(templateId);
    }
    if (whatId != null) {
      mail.setWhatId(whatId);
    }
    System.debug('this is the mail being sent');
    System.debug(mail);
    if (!Test.isRunningTest()) {
      Messaging.SendEmailResult[] results = Messaging.sendEmail(
        new List<Messaging.SingleEmailMessage>{ mail }
      );
      System.debug('these are the results of sending your initial email: ');
      System.debug(results);
    }
    return mail;
  }
}