force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TermSheetBypassControllerTest.cls
@isTest
private class TermSheetBypassControllerTest {    
    static TestMethod void testMethod1(){
        test_Helper.createDealLoanNumber();
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity deal = test_Helper.createOpportunity( acc, cont );
           
        ContentVersion contentVersionRecord = new ContentVersion(
          Title = 'Penguins',
          PathOnClient = 'Penguins.jpg',
          VersionData = Blob.valueOf('Test Content'),
          IsMajorVersion = true
        );
        insert contentVersionRecord;
        Id docId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: contentVersionRecord.Id LIMIT 1].ContentDocumentId;
        List<Id> listDocumentId = new List<Id>();
        listDocumentId.add(docId);
        
        
        Attachment att=new Attachment(ParentId=deal.Id, Name = 'Test', Body = Blob.valueOf('Test Data'));
        insert att;
        
        Deal_Document__c termSheet=new Deal_Document__c(
            ContentVersion_Id__c=contentVersionRecord.Id,
            Attachment_Id__c=att.Id,
            Type__c = 'Term Sheet',
            File_Name__c='Penguins.pdf',
            Document_Loaded__c=true,
            Deal__c=deal.Id,
            Is_Deleted__c=false
        );
        insert termSheet;
        
        Test.startTest();
        TermSheetBypassController.createAttachmentFromCV(contentVersionRecord.Id);
        TermSheetBypassController.returnDeal(deal.Id);
        TermSheetBypassController.bypassDeal(deal.Id);
        
        Test.stopTest();
    }
    
    static TestMethod void testMethod2(){
        test_Helper.createDealLoanNumber();
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity deal = test_Helper.createOpportunity( acc, cont );
           
        ContentVersion contentVersionRecord = new ContentVersion(
          Title = 'Penguins',
          PathOnClient = 'Penguins.jpg',
          VersionData = Blob.valueOf('Test Content'),
          IsMajorVersion = true
        );
        insert contentVersionRecord;
        Id docId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: contentVersionRecord.Id LIMIT 1].ContentDocumentId;
        List<Id> listDocumentId = new List<Id>();
        listDocumentId.add(docId);
        
        Test.startTest();
        try{
            TermSheetBypassController.createAttachmentFromCV(contentVersionRecord.Id);
            TermSheetBypassController.returnDeal(deal.Id);
            TermSheetBypassController.bypassDeal(deal.Id);
        }catch(exception e){}
        
        Test.stopTest();
    }
}