force-app/main/default/objects/Custom_Chatter_Mapping__c/Custom_Chatter_Mapping__c.object-meta.xml
<CustomObject>
    <label>Chatter</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-{0}</displayFormat>
        <label>CustomChatter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Chatter_Mapping__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Chatter</relationshipLabel>
    <relationshipName>Chatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Chatter_Mapping__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CustomChatterController.cls
public without sharing class CustomChatterController {
    @AuraEnabled
    public static String getRelatedChatterObject(String parentId)
    {
        List<Custom_Chatter_Mapping__c> records = new List<Custom_Chatter_Mapping__c>([SELECT Id,Parent_Id__c,Deal__c 
                                                                                       FROM Custom_Chatter_Mapping__c where Parent_Id__c=:parentId limit 1]);
        if(records!=null && !records.isEmpty())
        {
            return records[0].Id;
        }else{
            ProcessInstanceWorkItem piw = [SELECT ProcessInstance.TargetObjectId FROM ProcessInstanceWorkItem WHERE Id = :parentId LIMIT 1];
            
            Custom_Chatter_Mapping__c record=new Custom_Chatter_Mapping__c(
                Parent_Id__c=parentId,
                Deal__c=piw.ProcessInstance.TargetObjectId
            );
            insert record;
            
            return record.Id;
            
        }
    }
}