force-app/main/default/objects/Foreclosure__c/Foreclosure__c.object-meta.xml
<CustomObject>
    <label>Foreclosure</label>
    <nameField>
        <label>Foreclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foreclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Foreclosure__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Property this Foreclosure is related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Foreclosures</relationshipLabel>
    <relationshipName>Foreclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Foreclosure__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foreclosure__c/fields/Special_Asset__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Asset</label>
    <referenceTo>Special_Asset__c</referenceTo>
    <relationshipLabel>Foreclosures</relationshipLabel>
    <relationshipName>Foreclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Foreclosure__c.field-meta.xml
<CustomField>
    <fullName>Foreclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foreclosure</label>
    <referenceTo>Foreclosure__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <description>Date that this Property became Real Estate Owned</description>
    <inlineHelpText>Date that this Property became Real Estate Owned</inlineHelpText>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Special_Asset__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Current Special Asset Details</inlineHelpText>
    <label>Special Asset</label>
    <referenceTo>Special_Asset__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/Special_Asset__c.object-meta.xml
<CustomObject>
    <description>When a Property becomes a Special Asset, this record is created and related to the Property.</description>
    <label>Special Asset</label>
    <nameField>
        <label>Special Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Asset__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Special Assets</relationshipLabel>
    <relationshipName>Special_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <description>Date that this Property became Real Estate Owned</description>
    <inlineHelpText>Date that this Property became Real Estate Owned</inlineHelpText>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ForeclosureHelper.cls
public without sharing class ForeclosureHelper {
  public static void beforeInsert(List<Foreclosure__c> newList) {
    Map<Id, Property__c> propMap = new Map<Id,Property__c>();

    for(Foreclosure__c f : newList) {
      if(f.Special_Asset__c == null && f.Property__c != null) {
        propMap.put(f.Property__c, new Property__c());
      }
    }

    propMap = new Map<Id,Property__c>([
      SELECT Id, Special_Asset__c FROM Property__c WHERE Id IN :propMap.keySet() AND Special_Asset__c != null
    ]);

    for(Foreclosure__c f : newList) {
      if(f.Special_Asset__c == null && f.Property__c !=null && propMap.containsKey(f.Property__c)) {
        f.Special_Asset__c = propMap.get(f.Property__c).Special_Asset__c;
      }
    }
  }
  public static void afterInsert(List<Foreclosure__c> newList) {
    Map<Id, Foreclosure__c> specAssetsToUpdate = new Map<Id, Foreclosure__c>();
    for (Foreclosure__c fc : newList) {
      if (fc.Special_Asset__c != null) {
        specAssetsToUpdate.put(fc.Id, fc);
      }
    }

    if (specAssetsToUpdate.size() > 0) {
      updateSpecialAssets(specAssetsToUpdate, true);
    }
  }

  public static void afterUpdate(
    Map<Id, Foreclosure__c> oldMap,
    Map<Id, Foreclosure__c> newMap
  ) {
    Map<Id, Foreclosure__c> specAssetsToUpdate = new Map<Id, Foreclosure__c>();
    for (Id key : newMap.keySet()) {
      Foreclosure__c nFc = newMap.get(key);
      Foreclosure__c oFc = oldMap.get(key);
      if (
        nFc.Special_Asset__c != null &&
        (nFc.REO_date__c != oFc.REO_date__c ||
        nFc.Special_Asset__c != oFc.Special_Asset__c)
      ) {
        specAssetsToUpdate.put(key, nFc);
      }
    }

    if (specAssetsToUpdate.size() > 0) {
      updateSpecialAssets(specAssetsToUpdate, false);
    }
  }

  public static void updateSpecialAssets(
    Map<Id, Foreclosure__c> fcMap,
    Boolean isInsert
  ) {
    Map<Id, Special_Asset__c> specAssets = new Map<Id, Special_Asset__c>(
      [
        SELECT Id, REO_Date__c
        FROM Special_Asset__c
        WHERE
          Id IN (
            SELECT Special_Asset__c
            FROM Foreclosure__c
            WHERE Id IN :fcMap.keySet()
          )
      ]
    );

    List<Special_Asset__c> forUpdate = new List<Special_Asset__c>();
    List<Foreclosure__c> forUpdateFc = new List<Foreclosure__c>();

    if (specAssets.size() > 0) {
      for (Foreclosure__c fc : fcMap.values()) {
        Special_Asset__c sa = specAssets.get(fc.Special_Asset__c);
        if (sa != null && sa.REO_Date__c != fc.REO_date__c) {
          if (isInsert && sa.REO_Date__c != null && fc.REO_Date__c == null) {
            forUpdateFc.add(
              new Foreclosure__c(Id = fc.Id, REO_date__c = sa.REO_Date__c)
            );
          } else {
            sa.REO_Date__c = fc.REO_date__c;
            forUpdate.add(sa);
          }
        }
      }
    }

    if (forUpdate.size() > 0) {
      update (forUpdate);
    }

    if (forUpdateFc.size() > 0) {
      update (forUpdateFc);
    }

  }
}