force-app/main/default/objects/Foreclosure__c/Foreclosure__c.object-meta.xml
<CustomObject>
    <label>Foreclosure</label>
    <nameField>
        <label>Foreclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foreclosures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Foreclosure__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Property this Foreclosure is related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Foreclosures</relationshipLabel>
    <relationshipName>Foreclosures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Foreclosure__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Foreclosure__c/fields/Special_Asset__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Asset</label>
    <referenceTo>Special_Asset__c</referenceTo>
    <relationshipLabel>Foreclosures</relationshipLabel>
    <relationshipName>Foreclosures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Foreclosure__c.field-meta.xml
<CustomField>
    <fullName>Foreclosure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Foreclosure</label>
    <referenceTo>Foreclosure__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <description>Date that this Property became Real Estate Owned</description>
    <inlineHelpText>Date that this Property became Real Estate Owned</inlineHelpText>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Special_Asset__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Current Special Asset Details</inlineHelpText>
    <label>Special Asset</label>
    <referenceTo>Special_Asset__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/Special_Asset__c.object-meta.xml
<CustomObject>
    <description>When a Property becomes a Special Asset, this record is created and related to the Property.</description>
    <label>Special Asset</label>
    <nameField>
        <label>Special Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Asset__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Special Assets</relationshipLabel>
    <relationshipName>Special_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <description>Date that this Property became Real Estate Owned</description>
    <inlineHelpText>Date that this Property became Real Estate Owned</inlineHelpText>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Resolution_Type__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Type__c</fullName>
    <label>Resolution Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bring Current</fullName>
            </value>
            <value>
                <fullName>Covenant Default</fullName>
            </value>
            <value>
                <fullName>Deed In Lieu</fullName>
            </value>
            <value>
                <fullName>Discounted Payoff</fullName>
            </value>
            <value>
                <fullName>Extension Req</fullName>
            </value>
            <value>
                <fullName>FC with Guarantee</fullName>
            </value>
            <value>
                <fullName>FC without Guarantee</fullName>
            </value>
            <value>
                <fullName>Forbearance</fullName>
            </value>
            <value>
                <fullName>Foreclosure</fullName>
            </value>
            <value>
                <fullName>In-House Refi</fullName>
            </value>
            <value>
                <fullName>Mod/Assumption</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Payoff Pending</fullName>
            </value>
            <value>
                <fullName>Pursue Guarantee</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Reinstated</fullName>
            </value>
            <value>
                <fullName>REO with Guarantee</fullName>
            </value>
            <value>
                <fullName>REO without Guarantee</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Sell REO</fullName>
            </value>
            <value>
                <fullName>Special Asset Tracking</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Resolved_Date__c.field-meta.xml
<CustomField>
    <fullName>Resolved_Date__c</fullName>
    <label>Resolved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Severity_Level__c.field-meta.xml
<CustomField>
    <fullName>Severity_Level__c</fullName>
    <label>Severity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Decision Required</fullName>
                <default>true</default>
                <label>Decision Required</label>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Special_Asset_Manager__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Asset Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Special_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Special_Asset_Reason__c.field-meta.xml
<CustomField>
    <fullName>Special_Asset_Reason__c</fullName>
    <description>The reason that this Property is a Special Asset</description>
    <label>Special Asset Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st Payment Default</fullName>
            </value>
            <value>
                <fullName>60+ Days</fullName>
            </value>
            <value>
                <fullName>75+ Days Delinquent</fullName>
            </value>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Cross Default/Same Borrower</fullName>
            </value>
            <value>
                <fullName>Matured</fullName>
            </value>
            <value>
                <fullName>Non-Monetary Default</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ForeclousreHelperTest.cls
@isTest
public with sharing class ForeclousreHelperTest {
   @TestSetup
   static void makeData(){
    Test_Helper.createDealLoanNumber();
        Account a = Test_Helper.createAccount();
        Contact c = Test_Helper.createContact(a);
        Opportunity o = Test_Helper.createOpportunity(a, c);

        List<Property__c> props = Test_Helper.createProperties(o);

        List<Special_Asset__c> sas = new List<Special_Asset__c>();

        for(Property__c p : props) {
            sas.add(new Special_Asset__c(
                Property__c = p.Id,
                Special_Asset_Manager__c = Userinfo.getUserId(),
                Special_Asset_Reason__c = 'Title',
                Severity_Level__c = 'Decision Required',
                Resolved_Date__c = System.today(),
                Resolution_Type__c = 'Sell REO',
                REO_Date__c = System.today()
            ));
        }

        insert sas;
   }

   @isTest
   public static void testForeclousreTrigger() {
    Foreclosure__c fc = new Foreclosure__c();

    List<Special_Asset__c> sas = [SELECT Id, Property__c, REO_Date__c FROM Special_Asset__c];

    fc.Special_Asset__c = sas[0].Id;
    fc.Property__c = sas[0].Property__c;

    insert fc;

    fc = [SELECT Id, REO_Date__c, Special_Asset__c FROM Foreclosure__c WHERE Id = :fc.Id];

    System.assertEquals(sas[0].REO_Date__c, fc.REO_Date__c, 'REO dates should match.');

    fc.REO_Date__c = System.today().addDays(-1);

    update fc;

    Special_Asset__c sa = [SELECT REO_Date__c FROM Special_Asset__c WHERE Id = :fc.Special_Asset__c];

    System.assertEquals(fc.REO_Date__c, sa.REO_Date__c, 'REO Dates should still match');


   }
}