force-app/main/default/objects/Beekin_Settings__c/Beekin_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Get property rental information detail from Beekin</description>
    <label>Beekin Settings</label>
</CustomObject>

force-app/main/default/objects/Beekin_Settings__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <description>API Key for Beekin call</description>
    <inlineHelpText>API Key for Beekin call</inlineHelpText>
    <label>APIKey</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beekin_Settings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Beeking Endpoint</description>
    <label>Endpoint</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>Property Details Section</description>
    <label>Property Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Multi-unit (5+)</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
                <default>true</default>
                <label>SFR</label>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Condo - Detached</fullName>
            </value>
            <value>
                <fullName>Condo - High Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Low Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Mid Rise</fullName>
            </value>
            <value>
                <fullName>Condo - NonWarrantable</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>Multi-unit (1-4)</fullName>
                <isActive>false</isActive>
                <label>Multi-unit (1-4)</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
                <isActive>false</isActive>
                <label>Student Housing</label>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
                <isActive>false</isActive>
                <label>Vacation Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Bath__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Beds__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Beds__c</fullName>
    <label>Beds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <label>Pool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <label>Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet__c</fullName>
    <label>Square Feet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <label>Year Built</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BeekinAPITests.cls
@isTest
public class BeekinAPITests {
  @testSetup
  static void setUpData() {
    Beekin_Settings__c beekinSettings = Beekin_Settings__c.getInstance();
	BeekinSettings.Endpoint__c = 'https://beta.api.beekin.co/';
    BeekinSettings.APIKey__c = '123ABC&';      
    insert beekinSettings;
test_Helper.createDealLoanNumber();
    Account acc = new Account();
    acc.Name = 'Test';
    insert acc;

    Contact con = new Contact();
    con.FirstName = 'Test';
    con.LastName = 'Test';
    con.AccountId = acc.Id;
    insert con;

    Opportunity opp = new Opportunity();
    opp.Name = 'Test';
    opp.AccountId = acc.Id;
    opp.Contact__c = con.Id;
    opp.StageName = 'Initial Review';
    opp.CloseDate = System.today();
    insert opp;

    Property__c p = new Property__c();
    p.Deal__c = opp.Id;
    p.Property_Type__c = 'SFR';
    p.Name = '1810 LEDGESTONE DRIVE';
    p.Property_Name__c = '1810 LEDGESTONE DRIVE';
    p.City__c = 'Houston';
    p.State__c = 'TX';
    p.ZipCode__c = '76549';
    p.Number_of_Beds__c = 4;
    p.Number_of_Bath__c =3;
    p.Square_Feet__c = '3000';
    p.pool__c = 'No';
    insert p;
  }

  static testMethod void testCallBeekin() {
    List<Property__c> ps = [
      SELECT
        Id,
        Name,
        City__c,
        State__c,
        ZipCode__c,
        Number_of_Beds__c,
        Number_of_Bath__c,
        Square_Feet__c,
        Year_Built__c,
        Property__c.Deal__c,
        pool__c,
        Property_Type__c
      FROM Property__c
      LIMIT 1
    ];
    Id recordId = ps[0].Id;
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockBeekinCallout());
    BeekinAPI.callBeekinSingle(ps[0], recordId);
    Test.stopTest();
  }
    
  static testMethod void testCallBeekinBatch() {
    List<Property__c> ps = [
      SELECT
        Id,
        Name,
        City__c,
        State__c,
        ZipCode__c,
        Number_of_Beds__c,
        Number_of_Bath__c,
        Square_Feet__c,
        Year_Built__c,
        Property__c.Deal__c,
        pool__c,
        Property_Type__c
      FROM Property__c
      LIMIT 1
    ];
    Id recordId = ps[0].Id;
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockBeekinCallout());
    BeekinAPI.callBeekin(ps);
    Test.stopTest();
  }    
    
  public class MockBeekinCallout implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest request) {
     String endpoint = 'https://beta.api.beekin.co/' + '/rent-estimate' + 'address=9216 Maverick Dr,Cincinnati,OH,45231&sqft=1359&beds=4&baths=1&property_type=0';
     String method = 'GET';
     HTTPResponse response = new HTTPResponse();
     response.setBody(
        '{"address": "9216 Maverick Dr,Cincinnati,OH,45231", "estimated_rent": 1607, "geolocation": { "lat": 39.2388118, "lng": -84.57107409999999},"lower": 1602,"upper": 1610}'
      );
     response.setHeader('Content-Type', 'application/json');
     response.setStatusCode(200);

     return response;
    }
  }
   
}