force-app/main/default/objects/Account/recordTypes/Correspondent_Bridge.recordType-meta.xml
<RecordType>
    <fullName>Correspondent_Bridge</fullName>
    <active>true</active>
    <label>Correspondent - Bridge</label>
</RecordType>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Correspondent__c.field-meta.xml
<CustomField>
    <fullName>Correspondent__c</fullName>
    <label>Correspondent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trades</relationshipLabel>
    <relationshipName>Trades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Deal__c/Trade_Deal__c.object-meta.xml
<CustomObject>
    <label>Trade Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Trade Deal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Deal__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Trade Deals</relationshipLabel>
    <relationshipName>Trade_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TradeTests.cls
@isTest
private class TradeTests {

    static testmethod void tradeTest1(){
        RecordType r = [SELECT Id FROM RecordType WHERE DeveloperName = 'Correspondent_Bridge' LIMIT 1];
        Account a = new Account(Name='Test Account', RecordTypeId = r.Id, BillingCountry = 'United States', BillingState = 'California');
        insert a;
        
        Trade__C t1 = new Trade__c(Correspondent__c = a.Id );
        insert t1;

        Test.startTest();
        
        Trade__C t = new Trade__c(Correspondent__c = a.Id );
        insert t;

        List<Trade_Deal__c> deals = new List<Trade_Deal__c>();
        for(Integer i = 0; i < 5; i++){
            Trade_Deal__c deal = new Trade_Deal__c();
            deal.Address__c = i + ' St';
            deal.State__c = 'CA';
            deal.Trade__c = t.Id;
            deals.add(deal);
        }

        insert deals;

        t.Status__c = 'Completed';
        update t;
        
        update deals;

        t.Status__c = 'Pending';
        update t;
        
        delete deals;

        update t;
        
        delete t;
        
        undelete t;
        
        Test.stopTest();
    }
    
    static testmethod void tradeTest2(){
        RecordType r = [SELECT Id FROM RecordType WHERE DeveloperName = 'Correspondent_Bridge' LIMIT 1];
        Account a = new Account(Name='Test Account', RecordTypeId = r.Id, BillingCountry = 'United States', BillingState = 'California');
        insert a;
        
        Trade__C t1 = new Trade__c(Correspondent__c = a.Id );
        insert t1;

        Test.startTest();
        
        Trade__C t = new Trade__c(Correspondent__c = a.Id );
        insert t;

        List<Trade_Deal__c> deals = new List<Trade_Deal__c>();
        for(Integer i = 0; i < 5; i++){
            Trade_Deal__c deal = new Trade_Deal__c();
            deal.Address__c = i + ' St';
            deal.State__c = 'CA';
            deal.Trade__c = t.Id;
            deals.add(deal);
        }
        insert deals;

        t.Status__c = 'Completed';
        update t;
        
        update deals;

        try{
            delete deals;
        }catch(exception e){}
        
        delete t;
        undelete t;
        
        Test.stopTest();
    }

}