force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Status__c</field>
            <operation>equals</operation>
            <value>Active CoreVest Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Entities</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>IF(  
 CONTAINS(RecordType.DeveloperName, &apos;LOC&apos;),
 &apos;Bridge&apos;,
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Term&apos;), 
 &apos;Term&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Loan&apos;), 
 &apos;Single Asset Rental&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Investor_DSCR&apos;), 
 &apos;Investor DSCR&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Bridge&apos;), 
 &apos;Bridge&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Acquired_Bridge_Loan&apos;), 
 &apos;Acquired Bridge Loan&apos;, 
 &apos;&apos;
 ) 
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>Formula based on the Record Type</description>
    <formula>IF( 
OR(CONTAINS(RecordType.DeveloperName, &quot;No_Renovation&quot;), 
CONTAINS(RecordType.DeveloperName, &quot;LOC&quot;) 
), &quot;Bridge&quot;, 
IF( 
CONTAINS(RecordType.DeveloperName, &quot;Term&quot;), 
&quot;Term&quot;, 
IF(
OR(
CONTAINS(RecordType.DeveloperName, &quot;Bridge_Renovation&quot;),
CONTAINS(RecordType.DeveloperName, &quot;Ground_Up_Construction&quot;)),
&quot;Renovation&quot;,
&quot;&quot;
)
 
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula based on the Record Type</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>General Task</description>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/CommunityTests.cls
@isTest
private class CommunityTests {
    // @TestSetup
    // static void makeData(){
    //   Account acc = test_Helper.createAccount();
    //     Contact cont = test_Helper.createContact( acc );
    // }

    static TestMethod void BorrowerTests(){
        User u = setupBorrower();
        Id i = [SELECT Id FROM Opportunity LIMIT 1].Id;
        Id propertyId = [SELECT Id FROM Property__c LIMIT 1].Id;
        Opportunity testOpportunity = [SELECT id,RecordType__c from Opportunity Limit 1];
        test.startTest();
        system.runAs(u){
            CommunityController.getRelationshipManager();
            CommunityController.getDealMembers(i);
            CommunityController.checkAccess(propertyId);
            RecordDetailsController.getCommunityDetails(i);
            
            //Code Added by Trivikram : Start
            CommunityController.getRecordType(propertyId);
            CommunityController.getDealInfo(testOpportunity.Id);
            CommunityController.getPortalUser();
            Contact testContact = CommunityController.getContactDetails();
            CommunityController.getUnderwriter(testOpportunity.RecordType__c);
            
            try {
                Task testTaskForException = new Task();
                CommunityController.submitRequest(testContact,testTaskForException);
            }
            catch(Exception ex) {
                system.debug('Exception >>>>>> '+ex);
            }
            
            //Code Added by Trivikram : End
        }
        
        test.stopTest();
      
    }

    static TestMethod void VendorTests(){
        User u = setupVendor();
        Id i = [SELECT Id FROM Opportunity LIMIT 1].Id;
        Id propertyId = [SELECT Id FROM Property__c LIMIT 1].Id;
        test.startTest();
        system.runAs(u){
            CommunityController.getRelationshipManager();
            CommunityController.getDealMembers(i);
            CommunityController.checkAccess(propertyId);
            RecordDetailsController.getCommunityDetails(i);
        }
        
        test.stopTest();
      
    }

    // static TestMethod void Test2(){
    //     UserResource u = new UserResource()
    // }

    private static User setupBorrower(){
        Id p = [select id from profile where name='Customer Portal User'].id;

        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
       
        Contact con = new Contact(FirstName = 'test',LastName ='testCon',AccountId = ac.Id);
        insert con;

        User user = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id,
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
       
        insert user;


test_Helper.createDealLoanNumber();
        Opportunity opp = test_Helper.createOpportunity( ac, con );
        insert new Deal_Contact__c(Account__c = ac.Id, Deal__c = opp.Id);
        insert new Deal_Contact__c(Account__c = ac.Id, Deal__c = opp.Id);
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Term_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = test_Helper.createProperties(opp);

        return user; 
    }

    private static User setupVendor(){
        Id p = [SELECT Id FROM Profile WHERE Name = 'Vendor Portal User'].Id;
        Id recordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Vendor' LIMIT 1].Id;
        Account ac = new Account(name ='Grazitti') ;
        ac.RecordTypeId = recordType;
        insert ac; 
       
        Contact con = new Contact(FirstName = 'test',LastName ='testCon',AccountId = ac.Id);
        insert con;

        User user = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id,
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
       
        insert user;


test_Helper.createDealLoanNumber();
        Opportunity opp = test_Helper.createOpportunity( ac, con );
        insert new Deal_Contact__c(Account__c = ac.Id, Deal__c = opp.Id);
        insert new Deal_Contact__c(Account__c = ac.Id, Deal__c = opp.Id);
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Term_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = test_Helper.createProperties(opp);

        return user;
    }

}