force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Appraisal__c/Appraisal__c.object-meta.xml
<CustomObject>
    <label>Appraisal</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appraisal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal__c/fields/Appraisal_Firm_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Firm_Transaction_ID__c</fullName>
    <description>Transaction ID from the Appraisal Firm</description>
    <inlineHelpText>Transaction ID from the Appraisal Firm</inlineHelpText>
    <label>Appraisal Firm Transaction ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Appraisals</relationshipLabel>
    <relationshipName>Appraisals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>Property Details Section</description>
    <label>Property Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Multi-unit (5+)</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
                <default>true</default>
                <label>SFR</label>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Condo - Detached</fullName>
            </value>
            <value>
                <fullName>Condo - High Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Low Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Mid Rise</fullName>
            </value>
            <value>
                <fullName>Condo - NonWarrantable</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>Multi-unit (1-4)</fullName>
                <isActive>false</isActive>
                <label>Multi-unit (1-4)</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
                <isActive>false</isActive>
                <label>Student Housing</label>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
                <isActive>false</isActive>
                <label>Vacation Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Calc_AveValue__c.field-meta.xml
<CustomField>
    <fullName>Calc_AveValue__c</fullName>
    <description>Comes from the AVM Provider</description>
    <inlineHelpText>Comes from the AVM Provider (Red Bell)</inlineHelpText>
    <label>Calc AveValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interior_Access_POC__c.field-meta.xml
<CustomField>
    <fullName>Interior_Access_POC__c</fullName>
    <description>Interior Access Point of Contact</description>
    <inlineHelpText>Name of person/company to contact for internal access to this Property</inlineHelpText>
    <label>Interior Access POC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <label>Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClearCapitalAPITests.cls
@isTest
private with sharing class ClearCapitalAPITests {
  @TestSetup
  static void setupTestData() {
    RecordType rt = [
      SELECT Id, DeveloperName
      FROM RecordType
      WHERE DeveloperName = 'Vendor' AND sobjectType = 'Account'
      LIMIT 1
    ];
    insert new Account(Name = 'Clear Capital', RecordTypeId = rt.Id);

    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    opp.StageName = 'Submitted to Underwriting';
    opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get('Term Loan')
      .getRecordTypeId();

    Property__c prop = new Property__c();
    prop.Property_Type__c = 'SFR';
    prop.Deal__c = opp.Id;
    prop.Calc_AveValue__c = 100000;
    prop.Name = 'test';
    prop.Property_Name__c = 'test Street';
    prop.City__c = 'test';
    prop.State__c = 'test';
    prop.ZipCode__c = '90802';
    prop.Interior_Access_POC__c = 'Test Person';

    insert prop;
  }

  static testMethod void unittest() {
    Property__c p = [SELECT Id FROM Property__c LIMIT 1];

    Test.startTest();
    System.enqueueJob(new SmartyStreetsQueueable(new List<Id>{ p.Id }));

    Map<String, Object> arguments = new Map<String, Object>();
    arguments.put('appraisalFirm', 'Clear Capital');
    arguments.put('productType', 'Interior Appraisal');
    arguments.put('rushOrder', false);
    arguments.put('turnTime', '48');
    arguments.put('dueDate', String.valueOf(System.today().addDays(10)));
    arguments.put('vendorComments', 'adsfa');
    arguments.put('', '');
    AppraisalMergeController.submitOrder(p.Id, arguments);

    Appraisal__c app = [SELECT Id FROM Appraisal__c LIMIT 1];

    AppraisalMergeController.checkStatus(app.Id);

    Database.executeBatch(new ClearCapitalBatch(), 1);
    AppraisalMergeController.retrieveOrderClearCapital(app.Id);

    Test.stopTest();
  }

  static testMethod void bpoPushTest() {
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    Property__c property = [SELECT Id FROM Property__c LIMIT 1];

    Appraisal__c app = new Appraisal__c();
    app.Property__c = property.Id;
    app.Deal__c = opp.Id;
    app.Appraisal_Firm_Transaction_ID__c = '30078381';
    insert app;

    StaticResource sr = [
      SELECT Id, NamespacePrefix, SystemModstamp, Body
      FROM StaticResource
      WHERE Name = 'ClearCapitalPushBPOTest'
      LIMIT 1
    ];

    String body = sr.Body.toString();

    Test.startTest();
    ClearCapitalPushAPI.parseBPO(body);
    Test.stopTest();
  }

  static testMethod void appraisalPushTest() {
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    Property__c property = [SELECT Id FROM Property__c LIMIT 1];

    Appraisal__c app = new Appraisal__c();
    app.Property__c = property.Id;
    app.Deal__c = opp.Id;
    app.Appraisal_Firm_Transaction_ID__c = '30078370';
    insert app;
    ClearCapitalPushAPI.createSuccessAck();
    StaticResource sr = [
      SELECT Id, NamespacePrefix, SystemModstamp, Body
      FROM StaticResource
      WHERE Name = 'ClearCapitalPushAppraisalTest'
      LIMIT 1
    ];

    String body = sr.Body.toString();

    Test.startTest();
    ClearCapitalPushAPI.parseAppraisal(body);
    Test.stopTest();
  }

  static testMethod void clearvalPushTest() {
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    Property__c property = [SELECT Id FROM Property__c LIMIT 1];

    Appraisal__c app = new Appraisal__c();
    app.Property__c = property.Id;
    app.Deal__c = opp.Id;
    app.Appraisal_Firm_Transaction_ID__c = '30078377';
    insert app;

    StaticResource sr = [
      SELECT Id, NamespacePrefix, SystemModstamp, Body
      FROM StaticResource
      WHERE Name = 'ClearCapitalPushClearValTest'
      LIMIT 1
    ];

    String body = sr.Body.toString();

    Test.startTest();
    ClearCapitalPushAPI.parseClearVal(body);
    Test.stopTest();
  }
}