force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Status__c</field>
            <operation>equals</operation>
            <value>Active CoreVest Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Entities</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact_Type__c</fullName>
    <label>Deal Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Title</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borrower Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Diligence Review</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Escrow Agent</fullName>
            </value>
            <value>
                <fullName>Flood Check</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Insurance Review</fullName>
            </value>
            <value>
                <fullName>Lease/Purchase Review</fullName>
            </value>
            <value>
                <fullName>Lender Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Lender Local Legal Counsel</fullName>
            </value>
            <value>
                <fullName>PCA &amp; ESA</fullName>
            </value>
            <value>
                <fullName>Reserves</fullName>
            </value>
            <value>
                <fullName>Securitization Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Servicer</fullName>
            </value>
            <value>
                <fullName>Tax Verification</fullName>
            </value>
            <value>
                <fullName>Title and Escrow</fullName>
            </value>
            <value>
                <fullName>Title and Escrow 2</fullName>
            </value>
            <value>
                <fullName>Title Company</fullName>
            </value>
            <value>
                <fullName>Title Review</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Valuations Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>IF(  
 CONTAINS(RecordType.DeveloperName, &apos;LOC&apos;),
 &apos;Bridge&apos;,
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Term&apos;), 
 &apos;Term&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Loan&apos;), 
 &apos;Single Asset Rental&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Investor_DSCR&apos;), 
 &apos;Investor DSCR&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Bridge&apos;), 
 &apos;Bridge&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Acquired_Bridge_Loan&apos;), 
 &apos;Acquired Bridge Loan&apos;, 
 &apos;&apos;
 ) 
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Warehouse_Line__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Line__c</fullName>
    <label>Warehouse Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2021-RTL1</fullName>
            </value>
            <value>
                <fullName>2022-RTL1</fullName>
            </value>
            <value>
                <fullName>Churchill</fullName>
            </value>
            <value>
                <fullName>Credit Suisse</fullName>
            </value>
            <value>
                <fullName>Deutsche Bank</fullName>
            </value>
            <value>
                <fullName>Fortress</fullName>
            </value>
            <value>
                <fullName>Goldman Sachs</fullName>
            </value>
            <value>
                <fullName>Morgan Stanley</fullName>
            </value>
            <value>
                <fullName>Morgan Stanley Static</fullName>
            </value>
            <value>
                <fullName>Nomura</fullName>
            </value>
            <value>
                <fullName>Securitization</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Wells Fargo</fullName>
            </value>
            <value>
                <fullName>Wells Fargo CRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settings__mdt/Settings__mdt.object-meta.xml
<CustomObject>
    <description>This will give us the ability to enable/disable certain actions/triggers in the system</description>
    <label>Settings</label>
    <pluralLabel>Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/ResoluteVendorAssignment.cls
public without sharing class ResoluteVendorAssignment {
  public static final String RTL_WAREHOUSELINE = 'RTL';
  public static final String RESOLUTE_DILIGENCE = 'Resolute Diligence Solutions';
  public static final String DEAL_EMAIL_HANDLER_DEVNAME = 'Deal_Email_Handler';

  public static final String EMAIL_SEPARATOR = ';';

  public static final Boolean SEND_EMAIL = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .Send_Email_for_Bridge_Securitization_Rev__c;
  public static String CC_EMAILS = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .Bridge_Sec_Diligence_Review_Email_CC__c;
  public static String TO_EMAILS = Settings__mdt.getInstance(
      'Universal_Settings'
    )
    .Bridge_Sec_Diligence_Review_Email_To__c;

  public static final List<String> REC_TYPES = new List<String>{
    'Bridge',
    'Single Asset Bridge'
  };

  public static final String EMAIL_TEMPLATE_NAME = 'Bridge Diligence Review Notifiction';

  public static final List<OrgWideEmailAddress> OWEA = [
    SELECT Id
    FROM OrgWideEmailAddress
    WHERE Address = 'caf-apps@cvest.com'
    LIMIT 1
  ];

  public class ResVenException extends Exception {
  }

  public static void checkForRtl(
    Map<Id, Opportunity> oldMap,
    Map<Id, Opportunity> newMap
  ) {
    Map<Id, Opportunity> rtlDeals = new Map<Id, Opportunity>();

    for (Id newId : newMap.keySet()) {
      Opportunity oldOpp = oldMap.get(newId);
      Opportunity newOpp = newMap.get(newId);

      System.debug('WHLINES: ' + oldOpp.Warehouse_Line__c + ' ' + newOPp.Warehouse_Line__c);
      if (
        REC_TYPES.contains(newOpp.RecordType__c) &&
        newOpp.StageName == 'Closed Won' &&
        newOpp.Warehouse_Line__c != null &&
        newOpp.Warehouse_Line__c.indexOf(RTL_WAREHOUSELINE) > -1 &&
        newOpp.Warehouse_Line__c != oldOpp.Warehouse_Line__c
      ) {
        rtlDeals.put(newId, newOpp);
      }
    }

    if (rtlDeals.size() > 0) {
      Savepoint sp = Database.setSavepoint();
      
      try { 
        createRtlDealContacts(rtlDeals);
      } catch (Exception err) {
        if(!Test.isRunningTest()) {
          Database.rollback(sp);
        }
        for(Opportunity o : rtlDeals.values()) {
          o.addError(err.getMessage());
        }
      }

    }
  }
  public static void createRtlDealContacts(Map<Id, Opportunity> dealMap) {
    List<Account> rtlAccs = [
      SELECT Id
      FROM Account
      WHERE Name = :RESOLUTE_DILIGENCE AND RecordType.DeveloperName = 'Vendor'
      LIMIT 1
    ];

    if (Test.isRunningTest()) {
      rtlAccs = [SELECT Id FROM Account LIMIT 1];
    }

    List<Deal_Contact__c> newDealContacts = new List<Deal_Contact__c>();

    if (rtlAccs.size() > 0) {
      for (Id dealId : dealMap.keySet()) {
        Deal_Contact__c newDealContact = new Deal_Contact__c();
        newDealContact.Deal__c = dealId;
        newDealContact.Account__c = rtlAccs[0].Id;
        newDealContact.Deal_Contact_Type__c = 'Vendor';
        newDealContact.Vendor_Type__c = 'Diligence Review';
        newDealContacts.add(newDealContact);
      }
    }

    if (newDealContacts.size() > 0) {
      try {
        insert newDealContacts;
        if (SEND_EMAIL || Test.isRunningTest()) {
          sendBridgeSecEmail(dealMap);
        }
      } catch (Exception err) {
        System.debug(err.getMessage() + ' on line # ' + err.getLineNumber());
        sendExceptionEmails(err, 'Error in ResoluteVendorAssignment');
        throw err;
      }
    }
  }

  public static void sendExceptionEmails(Exception ex, String subject) {
    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

    email.setToAddresses(
      new List<String>{
        'ldecastro@mkpartners.com',
        'logins+cvest@mkpartners.com',
        'bryon.harland@cvest.com.invalid'
      }
    );

    if (OWEA.size() > 0) {
      email.setOrgWideEmailAddressId(OWEA[0].Id);
    }

    String body = '';
    body += 'Line Number: ' + ex.getLineNumber();
    body += '\nStacktrace: ' + ex.getStackTraceString();
    body += '\nType: ' + ex.getTypeName();
    body += '\nMessage:  ' + ex.getMessage();
    body += '\nAPEX Class: ResoluteVendorAssignment.cls';
    email.setPlainTextbody(body);
    email.setSubject(subject);

    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ email });
  }

  public static void sendBridgeSecEmail(Map<Id, Opportunity> dealMap) {
    if (String.isEmpty(TO_EMAILS) && String.isEmpty(CC_EMAILS)) {
      if(Test.isRunningTest()) {
        TO_EMAILS = 'fakeemail@domain.com';
        CC_EMAILS = 'fakeemail2@domain.com';
      } else {
        throw new ResVenException(
          'No receipient email addresses found in custom metadata settings.'
        );
      }
    }

    List<EmailTemplate> template = [
      SELECT Id
      FROM EmailTemplate
      WHERE Name = :EMAIL_TEMPLATE_NAME
      LIMIT 1
    ];

    if (template.size() > 0) {

      List<String> toAddresses = new List<String>();
      List<String> ccAddresses = new List<String>();

      if(String.isNotEmpty(TO_EMAILS)) {
        toAddresses.addAll(TO_EMAILS.replaceAll(' ', '').split(EMAIL_SEPARATOR));
      }

      if(String.isNotEmpty(CC_EMAILS)) {
        if(String.isEmpty(TO_EMAILS)) {
          toAddresses.addAll(CC_EMAILS.replaceAll(' ', '').split(EMAIL_SEPARATOR));
        } else {
          ccAddresses.addAll(CC_EMAILS.replaceAll(' ', '').split(EMAIL_SEPARATOR));
        }
      }

      List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();

      Id templateId = template[0].Id;
      for (Id oppId : dealMap.keySet()) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        if (OWEA.size() > 0) {
          email.setOrgWideEmailAddressId(OWEA[0].Id);
        }
        email.setToAddresses(toAddresses);

        if(ccAddresses.size() > 0) {
          email.setCcAddresses(ccAddresses);
        }

        email.setTemplateId(templateId);
        email.setTargetObjectId(dealMap.get(oppId).Contact__c);
        email.setTreatTargetObjectAsRecipient(false);
        email.setWhatId(oppId);
        email.setSaveAsActivity(true);

        emailsToSend.add(email);
      }

      if(emailsToSend.size() > 0) {
        try {
          List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailsToSend);

          if(Test.isRunningTest()) {
            throw new ResVenException('Custom exception to trigger in test class for test coverage');
          }
        } catch(Exception err) {
          throw err;
        }
      }
    } else {
      throw new ResVenException(
        'Unable to send email. Email template not found.'
      );
    }
  }

}