force-app/main/default/objects/Checklist_Item__c/Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <label>Checklist Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist Items</relationshipLabel>
    <relationshipName>Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Doc_Structure_Id__c.field-meta.xml
<CustomField>
    <fullName>Doc_Structure_Id__c</fullName>
    <externalId>true</externalId>
    <label>Doc Structure Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Folder_String__c.field-meta.xml
<CustomField>
    <fullName>Folder_String__c</fullName>
    <label>Folder String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Checklist Items</relationshipLabel>
    <relationshipName>Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/recordTypes/Document_Upload.recordType-meta.xml
<RecordType>
    <fullName>Document_Upload</fullName>
    <active>true</active>
    <label>Document Upload</label>
</RecordType>

force-app/main/default/objects/Checklist_Section__c/Checklist_Section__c.object-meta.xml
<CustomObject>
    <label>Checklist Section</label>
    <nameField>
        <label>Checklist Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Section__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist Sections</relationshipLabel>
    <relationshipName>Checklist_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Checklist Sections</relationshipLabel>
    <relationshipName>Checklist_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who uploaded this Document</description>
    <label>Added By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents_Added</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Added_On__c.field-meta.xml
<CustomField>
    <fullName>Added_On__c</fullName>
    <description>The Date the Document was uploaded</description>
    <label>Added On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Checklist_Item__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Item</label>
    <referenceTo>Checklist_Item__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 – Closing Statement</fullName>
            </value>
            <value>
                <fullName>2 – Settlement Statement</fullName>
            </value>
            <value>
                <fullName>Acquisition Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>Acquisition Questionnaire</fullName>
            </value>
            <value>
                <fullName>Advance Funding Document</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Alta Survey</fullName>
            </value>
            <value>
                <fullName>ALT Valuation Review / Letter</fullName>
            </value>
            <value>
                <fullName>AOM / Collateral AOM to Title</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Appraisal Report</fullName>
            </value>
            <value>
                <fullName>Approved Building Plans</fullName>
                <label>Approved building plans</label>
            </value>
            <value>
                <fullName>Architects Agreement</fullName>
            </value>
            <value>
                <fullName>Assignment of Leases, Contracts and Asset-Related Property</fullName>
            </value>
            <value>
                <fullName>Assignment of Management</fullName>
            </value>
            <value>
                <fullName>Assignment of Management Agreement</fullName>
            </value>
            <value>
                <fullName>Assignments</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Background/Credit</fullName>
            </value>
            <value>
                <fullName>Background and Credit Search</fullName>
            </value>
            <value>
                <fullName>Background Check</fullName>
            </value>
            <value>
                <fullName>Background Letter of Explanation</fullName>
            </value>
            <value>
                <fullName>Bank Statements (evidence of collections and bill payment)</fullName>
            </value>
            <value>
                <fullName>Bill of Sale</fullName>
            </value>
            <value>
                <fullName>Bills (Tax, Insurance, Utility, etc.)</fullName>
            </value>
            <value>
                <fullName>Bio / Resume</fullName>
            </value>
            <value>
                <fullName>Black Knight Tax Results</fullName>
            </value>
            <value>
                <fullName>Blank Form Lease</fullName>
            </value>
            <value>
                <fullName>Bonding Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Folder_String__c.field-meta.xml
<CustomField>
    <fullName>Folder_String__c</fullName>
    <formula>TEXT(Type__c) + IF(ISBLANK(Text(Section__c)),&apos;&apos;, &apos;;&apos;  + TEXT(Section__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Folder String</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Property__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User who reviewed this Document</description>
    <label>Reviewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Reviewed_On__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_On__c</fullName>
    <description>The Date the Document was reviewed</description>
    <label>Reviewed On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PortalAPIDocumentVault.cls
@RestResource(urlMapping='/portal/documentvault/*')
global without sharing class PortalAPIDocumentVault {
  static String portalId;
  static String contactId;

  public static Integer paginationStart;
  public static Integer paginationEnd;
  public static Boolean usePagination;

  static Id recordId;

  static Map<Id, ContentVersion> contentVersionMap;

  @HttpGet
  global static void doGet() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');

    String pageSizeParam = RestContext.request.params.get('pageSize');
    Integer pageSize = null;
    if (String.isNotBlank(pageSizeParam)) {
      pageSize = Integer.valueOf(pageSizeParam);
    }

    Integer page = null;
    String pageParam = RestContext.request.params.get('page');
    if (String.isNotBlank(pageParam)) {
      page = Integer.valueOf(pageParam);
    }

    usePagination = false;
    if (pageSize != null && page != null) {
      //   paginationStart = pageSize * (page - 1) - 1; // 2
      //   paginationEnd = page * pageSize - 1; // 2
      paginationStart = (page - 1) * pageSize; //2
      paginationEnd = page * pageSize; //3
      usePagination = true;
    }

    portalId = params[3];
    system.debug(params);
    PortalAPIUser.PortalUser user = new PortalAPIUser.PortalUser(portalId);
    if (user.id != null) {
      if (params[4] == 'uncategorized') {
        List<UncategorizedDocument> docs = getUncategorizedDocuments();

        if (params.size() > 5 && params[5] == 'count') {
          Map<String, Object> countResponse = new Map<String, Integer>();
          countResponse.put('count', docs.size());

          res.addHeader('Content-Type', 'application/json');
          res.responseBody = Blob.valueOf(JSON.serialize(countResponse, true));
        } else {
          List<UncategorizedDocument> docsToSend = new List<UncategorizedDocument>();
          if (usePagination) {
            for (Integer i = paginationStart; i < paginationEnd; i++) {
              if (i < docs.size()) {
                docsToSend.add(docs[i]);
              }
            }
          } else {
            docsToSend = docs;
          }

          res.addHeader('Content-Type', 'application/json');
          res.responseBody = Blob.valueOf(JSON.serialize(docsToSend, true));
        }
      } else {
        contactId = user.contactId;
        recordId = params[4];
        DocumentVault vault = createVault();
        system.debug(vault);
        res.addHeader('Content-Type', 'application/json');
        res.responseBody = Blob.valueOf(JSON.serialize(vault, true));
      }
    } else {
      Map<String, String> respBody = new Map<String, String>();
      res.addHeader('Content-Type', 'application/json');
      respBody.put('status', 'error');
      respBody.put('message', 'User Id Not Found');
      res.statusCode = 404;
      res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    }
  }

  public static List<UncategorizedDocument> getUncategorizedDocuments() {
    List<UncategorizedDocument> documents = new List<UncategorizedDocument>();
    for (ContentVersion cv : [
      SELECT Id, Title, FileType, FileExtension, ContentSize, LastModifiedDate
      FROM ContentVersion
      WHERE
        Uploaded_From_Portal_Id__c = :portalId
        AND Linked_To_Record__c = FALSE
      ORDER BY LastModifiedDate DESC
    ]) {
      documents.add(new UncategorizedDocument(cv));
    }

    return documents;
  }

  class UncategorizedDocument {
    Id id;
    String fileName;
    String fileExtension;
    Integer fileSize;
    DateTime lastModifiedDate;

    UncategorizedDocument(ContentVersion cv) {
      this.id = cv.Id;
      this.fileName = cv.Title;
      this.fileExtension = cv.FileExtension;
      this.fileSize = cv.ContentSize;
      this.lastModifiedDate = cv.LastModifiedDate;
    }
  }

  public static DocumentVault createVault() {
    String sobjectType = recordId.getSObjectType().getDescribe().getName();
    DocumentVault vault = new DocumentVault();
    if (sobjectType == 'Property__c') {
      vault = createPropertyVault();
    } else if (sobjectType == 'Opportunity') {
      vault = createLoanVault();
    }

    return vault;
  }

  public static DocumentVault createLoanVault() {
    Opportunity deal = [SELECT Id, Name FROM Opportunity WHERE Id = :recordId];
    DocumentVault vault = new DocumentVault();
    vault.id = deal.Id;
    vault.Name = deal.Name;

    List<Checklist_Item__c> items = new List<Checklist_Item__c>();
    contentVersionMap = new Map<Id, ContentVersion>();
    for (Checklist_Item__c item : [
      SELECT
        Id,
        Property__c,
        Deal__c,
        Doc_Structure_Id__c,
        Document_Type__c,
        Folder_String__c,
        (
          SELECT
            Id,
            Added_On__c,
            Added_By__r.Name,
            Document_Type__c,
            Reviewed_By__r.Name,
            Reviewed_On__c,
            File_Name__c,
            ContentVersion_Id__c
          FROM Deal_Documents__r
        )
      FROM Checklist_Item__c
      WHERE
        Checklist_Section__r.Checklist__r.Deal__c = :recordId
        AND RecordType.DeveloperName = 'Document_Upload'
        AND ((Checklist_Section__r.Type__c = 'Opportunity'
        AND Responsible_Party__c = 'Sponsor')
        OR (Checklist_Section__r.Type__c = 'Sponsor'
        AND Checklist_Section__r.Deal_Contact__r.Contact__c = :contactId))
    ]) {
      items.add(item);
      for (Deal_Document__c doc : item.Deal_Documents__r) {
        contentVersionMap.put(doc.ContentVersion_Id__c, null);
      }
      //vault.addItem(item);
    }

    for (ContentVersion cv : [
      SELECT Id, FileExtension
      FROM ContentVersion
      WHERE Id IN :contentVersionMap.keySet()
    ]) {
      contentVersionMap.put(cv.Id, cv);
    }

    for (Checklist_Item__c item : items) {
      vault.addItem(item);
    }
    vault.folders.sort();
    for (DocumentFolder folder : vault.folders) {
      folder.documents.sort();
    }
    return vault;
  }

  public static DocumentVault createPropertyVault() {
    Property__c property = [
      SELECT Id, Deal__c, Name
      FROM Property__c
      WHERE Id = :recordId
    ];
    DocumentVault vault = new DocumentVault();
    vault.id = property.Id;
    vault.Name = property.Name;
    List<Checklist_Item__c> items = new List<Checklist_Item__c>();
    contentVersionMap = new Map<Id, ContentVersion>();
    for (Checklist_Item__c item : [
      SELECT
        Id,
        Property__c,
        Deal__c,
        Doc_Structure_Id__c,
        Document_Type__c,
        Folder_String__c,
        (
          SELECT
            Id,
            Added_On__c,
            Added_By__r.Name,
            Document_Type__c,
            Reviewed_By__r.Name,
            Reviewed_On__c,
            File_Name__c,
            ContentVersion_Id__c
          FROM Deal_Documents__r
        )
      FROM Checklist_Item__c
      WHERE
        Property__c = :recordId
        AND RecordType.DeveloperName = 'Document_Upload'
        AND Responsible_Party__c = 'Sponsor'
    ]) {
      //vault.addItem(item);
      items.add(item);
      for (Deal_Document__c doc : item.Deal_Documents__r) {
        contentVersionMap.put(doc.ContentVersion_Id__c, null);
      }
    }

    for (ContentVersion cv : [
      SELECT Id, FileExtension
      FROM ContentVersion
      WHERE Id IN :contentVersionMap.keySet()
    ]) {
      contentVersionMap.put(cv.Id, cv);
    }

    for (Checklist_Item__c item : items) {
      vault.addItem(item);
    }
    vault.folders.sort();

    for (DocumentFolder folder : vault.folders) {
      folder.documents.sort();
    }

    return vault;
  }

  public class DocumentVault {
    public List<DocumentFolder> folders;
    public Id id;
    public string name;

    transient Map<String, DocumentFolder> folderMap;

    DocumentVault() {
      folders = new List<DocumentFolder>();
      folderMap = new Map<String, DocumentFolder>();
    }

    public void addItem(Checklist_Item__c item) {
      String folderString = item.Folder_String__c;
      List<String> folderStrings = folderString.split(';');

      if (folderStrings.size() > 1) {
        String folderName = folderStrings[1];
        if (!folderMap.containsKey(folderName)) {
          folderMap.put(folderName, new DocumentFolder(folderName));
          folders.add(folderMap.get(folderName));
        }

        folderMap.get(folderName).addItem(item);
      } else {
        if (!folderMap.containsKey(folderStrings[0])) {
          folderMap.put(folderStrings[0], new DocumentFolder(folderStrings[0]));
          folders.add(folderMap.get(folderStrings[0]));
        }

        folderMap.get(folderStrings[0]).addItem(item);
      }
    }
  }

  public class DocumentFolder implements Comparable {
    String folderName;
    public List<ChecklistItem> documents;
    //public List<DocumentFolder> folders;

    //transient Map<String, DocumentFolder> folderMap;
    DocumentFolder(String folderName) {
      this.folderName = folderName;
      //folderMap = new Map<String, DocumentFolder>();
      //folders = new List<DocumentFolder>();
      documents = new List<ChecklistItem>();
    }

    public void addItem(Checklist_Item__c item) {
      String folderString = item.Folder_String__c;
      List<String> folderStrings = folderString.split(';');

      ChecklistItem checklistItem = new ChecklistItem(item);
      //system.debug(folderString);
      // if (folderStrings.size() > 1) {
      //   String folderName = folderStrings[1];
      //   if (!folderMap.containsKey(folderName)) {
      //     folderMap.put(folderName, new DocumentFolder(folderName));
      //     folders.add(folderMap.get(folderName));
      //   }

      //   folderMap.get(folderName).documents.add(checklistItem);
      //   //folderMap.get(folders[1]).addDocument(item);
      // } else {
      //   documents.add(checklistItem);
      // }
      documents.add(checklistItem);
    }

    public Integer compareTo(Object folder) {
      DocumentFolder compareToFOlder = (DocumentFOlder) folder;
      if (this.folderName > compareToFolder.folderName) {
        return 1;
      } else if (this.folderName < compareToFolder.folderName) {
        return -1;
      } else {
        return 0;
      }
    }
  }

  public class ChecklistItem implements Comparable {
    Id itemId;
    // List<Deal_Document__c> uploadedDocuments;
    List<Document> uploadedDocuments;
    String documentType;

    ChecklistItem(Checklist_Item__c item) {
      itemId = item.id;
      documentType = item.Document_Type__c;

      uploadedDocuments = new List<Document>();
      // if (item.Deal_Documents__r.size() > 0) {
      //   uploadedDocuments.add(new Document(doc));
      //   // uploadedDocuments = item.Deal_Documents__r;
      // }
      for (Deal_Document__c doc : item.Deal_Documents__r) {
        uploadedDocuments.add(new Document(doc));
      }
    }

    public Integer compareTo(Object item) {
      ChecklistItem itemToCompare = (ChecklistItem) item;
      if (this.documentType > itemToCompare.documentType) {
        return 1;
      } else if (this.documentType < itemToCompare.documentType) {
        return -1;
      } else {
        return 0;
      }
    }
  }

  public class Document {
    public String fileName;
    public string fileExtension;
    public String id;
    Document(Deal_Document__c doc) {
      fileName = doc.File_Name__c;

      ContentVersion cv = contentVersionMap.get(doc.ContentVersion_Id__c);
      if (cv != null) {
        this.fileExtension = cv.FileExtension;
        this.id = cv.Id;
      }
    }
  }

  @HttpPost
  global static void doPost() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');

    if (params[3] == 'upload') {
      Map<String, Object> body = (Map<String, Object>) System.JSON.deserializeUntyped(
        req.requestBody.toString()
      );

      Id id = (Id) body.get('id');
      //   Id docStructureId = body.get('docStructureId');
      Id itemId = (Id) body.get('itemId');

      Checklist_Item__c item = [
        SELECT
          Id,
          Doc_Structure_Id__c,
          Property__c,
          Deal__c,
          Property__r.Deal__c,
          Deal_Contact__c,
          Deal_Contact__r.Deal__c
        FROM Checklist_Item__c
        WHERE Id = :itemId
        LIMIT 1
      ];
      ContentVersion cv = [
        SELECT Id, Title, ContentDocumentId
        FROM ContentVersion
        WHERE Id = :id
        LIMIT 1
      ];
      Deal_Document__c dealDoc = new Deal_Document__c();
      dealDoc.Document_Structure_Id__c = item.Doc_Structure_Id__c;
      dealDoc.File_Name__c = cv.Title;
      dealDoc.ContentVersion_Id__c = cv.Id;
      dealDoc.Attachment_Id__c = cv.ContentDocumentId;
      dealDoc.Deal__c = item.Deal__c;
      if (String.isNotBlank(item.Property__c)) {
        dealDoc.Property__c = item.Property__c;
        dealDoc.Deal__c = item.Deal__c;
      }

      if (String.isNotBlank(item.Deal_Contact__c)) {
        dealDoc.Deal_Contact__c = item.Deal_Contact__c;
        dealDoc.Deal__C = item.Deal_Contact__r.Deal__c;
      }

      dealDoc.Checklist_Item__c = itemId;

      dealDoc.Added_By__c = UserInfo.getUserId();
      dealDoc.Added_On__c = system.now();

      insert dealDoc;

      cv.Linked_To_Record__c = true;
      update cv;

      ContentDocumentLink cdl = new ContentDocumentLink();
      cdl.ContentDocumentId = cv.ContentDocumentId;
      cdl.LinkedEntityId = dealDoc.Id;
      cdl.ShareType = 'V';
      cdl.Visibility = 'AllUsers';
      insert cdl;

      Map<String, String> responseBody = new Map<String, String>();
      responseBody.put('status', 'success');
      responseBody.put('message', 'Deal Document created successfully');
      res.addHeader('Content-Type', 'application/json');
      res.responseBody = Blob.valueOf(JSON.serialize(responseBody, true));
    }
  }
}