force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comment</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Status__c/Loan_Status__c.object-meta.xml
<CustomObject>
    <label>Loan Note</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Status__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Loan_Status__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <description>Deal this Loan Status Update is related to</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Loan_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Status__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Subject of this Loan Status update</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoanStatusUpdatesController.cls
public class LoanStatusUpdatesController {
	@AuraEnabled
    public static List<Loan_Status__c> getRecord(String dealId){
        return [Select Id,Subject__c,Comment__c,CreatedBy.Name,CreatedDate from Loan_Status__c where Deal__c=:dealId ORDER BY CreatedDate DESC NULLS LAST];
    }
    
    @AuraEnabled
    public static List<Loan_Status__c> deleteRecord(String recordId, String dealId){
        delete [Select Id from Loan_Status__c where Id=:recordId];
        return getRecord(dealId);
    }
}