force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Alchemy_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_User_Id__c</fullName>
    <label>Alchemy_User_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Application_Property__c/Application_Property__c.object-meta.xml
<CustomObject>
    <label>Application Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Property__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Properties</relationshipLabel>
    <relationshipName>Application_Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Alchemy_Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Alchemy Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>Property Details Section</description>
    <label>Property Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationTests.cls
@isTest
private class ApplicationTests {
  @testSetup
  static void setup() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    test_Helper.createDealLoanNumber();
    Application__c app = new Application__c(
      Contact__c = cont.Id,
      Alchemy_User_Id__c = 'af-sdba',
      Loan_Type__c = 'Single Asset Bridge Loan'
    );
    insert app;

    cont.Alchemy_Portal_Id__c = 'af-sdba';
    cont.Email = 'portalapitest@example.com';
    update cont;
  }

  static testMethod void applicationAPITest() {
    Application__c app = [SELECT Id FROM Application__c LIMIT 1];

    Map<String, String> params = new Map<String, String>();

    params.put('recordId', app.Id);
    params.put('Name', 'Test');

    Application_Property__c prop = new APplication_Property__c();
    prop.Application__c = app.Id;
    prop.Property_Type__c = 'Townhome';
    prop.Address__c = 'Test Property';
    insert prop;

    ApplicationHelper.convertApplication(params, null);

  }
}