force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Alchemy_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_User_Id__c</fullName>
    <label>Alchemy_User_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <label>Borrower Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application (Broker)</relationshipLabel>
    <relationshipName>Broker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Broker_Alchemy_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Broker_Alchemy_User_Id__c</fullName>
    <label>Broker Alchemy User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Application__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/objects/Application__c/recordTypes/Term.recordType-meta.xml
<RecordType>
    <fullName>Term</fullName>
    <active>true</active>
    <label>Term</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Alchemy_Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Alchemy Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Alchemy_Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Alchemy Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Project_Strategy__c</fullName>
    <description>Bridge Use - Multifamily Light Lift: renovation loan is less than 50% of purchase price, Multifamily Heavy Lift: renovation loan is more than 50% of purchase price, Multifamily Lease-Up/No Rehab: no renovation funds given, Conversion to Multifamily: Converting a property into MF, Multifamily GUC: ground up construction for MF properties</description>
    <label>Project Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fix and Flip</fullName>
            </value>
            <value>
                <fullName>Renovate and Rent</fullName>
            </value>
            <value>
                <fullName>Portfolio Acquisition</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Multifamily Light Lift</fullName>
            </value>
            <value>
                <fullName>Multifamily Heavy Lift</fullName>
            </value>
            <value>
                <fullName>Multifamily Lease-Up/No Rehab</fullName>
            </value>
            <value>
                <fullName>Conversion to Multifamily</fullName>
            </value>
            <value>
                <fullName>Multifamily GUC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PortalAPIBroker.cls
@RestResource(urlMapping='/portal/broker/*')
global without sharing class PortalAPIBroker {
  @HttpPost
  global static void doPost() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');

    Map<String, Object> body = (Map<String, Object>) System.JSON.deserializeUntyped(
      req.requestBody.toString()
    );

    if (params[3] == 'invite') {
      String brokerId = (String) body.get('brokerId');
      String borrowerEmail = (String) body.get('borrowerEmail');
      String borrowerFirstName = (String) body.get('borrowerFirstName');
      String borrowerLastName = (String) body.get('borrowerLastName');
      String companyName;
      if (body.containsKey('borrowerCompany')) {
        companyName = (String) body.get('borrowerCompany');
      }
      String borrowerId = (String) body.get('borrowerId');
      String dealId = (String) body.get('dealId');

      Id applicationId;
      if (body.containsKey('applicationId')) {
        applicationId = (Id) body.get('applicationId');
      }

      if (applicationId != null) {
        Application__c application = [
          SELECT Id, Deal__c
          FROM Application__c
          WHERE Id = :applicationId
          LIMIT 1
        ];

        if (dealId == null) {
          dealId = application.Deal__c;
        }
      }

      List<Contact> existingContacts = [
        SELECT Id
        FROM Contact
        WHERE Alchemy_Portal_Id__c = :borrowerId
      ];
      List<Lead> existingLeads = [
        SELECT Id
        FROM Lead
        WHERE Alchemy_Portal_Id__c = :borrowerId
      ];

      Id leadId;
      Id contactId;

      Contact broker = [
        SELECT Id
        FROM Contact
        WHERE Alchemy_Portal_Id__c = :brokerId
        LIMIT 1
      ];

      if (existingContacts.size() > 0) {
        contactId = existingContacts[0].Id;
      } else if (existingLeads.size() > 0) {
        leadId = existingLeads[0].Id;
      }

      if (leadId == null && contactId == null) {
        Lead newLead = new Lead();
        newLead.FirstName = borrowerFirstName;
        newLead.LastName = borrowerLastName;
        newLead.Company = companyName;

        insert newLead;

        leadId = newLead.Id;
      }

      system.debug(dealId);

      List<Opportunity> opps = [
        SELECT
          Id,
          LOC_Loan_Type__c,
          Project_Strategy__c,
          Product_Sub_Type__c,
          Type
        FROM Opportunity
        WHERE Id = :dealId
      ];
      String dealType = '';
      String loanType = '';
      if (opps.size() > 0) {
        Opportunity opp = opps[0];
        if (opp.LOC_Loan_Type__c == 'Term Loan') {
          dealType = 'Rental Portfolio';
        }
        if (
          opp.LOC_Loan_Type__c == 'Credit Line' &&
          opp.Project_Strategy__c != 'Fix and Flip'
        ) {
          dealType = 'Credit Line';
        }
        if (
          opp.LOC_Loan_Type__c == 'Credit Line' &&
          opp.Project_Strategy__c == 'Fix and Flip'
        ) {
          dealType = 'Credit Line';
        }

        if (
          opp.LOC_Loan_Type__c == 'Credit Line' &&
          opp.Product_Sub_Type__c == 'Build to Rent'
        ) {
          dealType = 'Build for Rent';
        }

        if (opp.LOC_Loan_Type__c == 'Build to Rent') {
          dealType = 'Build for Rent';
        }

        if (
          opp.LOC_Loan_Type__c == 'Single Asset (1-4 Unit)' ||
          opp.LOC_Loan_Type__c == 'Single Asset (5-10 Unit)'
        ) {
          dealType = 'Single Asset Bridge Loan';
        }
        if (opp.Loc_Loan_Type__c == 'Multifamily/CRE') {
          dealType = 'Multifamily';
        }

        if (opp.LOC_Loan_Type__c == 'Model Home Release') {
          dealType = 'Model Home Release';
        }

        if (opp.LOC_Loan_Type__c == 'Single Asset Rental') {
          dealType = 'Single Rental';
        }

        if (opp.LOC_Loan_Type__c == 'Single Rental Loan') {
          dealType = 'Single Rental';
        }

        if (dealType == 'Rental Portfolio') {
          loanType = 'Rental Portfolio';
        } else if (dealType == 'Build for Rent') {
          loanType = 'Build for Rent';
        } else if (dealType == 'Credit Line') {
          loanType = 'Credit Line';
        } else if (dealType == 'Bridge Loan') {
          loanType = 'Single Asset Bridge Loan';
        } else if (dealType == 'Multifamily') {
          loanType = 'Multifamily';
        } else if (dealType == 'Model Home Lease') {
          // loanType = 'Model Home Lease';
        } else if (dealType == 'Single Rental') {
          // loanType = 'Rental';
        }
      }

      Application__c app = new Application__c();
      app.Alchemy_User_Id__c = borrowerId;
      app.Borrower_Name__c = borrowerFirstName + ' ' + borrowerLastName;
      app.Lead__c = leadId;
      app.Contact__c = contactId;
      app.Broker__c = broker.Id;
      app.Broker_Alchemy_User_Id__c = brokerId;
      app.Deal__c = dealId;
      app.Id = applicationId;
      app.Loan_Type__c = loanType;
      //   stuff goes here..//

      //   app.Deal__c = dealId

      upsert app;

      PortalAPIApplication.ApplicationSmall applicationSmall = new PortalAPIApplication.ApplicationSmall(
        PortalAPIApplication.queryApplication(app.Id)
      );

      res.addHeader('Content-Type', 'application/json');
      res.responseBody = Blob.valueOf(JSON.serialize(applicationSmall, true));
    }
  }
}