force-app/main/default/objects/Loan_Fee__c/Loan_Fee__c.object-meta.xml
<CustomObject>
    <description>Fees associated to Loans</description>
    <label>Loan Fee</label>
    <nameField>
        <displayFormat>LF-{000000}</displayFormat>
        <label>Loan Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fee__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Deal associated with this fee</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The Amount of this Fee</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property that this Fee is related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Reference Number for this Fee</description>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vendor this fee is paid to</description>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/ScheduleOfLenderCostControllerTest.cls
@isTest
private class ScheduleOfLenderCostControllerTest {

    static TestMethod void testMethod1(){
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity opp = test_Helper.createOpportunity( acc, cont );
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Term_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = test_Helper.createProperties(opp);
		
		Loan_Fee__c Loan_Fee=new Loan_Fee__c
		(
			Deal__c=opp.Id,
			Fee_Amount__c=1000,
			Reference__c='121212',
			vendor__c=acc.Id
		);

        Test.startTest();
            ScheduleOfLenderCostController obj=new ScheduleOfLenderCostController();
			obj.filtersJSON='{"dealId":"0060a00000ZIMlrAAH","fundingDate2":"2018-03-31","originationfeepercentage":0,"yearSwapRate":0,"installmentcomment":"1111111111","creditSpread":0,"InterestRateTermSheet":0,"InterestRateRateLock":0,"stubInterestDayCount":11,"debtreserve":null,"stubInterest":"10694.37","CorevestProceeds":"5539010.13","cfcorevestpurchaser":"2","taxentry":"11","TotalSources":"5620350.00","totalLender":"81339.87","capexentry":"11","insuranceentry":"11","tax":"0.92","capex":"0.92","totalthirdparty":63000,"insurence":"0.92","totalreserves":33,"netproceedstoborrower":5475977.13,"totaluses":5620350,"reservetax":"1","totalreservetax":"11.00","totalreserveinsurance":"11.00","totalreservecapex":"11.00","rateType":"2","reserveinsurance":"1","reservecapex":"1","titlewiringinstructions":"1111111111111"}';
			obj.getData();
			
			ScheduleOfLenderCostController.getUrlAndInstance();
			ScheduleOfLenderCostController.getDealLoanFees(opp.Id);
			ScheduleOfLenderCostController.saveDealData(opp);
			
			List<sobject> sobjects= Database.query('select id from Loan_Fee__c');
			ScheduleOfLenderCostController.upsertRecords(sobjects);
			ScheduleOfLenderCostController.deleteRecords(sobjects);
        Test.stopTest();
    }

}