force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Watch List</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Borrowed_on_Bridge_Loans__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_on_Bridge_Loans__c</fullName>
    <inlineHelpText>Total amount borrowed through Bridge and Single Asset Bridge Loans</inlineHelpText>
    <label>Borrowed on Bridge Loans</label>
    <summarizedField>Opportunity.Aggregate_Funding__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won, Expired, Matured, Paid Off, Sold</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Type</field>
        <operation>equals</operation>
        <value>Bridge Loan, SAB Loan</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Borrowed_on_Term_Loans__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_on_Term_Loans__c</fullName>
    <inlineHelpText>Total amount borrowed through Term Loans</inlineHelpText>
    <label>Borrowed on Term Loans</label>
    <summarizedField>Opportunity.Final_Loan_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won, Expired, Matured, Paid Off, Sold</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Type</field>
        <operation>equals</operation>
        <value>Term Loan</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{0000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Account_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Account_Intro_Source__c</fullName>
    <description>Account Intro Source from the Deal</description>
    <label>Account Intro Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <label>CAF YSP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Detail__c.field-meta.xml
<CustomField>
    <fullName>Commission_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Commission Type Record</description>
    <inlineHelpText>Parent Commission Type Record</inlineHelpText>
    <label>Commission Detail</label>
    <referenceTo>Commission_Detail__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <description>Commission Type from the Deal</description>
    <inlineHelpText>Internal = CoreVest sourced |  Direct = RM sourced</inlineHelpText>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <formula>Deal__r.Final_Loan_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>SAB Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Acquired Bridge Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee__c</fullName>
    <inlineHelpText>Origination Fee + Caf YSP if Term
Origination Fee percent only if Bridge</inlineHelpText>
    <label>Origination Fee % + CAF YSP</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/Commission_Detail__c.object-meta.xml
<CustomObject>
    <description>When a Deal is Closed Won, the Commission Detail Record is created.  This is the Parent Record of the Commission Record.</description>
    <label>Commission Detail</label>
    <nameField>
        <displayFormat>COMTYPE-{00000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Detail__c/fields/Account_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Account_Intro_Source__c</fullName>
    <formula>TEXT( Deal__r.Account.Introductions_Source__c ) &amp; 
IF(ISBLANK(TEXT( Deal__r.Account.Introduction_Subsource__c )),&quot;; &quot;&amp; TEXT( Deal__r.Account.Introduction_Subsource__c ),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Intro Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <formula>TEXT(Deal__r.CAF_YSP__c)</formula>
    <label>CAF YSP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <description>Commission Type from the Deal</description>
    <inlineHelpText>Internal = CoreVest sourced | Direct = RM sourced</inlineHelpText>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Deal</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commission Details</relationshipLabel>
    <relationshipName>Commission_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <formula>IF(CONTAINS(Text(Deal__r.Type), &apos;Term&apos;) , Deal__r.Final_Loan_Amount__c,  Deal__r.LOC_Commitment__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Pricing Request Approval Status</description>
    <inlineHelpText>Pricing Request Approval Status</inlineHelpText>
    <label>Pricing Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Standard Pricing - Approval Not Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_Upfront_Fee__c.field-meta.xml
<CustomField>
    <fullName>CAF_Upfront_Fee__c</fullName>
    <description>Term and Bridge Use</description>
    <label>Origination Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <description>Term Use</description>
    <label>CAF YSP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>0 BPS in Spread</fullName>
            </value>
            <value>
                <fullName>+5 BPS in Spread / +25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-5 BPS in Spread / -25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+10 BPS in Spread / +25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-10 BPS in Spread / -25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+10 BPS in spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-10 BPS in spread / -50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+15 BPS in Spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-15 BPS in Spread / -50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+20 BPS in Spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-20 BPS in Spread / -50 BPS in Commissionable Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Calculated_Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Origination_Fee__c</fullName>
    <formula>IF(OR(Record_Type_Name__c = &apos;Single_Asset_Bridge_Loan&apos;, Record_Type_Name__c = &apos;LOC_Loan&apos;),  LOC_Commitment__c * CAF_Upfront_Fee__c,
Origination_Fee__c
)</formula>
    <inlineHelpText>This is the calculated Origination Fee</inlineHelpText>
    <label>Origination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commission_Detail__c.field-meta.xml
<CustomField>
    <fullName>Commission_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commission Detail</label>
    <referenceTo>Commission_Detail__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <inlineHelpText>Internal = CoreVest sourced |  Direct = RM sourced</inlineHelpText>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee__c</fullName>
    <label>Origination Fee Entry</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Commission_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <masterLabel>Commission Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CommissionDetailExt.cls
public class CommissionDetailExt {
    public static void afterUpdate(
        List<Commission_Detail__c> newList,
        List<Commission_Detail__c> oldList
    ) {
        
        list<id> myListApproved = new List<id>();
        list<id> myListPending = new List<id>();
        
        list<id> myList = new List<id>();
        
        for (Integer i = 0; i < newList.size(); i++) {
            myList.add(newList[i].id);
            
            if (
                newList[i].Approval_Status__c == 'Approved' &&
                newList[i].Approval_Status__c != oldList[i].Approval_Status__c
            ) {
                myListApproved.add(newList[i].id);
                System.debug(newList[i].id);
            }
            else if(newList[i].Approval_Status__c == 'Pending' &&
                    oldList[i].Approval_Status__c == 'Approved'){
                        myListPending.add(newList[i].id);
                        System.debug(newList[i].id);  
                    }
        }
        
        list<Commission__c> myCommsToAdd = new List<Commission__c>();
        
        list<Commission_Detail__c> myCommDetailsTerm = [
            SELECT
            Account_Intro_Source__c,
            Id,
            CAF_YSP__c,
            Commission_Type__c,
            Deal__c,
            Final_Loan_Amount__c,
            Deal__r.id,
            Deal__r.Calculated_Origination_Fee__c,
            Deal__r.CAF_Upfront_Fee__c,
            Deal__r.Account.Borrowed_on_Term_Loans__c,
            Deal__r.Account.Borrowed_on_Bridge_Loans__c,
            Loan_Type__c,
            Originator_Paid_in_Full__c,
            Internal_Referral__c,
            Internal_Referral_Fee_Bypass__c,
            Internal_Referral_Fee__c,
            Internal_Referral__r.id,
            OwnerId,
            Name
            FROM Commission_Detail__c
            WHERE Loan_Type__C = 'Term Loan' AND Id IN :myListApproved AND Final_Loan_Amount__c <= 750000
        ];
        System.debug(myCommDetailsTerm.size());
        
        list<Commission__c> myCommsToDel = [SELECT id from Commission__c WHERE Commission_Total__c IN: myListPending];
        System.debug(myCommsToDel.size());
        
        if (myCommDetailsTerm.size() > 0) {
            for (Commission_Detail__c termComm : myCommDetailsTerm) {
                system.debug('enter forloop');
                
                decimal originationPlusCaf;
                decimal above5Mill;
                decimal above5MillComm;
                decimal finComm;
                decimal finalCommAmount;
                decimal originationFeeTotal;
                decimal orgFee = termComm.Deal__r.CAF_Upfront_Fee__c / 100;
                decimal rateBasedOnBorrowed;
                
                if (
                    termComm.Final_Loan_Amount__c <= 750000 &&
                    termComm.Commission_Type__c == 'Direct' &&
                    termComm.Originator_Paid_in_Full__c != true
                ) {
                    system.debug('under 5 mil and direct');
                    rateBasedOnBorrowed = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c -
                        termComm.Final_Loan_Amount__c >= 5000000
                        ? 0.25
                        : 0.50;
                    //UNDER 750K : if loan amount in is less than 750k then origination defaults to 7500-- the calculation==loan amount x 50 caf ysp (comes out of final loan amount) + 7500
                    decimal orgFeeException = 7500;
                    
                    system.debug(
                        'o fee' + termComm.Deal__r.Calculated_Origination_Fee__c
                    );
                    
                    if (
                        termComm.Internal_Referral__c != null && termComm.Internal_Referral_Fee_Bypass__c !=true &&
                        termComm.Internal_Referral_Fee__c != null &&
                        termComm.Internal_Referral_Fee__c != 'N/A'
                    ) {
                        //decimal internalFee = termComm.Internal_Referral_Fee__c == '20%'
                        //? .20
                        //: .50;
                        decimal internalFee;
                        
                        if(termComm.Internal_Referral_Fee__c == '10%'){
                            internalFee = .10;
                        }else if(termComm.Internal_Referral_Fee__c == '20%'){
                            internalFee = .20;
                            
                        }else if(termComm.Internal_Referral_Fee__c == '30%'){
                            internalFee = .30;
                            
                        }else if(termComm.Internal_Referral_Fee__c == '50%'){
                            internalFee = .50;
                            
                        }
                        
                        if (
                            termComm.CAF_YSP__c == '0 BPS in Spread' ||
                            termComm.CAF_YSP__c == null
                        ) {
                            decimal commRefAmount = orgFeeException * rateBasedOnBorrowed;
                            system.debug(commRefAmount);
                            decimal finalCommFee = commRefAmount * internalFee;
                            system.debug(finalCommFee);
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = 0;
                            myCommission.Origination_Fee_Amt__c = orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = orgFeeException;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = 0;
                            refCommission.Origination_Fee_Amt__c = orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = orgFeeException;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+5 BPS in Spread / +25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+10 BPS in Spread / +25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee + 0.0025;
                            
                            decimal commRefAmount =
                                ((termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException) * rateBasedOnBorrowed;
                            decimal finalCommFee = commRefAmount * internalFee;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = 0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = 0.0025 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-5 BPS in Spread / -25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-10 BPS in Spread / -25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.0025;
                            
                            decimal commRefAmount = ((termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException)* rateBasedOnBorrowed;
                            decimal finalCommFee = commRefAmount * internalFee;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = -0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = -0.0025 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+10 BPS in spread / +50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '+15 BPS in Spread / +50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+20 BPS in Spread / +50 BPS in Commissionable Fee'
                        ) {
                            // originationPlusCaf = orgFee + 0.005;
                            //system.debug(originationPlusCaf);
                            decimal commRefAmount =
                                ((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            system.debug(commRefAmount);
                            decimal finalCommFee = commRefAmount * internalFee;
                            system.debug(finalCommFee);
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Origination_Fee__c = 0.005 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = 0.005 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-10 BPS in spread / -50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '-15 BPS in Spread / -50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-20 BPS in Spread / -50 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.005;
                            
                            decimal commRefAmount =
                                ((termComm.Final_Loan_Amount__c *  -0.005) + orgFeeException)* rateBasedOnBorrowed;
                            decimal finalCommFee = commRefAmount * internalFee;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = -0.005 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = -0.005 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            myCommission.Owner__c = termComm.OwnerId;
                            
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        }
                    } else {
                        
                        if (
                            termComm.CAF_YSP__c == null ||
                            termComm.CAF_YSP__c == '0 BPS in Spread'
                        ) {
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c = orgFeeException * rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = 0;
                            myCommission.Origination_Fee_Amt__c = orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =orgFeeException * rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+5 BPS in Spread / +25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+10 BPS in Spread / +25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee + 0.0025;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ( (termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException) * rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = 0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c =(termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-5 BPS in Spread / -25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-10 BPS in Spread / -25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.0025;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ( (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException)* rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = -0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+10 BPS in spread / +50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '+15 BPS in Spread / +50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+20 BPS in Spread / +50 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee + 0.005;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = 0.005 * 100;
                            myCommission.Origination_Fee_Amt__c =(termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-10 BPS in spread / -50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '-15 BPS in Spread / -50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-20 BPS in Spread / -50 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.005;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = -0.005 * 100;
                            myCommission.Origination_Fee_Amt__c =(termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        }
                    }
                } 
                else if (
                    termComm.Final_Loan_Amount__c <= 750000 &&
                    termComm.Commission_Type__c == 'Internal' &&
                    termComm.Originator_Paid_in_Full__c != true
                ) {
                    system.debug('under 5 mil and direct');
                    rateBasedOnBorrowed = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c -
                        termComm.Final_Loan_Amount__c >= 5000000
                        ? 0.15
                        : 0.35;
                    //UNDER 750K : if loan amount in is less than 750k then origination defaults to 7500-- the calculation==loan amount x 50 caf ysp (comes out of final loan amount) + 7500
                    decimal orgFeeException = 7500;
                    
                    system.debug(
                        'o fee' + termComm.Deal__r.Calculated_Origination_Fee__c
                    );
                    
                    if (
                        termComm.Internal_Referral__c != null && termComm.Internal_Referral_Fee_Bypass__c !=true &&
                        termComm.Internal_Referral_Fee__c != null &&
                        termComm.Internal_Referral_Fee__c != 'N/A'
                    ) {
                        // decimal internalFee = termComm.Internal_Referral_Fee__c == '20%'
                        // ? .20
                        //: .50;
                        decimal internalFee;
                        
                        if(termComm.Internal_Referral_Fee__c == '10%'){
                            internalFee = .10;
                        }else if(termComm.Internal_Referral_Fee__c == '20%'){
                            internalFee = .20;
                            
                        }else if(termComm.Internal_Referral_Fee__c == '30%'){
                            internalFee = .30;
                            
                        }else if(termComm.Internal_Referral_Fee__c == '50%'){
                            internalFee = .50;
                            
                        }
                        if (
                            termComm.CAF_YSP__c == '0 BPS in Spread' ||
                            termComm.CAF_YSP__c == null
                        ) {
                            decimal commRefAmount = orgFeeException * rateBasedOnBorrowed;
                            system.debug(commRefAmount);
                            decimal finalCommFee = commRefAmount * internalFee;
                            system.debug(finalCommFee);
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = 0;
                            myCommission.Origination_Fee_Amt__c = orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = orgFeeException;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = 0;
                            refCommission.Origination_Fee_Amt__c = orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = orgFeeException;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+5 BPS in Spread / +25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+10 BPS in Spread / +25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee + 0.0025;
                            
                            decimal commRefAmount =
                                ((termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException) * rateBasedOnBorrowed;
                            decimal finalCommFee = commRefAmount * internalFee;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = 0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = 0.0025 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-5 BPS in Spread / -25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-10 BPS in Spread / -25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.0025;
                            
                            decimal commRefAmount = ((termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException)* rateBasedOnBorrowed;
                            decimal finalCommFee = commRefAmount * internalFee;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = -0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = -0.0025 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+10 BPS in spread / +50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '+15 BPS in Spread / +50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+20 BPS in Spread / +50 BPS in Commissionable Fee'
                        ) {
                            // originationPlusCaf = orgFee + 0.005;
                            //system.debug(originationPlusCaf);
                            decimal commRefAmount =
                                ((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            system.debug(commRefAmount);
                            decimal finalCommFee = commRefAmount * internalFee;
                            system.debug(finalCommFee);
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Origination_Fee__c = 0.005 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = 0.005 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            refCommission.OwnerId = termComm.OwnerId;
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-10 BPS in spread / -50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '-15 BPS in Spread / -50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-20 BPS in Spread / -50 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.005;
                            
                            decimal commRefAmount =
                                ((termComm.Final_Loan_Amount__c *  -0.005) + orgFeeException)* rateBasedOnBorrowed;
                            decimal finalCommFee = commRefAmount * internalFee;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Commission_Amount1__c = finalCommFee;
                            myCommission.Origination_Fee__c = -0.005 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Owner__c = termComm.Internal_Referral__r.id;
                            myCommission.OwnerId = termComm.Internal_Referral__r.id;
                            
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(myCommission);
                            
                            Commission__c refCommission = new Commission__c();
                            refCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            refCommission.Commission_Detail__c = termComm.Id;
                            refCommission.Commission_Type__c = termComm.Commission_Type__c;
                            refCommission.Deal__c = termComm.Deal__c;
                            refCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            refCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            refCommission.Loan_Type__c = termComm.Loan_Type__c;
                            refCommission.Commission_Amount1__c =
                                commRefAmount - finalCommFee;
                            refCommission.Origination_Fee__c = -0.005 * 100;
                            refCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            refCommission.Owner__c = termComm.OwnerId;
                            myCommission.Owner__c = termComm.OwnerId;
                            
                            refCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            refCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            refCommission.Commissionable_Amount__c = commRefAmount;
                            
                            myCommsToAdd.add(refCommission);
                        }
                    } else {
                        
                        if (
                            termComm.CAF_YSP__c == null ||
                            termComm.CAF_YSP__c == '0 BPS in Spread'
                        ) {
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c = orgFeeException * rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = 0;
                            myCommission.Origination_Fee_Amt__c = orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =orgFeeException * rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+5 BPS in Spread / +25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+10 BPS in Spread / +25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee + 0.0025;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ( (termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException) * rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = 0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c =(termComm.Final_Loan_Amount__c * 0.0025) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-5 BPS in Spread / -25 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-10 BPS in Spread / -25 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.0025;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ( (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException)* rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = -0.0025 * 100;
                            myCommission.Origination_Fee_Amt__c = (termComm.Final_Loan_Amount__c * -0.0025) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '+10 BPS in spread / +50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '+15 BPS in Spread / +50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '+20 BPS in Spread / +50 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee + 0.005;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = 0.005 * 100;
                            myCommission.Origination_Fee_Amt__c =(termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        } else if (
                            termComm.CAF_YSP__c ==
                            '-10 BPS in spread / -50 BPS in Commissionable Fee' ||
                            termCOmm.CAF_YSP__c ==
                            '-15 BPS in Spread / -50 BPS in Commissionable Fee' ||
                            termComm.CAF_YSP__c ==
                            '-20 BPS in Spread / -50 BPS in Commissionable Fee'
                        ) {
                            //originationPlusCaf = orgFee - 0.005;
                            
                            Commission__c myCommission = new Commission__c();
                            myCommission.Commission_Detail__c = termComm.Id;
                            myCommission.CAF_YSP__c = termComm.CAF_YSP__c;
                            myCommission.Commission_Type__c = termComm.Commission_Type__c;
                            myCommission.Deal__c = termComm.Deal__c;
                            myCommission.Final_Loan_Amount_Trigger__c = termComm.Final_Loan_Amount__c;
                            
                            myCommission.Account_Intro_Source__c = termComm.Account_Intro_Source__c;
                            myCommission.Loan_Type__c = termComm.Loan_Type__c;
                            myCommission.Owner__c = termComm.OwnerId;
                            myCommission.OwnerId = termComm.OwnerId;
                            
                            myCommission.Commission_Amount1__c =
                                ((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            myCommission.Origination_Fee__c = -0.005 * 100;
                            myCommission.Origination_Fee_Amt__c =(termComm.Final_Loan_Amount__c * 0.005) + orgFeeException;
                            myCommission.Total_Borrowed_on_Term__c = termComm.Deal__r.Account.Borrowed_on_Term_Loans__c;
                            myCommission.Total_Borrowed_on_Bridge__c = termComm.Deal__r.Account.Borrowed_on_Bridge_Loans__c;
                            myCommission.Commissionable_Amount__c =((termComm.Final_Loan_Amount__c * 0.005) + orgFeeException)* rateBasedOnBorrowed;
                            
                            myCommsToAdd.add(myCommission);
                        }
                    }
                } 
                
            }
        }
        
        
        
        if (myCommsToAdd.size() > 0) {
            insert myCommsToAdd;
        }
        
        if(myCommsToDel.size() > 0){
            delete myCommsToDel;
        }
      
  }
}