force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Watch List</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Id__c</fullName>
    <label>Process Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Instance_Id__c</fullName>
    <label>Process Instance Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Property_Management__c.field-meta.xml
<CustomField>
    <fullName>Property_Management__c</fullName>
    <label>Property Management</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Fully Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apex_Context__c.field-meta.xml
<CustomField>
    <fullName>Apex_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for development work only</description>
    <label>Apex Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Pricing Request Approval Status</description>
    <inlineHelpText>Pricing Request Approval Status</inlineHelpText>
    <label>Pricing Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Standard Pricing - Approval Not Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_by_Capital_Markets__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Capital_Markets__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who approved the Pricing Request</inlineHelpText>
    <label>Approved by Capital Markets</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deals5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_by_Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who approved the Pricing Request</inlineHelpText>
    <label>Approved by Underwriter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deals4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Sub_Source__c</fullName>
    <label>Deal Intro Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deal_Intro_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
                <label>5arch</label>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deal_Lost_Reason__c</fullName>
    <description>When a deal is marked as Lost (Cancelled, Withdrawn, or Rejected).  A lost reason is needed.</description>
    <inlineHelpText>Select a Deal Lost/Hold Reason, if a deal is moved to UW Hold, Withdrawn, or Rejected.</inlineHelpText>
    <label>Deal Lost/Hold Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Background</fullName>
            </value>
            <value>
                <fullName>Borrower does not like terms</fullName>
            </value>
            <value>
                <fullName>Borrower does not meet requirements</fullName>
            </value>
            <value>
                <fullName>Borrower Requested</fullName>
            </value>
            <value>
                <fullName>Borrower Unresponsive</fullName>
            </value>
            <value>
                <fullName>Broker Requested</fullName>
            </value>
            <value>
                <fullName>Business Plan</fullName>
            </value>
            <value>
                <fullName>Cost Too High</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Does not meet occupancy</fullName>
            </value>
            <value>
                <fullName>Economic Downturn</fullName>
            </value>
            <value>
                <fullName>Existing Rate Lower</fullName>
            </value>
            <value>
                <fullName>Failed to Close</fullName>
            </value>
            <value>
                <fullName>Failed to Qualify</fullName>
            </value>
            <value>
                <fullName>In Process of Withdrawal/Rejection</fullName>
            </value>
            <value>
                <fullName>Insufficient Income</fullName>
            </value>
            <value>
                <fullName>Insufficient Track Record Experience</fullName>
            </value>
            <value>
                <fullName>Litigation</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>Money Laundering</fullName>
            </value>
            <value>
                <fullName>Other – See Deal Notes</fullName>
            </value>
            <value>
                <fullName>Pending Financial Documents/Tax Returns</fullName>
            </value>
            <value>
                <fullName>Pending Property Rehab</fullName>
            </value>
            <value>
                <fullName>Pending Rehab</fullName>
            </value>
            <value>
                <fullName>Portfolio Leveraged</fullName>
            </value>
            <value>
                <fullName>Prior to Reason Requirement</fullName>
            </value>
            <value>
                <fullName>Property List Not Finalized</fullName>
            </value>
            <value>
                <fullName>Split Up Deal</fullName>
            </value>
            <value>
                <fullName>Terms Not Accepted</fullName>
            </value>
            <value>
                <fullName>Won through another broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Management__c.field-meta.xml
<CustomField>
    <fullName>Property_Management__c</fullName>
    <label>Property Management</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Self Managed</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Third Party &amp; Affiliate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Approval_TestDataFactory.cls
public class Approval_TestDataFactory {
  // public static ProcessInstanceStep createProcessInstanceStep(ProcessInstance pi){
  //     ProcessInstanceStep pis = new ProcessInstanceStep(
  //         Comments='TestComments'
  //         , ActorId = UserInfo.getUserId()
  //         , StepStatus = 'Pending'
  //         , ProcessInstanceId = pi.Id
  //         , OriginalActorId = UserInfo.getUserId()
  //         // , RemindersSent = 0
  //     );
  //     insert pis;
  //     return pis;
  // }
  //
  // public static ProcessInstance createProcessInstance(Opportunity o, String status){
  //     ProcessInstance pi = new ProcessInstance(
  //         Status = status
  //         , TargetObjectId = o.Id
  //     );
  //     insert pi;
  //     return pi;
  // }

  public static UserRole createUserRole(String s) {
    String devName = s.replace(' ', '_');
    UserRole ur = new UserRole(DeveloperName = devName, Name = s);
    insert ur;
    return ur;
  }

  public static Opportunity createDeal(
    Id capMarketId,
    Id acceptableId,
    String approvalStatus
  ) {
    Account a = new Account(
      Name = 'Approval Test Account',
      BillingStreet = 'Test',
      BillingCountry = 'United States',
      BillingState = 'California',
      BillingPostalCode = '92627'
    );
    insert a;
    Contact c = new Contact(
      FirstName = 'Alpha',
      LastName = 'Omega',
      MailingStreet = 'Gamma',
      MailingCountry = 'United States',
      MailingState = 'California',
      MailingPostalCode = '92927',
      accountId = a.Id
    );
    insert c;
    Opportunity o = new Opportunity(
      AccountId = a.Id,
      Contact__c = c.Id,
      CloseDate = System.today(),
      Name = 'TestName',
      StageName = Opportunity.StageName.getDescribe().getPicklistValues()[1]
        .getValue(),
      Deal_Lost_Reason__c = Opportunity.Deal_Lost_Reason__c.getDescribe()
          .getPicklistValues()[0]
        .getValue(),
      Approved_by_Capital_Markets__c = capMarketId,
      Approved_by_Underwriter__c = acceptableId,
      Approval_Status__c = approvalStatus,
      Deal_Intro_Source__c = 'Email',
      Deal_Intro_Sub_Source__c = 'Email'
    );
    o.Apex_Context__c = true;
    o.Property_Management__c = 'Third Party';
    insert o;
    o.Apex_Context__c = true;
    return o;
  }

  public static Profile findProfile() {
    Profile p = [
      SELECT Id
      FROM Profile
      WHERE Name = 'System Administrator'
      LIMIT 1
    ];
    return p;
  }

  public static User createUser(Integer i, Id urId, Id pId) {
    User u = new User(
      Alias = 'Alias' + String.valueOf(i),
      UserRoleId = urId,
      Username = 'cho32789@test.com',
      LastName = 'Test',
      Email = 'test@test.com',
      CommunityNickname = 'Test',
      TimeZoneSidKey = 'America/Los_Angeles',
      LocaleSidKey = 'en_US',
      LanguageLocaleKey = 'en_US',
      EmailEncodingKey = 'utf-8',
      ProfileId = pId
    );
    insert u;
    return u;
  }

  public static Approval_History__c createApprovalHistory(Id piwId, Id pisId) {
    Approval_History__c ahc = new Approval_History__c(
      Process_Id__c = piwId,
      Process_Instance_Id__c = pisId
    );
    insert ahc;
    return ahc;
  }

  public static Attachment createAttachment(Id parentId) {
    Attachment a = new Attachment(
      Body = Blob.valueOf('hello'),
      Description = 'TestDescription',
      Name = 'TestName',
      ParentId = parentId
    );
    insert a;
    return a;
  }

  public static ContentVersion createCv() {
    ContentVersion cv = new ContentVersion(
      PathOnClient = 'TestClient',
      Title = 'TestTitle',
      VersionData = Blob.valueOf('hello')
    );
    insert cv;
    ContentVersion queryCv = [
      SELECT Id, ContentDocumentId
      FROM ContentVersion
      WHERE Id = :cv.Id
    ];
    return queryCv;
  }

  public static ContentDocumentLink createCdl(Id cdId, Id parentId) {
    ContentDocumentLink cdl = new ContentDocumentLink(
      ContentDocumentId = cdId,
      LinkedEntityId = parentId,
      ShareType = 'V'
    );
    insert cdl;
    return cdl;
  }

  public static Email__c createEmail(Id aId, Id cvId, Id oId) {
    Email__c e = new Email__c(
      AttachmentId__c = aId,
      ContentVersionId__c = cvId,
      Deal__c = oId
    );
    insert e;
    return e;
  }
}