force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Watch List</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{0000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <label>CAF YSP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Detail__c.field-meta.xml
<CustomField>
    <fullName>Commission_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Commission Type Record</description>
    <inlineHelpText>Parent Commission Type Record</inlineHelpText>
    <label>Commission Detail</label>
    <referenceTo>Commission_Detail__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <description>Commission Type from the Deal</description>
    <inlineHelpText>Internal = CoreVest sourced |  Direct = RM sourced</inlineHelpText>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <formula>Deal__r.Final_Loan_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/Commission_Detail__c.object-meta.xml
<CustomObject>
    <description>When a Deal is Closed Won, the Commission Detail Record is created.  This is the Parent Record of the Commission Record.</description>
    <label>Commission Detail</label>
    <nameField>
        <displayFormat>COMTYPE-{00000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Detail__c/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <formula>TEXT(Deal__r.CAF_YSP__c)</formula>
    <label>CAF YSP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <description>Commission Type from the Deal</description>
    <inlineHelpText>Internal = CoreVest sourced | Direct = RM sourced</inlineHelpText>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Deal</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commission Details</relationshipLabel>
    <relationshipName>Commission_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <formula>TEXT(Deal__r.Deal_Intro_Source__c) + &quot;; &quot; +  TEXT(Deal__r.Deal_Intro_Sub_Source__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Intro Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Detail__c/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <formula>IF(CONTAINS(Text(Deal__r.Type), &apos;Term&apos;) , Deal__r.Final_Loan_Amount__c,  Deal__r.LOC_Commitment__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/commissionAutomationSetting__c/commissionAutomationSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used for CommissionDetail_Test class</description>
    <label>commissionAutomationSetting</label>
</CustomObject>

force-app/main/default/objects/commissionAutomationSetting__c/fields/SkipProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>SkipProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SkipProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apex_Context__c.field-meta.xml
<CustomField>
    <fullName>Apex_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for development work only</description>
    <label>Apex Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_Upfront_Fee__c.field-meta.xml
<CustomField>
    <fullName>CAF_Upfront_Fee__c</fullName>
    <description>Term and Bridge Use</description>
    <label>Origination Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <description>Term Use</description>
    <label>CAF YSP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>0 BPS in Spread</fullName>
            </value>
            <value>
                <fullName>+5 BPS in Spread / +25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-5 BPS in Spread / -25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+10 BPS in Spread / +25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-10 BPS in Spread / -25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+10 BPS in spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-10 BPS in spread / -50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+15 BPS in Spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-15 BPS in Spread / -50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+20 BPS in Spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-20 BPS in Spread / -50 BPS in Commissionable Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commission_Detail__c.field-meta.xml
<CustomField>
    <fullName>Commission_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commission Detail</label>
    <referenceTo>Commission_Detail__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <inlineHelpText>Internal = CoreVest sourced |  Direct = RM sourced</inlineHelpText>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Sub_Source__c</fullName>
    <label>Deal Intro Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deal_Intro_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
                <label>5arch</label>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/globalValueSets/Commission_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <masterLabel>Commission Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CommissionDetail_Test.cls
@isTest
private  class CommissionDetail_Test {
    //Term Section no referrals 
    @isTest static void termCommissiontest1() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 1000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Direct';
        commDetail.OwnerId = origU.Id;
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Direct';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Direct';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Direct';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Direct';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Direct';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Direct';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
                commDetail7.Approval_Status__c = 'Approved';
        update commDetail7;
        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Direct';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
                commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;
        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Direct';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
        commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;
        
        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Direct';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    } 
    
    @isTest static void termCommissiontest2() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 1000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Internal';
        commDetail.OwnerId = origU.Id;
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Internal';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Internal';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Internal';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Internal';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Internal';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Internal';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
                commDetail7.Approval_Status__c = 'Approved';
        update commDetail7;
        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Internal';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
                commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;
        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Internal';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
                commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;
        
        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Internal';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    } 
    
    @isTest static void termCommissiontest3() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 50000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Direct';
        commDetail.OwnerId = origU.Id;
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Direct';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Direct';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Direct';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Direct';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Direct';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Direct';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
                commDetail7.Approval_Status__c = 'Approved';
        update commDetail7;
        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Direct';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
                commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;
        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Direct';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
                commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;
        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Direct';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    } 
    
    @isTest static void termCommissiontest4() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 50000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Internal';
        commDetail.OwnerId = origU.Id;
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Internal';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Internal';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Internal';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Internal';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Internal';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Internal';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
        
        commDetail7.Approval_Status__c = 'Approved';
        update commDetail7;
        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Internal';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
        commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;
        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Internal';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
        commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;
        
        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Internal';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    }
    
    // with referrals
    @isTest static void termCommissiontest5() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Internal_Referral__c = origU2.id;
        topp1.Internal_Referral_Fee__c = '50%';
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 1000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Direct';
        commDetail.OwnerId = origU.Id;
        commDetail.Internal_Referral__c=origU2.Id;
        commDetail.Internal_Referral_Fee__c = '50%';
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Internal_Referral__c=origU2.Id;
        commDetail1.Internal_Referral_Fee__c = '50%';
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Direct';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Internal_Referral__c=origU2.Id;
        commDetail2.Internal_Referral_Fee__c = '50%';
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Direct';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Internal_Referral__c=origU2.Id;
        commDetail3.Internal_Referral_Fee__c = '50%';
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Direct';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Internal_Referral__c=origU2.Id;
        commDetail4.Internal_Referral_Fee__c = '50%';
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Direct';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Internal_Referral__c=origU2.Id;
        commDetail5.Internal_Referral_Fee__c = '50%';
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Direct';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Internal_Referral__c=origU2.Id;
        commDetail6.Internal_Referral_Fee__c = '50%';
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Direct';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Internal_Referral__c=origU2.Id;
        commDetail7.Internal_Referral_Fee__c = '50%';
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
                commDetail7.Approval_Status__c = 'Approved';

                update commDetail7;

        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Direct';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Internal_Referral__c=origU2.Id;
        commDetail8.Internal_Referral_Fee__c = '50%';
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
                commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;

        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Direct';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Internal_Referral__c=origU2.Id;
        commDetail9.Internal_Referral_Fee__c = '50%';
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
        
                commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;

        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Direct';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Internal_Referral__c=origU2.Id;
        commDetail10.Internal_Referral_Fee__c = '50%';
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    } 
    
    @isTest static void termCommissiontest6() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.Internal_Referral__c = origU2.id;
        topp1.Internal_Referral_Fee__c = '50%';
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 1000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Internal';
        commDetail.OwnerId = origU.Id;
        commDetail.Internal_Referral__c=origU2.Id;
        commDetail.Internal_Referral_Fee__c = '50%';
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Internal_Referral__c=origU2.Id;
        commDetail1.Internal_Referral_Fee__c = '50%';
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Internal';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Internal_Referral__c=origU2.Id;
        commDetail2.Internal_Referral_Fee__c = '50%';
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Internal';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Internal_Referral__c=origU2.Id;
        commDetail3.Internal_Referral_Fee__c = '50%';
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Internal';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Internal_Referral__c=origU2.Id;
        commDetail4.Internal_Referral_Fee__c = '50%';
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Internal';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Internal_Referral__c=origU2.Id;
        commDetail5.Internal_Referral_Fee__c = '50%';
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Internal';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Internal_Referral__c=origU2.Id;
        commDetail6.Internal_Referral_Fee__c = '50%';
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Internal';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Internal_Referral__c=origU2.Id;
        commDetail7.Internal_Referral_Fee__c = '50%';
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
                commDetail7.Approval_Status__c = 'Pending';
        update commDetail7;

        
        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Internal';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Internal_Referral__c=origU2.Id;
        commDetail8.Internal_Referral_Fee__c = '50%';
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
                        commDetail8.Approval_Status__c = 'Approved';

        update commDetail8;
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Internal';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Internal_Referral__c=origU2.Id;
        commDetail9.Internal_Referral_Fee__c = '50%';
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
                commDetail9.Approval_Status__c = 'Approved';

        update commDetail9;

        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Internal';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Internal_Referral__c=origU2.Id;
        commDetail10.Internal_Referral_Fee__c = '50%';
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    } 
    
    @isTest static void termCommissiontest7() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.Internal_Referral__c = origU2.id;
        topp1.Internal_Referral_Fee__c = '50%';
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 50000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Direct';
        commDetail.OwnerId = origU.Id;
        commDetail.Internal_Referral__c=origU2.Id;
        commDetail.Internal_Referral_Fee__c = '50%';
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Internal_Referral__c=origU2.Id;
        commDetail1.Internal_Referral_Fee__c = '50%';
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Direct';
        commDetail2.OwnerId = origU.Id;
        commDetail2.Internal_Referral__c=origU2.Id;
        commDetail2.Internal_Referral_Fee__c = '50%';
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Direct';
        commDetail3.OwnerId = origU.Id;
        commDetail3.Internal_Referral__c=origU2.Id;
        commDetail3.Internal_Referral_Fee__c = '50%';
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Direct';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Internal_Referral__c=origU2.Id;
        commDetail4.Internal_Referral_Fee__c = '50%';
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Direct';
        commDetail5.OwnerId = origU.Id;
        commDetail5.Internal_Referral__c=origU2.Id;
        commDetail5.Internal_Referral_Fee__c = '50%';
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Direct';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Internal_Referral__c=origU2.Id;
        commDetail6.Internal_Referral_Fee__c = '50%';
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Direct';
        commDetail7.OwnerId = origU.Id;
        commDetail7.Internal_Referral__c=origU2.Id;
        commDetail7.Internal_Referral_Fee__c = '50%';
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
                commDetail7.Approval_Status__c = 'Approved';
        update commDetail7;

        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Direct';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Internal_Referral__c=origU2.Id;
        commDetail8.Internal_Referral_Fee__c = '50%';
        commDetail8.Approval_Status__c = 'Pending';

        insert commDetail8;
                  commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;
        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Direct';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Internal_Referral__c=origU2.Id;
        commDetail9.Internal_Referral_Fee__c = '50%';
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
                  commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;
        
        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Direct';
        commDetail10.OwnerId = origU.Id;
        commDetail10.Internal_Referral__c=origU2.Id;
        commDetail10.Internal_Referral_Fee__c = '50%';
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    } 
    
    @isTest static void termCommissiontest8() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.Internal_Referral__c = origU2.id;
        topp1.Internal_Referral_Fee__c = '50%';
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 50000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
            .Id;
        insert topp1;
        topp1.CAF_Upfront_Fee__c = 2;
        update topp1;
        //Final Loan amount under 5 million
        
        Commission_Detail__c commDetail = new Commission_Detail__c();
        commDetail.Deal__c = topp1.Id;
        commDetail.Commission_Type__c = 'Internal';
        commDetail.OwnerId = origU.Id;
        commDetail.Approval_Status__c = 'Pending';
        
        insert commDetail;
        
        test.startTest();
        
        Commission_Detail__c commDetailUpdate = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail.Id];  
        
        commDetailUpdate.Approval_Status__c = 'Approved';
        
        update commDetailUpdate;
        
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Internal_Referral__c=origU2.Id;
        commDetail1.Internal_Referral_Fee__c = '50%';
        commDetail1.Approval_Status__c = 'Pending';
        
        insert commDetail1;
        
        Commission_Detail__c commDetail1Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail1.Id];  
        
        commDetail1Update.Approval_Status__c = 'Approved';
        
        update commDetail1Update;
        
        
        
        //CAF YSP Section 
        
        topp1.CAF_YSP__c = '0 BPS in Spread';
        update topp1;
        
        Commission_Detail__c commDetail2 = new Commission_Detail__c();
        commDetail2.Deal__c = topp1.Id;
        commDetail2.Commission_Type__c = 'Internal';
        commDetail2.OwnerId = origU.Id;
                commDetail2.Internal_Referral__c=origU2.Id;
        commDetail2.Internal_Referral_Fee__c = '50%';
        commDetail2.Approval_Status__c = 'Pending';
        
        insert commDetail2;
        
        Commission_Detail__c commDetail2Update = [SELECT Approval_Status__c from Commission_Detail__c WHERE id=:commDetail2.Id];  
        
        commDetail2Update.Approval_Status__c = 'Approved';
        
        update commDetail2Update;
        
        topp1.CAF_YSP__c = '+5 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail3 = new Commission_Detail__c();
        commDetail3.Deal__c = topp1.Id;
        commDetail3.Commission_Type__c = 'Internal';
        commDetail3.OwnerId = origU.Id;        
        commDetail3.Internal_Referral__c=origU2.Id;
        commDetail3.Internal_Referral_Fee__c = '50%';
        commDetail3.Approval_Status__c = 'Pending';
        
        insert commDetail3;
        
        commDetail3.Approval_Status__c = 'Approved';
        update commDetail3;
        
        topp1.CAF_YSP__c = '-5 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail4 = new Commission_Detail__c();
        commDetail4.Deal__c = topp1.Id;
        commDetail4.Commission_Type__c = 'Internal';
        commDetail4.OwnerId = origU.Id;
        commDetail4.Internal_Referral__c=origU2.Id;
        commDetail4.Internal_Referral_Fee__c = '50%';
        commDetail4.Approval_Status__c = 'Pending';
        
        insert commDetail4;
        
        commDetail4.Approval_Status__c = 'Approved';
        update commDetail4;
        
        
        topp1.CAF_YSP__c = '+10 BPS in Spread / +25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail5 = new Commission_Detail__c();
        commDetail5.Deal__c = topp1.Id;
        commDetail5.Commission_Type__c = 'Internal';
        commDetail5.OwnerId = origU.Id;
                commDetail5.Internal_Referral__c=origU2.Id;
        commDetail5.Internal_Referral_Fee__c = '50%';
        commDetail5.Approval_Status__c = 'Pending';
        
        insert commDetail5;
        
        commDetail5.Approval_Status__c = 'Approved';
        update commDetail5;
        
        
        topp1.CAF_YSP__c = '-10 BPS in Spread / -25 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail6 = new Commission_Detail__c();
        commDetail6.Deal__c = topp1.Id;
        commDetail6.Commission_Type__c = 'Internal';
        commDetail6.OwnerId = origU.Id;
        commDetail6.Internal_Referral__c=origU2.Id;
        commDetail6.Internal_Referral_Fee__c = '50%';
        commDetail6.Approval_Status__c = 'Pending';
        
        insert commDetail6;
        
        commDetail6.Approval_Status__c = 'Approved';
        update commDetail6;
        
        
        topp1.CAF_YSP__c = '+10 BPS in spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail7 = new Commission_Detail__c();
        commDetail7.Deal__c = topp1.Id;
        commDetail7.Commission_Type__c = 'Internal';
        commDetail7.OwnerId = origU.Id;
               commDetail7.Internal_Referral__c=origU2.Id;
        commDetail7.Internal_Referral_Fee__c = '50%';
        commDetail7.Approval_Status__c = 'Pending';
        
        insert commDetail7;
        
                commDetail7.Approval_Status__c = 'Approved';
        update commDetail7;

        
        topp1.CAF_YSP__c = '-10 BPS in spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail8 = new Commission_Detail__c();
        commDetail8.Deal__c = topp1.Id;
        commDetail8.Commission_Type__c = 'Internal';
        commDetail8.OwnerId = origU.Id;
        commDetail8.Internal_Referral__c=origU2.Id;
        commDetail8.Internal_Referral_Fee__c = '50%';
        commDetail8.Approval_Status__c = 'Pending';
        
        insert commDetail8;
                commDetail8.Approval_Status__c = 'Approved';
        update commDetail8;

        
        topp1.CAF_YSP__c = '+15 BPS in Spread / +50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail9 = new Commission_Detail__c();
        commDetail9.Deal__c = topp1.Id;
        commDetail9.Commission_Type__c = 'Internal';
        commDetail9.OwnerId = origU.Id;
        commDetail9.Internal_Referral__c=origU2.Id;
        commDetail9.Internal_Referral_Fee__c = '50%';
        commDetail9.Approval_Status__c = 'Pending';
        
        insert commDetail9;
        
                commDetail9.Approval_Status__c = 'Approved';
        update commDetail9;

        
        topp1.CAF_YSP__c = '-15 BPS in Spread / -50 BPS in Commissionable Fee';
        update topp1;
        
        
        Commission_Detail__c commDetail10 = new Commission_Detail__c();
        commDetail10.Deal__c = topp1.Id;
        commDetail10.Commission_Type__c = 'Internal';
        commDetail10.OwnerId = origU.Id;
               commDetail10.Internal_Referral__c=origU2.Id;
        commDetail10.Internal_Referral_Fee__c = '50%';
        commDetail10.Approval_Status__c = 'Pending';
        
        insert commDetail10;
        
        commDetail10.Approval_Status__c = 'Approved';
        update commDetail10;
        Test.stopTest();
        
    }
    
    //Bridge Section
    @isTest static void termCommissiontestBridge2() {
        commissionAutomationSetting__c  settings = new commissionAutomationSetting__c (SetupOwnerId=UserInfo.getOrganizationId(), SkipProcessBuilder__c= true);
        insert settings;
        CommissionDetail_TestSkip.setDoNotRunTrigger();
        
        //Total Borrowed on term (account) under 5 million no split;Final Loan Amount under 5 million
        User origU = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator@teada.com'
        );
        
        insert origU;
        
        User origU2 = new User(
            Alias = 'orig',
            Email = 'standarduser@cvest.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Relationship Manager']
            .Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'originator2@teada.com'
        );
        insert origU2;
        
        Account acc = test_Helper.createAccount();
        acc.Alternate_Phone__c = '7777777777';
        update acc;
        Contact cont = test_Helper.createContact(acc);
        cont.MobilePhone = '2222222222';
        cont.Phone = '9999999999';
        
        Opportunity topp1 = new Opportunity();
        topp1.Name = 'test';
        topp1.CloseDate = System.today();
        topp1.StageName = 'Initial Review';
        topp1.Loan_Size__c = 2000000;
        topp1.AccountId = acc.Id;
        topp1.Contact__c = cont.Id;
        topp1.OwnerId = origU.id;
        topp1.CAF_YSP__c= null;
        topp1.CAF_Upfront_Fee__c = 2;
        topp1.Final_Loan_Amount__c = 1000000;
        topp1.Deal_Intro_Source__c = 'Hotline';
        topp1.Deal_Intro_Sub_Source__c = 'Main';
        topp1.Apex_Context__c = true;
        topp1.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
        ]
            .Id;
        insert topp1;
        
        
        Commission__c comm = new Commission__c();
        
        comm.Owner__c = origU.id;
        comm.Deal__c = topp1.Id;
        
        insert comm;
        
        Commission_Detail__c commDetail1 = new Commission_Detail__c();
        commDetail1.Deal__c = topp1.Id;
        commDetail1.Commission_Type__c = 'Internal';
        commDetail1.OwnerId = origU.Id;
        commDetail1.Internal_Referral__c = origU.Id;
        commDetail1.Internal_Referral_Fee__c = '50%';
        commDetail1.Approval_Status__c = 'Pending';
        
        test.startTest();
        
        insert commDetail1;
        
        commDetail1.Approval_Status__c = 'Approved';
        
        Commission__c comm2 = new Commission__c();
        
        comm2.Owner__c = origU.id;
        comm2.Deal__c = topp1.Id;
        insert comm2;
        
        update commDetail1;
        
        test.stopTest();
        
    } 
    

}