force-app/main/default/objects/Account/fields/Do_Not_Lend__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Lend__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if this Account has been identified as a Borrower we do not want to lend to.  The Notes tab may have details regarding the reason.</inlineHelpText>
    <label>Do Not Lend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/In_Foreclosure__c.field-meta.xml
<CustomField>
    <fullName>In_Foreclosure__c</fullName>
    <businessOwnerGroup>Asset_Management</businessOwnerGroup>
    <defaultValue>false</defaultValue>
    <description>Asset Management will check this box to indicate the Account is in foreclosure. Show Rich Text Banner for All Account, Deal, and Properties.</description>
    <inlineHelpText>This Account is in Foreclosure – Please refer to Asset Management</inlineHelpText>
    <label>In Foreclosure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flagging an account as in litigation</description>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introductions_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Introductions_Source__c.field-meta.xml
<CustomField>
    <fullName>Introductions_Source__c</fullName>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_Not_Lend__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Lend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Lend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contact is associated to a litigation case</description>
    <inlineHelpText>Please make sure the &quot;In Litigation&quot; field on related contacts are unchecked.</inlineHelpText>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>Adam Luray Sourced</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Sarhad Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Charlie Flynn Sourced</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_UPB__c.field-meta.xml
<CustomField>
    <fullName>Current_UPB__c</fullName>
    <description>Data comes from Servicer</description>
    <label>Current UPB</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Spread__c.field-meta.xml
<CustomField>
    <fullName>Final_Spread__c</fullName>
    <description>Term Use</description>
    <label>Final Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Swap__c.field-meta.xml
<CustomField>
    <fullName>Final_Swap__c</fullName>
    <description>Term Use</description>
    <label>Final Swap</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/In_Foreclosure__c.field-meta.xml
<CustomField>
    <fullName>In_Foreclosure__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Asset Management will check this box to indicate the Deal is in foreclosure. Show Rich Text Banner for All Account, Deal, and Properties.</description>
    <inlineHelpText>This Deal is in Foreclosure – Please refer to Asset Management</inlineHelpText>
    <label>In Foreclosure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Term_Loan_Type__c</fullName>
    <label>Term Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 Year</fullName>
            </value>
            <value>
                <fullName>5 Year</fullName>
            </value>
            <value>
                <fullName>7 Year</fullName>
            </value>
            <value>
                <fullName>10 Year</fullName>
            </value>
            <value>
                <fullName>30 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/OpenPeriodTaskEmailScheduleTest.cls
@isTest
private class OpenPeriodTaskEmailScheduleTest {
  @isTest
  static void OpenPeriodTaskEmailScheduleTestMethod() {
    test_Helper.createDealLoanNumber();
    Profile profileDetail = [
      SELECT Id
      FROM Profile
      WHERE Name = 'Standard User'
    ];
    String orgId = UserInfo.getOrganizationId();
    String dateString = String.valueof(Datetime.now())
      .replace(' ', '')
      .replace(':', '')
      .replace('-', '');
    Integer RandomId = Integer.valueOf(Math.rint(Math.random() * 1000000));
    String uniqueName = orgId + dateString + RandomId;
    String uniqueName1 = orgId + dateString + RandomId + '1';
    String uniqueName2 = orgId + dateString + RandomId + '2';

    User oneUser = new User(
      Alias = 'standt',
      Email = 'standarduser@testorg.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = profileDetail.Id,
      IsActive = true,
      TimeZoneSidKey = 'America/New_York',
      UserName = uniqueName + '@test' + orgId + '.org'
    );
    insert oneUser;

    User twoUser = new User(
      Alias = 'standt',
      Email = 'standarduser1@testorg.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = profileDetail.Id,
      IsActive = false,
      TimeZoneSidKey = 'America/New_York',
      UserName = uniqueName1 + '@test' + orgId + '.org'
    );
    insert twoUser;

    User threeUser = new User(
      Alias = 'standt',
      Email = 'standarduser2@testorg.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing2',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = profileDetail.Id,
      IsActive = true,
      TimeZoneSidKey = 'America/New_York',
      UserName = uniqueName2 + '@test' + orgId + '.org'
    );
    insert threeUser;
    Account a = new Account();
    a.Name = 'Alston & Bird';
    a.BillingCountry = 'United States';
    a.BillingState = 'California';
    a.Introductions_Source__c = 'Hotline';
    a.Introduction_Subsource__c = 'Main';
    a.Alternate_Phone__c = '55555555355';
    a.OwnerId = oneUser.id;
    a.In_Litigation__c = false;
    a.Do_Not_Lend__c = false;
    a.In_Foreclosure__c = false;

    insert a;

    Contact cont = test_Helper.createContact(a);

    Opportunity opp = new Opportunity();
    opp.Name = 'test';
    opp.OwnerId = oneUser.id;
    opp.Current_UPB__c = 100;
    opp.CloseDate = System.today();
    opp.Final_Spread__c = 2;
    opp.Final_Swap__c = 2;
    opp.StageName = 'Closed Won';
    opp.Type = 'Term Loan';
    opp.Loan_Size__c = 2000000;
    opp.AccountId = a.Id;
    opp.Contact__c = cont.Id;
    opp.Term_Loan_Type__c = '5 Year';
    opp.Final_Loan_Amount__c = 100;
    opp.Deal_Intro_Source__c = 'Hotline';
    opp.Deal_Intro_Sub_Source__c = 'Main';
    opp.Apex_Context__c = true;
    //opp.Loan_in_Default__c = false;

    // opp.Updated_Loan_Maturity_Date__c = System.today().addMonths(9);
    opp.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
    ]
    .Id;
    opp.GLC_Approved__c = false;
    opp.Background_Check_Completed__c = false;
    opp.Term_Loan_Type__c = '5 Year';
    opp.YM_Prepayment_Penalty__c = '34 Months';
    opp.First_Payment_Date__c = System.today().addmonths(-22);

    insert opp;
    opportunity myOpp = [
      SELECT Open_Period_Begins__c
      FROM Opportunity
      WHERE ID = :opp.ID
    ];
    system.debug('date?' + myOpp.Open_Period_Begins__c);
    Opportunity opp2 = new Opportunity();
    opp2.Name = 'test';
    opp2.OwnerId = twoUser.id;
    opp2.Current_UPB__c = 100;
    opp2.CloseDate = System.today();
    opp2.Final_Spread__c = 2;
    opp2.Final_Swap__c = 2;
    opp2.StageName = 'Closed Won';
    opp2.Type = 'Term Loan';
    opp2.Term_Loan_Type__c = '5 Year';

    opp2.Loan_Size__c = 2000000;
    opp2.AccountId = a.Id;
    opp2.Contact__c = cont.Id;
    opp2.Final_Loan_Amount__c = 100;
    opp2.Deal_Intro_Source__c = 'Hotline';
    opp2.Deal_Intro_Sub_Source__c = 'Main';
    opp2.Apex_Context__c = true;

    //opp.Loan_in_Default__c = false;

    // opp2.Updated_Loan_Maturity_Date__c = System.today().addMonths(12);
    opp2.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
    ]
    .Id;
    opp2.GLC_Approved__c = false;
    opp2.Background_Check_Completed__c = false;
    opp2.Term_Loan_Type__c = '5 Year';
    opp2.YM_Prepayment_Penalty__c = '34 Months';
    opp2.First_Payment_Date__c = System.today().addmonths(-25);

    insert opp2;

    opportunity myOpp2 = [
      SELECT Open_Period_Begins__c
      FROM Opportunity
      WHERE ID = :opp2.ID
    ];
    system.debug('date2?' + myOpp2.Open_Period_Begins__c);

    test.startTest();
    OpenPeriodTaskEmailScheduled myClass = new OpenPeriodTaskEmailScheduled();
    String chron = '0 0 21 * * ?';
    system.schedule('Test Sched', chron, myClass);
    System.debug(myClass);
    test.stopTest();
  }
}