force-app/main/default/objects/Account/fields/Do_Not_Lend__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Lend__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if this Account has been identified as a Borrower we do not want to lend to.  The Notes tab may have details regarding the reason.</inlineHelpText>
    <label>Do Not Lend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flagging an account as in litigation</description>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contacts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Contacts that belong to this Account</description>
    <inlineHelpText>Number of Contacts that belong to this Account</inlineHelpText>
    <label># of Contacts</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_Not_Lend__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Lend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Lend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contact is associated to a litigation case</description>
    <inlineHelpText>Please make sure the &quot;In Litigation&quot; field on related contacts are unchecked.</inlineHelpText>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Leads.recordType-meta.xml
<RecordType>
    <fullName>Leads</fullName>
    <active>true</active>
    <businessProcess>Leads</businessProcess>
    <description>CAF Leads</description>
    <label>Leads</label>
</RecordType>

force-app/main/default/classes/contact_Helper.cls
public class contact_Helper {
  public static Map<String, Schema.SObjectField> FIELD_MAP = Schema.SObjectType.Contact.fields.getMap();

  /**
   * @name beforeInsert
   * @description
   * @param
   **/
    public static void beforeInsert(List<Contact> newList) {
        for (Integer i = 0; i < newList.size(); i++) {
            if (String.isNotBlank(newList[i].Phone)) {
                newList[i].Phone = util.formatPhone(newList[i].Phone);
            }

            if (String.isNotBlank(newList[i].MobilePhone)) {
                newList[i].MobilePhone = util.formatPhone(newList[i].MobilePhone);
            }
        }
    }

  /**
   * @name afterInsert
   * @description
   * @param
   **/
  //public static void afterInsert(List<Contact> newList){
  //    for ( Integer i=0;i<newList.size();i++ ){

  //    }
  //}

  /**
   * @name beforeUpdate
   * @description
   * @param
   **/
    public static void beforeUpdate(
        List<Contact> newList,
        List<Contact> oldList
        ) {
        for (Integer i = 0; i < newList.size(); i++) {
            if (newList[i].Phone != oldList[i].Phone) {
                if (String.isNotBlank(newList[i].Phone)) {
                  newList[i].Phone = util.formatPhone(newList[i].Phone);
                }
            }

            if (newList[i].MobilePhone != oldList[i].MobilePhone) {
                if (String.isNotBlank(newList[i].MobilePhone)) {
                  newList[i].MobilePhone = util.formatPhone(newList[i].MobilePhone);
                }
            }
        }
    }

    public static void afterUpdate(List<Contact> newList){
    //Related account list
        list<id> myAcc = new list<id>();
        for(Contact con : newList){
            if (con.In_Litigation__c == true){
                myAcc.add(con.AccountId);
            }
        }
        if(myAcc.size()>0){
            list<account> myAccs = new list<account>();
            list<account> accToUpdate = [SELECT Do_Not_Lend__c from Account where ID in :myAcc];
            for(account acc : accToUpdate){
                acc.In_Litigation__c = true;
            }
            if(accToUpdate.size()>0){
                update accToUpdate;
            }
        }
    }


    public static void isAfter(set<Id> parentIdsSet) {
        List<Account> accountListToUpdate = new List<Account>();
        List<Account> accountList = new List<Account>(
            [
                SELECT id, Name, Number_of_Contacts__c, (SELECT id, Name FROM Contacts)
                FROM Account
                WHERE id IN :parentIdsSet
            ]
        );
        for (Account acc : accountList) {
            List<Contact> contactList = acc.Contacts;
            acc.Number_of_Contacts__c = acc.Contacts.size();
            accountListToUpdate.add(acc);
        }
        system.debug('accountListToUpdate:::' + accountListToUpdate);
        try {
            if (accountListToUpdate != null && accountListToUpdate.size() > 0) {
                update accountListToUpdate;
            }
        } catch (System.Exception e) {
            system.debug('Exception::::::' + e.getLineNumber());
        }
    }

  /**
   * @name afterUpdate
   * @description
   * @param
   **/
  //public static void afterUpdate(List<Contact> newList, List<Contact> oldList){

  //   Map<Id, Id> contactOwnerMap = new Map<Id, Id>();

  //   for ( Integer i=0;i<newList.size();i++ ){

  //       if(newList[i].OwnerId != oldList[i].OwnerId){
  //           contactOwnerMap.put(newList[i].Id, newList[i].OwnerId);
  //       }
  //   }
  //   if(contactOwnerMap.values().size() > 0){
  //       updateLeadOwners(contactOwnerMap);
  //   }
  //}

  /**
   * @name beforeDelete
   * @description
   * @param
   **/
  //public static void beforeDelete(List<Contact> newList){
  //    for ( Integer i=0;i<newList.size();i++ ){

  //    }
  //}

  /**
   * @name afterDelete
   * @description
   * @param
   **/
  //public static void afterDelete(List<Contact> newList, List<Contact> oldList){
  //}

  /**
   * @name afterUndelete
   * @description
   * @param
   **/
  //public static void afterUndelete(List<Contact> oldList){
  //    for ( Integer i=0;i<oldList.size();i++ ){

  //    }
  //}

  //public static void updateLeadOwners(Map<Id, Id> contactOwnerMap){
  //    List<Lead> leads = new List<Lead>();
  //    for(Lead l : [SELECT Id, ConvertedContactId, OwnerId FROM Lead where ConvertedContactId IN : contactOwnerMap.keySet()]){
  //        l.ownerId = contactOwnerMap.get(l.ConvertedContactId);
  //       leads.add(l);
  //   }

  //   upsert leads;
  //}
}