force-app/main/default/objects/Account/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flagging an account as in litigation</description>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Requested_Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Requested_Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contact is associated to a litigation case</description>
    <inlineHelpText>Please make sure the &quot;In Litigation&quot; field on related contacts are unchecked.</inlineHelpText>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Introduction_Source__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Source__c</fullName>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Introduction_Source__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Source__c</fullName>
    <inlineHelpText>If the introduction source is Website Chat Bot, please review the past activities to view the conversation in Drift.</inlineHelpText>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/contact_Tests.cls
@isTest
private class contact_Tests {

    //static List<Account> testAccounts = testDataFactory.createTestRecords(new Account[10]);

    static TestMethod void contact_Tests_UnitTest(){
        List<User> users = [SELECT Id FROM User];
        Lead l = new Lead(FirstName='Test', LastName='Tester',
            Requested_Loan_Size__c=500, Company='Tester', Introduction_Source__c = 'CAF Website', Email='none@gmail.com');

        insert l;

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(l.id);

        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        lc.setDoNotCreateOpportunity(true);
        Database.LeadConvertResult lcr = Database.convertLead(lc);

        Lead convertedLead = [SELECT Id, ConvertedContactId FROM Lead WHERE Id = : l.Id];
        Contact c = [SELECT Id, OwnerId FROM Contact WHERE Id = : convertedLead.ConvertedContactId];

        Test.startTest();
            if(c.OwnerId != users[0].Id){
                c.OwnerId = users[0].Id;
            }else{
                c.OwnerId = users[1].Id;
            }

            update c;
        Test.stopTest();

       // Lead updatedLead = [SELECT Id, OwnerId FROM Lead WHERE Id = : l.Id];
        //system.assertEquals(c.OwnerId, updatedLead.OwnerId);
    }
    
    static TestMethod void contact_Tests_UnitTest2(){
        account acc = new account();
        acc.name = 'test123';
        acc.Site = 'California';
        insert acc;
        contact con = new contact();
        con.FirstName = 'testfirst';
        con.LastName = 'testlast';
        con.AccountId = acc.id;
        insert con;
        con.In_Litigation__c = true;
        update con;
        account acc2 = new account();
        acc2.name = 'test456';
        acc2.Site = 'California';
        insert acc2;
        con.AccountId = acc2.Id;
        update con;
        delete con;
    }
       
          
}