force-app/main/default/objects/Account/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flagging an account as in litigation</description>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/In_Litigation__c.field-meta.xml
<CustomField>
    <fullName>In_Litigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contact is associated to a litigation case</description>
    <inlineHelpText>Please make sure the &quot;In Litigation&quot; field on related contacts are unchecked.</inlineHelpText>
    <label>In Litigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Closing_Date__c</fullName>
    <defaultValue>TODAY()+75</defaultValue>
    <label>Anticipated Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Single_Asset_Bridge_Loan.recordType-meta.xml
<RecordType>
    <fullName>Single_Asset_Bridge_Loan</fullName>
    <active>true</active>
    <businessProcess>SAB Process</businessProcess>
    <label>Single Asset Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/UpdateCloseDateBatch.cls
global class UpdateCloseDateBatch implements Database.Batchable<sObject>{
    String queryString;
    String recordType;
    Map<String, Integer> termDaysMap = new Map<String, Integer>{
        'Initial Review' => 100,
        'Data Tape Received' => 80,
        'Term Sheet Issued' => 65,
        'Term Sheet Signed/Deposit Collected' => 60
    };

    Map<String, Integer> bridgeDaysMap = new Map<String, Integer>{
        'Initial Review' => 65,
        'Term Sheet Issued' => 40,
        'Term Sheet Signed/Deposit Collected' => 30
    }; 

    Map<String, Integer> sabDaysMap = new Map<String, Integer>{
        'Initial Review' => 12
    };

    Map<String, Integer> selectedDaysMap;

    public UpdateCloseDateBatch(String recordType) {
        String queryString = 'SELECT Id, CloseDate, Anticipated_Closing_Date__c, StageName FROM Opportunity WHERE';
        this.recordType = recordType;
        if(recordType == 'Term'){
            this.selectedDaysMap = termDaysMap;
            queryString += ' RecordType.DeveloperName = \'Term_Loan\'';
        }else if(recordType == 'Bridge'){
            this.selectedDaysMap = bridgeDaysMap;
            queryString += ' RecordType.DeveloperName = \'LOC_Loan\'';
        }else if(recordType == 'Single Asset Bridge'){
            this.selectedDaysMap = sabDaysMap;
            queryString += ' RecordType.DeveloperName = \'Single_Asset_Bridge_Loan\'';
        }

        //queryString += ' AND StageName IN : selectedDaysMap.keySet()';
        queryString += ' AND StageName IN (';
        for(String stageName : selectedDaysMap.keySet()){
            queryString += '\'' + stageName + '\','; 
        }

        queryString = queryString.substringBeforeLast(',');
        queryString += ') ORDER BY CloseDate ASC';
        //queryString += ' FOR UPDATE ';
        // queryString += ' AND In_Litigation__c = false';
        // queryString += ' AND Account.In_Litigation__c = false';
        // queryString += ' AND Contact__r.In_Litigation__c = false';
        this.queryString = queryString;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug(queryString);
        return Database.getQueryLocator(this.queryString);

    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        // List<Opportunity> oppsToUpdate = new List<Opportunity>
        for(Opportunity deal : (List<Opportunity>)scope){
            deal.CloseDate = system.today().addDays(selectedDaysMap.get(deal.StageName));
            deal.Anticipated_Closing_Date__c = system.today().addDays(selectedDaysMap.get(deal.StageName));
        }
        // system.debug(scope);
        // system.debug(scope.size());
        update scope;
    }

    global void finish(Database.BatchableContext BC){
        if(this.recordType == 'Term'){
            Database.executeBatch(new UpdateCloseDateBatch('Bridge'), 10);
        }else if(this.recordType == 'Bridge'){
            Database.executeBatch(new UpdateCloseDateBatch('Single Asset Bridge'), 10);
        }
    }

}