force-app/main/default/objects/Account/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introductions_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Introductions_Source__c.field-meta.xml
<CustomField>
    <fullName>Introductions_Source__c</fullName>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clear_Result__c/Clear_Result__c.object-meta.xml
<CustomObject>
    <label>Clear Result</label>
    <nameField>
        <label>Clear Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clear Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clear_Result__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clear Results</relationshipLabel>
    <relationshipName>Clear_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>Adam Luray Sourced</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Sarhad Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Charlie Flynn Sourced</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorCity__c.field-meta.xml
<CustomField>
    <fullName>SponsorCity__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor City</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorHomeAddress__c.field-meta.xml
<CustomField>
    <fullName>SponsorHomeAddress__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor Home Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorState__c.field-meta.xml
<CustomField>
    <fullName>SponsorState__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor State</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorZipCode__c.field-meta.xml
<CustomField>
    <fullName>SponsorZipCode__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor Zip Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact this Document is related to</description>
    <inlineHelpText>Contact this Document is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/ClearBaseTest.cls
@isTest
private  class ClearBaseTest {
    @isTest static void testMethod1() {
        test_Helper.createDealLoanNumber();

        Account a = new Account();
        a.Name = 'test';
        a.BillingCountry = 'United States';
        a.BillingState = 'California';
        a.Introductions_Source__c = 'Hotline';
        a.Introduction_Subsource__c = 'Main';
        a.Alternate_Phone__c = '5555555555';
        insert a;
        
        Contact c = new Contact();
        c.FirstName = 'Daniel';
        c.LastName = 'Galli';
        c.MailingCountry = 'United States';
        c.MailingState = 'California';
        c.AccountId = a.Id;
        c.MobilePhone = '5555555555';
        c.Phone = '7777777777';
        c.SponsorHomeAddress__c = '1024 Washington Ave';
        c.SponsorState__c = 'Maine';
        c.SponsorCity__c = 'Portland';
        c.SponsorZipCode__c = '04103-2779';
        insert c;
        
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.CloseDate = System.today();
        o.StageName = 'Initial Review';
        o.Loan_Size__c = 2000000;
        o.AccountId = a.Id;
        o.Contact__c = c.Id;
        o.Deal_Intro_Source__c = 'Hotline';
        o.Deal_Intro_Sub_Source__c = 'Main';
        o.Apex_Context__c = true;
        o.RecordTypeId = [
          SELECT Id
          FROM RecordType
          WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
        .Id;
        insert o;
        
        Deal_Contact__c dealContact = new Deal_Contact__c();
        dealContact.Deal__c = o.id;
        dealContact.Contact__c = c.id;
        insert dealContact;
        
        Clear_Result__c cr = new Clear_Result__c();
        cr.akaFirstName__c = 'DANIEL';
        cr.akaLastName__c = 'GALLI';
        cr.EntityId__c = 'P1__NDExNjYyNTQ4';
        cr.Contact__c = c.id;
        cr.Group_ID_for_Person_Search__c = '01852a301b8a47428b36ad4979d6e921';
        cr.Group_ID_for_Risk_search__c = '9dda314682dd43a5a682b6d45bcf247c';
        insert cr;
        
        ClearBase.getContactDetailforPersonSearch(c.id,false,false,false,false,false);
        ClearBase.getContactDetailforRiskSearch(dealContact.id);
        ClearBase.GetReport(dealContact.id,'PersonSearchReport',o.id);
    }
    
    @isTest static void testMethod2() {
      test_Helper.createDealLoanNumber();

        Account a = new Account();
        a.Name = 'test';
        a.BillingCountry = 'United States';
        a.BillingState = 'California';
        a.Introductions_Source__c = 'Hotline';
        a.Introduction_Subsource__c = 'Main';
        a.Alternate_Phone__c = '5555555555';
        insert a;
        
        Contact c = new Contact();
        c.FirstName = 'Daniel';
        c.LastName = 'Galli';
        c.MailingCountry = 'United States';
        c.MailingState = 'California';
        c.AccountId = a.Id;
        c.MobilePhone = '5555555555';
        c.Phone = '7777777777';
        c.SponsorHomeAddress__c = '1024 Washington Ave';
        c.SponsorState__c = 'Maine';
        c.SponsorCity__c = 'Portland';
        c.SponsorZipCode__c = '04103-2779';
        insert c;
        
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.CloseDate = System.today();
        o.StageName = 'Initial Review';
        o.Loan_Size__c = 2000000;
        o.AccountId = a.Id;
        o.Contact__c = c.Id;
        o.Deal_Intro_Source__c = 'Hotline';
        o.Deal_Intro_Sub_Source__c = 'Main';
        o.Apex_Context__c = true;
        o.RecordTypeId = [
          SELECT Id
          FROM RecordType
          WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
        .Id;
        insert o;
        
        Deal_Contact__c dealContact = new Deal_Contact__c();
        dealContact.Deal__c = o.id;
        dealContact.Contact__c = c.id;
        insert dealContact;
        
        Clear_Result__c cr = new Clear_Result__c();
        cr.akaFirstName__c = 'DANIEL';
        cr.akaLastName__c = 'GALLI';
        cr.EntityId__c = 'P1__NDExNjYyNTQ4';
        cr.Contact__c = c.id;
        cr.Group_ID_for_Person_Search__c = '01852a301b8a47428b36ad4979d6e921';
        cr.Group_ID_for_Risk_search__c = '9dda314682dd43a5a682b6d45bcf247c';
        insert cr;
        
        list<string> conIdList = new list<string>();
        conIdList.add(c.id);
        
        ClearBase.getEntityId(conIdList);
        ClearBase.getContactDetailforRiskSearch(dealContact.id);
        ClearBase.riskReport(c.id);
    }
    
    @isTest static void testMethod3() {
      test_Helper.createDealLoanNumber();
  
        Account a = new Account();
        a.Name = 'test';
        a.BillingCountry = 'United States';
        a.BillingState = 'California';
        a.Introductions_Source__c = 'Hotline';
        a.Introduction_Subsource__c = 'Main';
        a.Alternate_Phone__c = '5555555555';
        insert a;
        
        Contact c = new Contact();
        c.FirstName = 'Daniel';
        c.LastName = 'Galli';
        c.MailingCountry = 'United States';
        c.MailingState = 'California';
        c.AccountId = a.Id;
        c.MobilePhone = '5555555555';
        c.Phone = '7777777777';
        c.SponsorHomeAddress__c = '1024 Washington Ave';
        c.SponsorState__c = 'Maine';
        c.SponsorCity__c = 'Portland';
        c.SponsorZipCode__c = '04103-2779';
        insert c;
        
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.CloseDate = System.today();
        o.StageName = 'Initial Review';
        o.Loan_Size__c = 2000000;
        o.AccountId = a.Id;
        o.Contact__c = c.Id;
        o.Deal_Intro_Source__c = 'Hotline';
        o.Deal_Intro_Sub_Source__c = 'Main';
        o.Apex_Context__c = true;
        o.RecordTypeId = [
          SELECT Id
          FROM RecordType
          WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
        .Id;
        insert o;
        
        Deal_Contact__c dealContact = new Deal_Contact__c();
        dealContact.Deal__c = o.id;
        dealContact.Contact__c = c.id;
        insert dealContact;
        
        Clear_Result__c cr = new Clear_Result__c();
        cr.akaFirstName__c = 'DANIEL';
        cr.akaLastName__c = 'GALLI';
        cr.EntityId__c = 'P1__NDExNjYyNTQ4';
        cr.Contact__c = c.id;
        cr.Group_ID_for_Person_Search__c = '01852a301b8a47428b36ad4979d6e921';
        cr.Group_ID_for_Risk_search__c = '9dda314682dd43a5a682b6d45bcf247c';
        insert cr;
        
        list<string> conIdList = new list<string>();
        conIdList.add(c.id);
        
        ClearBase.GetReport(dealContact.id,'RiskSearchReport',o.id);
    }
    
    @isTest static void testMethod4() {
      test_Helper.createDealLoanNumber();
   
        Account a = new Account();
        a.Name = 'test';
        a.BillingCountry = 'United States';
        a.BillingState = 'California';
        a.Introductions_Source__c = 'Hotline';
        a.Introduction_Subsource__c = 'Main';
        a.Alternate_Phone__c = '5555555555';
        insert a;
        
        Contact c = new Contact();
        c.FirstName = 'Daniel';
        c.LastName = 'Galli';
        c.MailingCountry = 'United States';
        c.MailingState = 'California';
        c.AccountId = a.Id;
        c.MobilePhone = '5555555555';
        c.Phone = '7777777777';
        c.SponsorHomeAddress__c = '1024 Washington Ave';
        c.SponsorState__c = 'Maine';
        c.SponsorCity__c = 'Portland';
        c.SponsorZipCode__c = '04103-2779';
        insert c;
        
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.CloseDate = System.today();
        o.StageName = 'Initial Review';
        o.Loan_Size__c = 2000000;
        o.AccountId = a.Id;
        o.Contact__c = c.Id;
        o.Deal_Intro_Source__c = 'Hotline';
        o.Deal_Intro_Sub_Source__c = 'Main';
        o.Apex_Context__c = true;
        o.RecordTypeId = [
          SELECT Id
          FROM RecordType
          WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
        ]
        .Id;
        insert o;
        
        Deal_Contact__c dealContact = new Deal_Contact__c();
        dealContact.Deal__c = o.id;
        dealContact.Contact__c = c.id;
        insert dealContact;
        
        Clear_Result__c cr = new Clear_Result__c();
        cr.akaFirstName__c = 'DANIEL';
        cr.akaLastName__c = 'GALLI';
        cr.EntityId__c = 'P1__NDExNjYyNTQ4';
        cr.Contact__c = c.id;
        cr.Group_ID_for_Person_Search__c = '01852a301b8a47428b36ad4979d6e921';
        cr.Group_ID_for_Risk_search__c = '9dda314682dd43a5a682b6d45bcf247c';
        insert cr;
        
        Deal_Document__c dealDoc = new Deal_Document__c();
        dealDoc.Contact__c = c.id;
        dealDoc.Clear_Result_Report_Type__c = 'PersonSearchReport';
        insert dealDoc;
        
        ClearBase.GetReport(dealContact.id,'PersonSearchReport',o.id);
        
    }
}