force-app/main/default/objects/Account/fields/Introductions_Source__c.field-meta.xml
<CustomField>
    <fullName>Introductions_Source__c</fullName>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <description>DocuSign multi-select checkboxes converted to a multi-select picklist. 
Loan Purpose field located in Bridge Loan form within the Loan Request section.</description>
    <label>Loan Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refinance Debt</fullName>
            </value>
            <value>
                <fullName>Refinance Equity (Cash-out)</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amortization_Term__c.field-meta.xml
<CustomField>
    <fullName>Amortization_Term__c</fullName>
    <description>Term Use</description>
    <label>Amortization Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 months</fullName>
                <default>true</default>
                <label>0 months</label>
            </value>
            <value>
                <fullName>120 months</fullName>
            </value>
            <value>
                <fullName>180 months</fullName>
            </value>
            <value>
                <fullName>240 months</fullName>
            </value>
            <value>
                <fullName>300 months</fullName>
            </value>
            <value>
                <fullName>360 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Closing_Date__c</fullName>
    <defaultValue>TODAY()+75</defaultValue>
    <label>Anticipated Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Are_Assets_Being_RFNC_From_Existing_Term__c.field-meta.xml
<CustomField>
    <fullName>Are_Assets_Being_RFNC_From_Existing_Term__c</fullName>
    <description>Indicates if Assets/Properties on this Term Loan are being refinanced from another Term Loan</description>
    <inlineHelpText>Indicate if Assets/Properties on this Term Loan are being refinanced from another Term Loan</inlineHelpText>
    <label>Are Assets Being RFNC From Existing Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Borrower__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cash_Management__c.field-meta.xml
<CustomField>
    <fullName>Cash_Management__c</fullName>
    <label>Cash Management</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Closer on this Deal</description>
    <label>Closer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Closer</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Closer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Closer)</relationshipLabel>
    <relationshipName>Deals2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Loan_Amount__c</fullName>
    <label>Current Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>This will replace the manual auto assignment</description>
    <displayFormat>{00000}</displayFormat>
    <label>Deal Loan Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Spread__c.field-meta.xml
<CustomField>
    <fullName>Final_Spread__c</fullName>
    <description>Term Use</description>
    <label>Final Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Loan Coordinator</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Loan Coordinator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Loan Coordinator)</relationshipLabel>
    <relationshipName>Deals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
                <default>true</default>
                <label>Purchase</label>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Refinance/Purchase</fullName>
            </value>
            <value>
                <fullName>Cash Out Refi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LTV__c.field-meta.xml
<CustomField>
    <fullName>LTV__c</fullName>
    <description>Term and Bridge use</description>
    <inlineHelpText>Initial LTV % in Bridge</inlineHelpText>
    <label>Max LTV %</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Recourse__c.field-meta.xml
<CustomField>
    <fullName>Recourse__c</fullName>
    <label>Recourse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Recourse</fullName>
            </value>
            <value>
                <fullName>Non-Recourse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spread_BPS__c.field-meta.xml
<CustomField>
    <fullName>Spread_BPS__c</fullName>
    <label>Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State_Percentages__c.field-meta.xml
<CustomField>
    <fullName>State_Percentages__c</fullName>
    <description>Percentage of Properties by State</description>
    <inlineHelpText>Percentage of Properties by State</inlineHelpText>
    <label>State Percentages</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Term_Loan_Type__c</fullName>
    <label>Term Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 Year</fullName>
            </value>
            <value>
                <fullName>5 Year</fullName>
            </value>
            <value>
                <fullName>7 Year</fullName>
            </value>
            <value>
                <fullName>10 Year</fullName>
            </value>
            <value>
                <fullName>30 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Third_Party_Title__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Title__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Updated via Apex - When an &quot;3rd Party Title&quot; Deal Contact is created, the Account is populated
Term Use</description>
    <inlineHelpText>3rd Party Title from the Vendor Entities Section</inlineHelpText>
    <label>3rd Party Title</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals (3rd Party Title)</relationshipLabel>
    <relationshipName>Deals_as_3rd_Party_Title</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Updated via Apex - When an &quot;Title and Escrow&quot; Deal Contact is created, the Account is populated</description>
    <inlineHelpText>Title and Escrow from the Vendor Entities Section</inlineHelpText>
    <label>Title</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals (Title and Escrow)</relationshipLabel>
    <relationshipName>Deals_as_Title</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Term and Bridge Use</description>
    <label>Underwriter</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Bridge Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Term Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>SAB Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Underwriter)</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Properties1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>The Loan Number of the Deal associated to this Property</description>
    <label>Deal Loan Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Underwriter lookup field on the Property object.</description>
    <label>Underwriter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <formula>LEFT(FirstName,1) + LEFT(LastName,1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initials</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RStest.cls
@isTest
private class RStest {

  static testMethod void lightning_Tests_UnitTest() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    List<Property__c> properties = test_Helper.createProperties(opp);

    Test.startTest();
    lightning_Controller.getSession();
    lightning_Controller.getRecord(opp.Id);
     lightning_Controller.getRecordListPileLineRpt(
      opp.Id,
      '',
      'opportunity',
	  new List<String>{ 'Anticipated_Closing_Date__c','Name' ,'Spread_BPS__c','Are_Assets_Being_RFNC_From_Existing_Term__c','Final_Spread__c', 'Loan_Purpose__c','Deal_Loan_Number__c','Account.Introductions_Source__c','Recourse__c','Cash_Management__c','Term_Loan_Type__c','LTV__c','Amortization_Term__c','Floor__c','State_Percentages__c','StageName','Current_Loan_Amount__c','Owner.LastName','Underwriter__r.Initials__c','Loan_Coordinator__r.Initials__c','Closer__r.Initials__c','Title__r.Name','Third_Party_Title__r.Name','Are_Assets_Coming_Off_Bridge_Line__c','Warehouse_Line__c','Kickoff_Date__c','Days_In_Underwriting__c','Anticipated_IC_Approval__c','CloseDate','Loan_Size__c','Final_Loan_Amount__c','Awaiting_Kickoff_Call__c','In_Process_of_Withdrawn_or_Rejected__c','id'} ,        
      'Id',
      'Desc',
      ' Account.Name != \'Inhouse Test Account\' AND Lender__c LIKE \'%CoreVest%\' AND CloseDate = THIS_MONTH',
      'Awaiting_Kickoff_Call__c ASC, Anticipated_Closing_Date__c ASC, StageName DESC ',
      'P'
    );      
 
    Test.stopTest();
  }
}