force-app/main/default/objects/Account/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introductions_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Introductions_Source__c.field-meta.xml
<CustomField>
    <fullName>Introductions_Source__c</fullName>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Equifax__c.field-meta.xml
<CustomField>
    <fullName>Equifax__c</fullName>
    <label>Equifax</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Experian__c.field-meta.xml
<CustomField>
    <fullName>Experian__c</fullName>
    <label>Experian</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Number of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>Adam Luray Sourced</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Sarhad Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Charlie Flynn Sourced</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Rental_Units_Owned__c.field-meta.xml
<CustomField>
    <fullName>Rental_Units_Owned__c</fullName>
    <label>Rental Units Owned</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsor_Tier__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Tier__c</fullName>
    <description>Bridge Use</description>
    <label>Sponsor Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TransUnion__c.field-meta.xml
<CustomField>
    <fullName>TransUnion__c</fullName>
    <label>TransUnion</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Chatter_Mapping__c/Custom_Chatter_Mapping__c.object-meta.xml
<CustomObject>
    <label>Chatter</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-{0}</displayFormat>
        <label>CustomChatter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Chatter_Mapping__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Chatter</relationshipLabel>
    <relationshipName>Chatter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Chatter_Mapping__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apex_Context__c.field-meta.xml
<CustomField>
    <fullName>Apex_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for development work only</description>
    <label>Apex Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Spread__c.field-meta.xml
<CustomField>
    <fullName>Final_Spread__c</fullName>
    <description>Term Use</description>
    <label>Final Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Swap__c.field-meta.xml
<CustomField>
    <fullName>Final_Swap__c</fullName>
    <description>Term Use</description>
    <label>Final Swap</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Effective_Date__c</fullName>
    <description>Bridge Use</description>
    <label>Loan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_Locked__c.field-meta.xml
<CustomField>
    <fullName>Rate_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Rate on this Loan has been locked</description>
    <inlineHelpText>Indicates that the Rate on this Loan has been locked</inlineHelpText>
    <label>Rate Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Term_Loan_Type__c</fullName>
    <label>Term Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 Year</fullName>
            </value>
            <value>
                <fullName>5 Year</fullName>
            </value>
            <value>
                <fullName>7 Year</fullName>
            </value>
            <value>
                <fullName>10 Year</fullName>
            </value>
            <value>
                <fullName>30 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/oppChatter_test.cls
@istest
public class oppChatter_test {
@testsetup
static void datasetup() {
    test_Helper.createDealLoanNumber();
    List<Account> al = new List<Account>();
    Account a0 = new Account();
    a0.Name = 'Berkadia Commercial Mortgage';
    a0.BillingCountry = 'United States';
    a0.BillingState = 'California';
    a0.Introductions_Source__c = 'Hotline';
    a0.Introduction_Subsource__c = 'Main';
    a0.Alternate_Phone__c = '5555555555';
    al.add(a0);
    insert al;
    List<Contact> cl = new List<Contact>();
    Contact c0 = new Contact();
    c0.FirstName = 'test';
    c0.LastName = 'test';
    c0.MailingCountry = 'United States';
    c0.MailingState = 'California';
    c0.AccountId = al[0].Id;
    c0.MobilePhone = '5555555555';
    c0.Phone = '7777777777';
    c0.Experian__c = 700;
    c0.TransUnion__c = 710;
    c0.Equifax__c = 700;
    c0.Years_of_Experience__c = 10;
    c0.Rental_Units_Owned__c = '5';
    c0.Sponsor_Tier__c = 'Tier 1';
    c0.Experience__c = 5;
    cl.add(c0);
    Opportunity opp0 = new Opportunity();
    opp0.Name = 'TERM TEST 0';
    opp0.CloseDate = System.today();
    opp0.Rate_Locked__c = false;
    opp0.Term_Loan_Type__c = '5 Year';
    opp0.StageName = 'Initial Review';
    opp0.Loan_Size__c = 2000000;
    opp0.AccountId = al[0].Id;
    opp0.Contact__c = cl[0].Id;
    opp0.Final_Loan_Amount__c = 100;
    opp0.Final_Swap__c = 1.7;
    opp0.Final_Spread__c = 1.1;
    opp0.Apex_Context__c = true;
    opp0.Loan_Effective_Date__c = date.today();
    Id id1 = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
    ]
    .Id;
    opp0.RecordTypeId = id1;

///////////////////////////////////////////////

    List<Opportunity> oppLst = new List<Opportunity>();
    oppLst.add(opp0);
    insert oppLst;

	Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
	req.setObjectId(oppLst[0].Id);
    req.setSkipEntryCriteria(true);
    Approval.ProcessResult result = Approval.process(req);
    
 	ProcessInstanceWorkItem piw = [SELECT ProcessInstance.TargetObjectId FROM ProcessInstanceWorkItem WHERE ProcessInstance.TargetObjectId = :oppLst[0].Id LIMIT 1];
            
    Custom_Chatter_Mapping__c record=new Custom_Chatter_Mapping__c(
        Parent_Id__c=oppLst[0].Id,
        Deal__c=piw.ProcessInstance.TargetObjectId
    );
    insert record;

    FeedItem newFI 		= new FeedItem();
    newFI.Type			= 'TextPost';
    newFI.NetworkScope 	= 'AllNetworks';
    newFI.Visibility 	= 'AllUsers';
    newFI.Body 			= 'Testing';
    newFI.IsRichText 	=  false;
    newFI.ParentId 		= record.Id;
    Insert newFI;    
    
    FeedComment newFIc = new FeedComment();
    newFIc.CommentType		=	'TextComment';
    newFIc.FeedItemId		=	newFI.id;	
    newFIc.CommentBody		=	'Comment Test';
    newFIc.IsRichText		=	false;
    newFI.Status			=	'Published';
    insert newFIc;
    
    System.debug(
      '2.RS 999 Number of Queries used in this apex code so far: ' +
      Limits.getQueries()
    );
  }

public static testMethod void unitTest1() {
    Test.startTest();
     List<FeedItem> fI = [SELECT id,body from  FeedItem];
    System.debug('RS 999 fI :' +fI); 
     List<FeedComment> FIc = [SELECT id,CommentBody from  FeedComment];
    System.debug('RS 999 FIc :' +FIc);    
     fI[0].body = 'test12';
    update fI;
    FIc[0].CommentBody = 'Comment Test 123';
    update FIc;
    delete FIc[0];
    delete FI[0];
    
    Test.stopTest();
  }    
    
}