force-app/main/default/objects/Account/fields/Non_Borrower_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Non_Borrower_Account_Type__c</fullName>
    <label>Account Record Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Auction Company</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker Plus</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>Correspondent - Bridge</fullName>
            </value>
            <value>
                <fullName>Credit and Background Search</fullName>
            </value>
            <value>
                <fullName>Diligence Review</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entity Search</fullName>
            </value>
            <value>
                <fullName>Flood Check</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Insurance Review</fullName>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
            </value>
            <value>
                <fullName>Investment Bank</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Lease/Purchase Review</fullName>
            </value>
            <value>
                <fullName>Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>Lender Underwriter</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker/Banker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Property Manager</fullName>
            </value>
            <value>
                <fullName>Ratings Agency</fullName>
            </value>
            <value>
                <fullName>Real Estate Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Alchemy_Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Alchemy Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Foreign_National__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/License_No__c.field-meta.xml
<CustomField>
    <fullName>License_No__c</fullName>
    <inlineHelpText>Broker License Number</inlineHelpText>
    <label>License No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Non_Borrower_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Non_Borrower_Account_Type__c</fullName>
    <formula>TEXT ( Account.Non_Borrower_Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Record Sub-Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorCity__c.field-meta.xml
<CustomField>
    <fullName>SponsorCity__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor City</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorHomeAddress__c.field-meta.xml
<CustomField>
    <fullName>SponsorHomeAddress__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor Home Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorState__c.field-meta.xml
<CustomField>
    <fullName>SponsorState__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor State</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SponsorZipCode__c.field-meta.xml
<CustomField>
    <fullName>SponsorZipCode__c</fullName>
    <description>DocuSign App Integration</description>
    <label>Sponsor Zip Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Alchemy_Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Alchemy_Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Alchemy Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Entry_Id__c.field-meta.xml
<CustomField>
    <fullName>Entry_Id__c</fullName>
    <description>Id from the Short Form on the marketing website</description>
    <inlineHelpText>Id from the Short Form on the marketing website</inlineHelpText>
    <label>Entry Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Form_Title__c.field-meta.xml
<CustomField>
    <fullName>Form_Title__c</fullName>
    <description>Title of the Form on the website used to create this Lead</description>
    <inlineHelpText>Title of the Form on the website used to create this Lead</inlineHelpText>
    <label>Form Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Home_City__c.field-meta.xml
<CustomField>
    <fullName>Home_City__c</fullName>
    <label>Home City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Home_State__c.field-meta.xml
<CustomField>
    <fullName>Home_State__c</fullName>
    <label>Home State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Home_Zip__c.field-meta.xml
<CustomField>
    <fullName>Home_Zip__c</fullName>
    <label>Home Zip</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Portal_Last_Login__c.field-meta.xml
<CustomField>
    <fullName>Portal_Last_Login__c</fullName>
    <label>Portal Last Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Portal_Username__c.field-meta.xml
<CustomField>
    <fullName>Portal_Username__c</fullName>
    <description>Username used for the Loan Portal</description>
    <inlineHelpText>Username used for the Loan Portal</inlineHelpText>
    <label>Portal Username</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <description>Years lender has been in business.</description>
    <label>Years of Experience</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Leads.recordType-meta.xml
<RecordType>
    <fullName>Leads</fullName>
    <active>true</active>
    <businessProcess>Leads</businessProcess>
    <description>CAF Leads</description>
    <label>Leads</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>List of 239 Countries</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PortalAPIUser.cls
@RestResource(urlMapping='/portal/user/*')
global without sharing class PortalAPIUser {
  public static String portalId;
  public static Integer paginationStart;
  public static Integer paginationEnd;
  public static Boolean usePagination;

  @HttpGet
  global static void doGet() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');

    String pageSizeParam = RestContext.request.params.get('pageSize');
    Integer pageSize = null;
    if (String.isNotBlank(pageSizeParam)) {
      pageSize = Integer.valueOf(pageSizeParam);
    }

    Integer page = null;
    String pageParam = RestContext.request.params.get('page');
    if (String.isNotBlank(pageParam)) {
      page = Integer.valueOf(pageParam);
    }

    usePagination = false;
    if (pageSize != null && page != null) {
      paginationStart = (page - 1) * pageSize; //2
      paginationEnd = page * pageSize; //3
      usePagination = true;
    }

    if (params[3] == 'entryId') {
      String entryId = params[4];
      List<Lead> leads = [
        SELECT
          Id,
          FirstName,
          LastName,
          Alchemy_Portal_Id__c,
          Email,
          Form_Title__c,
          Phone,
          Entry_Id__c
        FROM Lead
        WHERE
          Entry_Id__c = :entryId
          AND Alchemy_Portal_Id__c != NULL
          AND Alchemy_Portal_Id__c != 'xx'
      ];

      if (!Test.isRunningTest()) {
        while (leads.size() == 0) {
          Long startTime = DateTime.now().getTime();
          Long finishTime = DateTime.now().getTime();
          while ((finishTime - startTime) < 9000) {
            //sleep for 9s
            finishTime = DateTime.now().getTime();
          }

          leads = [
            SELECT
              Id,
              FirstName,
              LastName,
              Alchemy_Portal_Id__c,
              Email,
              Form_Title__c,
              Phone,
              Entry_Id__c
            FROM Lead
            WHERE
              Entry_Id__c = :entryId
              AND Alchemy_Portal_Id__c != NULL
              AND Alchemy_Portal_Id__c != 'xx'
          ];
        }
      }

      if (leads.size() > 0) {
        Map<String, String> responseBody = new Map<String, String>();
        responseBody.put('userId', leads[0].Alchemy_Portal_Id__c);
        // responseBody.put('name', leads[0].Name);
        responseBody.put('firstName', leads[0].FIrstName);
        responseBody.put('lastName', leads[0].LastName);
        responseBody.put('email', leads[0].Email);
        responseBody.put('formTitle', leads[0].Form_Title__c);
        responseBody.put('entryId', leads[0].Entry_Id__c);

        system.debug(responseBody);

        res.addHeader('Content-Type', 'application/json');
        res.responseBody = Blob.valueOf(JSON.serialize(responseBody, true));
      } else {
        Map<String, String> responseBody = new Map<String, String>();
        responseBody.put('status', 'error');
        responseBody.put('message', 'Entry Id not found');

        res.addHeader('Content-Type', 'application/json');
        res.statusCode = 404;
        res.responseBody = Blob.valueOf(JSON.serialize(responseBody, true));
      }
    } else if (params[3] == 'operations') {
      portalId = params[4];

      List<User> user = [SELECT Id FROM User WHERE Portal_Id__c = :portalId];

      if (user.size() > 0) {
        Id userId = user[0].Id;

        Set<String> borrowerIds = new Set<String>();
        for (Contact c : [
          SELECT Id, Alchemy_Portal_Id__c
          FROM Contact
          WHERE
            OwnerId = :userId
            AND RecordType.DeveloperName = 'Borrower'
            AND Alchemy_Portal_Id__c != NULL
        ]) {
          borrowerIds.add(c.alchemy_portal_id__c);
        }

        for (Lead l : [
          SELECT Id, Alchemy_Portal_Id__c
          FROM Lead
          WHERE
            OwnerId = :userId
            AND IsConverted = FALSE
            AND Alchemy_Portal_Id__c != NULL
        ]) {
          borrowerIds.add(l.Alchemy_Portal_Id__c);
        }

        for (OpportunityTeamMember otm : [
          SELECT Id, Opportunity.Contact__r.Alchemy_Portal_Id__c
          FROM OpportunityTeamMember
          WHERE
            UserId = :userId
            AND Opportunity.Contact__r.RecordType.DeveloperName = 'Borrower'
            AND Opportunity.Contact__r.Alchemy_Portal_Id__c != NULL
        ]) {
          borrowerIds.add(otm.Opportunity.Contact__r.Alchemy_Portal_Id__c);
        }

        List<Borrower> borrowers = new List<Borrower>();
        for (Lead l : [
          SELECT
            Id,
            Alchemy_Portal_Id__c,
            CreatedDate,
            Portal_Last_Login__c,
            LastName,
            FirstName,
            Email
          FROM Lead
          WHERE Alchemy_Portal_Id__c IN :borrowerIds AND IsConverted = FALSE
        ]) {
          borrowers.add(new Borrower(l));
        }

        for (Contact c : [
          SELECT
            Id,
            Alchemy_Portal_Id__c,
            CreatedDate,
            Portal_Last_Login__c,
            FirstName,
            LastName,
            Email
          FROM Contact
          WHERE Alchemy_Portal_Id__c IN :borrowerIds
        ]) {
          borrowers.add(new Borrower(c));
        }

        borrowers.sort();

        if (params.size() > 6 && params[6] == 'count') {
          Map<String, Object> responseBody = new Map<String, Object>();
          responseBody.put('count', borrowers.size());
          res.addHeader('Content-Type', 'application/json');
          res.responseBody = Blob.valueOf(JSON.serialize(responseBody));
        } else {
          List<Borrower> borrowersToSend = new List<Borrower>();
          if (usePagination) {
            for (Integer i = paginationStart; i < paginationEnd; i++) {
              if (i < borrowers.size()) {
                borrowersToSend.add(borrowers[i]);
              }
            }
          } else {
            borrowersToSend = borrowers;
          }

          res.addHeader('Content-Type', 'application/json');
          res.responseBody = Blob.valueOf(JSON.serialize(borrowersToSend));
        }
      } else {
        Map<String, String> responseBody = new Map<String, String>();
        responseBody.put('status', 'error');
        responseBody.put('message', 'User Id not found');

        res.addHeader('Content-Type', 'application/json');
        res.statusCode = 404;
        res.responseBody = Blob.valueOf(JSON.serialize(responseBody, true));
      }
    } else {
      portalId = params[3];
      PortalUser user = new PortalUser(portalId);
      if (user.id != null) {
        res.addHeader('Content-Type', 'application/json');
        res.responseBody = Blob.valueOf(JSON.serialize(user));
      } else {
        Map<String, String> responseBody = new Map<String, String>();
        responseBody.put('status', 'error');
        responseBody.put('message', 'Entry Id not found');

        res.addHeader('Content-Type', 'application/json');
        res.statusCode = 404;
        res.responseBody = Blob.valueOf(JSON.serialize(responseBody, true));
      }
    }
  }

  @HttpPatch
  global static void doPatch() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');
    portalId = params[3];
    PortalUser user = new PortalUser(portalId);

    system.debug(portalId);
    if (user.id != null) {
      PortalUser userCopy = (PortalUser) JSON.deserialize(
        req.requestBody.toString(),
        PortalUser.class
      );

      String sobjectType = 'Lead';
      if (user.contactId != null) {
        sobjectType = 'Contact';
      } else if (user.leadId != null) {
        sobjectType = 'Lead';
      } else {
        sobjectType = 'User';
      }
      if (sobjectType != 'User') {
        sObject record = userCopy.getRecord(sobjectType);
        // system.debug(record);
        Map<String, Object> fieldsToValue = record.getPopulatedFieldsAsMap();
        record = user.getRecord(); //record.Id.getSObjectType().newSObject(record.Id);
        // system.debug(fieldsToValue);
        for (String fieldName : fieldsToValue.keySet()) {
          if (fieldsToValue.get(fieldName) != null) {
            record.put(fieldName, fieldsToValue.get(fieldName));
          }
        }

        update record;
        //user.updateUser();
        user = new PortalUser(portalId);
        res.addHeader('Content-Type', 'application/json');
        res.responseBody = Blob.valueOf(JSON.serialize(user, true));
      }
    } else {
      Map<String, String> responseBody = new Map<String, String>();
      responseBody.put('status', 'error');
      responseBody.put('message', 'User not found');
      res.statusCode = 404;
      res.addHeader('Content-Type', 'application/json');
      res.responseBody = Blob.valueOf(JSON.serialize(responseBody, true));
    }
  }

  public class PortalUser {
    public String firstName;
    public String lastName;
    public String fax;
    public String mobilePhone;
    public String businessPhone;
    public String email;
    public String portalUsername;
    public String homeStreetAddress;
    public String homeCity;
    public String homeState;
    public String homeZip;
    public String homeCountry;
    public String businessStreetAddress;
    public String businessCity;
    public String businessState;
    public String businessStateCode;
    public String businessCountry;
    public String businessZip;
    public String leadId;
    public String userType;
    public String id;
    public String contactId;
    public String accountId;
    public String accountType;
    public String companyName;

    public String title;
    public String alternativeEmail;
    public String licenseNo;
    public Decimal yearsOfExperience;

    public DateTime lastLogin;

    public PortalUser(String portalId) {
      Id contactId = AlchemyAPI.getContactIdByAlchemyId(portalId);
      Id leadId = AlchemyAPI.getLeadIdByAlchemyId(portalId);
      Id userId = AlchemyAPI.getUserIdByPortalId(portalId);

      if (contactId != null) {
        Contact c = [
          SELECT
            Id,
            FirstName,
            LastName,
            Fax,
            MobilePhone,
            Phone,
            Email,
            Portal_Username__c,
            MailingStreet,
            MailingCity,
            MailingState,
            MailingStateCode,
            MailingPostalCode,
            MailingCountry,
            Alchemy_Portal_Id__c,
            SponsorHomeAddress__c,
            SponsorCity__c,
            SponsorZipCode__c,
            Home_Country__c,
            SponsorState__c,
            AccountId,
            Alternative_Email__c,
            License_No__c,
            Years_of_Experience__c,
            Account.Name,
            Account.RecordType.DeveloperName,
            Account.Non_Borrower_Account_Type__c,
            Title,
            Portal_Last_Login__c
          FROM Contact
          WHERE Id = :contactId
          LIMIT 1
        ];
        this.id = c.Alchemy_Portal_Id__c;
        this.firstName = c.FirstName;
        this.lastName = c.LastName;
        this.Fax = c.Fax;
        this.mobilePhone = c.MobilePhone;
        this.businessphone = c.Phone;
        this.email = c.Email;
        this.portalUserName = c.Portal_Username__c;
        this.businessStreetAddress = c.MailingStreet;
        this.businessCity = c.MailingCity;
        this.businessStreetAddress = c.MailingStreet;
        this.businessState = c.MailingState;
        this.businessStateCode = c.MailingStateCode;
        this.businessZip = c.MailingPostalCode;
        this.businessCountry = c.MailingCountry;
        this.contactId = c.Id;

        this.homeStreetAddress = c.SPonsorHomeAddress__c;
        this.homeCity = c.SPonsorCity__c;
        this.homeState = c.SponsorState__c;
        this.homeCountry = c.Home_Country__c;
        this.homeZip = c.SponsorZipCode__c;
        this.accountId = c.AccountId;
        this.accountType = c.Account.Non_Borrower_Account_Type__c;
        if (c.Account.RecordType.DeveloperName == 'vendor') {
          this.userType = 'vendor';
        }

        this.title = c.Title;
        this.alternativeEmail = c.Alternative_Email__c;
        this.licenseNo = c.License_No__c;
        this.yearsOfExperience = c.Years_of_Experience__c;
        this.companyName = c.Account.Name;
        this.lastLogin = c.Portal_Last_Login__c;
      } else if (leadId != null) {
        Lead l = [
          SELECT
            Id,
            FirstName,
            LastName,
            Fax,
            Phone,
            MobilePhone,
            Email,
            Portal_Username__c,
            Street,
            City,
            State,
            StateCode,
            PostalCode,
            Country,
            Alchemy_Portal_Id__c,
            Home_Street_Address__c,
            Home_City__c,
            Home_State__c,
            Home_Zip__c,
            Home_Country__c,
            Company,
            Portal_Last_Login__c
          FROM Lead
          WHERE Id = :leadId
          LIMIT 1
        ];

        this.leadId = l.Id;
        this.id = l.Alchemy_Portal_Id__c;
        this.firstName = l.FirstName;
        this.lastName = l.LastName;
        this.fax = l.Fax;
        this.MobilePhone = l.MobilePhone;
        this.BusinessPhone = l.Phone;
        this.email = l.Email;
        this.portalUsername = l.Portal_Username__c;
        this.businessStreetAddress = l.Street;
        this.businessCity = l.City;
        this.businessState = l.State;
        this.businessStateCode = l.StateCode;
        this.businessCountry = l.country;
        this.businessZip = l.PostalCode;
        this.homeStreetAddress = l.Home_Street_Address__c;
        this.homeCity = l.Home_City__c;
        this.homeState = l.Home_State__c;
        this.homeCountry = l.Home_Country__c;
        this.homeZip = l.Home_Zip__c;
        this.companyName = l.Company;
        this.lastLogin = l.Portal_Last_Login__c;
      } else if (portalId != null) {
        User u = [
          SELECT Id, FirstName, LastName, Portal_Id__c, Email
          FROM User
          WHERE Id = :userId
          LIMIT 1
        ];
        this.id = u.Portal_Id__c;
        this.firstName = u.FirstName;
        this.lastName = u.LastName;
        this.email = u.Email;
      }
    }

    // public void updateUser() {
    //   if (this.contactId != null) {
    // Contact c = new Contact(Id = this.contactId);
    // c.FirstName = this.firstName;
    // c.LastName = this.lastName;
    // c.Fax = this.Fax;
    // c.MobilePhone = this.mobilePhone;
    // c.Phone = this.businessphone;
    // c.Email = this.email;
    // c.Portal_Username__c = this.portalUserName;
    // c.MailingStreet = this.businessStreetAddress;
    // c.MailingCity = this.businessCity;
    // c.MailingStreet = this.businessStreetAddress;
    // c.MailingState = this.businessState;
    // c.MailingStateCode = this.businessStateCode;
    // c.MailingPostalCode = this.businessZip;
    // c.MailingCountry = this.businessCountry;

    //     update c;
    //   } else if (this.leadId != null) {
    //     Lead l = new Lead(Id = this.leadId);

    //     l.FirstName = this.firstName;
    //     l.LastName = this.lastName;
    //     l.Fax = this.fax;
    //     l.MobilePhone = this.mobilePhone;
    //     l.Phone = this.BusinessPhone;
    //     l.Email = this.email;
    //     l.Portal_Username__c = this.portalUsername;
    //     l.Street = this.businessStreetAddress;
    //     l.City = this.businessCity;
    //     l.State = this.businessState;
    //     l.StateCode = this.businessStateCode;
    //     l.country = this.businessCountry;

    //     update l;
    //   }
    // }
    public sObject getRecord() {
      sObject record;
      // system.debug(this.contactId);
      // system.debug(this.leadId);
      if (this.contactId != null) {
        Contact c = new Contact(Id = this.contactId);
        c.FirstName = this.firstName;
        c.LastName = this.lastName;
        c.Fax = this.Fax;
        c.MobilePhone = this.mobilePhone;
        c.Phone = this.businessphone;
        c.Email = this.email;
        c.Portal_Username__c = this.portalUserName;
        c.MailingStreet = this.businessStreetAddress;
        c.MailingCity = this.businessCity;
        c.MailingStreet = this.businessStreetAddress;
        c.MailingState = this.businessState;
        c.MailingStateCode = this.businessStateCode;
        c.MailingPostalCode = this.businessZip;
        c.MailingCountry = this.businessCountry;

        c.SponsorHomeAddress__c = this.homeStreetAddress;
        c.SponsorCity__c = this.homeCity;
        c.SponsorState__c = this.homeState;
        c.SponsorZipCode__c = this.homeZip;
        c.Home_Country__c = this.homeCountry;

        c.Title = this.title;
        c.Alternative_Email__c = this.alternativeEmail;
        c.License_No__c = this.licenseNo;
        c.Years_of_Experience__c = this.yearsOfExperience;
        c.Portal_Last_Login__c = this.lastLogin;

        record = c;
      } else if (this.leadId != null) {
        Lead l = new Lead(Id = this.leadId);
        l.FirstName = this.firstName;
        l.LastName = this.lastName;
        l.Fax = this.fax;
        l.MobilePhone = this.mobilePhone;
        l.Phone = this.BusinessPhone;
        l.Email = this.email;
        l.Portal_Username__c = this.portalUsername;
        l.Street = this.businessStreetAddress;
        l.City = this.businessCity;
        l.State = this.businessState;
        l.StateCode = this.businessStateCode;
        l.country = this.businessCountry;
        system.debug(businessZip);
        l.PostalCode = this.businessZip;
        l.Home_Street_Address__c = this.homeStreetAddress;
        l.Home_City__c = this.homeCity;
        l.Home_Zip__c = this.homeZip;
        l.Home_Country__c = this.homeCountry;
        l.Home_State__c = this.homeState;
        l.Portal_Last_Login__c = this.lastLogin;

        record = l;
      }

      return record;
    }

    public sObject getRecord(String sobjectType) {
      sObject record;
      // system.debug(this.contactId);
      // system.debug(this.leadId);
      if (sobjectType == 'Contact') {
        Contact c = new Contact();
        c.FirstName = this.firstName;
        c.LastName = this.lastName;
        c.Fax = this.Fax;
        c.MobilePhone = this.mobilePhone;
        c.Phone = this.businessphone;
        c.Email = this.email;
        c.Portal_Username__c = this.portalUserName;
        c.MailingStreet = this.businessStreetAddress;
        c.MailingCity = this.businessCity;
        c.MailingStreet = this.businessStreetAddress;
        c.MailingState = this.businessState;
        c.MailingStateCode = this.businessStateCode;
        c.MailingPostalCode = this.businessZip;
        c.MailingCountry = this.businessCountry;

        c.SponsorHomeAddress__c = this.homeStreetAddress;
        c.SponsorCity__c = this.homeCity;
        c.SponsorState__c = this.homeState;
        c.SponsorZipCode__c = this.homeZip;
        c.Home_Country__c = this.homeCountry;

        c.Title = this.title;
        c.Alternative_Email__c = this.alternativeEmail;
        c.License_No__c = this.licenseNo;
        c.Years_of_Experience__c = this.yearsOfExperience;
        c.Portal_Last_Login__c = this.lastLogin;

        record = c;
      } else if (sobjectType == 'Lead') {
        Lead l = new Lead();
        l.FirstName = this.firstName;
        l.LastName = this.lastName;
        l.Fax = this.fax;
        l.MobilePhone = this.mobilePhone;
        l.Phone = this.BusinessPhone;
        l.Email = this.email;
        l.Portal_Username__c = this.portalUsername;
        l.Street = this.businessStreetAddress;
        l.City = this.businessCity;
        l.State = this.businessState;
        l.StateCode = this.businessStateCode;
        l.country = this.businessCountry;
        system.debug(this.businessZip);
        l.PostalCode = this.businessZip;

        l.Home_Street_Address__c = this.homeStreetAddress;
        l.Home_City__c = this.homeCity;
        l.Home_Zip__c = this.homeZip;
        l.Home_Country__c = this.homeCountry;
        l.Home_State__c = this.homeState;
        l.Portal_Last_Login__c = this.lastLogin;

        record = l;
      }

      return record;
    }
  }

  class Borrower implements Comparable {
    String userId;
    String email;
    DateTime createdDate;
    DateTime lastLoginDate;
    String firstName;
    String lastName;

    public Integer compareTo(Object compareTo) {
      Borrower compareToBor = (Borrower) compareTo;
      if (this.createdDate == compareToBor.createdDate)
        return 0;
      if (this.createdDate > compareToBor.createdDate)
        return -1;
      return 1;
    }

    Borrower(Contact c) {
      this.firstName = c.FirstName;
      this.lastName = c.LastName;

      this.email = c.Email;
      this.createdDate = c.CreatedDate;
      this.lastLoginDate = c.Portal_Last_Login__c;
      this.userId = c.Alchemy_Portal_Id__c;
    }

    Borrower(Lead l) {
      this.firstName = l.FirstName;
      this.lastName = l.lastName;

      this.email = l.Email;
      this.userId = l.Alchemy_Portal_Id__c;
      this.createdDate = l.CreatedDate;
      this.lastLoginDate = l.Portal_Last_Login__c;
    }
  }
}