force-app/main/default/objects/Account/fields/Payment_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instructions__c</fullName>
    <description>Payment Instructions that will reflect on the Closing Loan Documents</description>
    <inlineHelpText>Payment Instructions that will reflect on the Closing Loan Documents</inlineHelpText>
    <label>Payment Instructions</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Entity__c/Business_Entity__c.object-meta.xml
<CustomObject>
    <description>Business Entity connected to an Account</description>
    <label>Business Entity</label>
    <nameField>
        <label>Business Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Entity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Entities</relationshipLabel>
    <relationshipName>Business_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Status__c</field>
            <operation>equals</operation>
            <value>Active CoreVest Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Entities</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <description>Payment Reference to be entered when generating Closing Loan Documents/Schedule of Lender Costs</description>
    <inlineHelpText>Payment Reference/Invoice #</inlineHelpText>
    <label>Payment Reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Title</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borrower Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Diligence Review</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Escrow Agent</fullName>
            </value>
            <value>
                <fullName>Flood Check</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Insurance Review</fullName>
            </value>
            <value>
                <fullName>Lease/Purchase Review</fullName>
            </value>
            <value>
                <fullName>Lender Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Lender Local Legal Counsel</fullName>
            </value>
            <value>
                <fullName>PCA &amp; ESA</fullName>
            </value>
            <value>
                <fullName>Reserves</fullName>
            </value>
            <value>
                <fullName>Securitization Legal Counsel</fullName>
            </value>
            <value>
                <fullName>Servicer</fullName>
            </value>
            <value>
                <fullName>Tax Verification</fullName>
            </value>
            <value>
                <fullName>Title and Escrow</fullName>
            </value>
            <value>
                <fullName>Title and Escrow 2</fullName>
            </value>
            <value>
                <fullName>Title Company</fullName>
            </value>
            <value>
                <fullName>Title Review</fullName>
            </value>
            <value>
                <fullName>Valuation</fullName>
            </value>
            <value>
                <fullName>Valuations Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/Loan_Fee__c.object-meta.xml
<CustomObject>
    <description>Fees associated to Loans</description>
    <label>Loan Fee</label>
    <nameField>
        <displayFormat>LF-{000000}</displayFormat>
        <label>Loan Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fee__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Deal associated with this fee</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Deal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Deal Contact</label>
    <referenceTo>Deal_Contact__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The Amount of this Fee</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Reference Number for this Fee</description>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vendor this fee is paid to</description>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Type__c</fullName>
    <description>The Type of Vendor for this Loan Fee</description>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Title Review</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Insurance Premium</fullName>
            </value>
            <value>
                <fullName>Insurance Review</fullName>
            </value>
            <value>
                <fullName>Lender Diligence</fullName>
            </value>
            <value>
                <fullName>Lender Legal Counsel</fullName>
            </value>
            <value>
                <fullName>LexisNexis Risk Solutions</fullName>
            </value>
            <value>
                <fullName>MISC</fullName>
            </value>
            <value>
                <fullName>PCA &amp; ESA</fullName>
            </value>
            <value>
                <fullName>Post Closing Holdback</fullName>
            </value>
            <value>
                <fullName>Servicer</fullName>
            </value>
            <value>
                <fullName>Tax Verification</fullName>
            </value>
            <value>
                <fullName>Title and Escrow</fullName>
            </value>
            <value>
                <fullName>Title Review</fullName>
            </value>
            <value>
                <fullName>Valuations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_Upfront_Fee__c.field-meta.xml
<CustomField>
    <fullName>CAF_Upfront_Fee__c</fullName>
    <description>Term and Bridge Use</description>
    <label>Origination Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>This will replace the manual auto assignment</description>
    <displayFormat>{00000}</displayFormat>
    <label>Deal Loan Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <label>Deposit Amount Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Collected__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Collected__c</fullName>
    <label>Deposit Collected Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Lender_Out_of_Pocket__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Lender_Out_of_Pocket__c</fullName>
    <label>Deposit - Lender Diligence</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Loan_Amount__c</fullName>
    <label>Final Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Spread__c.field-meta.xml
<CustomField>
    <fullName>Final_Spread__c</fullName>
    <description>Term Use</description>
    <label>Final Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Swap__c.field-meta.xml
<CustomField>
    <fullName>Final_Swap__c</fullName>
    <description>Term Use</description>
    <label>Final Swap</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <label>Interest Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Term__c.field-meta.xml
<CustomField>
    <fullName>IO_Term__c</fullName>
    <description>Term Use</description>
    <inlineHelpText>Interest Only Term</inlineHelpText>
    <label>IO Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>24 months</fullName>
            </value>
            <value>
                <fullName>36 months</fullName>
            </value>
            <value>
                <fullName>48 months</fullName>
            </value>
            <value>
                <fullName>60 months</fullName>
            </value>
            <value>
                <fullName>84 months</fullName>
            </value>
            <value>
                <fullName>120 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spread_BPS__c.field-meta.xml
<CustomField>
    <fullName>Spread_BPS__c</fullName>
    <label>Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Swap_Rate__c.field-meta.xml
<CustomField>
    <fullName>Swap_Rate__c</fullName>
    <label>Swap Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ScheduleOfLenderCostController.cls
public without sharing class ScheduleOfLenderCostController {
  public boolean printReady { get; set; }
  public String filtersJSON { get; set; }
  public WrapperData unsavedObj { get; set; }
  public Opportunity Deal { get; set; }
  public List<Deal_Contact__c> vendors { get; set; }
  public List<Loan_Fee__c> loanFees { get; set; }
  public decimal stubInterest { get; set; }
  public decimal CorevestProceeds { get; set; }
  public decimal totalLender { get; set; }
  public decimal legalFee { get; set; }
  public decimal totalreservecapex { get; set; }
  public decimal totalreserveinsurance { get; set; }
  public decimal totalreservetax { get; set; }
  public decimal debtreserve { get; set; }
  public decimal totalreserves { get; set; }
  public decimal totalthirdparty { get; set; }
  public decimal netproceedstoborrower { get; set; }
  public decimal TotalSources { get; set; }
  public decimal totaluses { get; set; }

  public void getData() {
    printReady = false;
    if (filtersJSON.substring(0, 1) != '$') {
      if (String.isNotBlank(filtersJSON)) {
        try {
          System.debug('filtersJSON---> ' + filtersJSON);
          unsavedObj = (WrapperData) JSON.deserialize(
            filtersJSON,
            WrapperData.class
          );
          if (
            unsavedObj.stubInterest != null &&
            unsavedObj.totalreservetax != null &&
            unsavedObj.totalreservecapex != null &&
            unsavedObj.totalreserveinsurance != null
          ) {
            stubInterest = unsavedObj.stubInterest != null
              ? decimal.valueOf(unsavedObj.stubInterest)
              : null;
            totalLender = unsavedObj.totalLender != null
              ? decimal.valueOf(unsavedObj.totalLender)
              : null;
            legalFee = unsavedObj.legalFee != null
              ? decimal.valueOf(unsavedObj.legalFee)
              : null;
            CorevestProceeds = unsavedObj.CorevestProceeds != null
              ? decimal.valueOf(unsavedObj.CorevestProceeds)
              : null;
            totalreserveinsurance = unsavedObj.totalreserveinsurance != null
              ? decimal.valueOf(unsavedObj.totalreserveinsurance)
              : null;
            totalreservetax = unsavedObj.totalreservetax != null
              ? decimal.valueOf(unsavedObj.totalreservetax)
              : null;
            totalreservecapex = unsavedObj.totalreservecapex != null
              ? decimal.valueOf(unsavedObj.totalreservecapex)
              : null;
            totalreserves = unsavedObj.totalreserves != null
              ? decimal.valueOf(unsavedObj.totalreserves)
              : null;
            totalthirdparty = unsavedObj.totalthirdparty != null
              ? decimal.valueOf(unsavedObj.totalthirdparty)
              : null;
            netproceedstoborrower = unsavedObj.netproceedstoborrower != null
              ? decimal.valueOf(unsavedObj.netproceedstoborrower)
              : null;
            TotalSources = unsavedObj.TotalSources != null
              ? decimal.valueOf(unsavedObj.TotalSources)
              : null;
            totaluses = unsavedObj.totaluses != null
              ? decimal.valueOf(unsavedObj.totaluses)
              : null;
          }

          Deal = getData(unsavedObj.dealId);
          vendors = [
            SELECT
              Id,
              Name,
              Payment_Reference__c,
              Account__r.Name,
              Account__r.Payment_Instructions__c,
              Vendor_Type__c
            FROM Deal_Contact__C
            WHERE
              Deal__C = :unsavedObj.dealId
              AND Account__c != NULL
              AND Vendor_Type__c IN (
                'Legal Counsel',
                'Valuation',
                'Insurance Review',
                'Cash Management',
                '3rd Party Title',
                'Flood Check',
                'Architect',
                'Contractor',
                'Engineer',
                'Escrow Agent',
                'Insurance',
                'Lease/Purchase Review',
                'Rent Deposit Bank',
                'Servicer',
                'Tax Verification',
                'Title and Escrow',
                'Title and Escrow 2',
                'Title Company',
                'Reserves'
              )
          ];
          loanFees = [
            SELECT
              Id,
              Vendor_Type__c,
              Fee_Amount__c,
              Reference__c,
              vendor__r.Name,
              vendor__r.Payment_Instructions__c
            FROM Loan_Fee__c
            WHERE Deal__c = :unsavedObj.dealId AND vendor__c != NULL
          ];
        } catch (Exception ex) {
          unsavedObj = new WrapperData();
          System.debug('Invalid JSON string passed. Unable to deserialize.');
        }
      }
      printReady = true;
    }
  }

  @AuraEnabled
  public static Opportunity getData(String recordId) {
    List<Opportunity> deals = [
      SELECT
        Id,
        IO_Term__c,
        Deal_Loan_Number__c,
        Swap_Rate__c,
        Spread_BPS__c,
        Final_Spread__c,
        Final_Swap__c,
        Interest_Rate_Type__c,
        Final_Loan_Amount__c,
        Deposit_Lender_Out_of_Pocket__c,
        Deposit_Collected__c,
        CAF_Upfront_Fee__c,
        Deposit_Amount__c,
        Indicative_Rate_Calc__c,
        CloseDate,
        Borrower_Entity__r.Name,
        Total_Annual_Tax__c,
        Total_Annual_Insurance__c,
        Deposit_Legal_Counsel_Diligence__c,
        Calculated_Origination_Fee__c,
        Recourse__c,
        Cash_Management__c,
        Are_Assets_Coming_Off_Bridge_Line__c,
        Total_Annual_Cap_Ex__c,
        Reserve_Cap_Ex__c,
        Reserve_Insurance__c,
        Reserve_Tax__c,
        (
          SELECT Id, Vendor__c, Vendor_Type__c, Reference__c, Fee_Amount__c
          FROM Loan_Fees__r
          ORDER BY CreatedDate
        ) // Deal Loan fees
      FROM Opportunity
      WHERE id = :recordId
    ];

    return deals[0];
  }
  // Deal Loan fees
  @AuraEnabled
  public static List<sObject> getDealLoanFees(String recordId) {
    System.debug('getDealLoanFees----->  ' + recordId);
    return [
      SELECT Id, Vendor__c, Vendor_Type__c, Reference__c, Fee_Amount__c
      FROM Loan_Fee__c
      WHERE Deal__c = :recordId
    ];
  }
  @AuraEnabled
  public static List<sObject> upsertRecords(List<sObject> records) {
    System.debug('records----->  ' + records);
    return lightning_Util.upsertRecords(records);
  }
  @AuraEnabled
  public static Boolean deleteRecords(List<sObject> records) {
    try {
      delete records;
    } catch (DmlException e) {
      throw new AuraHandledException('Failed to delete');
    }

    return true;
  }
  @AuraEnabled
  public static Map<String, String> saveDealData(Opportunity deal) {
    Map<String, String> result = new Map<String, String>();
    try {
      update deal;
      result.put('Success', 'true');
      result.put('ErrorMessage', null);
    } catch (DMLException e) {
      result.put('Success', 'false');
      result.put('ErrorMessage', e.getMessage());
    }
    return result;
  }

  @AuraEnabled
  public static String getUrlAndInstance() {
    String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
    return baseUrl + '/apex/ScheduleOfLenderCostVfp';
  }

  public class WrapperData {
    public String dealId { public get; set; }
    public String fundingDate2 { public get; set; }
    //  public Decimal originationfeepercentage {public get; set;}
    public String yearSwapRate { public get; set; }
    public String installmentcomment { public get; set; }
    public String creditSpread { public get; set; }
    public Decimal InterestRateTermSheet { public get; set; }
    public Decimal InterestRateRateLock { public get; set; }
    public Decimal stubInterestDayCount { public get; set; }
    public Decimal debtreserve { public get; set; }
    public Decimal DebtService { public get; set; }
    public String stubInterest { public get; set; }
    public String CorevestProceeds { public get; set; }
    public Decimal cfcorevestpurchaser { public get; set; }
    //    public String taxentry {public get; set;}
    public String TotalSources { public get; set; }
    public String legalFee { public get; set; }
    public String totalLender { public get; set; }
    //    public String capexentry {public get; set;}
    //  public String insuranceentry {public get; set;}
    public String tax { public get; set; }
    public String capex { public get; set; }
    public String insurence { public get; set; }
    public String totalreserves { public get; set; }
    public String netproceedstoborrower { public get; set; }
    public String totalthirdparty { public get; set; }
    public String totaluses { public get; set; }
    public String rateType { public get; set; }
    public String totalreservetax { public get; set; }
    public String totalreservecapex { public get; set; }
    public String totalreserveinsurance { public get; set; }
    public String finalInterestRate { public get; set; }
  }
}