force-app/main/default/objects/Account/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referring Account</description>
    <inlineHelpText>Referring Brokerage, Vendor or Client Account.  Select the Referral Contact to populate this field.</inlineHelpText>
    <label>Referral Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Referred</relationshipLabel>
    <relationshipName>AccountsReferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referral_Source_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the contact that referred this Account</description>
    <inlineHelpText>Referring Broker, Vendor or Client Contact</inlineHelpText>
    <label>Referral Source Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts Referred</relationshipLabel>
    <relationshipName>AccountsReferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_YSP__c.field-meta.xml
<CustomField>
    <fullName>CAF_YSP__c</fullName>
    <description>Term Use</description>
    <label>CAF YSP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>0 BPS in Spread</fullName>
            </value>
            <value>
                <fullName>+5 BPS in Spread / +25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-5 BPS in Spread / -25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+10 BPS in Spread / +25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-10 BPS in Spread / -25 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+10 BPS in spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-10 BPS in spread / -50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+15 BPS in Spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-15 BPS in Spread / -50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>+20 BPS in Spread / +50 BPS in Commissionable Fee</fullName>
            </value>
            <value>
                <fullName>-20 BPS in Spread / -50 BPS in Commissionable Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Sub_Source__c</fullName>
    <label>Deal Intro Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deal_Intro_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
                <label>5arch</label>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Open_Period_Begins__c.field-meta.xml
<CustomField>
    <fullName>Open_Period_Begins__c</fullName>
    <formula>IF( CONTAINS(TEXT(YM_Prepayment_Penalty__c), &apos;Date of Maturity&apos;) ,
 Updated_Loan_Maturity_Date__c ,
ADDMONTHS(First_Payment_Date1__c, VALUE(  SUBSTITUTE(TEXT(YM_Prepayment_Penalty__c), &apos; Months&apos;, &apos;&apos;)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Open Period Begins</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referring Acount</description>
    <inlineHelpText>Referring Brokerage, Vendor or Client Account.  Select the Referral Contact to populate this field.</inlineHelpText>
    <label>Referral Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals Referred</relationshipLabel>
    <relationshipName>DealsReferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stepdown_Prepayment_Period__c.field-meta.xml
<CustomField>
    <fullName>Stepdown_Prepayment_Period__c</fullName>
    <description>The Stepdown Prepayment Period</description>
    <label>Stepdown Prepayment Period</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3,2,1,0,0</fullName>
            </value>
            <value>
                <fullName>3,2,1,1,1</fullName>
            </value>
            <value>
                <fullName>4,3,2,1,0</fullName>
            </value>
            <value>
                <fullName>5,4,2,2,1</fullName>
            </value>
            <value>
                <fullName>5,4,3,2,1</fullName>
            </value>
            <value>
                <fullName>5,4,3,2,1,0,0</fullName>
            </value>
            <value>
                <fullName>5,4,3,2,1,1,1</fullName>
            </value>
            <value>
                <fullName>5,4,3,2,2,1,1</fullName>
            </value>
            <value>
                <fullName>5,4,4,3,3,2,1</fullName>
            </value>
            <value>
                <fullName>5,5,4,3,2,1,0</fullName>
            </value>
            <value>
                <fullName>5,5,5,4,3,2,1</fullName>
            </value>
            <value>
                <fullName>7,6,5,4,3,2,1</fullName>
            </value>
            <value>
                <fullName>5,5,4,4,3,3,2,2,1,1</fullName>
            </value>
            <value>
                <fullName>5,5,5,5,5,4,3,2,0,0</fullName>
            </value>
            <value>
                <fullName>5,5,5,5,5,5,4,3,2,0</fullName>
            </value>
            <value>
                <fullName>5,5,5,5,5,4,3,2,1,1</fullName>
            </value>
            <value>
                <fullName>5,5,5,5,5,5,4,3,2,1</fullName>
            </value>
            <value>
                <fullName>10,9,8,7,6,5,4,3,2,1</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/YM_Prepayment_Penalty__c.field-meta.xml
<CustomField>
    <fullName>YM_Prepayment_Penalty__c</fullName>
    <description>Term Use</description>
    <inlineHelpText>Yield Maintenance Par Prepayment Period</inlineHelpText>
    <label>YM Par Prepayment Period</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>34 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>42 Months</fullName>
            </value>
            <value>
                <fullName>48 Months</fullName>
            </value>
            <value>
                <fullName>52 Months</fullName>
            </value>
            <value>
                <fullName>53 Months</fullName>
            </value>
            <value>
                <fullName>54 Months</fullName>
            </value>
            <value>
                <fullName>55 Months</fullName>
            </value>
            <value>
                <fullName>56 Months</fullName>
            </value>
            <value>
                <fullName>57 Months</fullName>
            </value>
            <value>
                <fullName>58 Months</fullName>
            </value>
            <value>
                <fullName>60 Months</fullName>
            </value>
            <value>
                <fullName>61 Months</fullName>
            </value>
            <value>
                <fullName>66 Months</fullName>
            </value>
            <value>
                <fullName>72 Months</fullName>
            </value>
            <value>
                <fullName>77 Months</fullName>
            </value>
            <value>
                <fullName>78 Months</fullName>
            </value>
            <value>
                <fullName>79 Months</fullName>
            </value>
            <value>
                <fullName>80 Months</fullName>
            </value>
            <value>
                <fullName>81 Months</fullName>
            </value>
            <value>
                <fullName>84 Months</fullName>
            </value>
            <value>
                <fullName>96 Months</fullName>
            </value>
            <value>
                <fullName>102 Months</fullName>
            </value>
            <value>
                <fullName>108 Months</fullName>
            </value>
            <value>
                <fullName>112 Months</fullName>
            </value>
            <value>
                <fullName>113 Months</fullName>
            </value>
            <value>
                <fullName>114 Months</fullName>
            </value>
            <value>
                <fullName>115 Months</fullName>
            </value>
            <value>
                <fullName>116 Months</fullName>
            </value>
            <value>
                <fullName>117 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/YM_Prepayment_Penalty_Description__c.field-meta.xml
<CustomField>
    <fullName>YM_Prepayment_Penalty_Description__c</fullName>
    <description>Term Use</description>
    <inlineHelpText>This field is required when &quot;Other&quot; is selected above.  The verbiage entered is shown on the Term Sheet.</inlineHelpText>
    <label>Stepdown Prepayment Period Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OpenPeriodTaskEmailScheduled.cls
global class OpenPeriodTaskEmailScheduled implements Schedulable{
    global void execute(SchedulableContext SC) {

        List<User> usersToEmail = new List<User>();
        List<Task> myTasks = new List<Task>();
       //Query for sender email 
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'integrations@cvest.com'];

        //Email message list
       	Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();

        
		//Query for records
        List<Opportunity> myDeals = new List<Opportunity>([Select ID,Type,Owner.FirstName,
                                                           Owner.LastName,CloseDate, OwnerID, Deal_Intro_Source__c,
                                                           Owner.isActive, Owner.Email,
                                                           Account.OwnerId, Account.Owner.Email,Account.Owner.LastName,
                                                           Account.Owner.FirstName, Name, Open_Period_Begins__c, YM_Prepayment_Penalty__c, 
                                                           Stepdown_Prepayment_Period__c, YM_Prepayment_Penalty_Description__c, Deal_Intro_Sub_Source__c,
                                                           CAF_YSP__c, Referral_Source__c,Referral_Source__r.Name, Referral_Source_Contact__c, Referral_Source_Contact__r.Name, Account.Name, Account_Introduction_Source__c
        FROM Opportunity 
        WHERE Type = 'Term Loan'
		AND StageName = 'Closed Won'
		AND (Open_Period_Begins__c =: System.today() 
		OR Open_Period_Begins__c =: System.today().addMonths(12)
		OR Open_Period_Begins__c =: System.today().addMonths(9)
		OR Open_Period_Begins__c =: System.today().addMonths(6)
		OR Open_Period_Begins__c =: System.today().addMonths(3))
		AND Loan_in_Default__c	= false
		AND Account.In_Litigation__c = false
		AND Account.Do_Not_Lend__c = false
		AND Account.In_Foreclosure__c = false
		AND	Current_UPB__c > 0
        ]);
        system.debug('# of Deals'+myDeals.size());
        
        if(myDeals.size()>0){
           
            for(integer i=0;i < myDeals.size();i++){
                 system.debug('open period'+myDeals[i].Open_Period_Begins__c );
                
    date openPeriodDt = myDeals[i].Open_Period_Begins__c;
    date closeDateDt = myDeals[i].CloseDate;
                
    //for date format            
    String openPeriodDtString = myDeals[i].Open_Period_Begins__c ==null?' ':openPeriodDt.month()+'/'+openPeriodDt.day()+'/'+openPeriodDt.year();
    String closeDateDtString = myDeals[i].CloseDate==null?' ' : closeDateDt.month()+'/'+closeDateDt.day()+'/'+closeDateDt.year();

    String loanType =  myDeals[i].Type == null? ' ':myDeals[i].Type;      
    String originatorFirstName = myDeals[i].Owner.FirstName== null? ' ': myDeals[i].Owner.FirstName;
    String originatorLastName = myDeals[i].Owner.LastName== null? ' ': myDeals[i].Owner.LastName;
    String ymParPrepaymentPeriod = myDeals[i].YM_Prepayment_Penalty__c== null? ' ': myDeals[i].YM_Prepayment_Penalty__c;
    String stepdownPrepaymentPeriod = myDeals[i].Stepdown_Prepayment_Period__c== null? ' ': myDeals[i].Stepdown_Prepayment_Period__c;
    String stepdownPrepaymentPeriodDescription = myDeals[i].YM_Prepayment_Penalty_Description__c== null? ' ': myDeals[i].YM_Prepayment_Penalty_Description__c;                    
    String dealIntroSource= myDeals[i].Deal_Intro_Source__c == null? ' ': myDeals[i].Deal_Intro_Source__c;
    String dealIntroSubSource= myDeals[i].Deal_Intro_Sub_Source__c == null? ' ': myDeals[i].Deal_Intro_Sub_Source__c;              
    String cafYsp = myDeals[i].CAF_YSP__c == null? ' ': myDeals[i].CAF_YSP__c ;
    String referralSourceAccount = myDeals[i].Referral_Source__c== null? ' ': myDeals[i].Referral_Source__r.Name;
    String referralSourceContact = myDeals[i].Referral_Source_Contact__c== null? ' ': myDeals[i].Referral_Source_Contact__r.Name;
    String accountName = myDeals[i].Account.Name == null? ' ': myDeals[i].Account.Name ;                
    String accountIntroSource = myDeals[i].Account_Introduction_Source__c == null? ' ' : myDeals[i].Account_Introduction_Source__c;
                
                
    string originatorId = myDeals[i].Owner.IsActive == true? myDeals[i].OwnerId : myDeals[i].Account.Owner.Id; 
        
               
                    Task myTask = new Task();
                    myTask.OwnerId = originatorId;
                    myTask.Subject = 'Deal '+ myDeals[i].Name +' Open period starts on ' + openPeriodDtString;
                    myTask.WhatId = myDeals[i].Id;
                    myTask.Status = 'Open';
                    myTask.Type = 'Reminder';
                    myTasks.add(myTask);
                    
    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
    string toEmailAddresses = myDeals[i].Owner.IsActive == true? myDeals[i].Owner.Email:myDeals[i].Account.Owner.Email;
    message.toAddresses = new String[] { toEmailAddresses , 'nadeem.elsewehy@cvest.com' };
	message.setReplyTo('integrations@cvest.com');
	//message.setSenderDisplayName('Cvest Reminders');
	
    //set to true and uncomment line below to save email record            
    message.setSaveAsActivity(false);
    //message.setWhatId(myDeals[i].id);        
                
    message.subject = 'Deal '+ myDeals[i].Name +' Open period starts on ' + openPeriodDtString;
    	
    if ( owea.size() > 0 ) {
    message.setOrgWideEmailAddressId(owea.get(0).Id);
    					}
                    
                    
    message.plainTextBody = 'Hello,\n\n' + 
'This is an update regarding the Maturity Date for your deal.\n\n'+

'Deal: ' + myDeals[i].Name + '\n\n'+

'Loan Type: ' + loanType + '\n\n'+
        
'Originator: ' + originatorFirstName + ' ' + originatorLastName +'\n\n'+

'Close Date: ' + closeDateDtString + '\n\n'+

'Open Period Begins: '+ openPeriodDtString + '\n\n'+

'YM Par Prepayment Period: '+ ymParPrepaymentPeriod +'\n\n'+

'Stepdown Prepayment Period:' +stepdownPrepaymentPeriod +'\n\n'+

'Stepdown Prepayment Period Description: '+ stepdownPrepaymentPeriodDescription +'\n\n'+
                    
'Deal Intro Source: '+ dealIntroSource +'; ' + dealIntroSubSource +'\n\n'+

'CAF YSP: '+cafYsp+ '\n\n'+

'Referral Source Account: '+referralSourceAccount +'\n\n'+

'Referral Source Contact: ' + referralSourceContact +'\n\n'+

'Account Name: '+accountName +'\n\n'+
    
'Account Intro Source: '+ accountIntroSource;

    
	messages.add(message);
  

            }
        }
        if(myTasks.size()>0){
            insert myTasks;
            system.debug('# Tasks Created'+ myTasks.size());
        }
        
        if(messages.size()>0){
    Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
         system.debug('# emails Created'+ messages.size());

            
if (results[0].success) {
    System.debug('The email was sent successfully.');
} else {
    System.debug('The email failed to send: ' + results[0].errors[0].message);
}
        }


    
}
}