force-app/main/default/objects/Document_Validation__mdt/Document_Validation__mdt.object-meta.xml
<CustomObject>
    <label>Document Validation</label>
    <pluralLabel>Document Validations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Document_Validation__mdt/fields/Document_Structure__c.field-meta.xml
<CustomField>
    <fullName>Document_Structure__c</fullName>
    <label>Document Structure</label>
    <referenceTo>Document_Structure__mdt</referenceTo>
    <relationshipLabel>Document Validations</relationshipLabel>
    <relationshipName>Document_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/Loan_Fee__c.object-meta.xml
<CustomObject>
    <description>Fees associated to Loans</description>
    <label>Loan Fee</label>
    <nameField>
        <displayFormat>LF-{000000}</displayFormat>
        <label>Loan Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fee__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Deal associated with this fee</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property that this Fee is related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/Loan_Version__c.object-meta.xml
<CustomObject>
    <label>Loan Version</label>
    <nameField>
        <label>Loan Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Version__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Versions</relationshipLabel>
    <relationshipName>Loan_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Version__c/fields/Loan_Fees_JSON__c.field-meta.xml
<CustomField>
    <fullName>Loan_Fees_JSON__c</fullName>
    <label>Loan Fees JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Escrow_Company_text__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Company_text__c</fullName>
    <label>Escrow Company text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Insurance_Company_text__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_text__c</fullName>
    <label>Insurance Company text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/classes/LoanVersionTests.cls
@isTest
private class LoanVersionTests {
  static void setup() {
    Test_Helper.createRate();
    Test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createTermDeal(acc, cont);

    List<Property__c> property = new List<Property__c>();
    for (Integer i = 0; i < 20; i++) {
      property.add(
        new Property__c(
          Name = 'Test + ' + i,
          Deal__c = opp.Id,
          Escrow_Company_text__c = 'ESCROW',
          Insurance_Company_text__c = 'INSURANCE',
          RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE
              sobjecttype = 'Property__c'
              AND DeveloperName = 'Term_Loan'
          ]
          .Id
        )
      );
    }
    insert property;
  }

  static testMethod void triggerTest() {
    setup();

    Id opportunityId = [SELECT Id FROM Opportunity LIMIT 1].Id;

    Test.startTest();
    Loan_Version__c vers = new Loan_Version__c(
      Deal__c = opportunityId,
      Loan_FEEs_JSON__c = JSON.serialize(new List<Loan_Fee__c>())
    );

    insert vers;

    PageReference pageRef = Page.ScheduleOfLenderCostsPDF;
    Test.setCurrentPage(pageRef);

    scheduleOfLenderCostsPDFExtension controller = new scheduleOfLenderCostsPDFExtension(
      new ApexPages.StandardController(vers)
    );

    //scheduleOfLenderCostsPDFExtension.getPDFContent(vers.Id);

    Test.stopTest();
  }

  static testMethod void validatorTest() {
    Id docStructureId = [
      SELECT Id, Document_Structure__c
      FROM Document_Validation__mdt
      WHERE Document_Structure__c != NULL
      LIMIT 1
    ]
    .Document_Structure__c;

    LoanVersionValidatorController.initScreen(docStructureId);
  }
}