force-app/main/default/objects/Deal_x_Funding_Vehicle__c/Deal_x_Funding_Vehicle__c.object-meta.xml
<CustomObject>
    <description>This Object connects Funding Vehicles to Deals</description>
    <label>Deal to Funding Vehicle Connection</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal to Funding Vehicle Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal to Funding Vehicle Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_x_Funding_Vehicle__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal to Funding Vehicle Connections</relationshipLabel>
    <relationshipName>Deal_to_Funding_Vehicle_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_x_Funding_Vehicle__c/fields/Funding_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Vehicle</label>
    <referenceTo>Funding_Vehicle__c</referenceTo>
    <relationshipLabel>Deal to Funding Vehicle Connections</relationshipLabel>
    <relationshipName>Deal_to_Funding_Vehicle_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_x_Funding_Vehicle__c/fields/Include_Yes_No__c.field-meta.xml
<CustomField>
    <fullName>Include_Yes_No__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to include Deal in Securitization</description>
    <label>Include In Securitization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Vehicle__c/Funding_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Funding Vehicle</label>
    <nameField>
        <label>Funding Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Vehicle__c/fields/Securitization__c.field-meta.xml
<CustomField>
    <fullName>Securitization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Securitization</label>
    <referenceTo>Securitization__c</referenceTo>
    <relationshipLabel>Funding Vehicles</relationshipLabel>
    <relationshipName>Funding_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Securitization__c.field-meta.xml
<CustomField>
    <fullName>Securitization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Securitization</label>
    <referenceTo>Securitization__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Securitized__c.field-meta.xml
<CustomField>
    <fullName>Securitized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate the deal has been securitized in a portfolio</description>
    <label>Securitized?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Securitization__c/Securitization__c.object-meta.xml
<CustomObject>
    <label>Securitization</label>
    <nameField>
        <label>Securitization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securitizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Securitization__c/fields/Funding_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Vehicle</label>
    <referenceTo>Funding_Vehicle__c</referenceTo>
    <relationshipLabel>Securitizations</relationshipLabel>
    <relationshipName>Securitizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DealXFundingVehicleHelper.cls
public without sharing class DealXFundingVehicleHelper {

  public static void beforeInsert(List<Deal_x_Funding_Vehicle__c> newList) {

    // Set<Id> fvIdsToCheck = new Set<Id>();

    for (Deal_x_Funding_Vehicle__c x : newList) {
      if(!x.Include_Yes_No__c) {
        // fvIdsToCheck.add(x.Funding_Vehicle__c);
      }
    }
  
    // Set<Id> fvSecIds = filterForSecuritizations(fvIdsToCheck);

    // for (Deal_x_Funding_Vehicle__c x : newList) {
    //   if(!x.Include_Yes_No__c && fvSecIds.contains(x.Funding_Vehicle__c)) {
    //     x.Include_Yes_No__c = true;
    //   }
    // }


  }

  public static void afterUpdate(
    Map<Id, Deal_x_Funding_Vehicle__c> oldMap,
    List<Deal_x_Funding_Vehicle__c> newList
  ) {
    Map<Id, Boolean> toggledDeals = new Map<Id, Boolean>();
    List<Id> toggledFundingVehicles = new List<Id>();

    for (Deal_x_Funding_Vehicle__c n : newList) {
      Deal_x_Funding_Vehicle__c o = oldMap.get(n.Id);
      if (
        n.Funding_Vehicle__c != null &&
        n.Deal__c != null &&
        o.Include_Yes_No__c !=
        n.Include_Yes_No__c
      ) {
        toggledFundingVehicles.add(n.Funding_Vehicle__c);
        toggledDeals.put(n.Deal__c, n.Include_Yes_No__c);
      }
    }

    if (toggledDeals.size() > 0 && toggledFundingVehicles.size() > 0) {
      toggleDealSecuritisation(toggledDeals, toggledFundingVehicles);
    }
  }

  public static void toggleDealSecuritisation(
    Map<Id, Boolean> dealToggledMap,
    List<Id> fvIds
  ) {
    Map<Id, Securitization__c> securitizationMap = new Map<Id, Securitization__c>(
      [
        SELECT Id
        FROM Securitization__c
        WHERE
          Id IN (
            SELECT Securitization__c
            FROM Funding_Vehicle__c
            WHERE Id IN :fvIds
          )
      ]
    );

    if (securitizationMap.size() > 0) {
      List<Opportunity> updatedDeals = new List<Opportunity>();

      for (Opportunity o : [
        SELECT Id, Securitization__c
        FROM Opportunity
        WHERE
          Id IN :dealToggledMap.keySet()
          AND Securitization__c IN :securitizationMap.keySet()
      ]) {
        o.Securitized__c = dealToggledMap.get(o.Id);
        // o.Securitization__c = null;
        updatedDeals.add(o);
      }

      if (updatedDeals.size() > 0) {
        update updatedDeals;
      }
    }
  }
  
  public static Set<Id> filterForSecuritizations(Set<Id> fvIds) {
    Map<Id, Funding_Vehicle__c> fvMap = new Map<Id, Funding_Vehicle__c>([
      SELECT Id
      FROM Funding_Vehicle__c
      WHERE Securitization__c != NULL
      AND Id IN :fvIds
    ]);

    return fvMap.keySet();
  }
}