force-app/main/default/objects/Deal_x_Funding_Vehicle__c/Deal_x_Funding_Vehicle__c.object-meta.xml
<CustomObject>
    <description>This Object connects Funding Vehicles to Deals</description>
    <label>Deal to Funding Vehicle Connection</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal to Funding Vehicle Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal to Funding Vehicle Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_x_Funding_Vehicle__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal to Funding Vehicle Connections</relationshipLabel>
    <relationshipName>Deal_to_Funding_Vehicle_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_x_Funding_Vehicle__c/fields/Funding_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Vehicle</label>
    <referenceTo>Funding_Vehicle__c</referenceTo>
    <relationshipLabel>Deal to Funding Vehicle Connections</relationshipLabel>
    <relationshipName>Deal_to_Funding_Vehicle_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Vehicle__c/Funding_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Funding Vehicle</label>
    <nameField>
        <label>Funding Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Vehicle__c/fields/Funding_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Vehicle_Type__c</fullName>
    <label>Funding Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Securitization</fullName>
            </value>
            <value>
                <fullName>Warehouse Line</fullName>
                <default>true</default>
                <label>Warehouse Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Vehicle__c/fields/Securitization__c.field-meta.xml
<CustomField>
    <fullName>Securitization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Securitization</label>
    <referenceTo>Securitization__c</referenceTo>
    <relationshipLabel>Funding Vehicles</relationshipLabel>
    <relationshipName>Funding_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Vehicle__c/recordTypes/Securitization.recordType-meta.xml
<RecordType>
    <fullName>Securitization</fullName>
    <active>true</active>
    <label>Securitization</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Securitization__c.field-meta.xml
<CustomField>
    <fullName>Securitization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Securitization</label>
    <referenceTo>Securitization__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Securitized__c.field-meta.xml
<CustomField>
    <fullName>Securitized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate the deal has been securitized in a portfolio</description>
    <label>Securitized?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Securitization__c/Securitization__c.object-meta.xml
<CustomObject>
    <label>Securitization</label>
    <nameField>
        <label>Securitization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securitizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Securitization__c/fields/Funding_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Vehicle</label>
    <referenceTo>Funding_Vehicle__c</referenceTo>
    <relationshipLabel>Securitizations</relationshipLabel>
    <relationshipName>Securitizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Securitization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this Securitization</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SecuritizationHelper.cls
public with sharing class SecuritizationHelper {
  public static final Map<String, Id> RT_MAP = queryRecordTypeMap();

  public static void beforeInsert(List<Securitization__c> newList) {
    // for (Securitization__c sec : newList) {
    //   Funding_Vehicle__c fv = new Funding_Vehicle__c();
    //   fv.Name = sec.Name;
    //   fv.Funding_Vehicle_Type__c = 'Securitization';
    //   fv.RecordTypeId = recordTypeMap.get('Securitization');
    //   fv.Securitization__c = sec.Id;
    //   insert fv;
    // response.put('fvId', fv.Id);
    //   sec.Funding_Vehicle__c = fv.Id;
    //   update sec;
  }

  public static void afterInsert(List<Securitization__c> newList) {
    createRelatedFundingVehicles(newList);
  }

  public static void afterUpdate(
    Map<Id, Securitization__c> oldMap,
    List<Securitization__c> newList
  ) {
    Map<Id, Securitization__c> secMap = new Map<Id, Securitization__c>();

    for (Securitization__c sec : newList) {
      Securitization__c oldSec = oldMap.get(sec.Id);
      if (
        (oldSec.Status__c != sec.Status__c && sec.Status__c == 'Redeemed') ||
        (sec.Status__c == 'Pending' &&
        oldSec.Close_Date__c != sec.Close_Date__c
        && sec.Close_Date__c != null)
      ) {
        secMap.put(sec.Id, sec);
      }
    }

    if (secMap.size() > 0) {
      updateFundingVehicleCnx(secMap);
    }
  }

  public static void updateFundingVehicleCnx(
    Map<Id, Securitization__c> secMap
  ) {
    Set<Id> dealsToUpdate = new Set<Id>();
    List<Deal_x_Funding_Vehicle__c> dfvs = [
      SELECT Id, End_Date__c, Deal__c, Funding_Vehicle__r.Securitization__c
      FROM Deal_x_Funding_Vehicle__c
      WHERE Funding_Vehicle__r.Securitization__c IN :secMap.keySet()
    ];

    for (Deal_x_Funding_Vehicle__c d : dfvs) {
      Securitization__c sec = secMap.get(d.Funding_Vehicle__r.Securitization__c);

      if (sec.Status__c == 'Pending') {
        d.Start_Date__c = sec.Close_Date__c;
      } else if (sec.Status__c == 'Redeemed') {
        d.End_Date__c = (Date) System.today();
        dealsToUpdate.add(d.Deal__c);
      }
    }

    update dfvs;
    updateDeals(dealsToUpdate);
  }

  public static void updateDeals(Set<Id> dealIds) {
    List<Opportunity> updDeals = new List<Opportunity>();

    for (Id id : dealIds) {
      updDeals.add(
        new Opportunity(
          Id = id,
          Securitization__c = null,
          Securitized__c = false
        )
      );
    }

    update updDeals;
  }

  public static Map<String, Id> queryRecordTypeMap() {
    Map<String, Id> recordTypeMap = new Map<String, Id>();

    for (RecordType rt : [
      SELECT Id, DeveloperName
      FROM RecordType
      WHERE Sobjecttype = 'Funding_Vehicle__c'
    ]) {
      recordTypeMap.put(rt.DeveloperName, rt.Id);
    }

    return recordTypeMap;
  }

  public static void createRelatedFundingVehicles(
    List<Securitization__c> newList
  ) {
    List<Funding_Vehicle__c> fvList = new List<Funding_Vehicle__c>();

    for (Securitization__c sec : newList) {
      Funding_Vehicle__c fv = new Funding_Vehicle__c();
      fv.Name = sec.Name;
      fv.Funding_Vehicle_Type__c = 'Securitization';
      fv.RecordTypeId = RT_MAP.get('Securitization');
      fv.Securitization__c = sec.Id;
      fvList.add(fv);
    }

    insert fvList;
  }
}