force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Loan Application Entity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Portal Access</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>EscrowAgent</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>TitleCompany</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/Loan_Fee__c.object-meta.xml
<CustomObject>
    <description>Fees associated to Loans</description>
    <label>Loan Fee</label>
    <nameField>
        <displayFormat>LF-{000000}</displayFormat>
        <label>Loan Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fee__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Deal associated with this fee</description>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Deal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Deal Contact</label>
    <referenceTo>Deal_Contact__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The Amount of this Fee</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Property that this Fee is related to</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Reference Number for this Fee</description>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Fee__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vendor this fee is paid to</description>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Active_States__c.field-meta.xml
<CustomField>
    <fullName>Active_States__c</fullName>
    <description>Bridge Use</description>
    <inlineHelpText>States that the Properties reside in</inlineHelpText>
    <label>Active States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BridgeICMemoControllerTest.cls
@isTest
private class BridgeICMemoControllerTest {

    static TestMethod void testMethod1(){
        test_Helper.createDealLoanNumber();
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity opp = test_Helper.createOpportunity( acc, cont );
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'LOC_Loan' and sobjecttype = 'Opportunity'].Id;
        List<Property__c> properties = test_Helper.createProperties(opp);
		
		Loan_Fee__c Loan_Fee=new Loan_Fee__c
		(
			Deal__c=opp.Id,
			Fee_Amount__c=1000,
			Reference__c='121212',
			vendor__c=acc.Id
		);

        Test.startTest();
            BridgeICMemoController obj=new BridgeICMemoController();
			obj.filtersJSON='{"dealId":"'+opp.Id+'","fundingDate2":"2018-03-31","originationfeepercentage":0,"yearSwapRate":0,"installmentcomment":"1111111111","creditSpread":0,"InterestRateTermSheet":0,"InterestRateRateLock":0,"stubInterestDayCount":11,"debtreserve":null,"stubInterest":"10694.37","CorevestProceeds":"5539010.13","cfcorevestpurchaser":"2","taxentry":"11","TotalSources":"5620350.00","totalLender":"81339.87","capexentry":"11","insuranceentry":"11","tax":"0.92","capex":"0.92","totalthirdparty":63000,"insurence":"0.92","totalreserves":33,"netproceedstoborrower":5475977.13,"totaluses":5620350,"reservetax":"1","totalreservetax":"11.00","totalreserveinsurance":"11.00","totalreservecapex":"11.00","rateType":"2","reserveinsurance":"1","reservecapex":"1","titlewiringinstructions":"1111111111111"}';
			obj.getData();
			BridgeICMemoController.getUrlAndInstance();
        Test.stopTest();
    }
    
    static TestMethod void testMethodSuccess(){
        test_Helper.createDealLoanNumber();
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity opp = test_Helper.createOpportunity( acc, cont );
        opp.Active_States__c='California;Richmond';
        update opp;
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'LOC_Loan' and sobjecttype = 'Opportunity'].Id;
        
        insert new deal_contact__c(deal__c=opp.Id, Contact__c=cont.Id, entity_type__c ='Sponsor');
        insert new deal_contact__c(deal__c=opp.Id, Contact__c=cont.Id, entity_type__c ='Guarantor');
        List<Property__c> properties = test_Helper.createProperties(opp);
		Loan_Fee__c Loan_Fee=new Loan_Fee__c
		(
			Deal__c=opp.Id,
			Fee_Amount__c=1000,
			Reference__c='121212',
			vendor__c=acc.Id
		);

        Test.startTest();
            BridgeICMemoController obj=new BridgeICMemoController();
			obj.filtersJSON='{"dealId":"'+opp.Id+'","fundingDate2":"2018-03-31","originationfeepercentage":0,"yearSwapRate":0,"installmentcomment":"1111111111","creditSpread":0,"InterestRateTermSheet":0,"InterestRateRateLock":0,"stubInterestDayCount":11,"debtreserve":null,"stubInterest":"10694.37","CorevestProceeds":"5539010.13","cfcorevestpurchaser":"2","taxentry":"11","TotalSources":"5620350.00","totalLender":"81339.87","capexentry":"11","insuranceentry":"11","tax":"0.92","capex":"0.92","totalthirdparty":63000,"insurence":"0.92","totalreserves":33,"netproceedstoborrower":5475977.13,"totaluses":5620350,"reservetax":"1","totalreservetax":"11.00","totalreserveinsurance":"11.00","totalreservecapex":"11.00","rateType":"2","reserveinsurance":"1","reservecapex":"1","titlewiringinstructions":"1111111111111"}';
			obj.getData();
        	BridgeICMemoController.getData(opp.Id);
			BridgeICMemoController.getUrlAndInstance();
        Test.stopTest();
    }
    
    static TestMethod void testMethodFail(){
        Test.startTest();
        BridgeICMemoController obj=new BridgeICMemoController();
        obj.filtersJSON='{"dealId":"1234","fundingDate2":"2018-03-31","originationfeepercentage":0,"yearSwapRate":0,"installmentcomment":"1111111111","creditSpread":0,"InterestRateTermSheet":0,"InterestRateRateLock":0,"stubInterestDayCount":11,"debtreserve":null,"stubInterest":"10694.37","CorevestProceeds":"5539010.13","cfcorevestpurchaser":"2","taxentry":"11","TotalSources":"5620350.00","totalLender":"81339.87","capexentry":"11","insuranceentry":"11","tax":"0.92","capex":"0.92","totalthirdparty":63000,"insurence":"0.92","totalreserves":33,"netproceedstoborrower":5475977.13,"totaluses":5620350,"reservetax":"1","totalreservetax":"11.00","totalreserveinsurance":"11.00","totalreservecapex":"11.00","rateType":"2","reserveinsurance":"1","reservecapex":"1","titlewiringinstructions":"1111111111111"}';
        obj.getData();
        
        BridgeICMemoController.WrapperData wd=new BridgeICMemoController.WrapperData();
            
        wd.annualincomeyear='1000';
        wd.annualincome='1000';
        wd.repeatborrower='1000';
        wd.recourse='1000';
        wd.glcapproveddate='1000';
        wd.fundedborrower='1000';
        wd.deliquencyhistory='1000';
        wd.valuepsf='1000';
        wd.valueperunit='1000';
        wd.sponsorcostpsf='1000';
        wd.sponsorcpu='1000';
        wd.loanpsf='1000';
        wd.loanperunit='1000';
        
        Test.stopTest();
    }
}