force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact_Type__c</fullName>
    <label>Deal Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Active_States__c.field-meta.xml
<CustomField>
    <fullName>Active_States__c</fullName>
    <description>Bridge Use</description>
    <inlineHelpText>States that the Properties reside in</inlineHelpText>
    <label>Active States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Advance_Period__c.field-meta.xml
<CustomField>
    <fullName>Advance_Period__c</fullName>
    <description>Bridge Use</description>
    <label>Advance Period Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Term__c.field-meta.xml
<CustomField>
    <fullName>LOC_Term__c</fullName>
    <businessOwnerGroup>Bridge_Ops</businessOwnerGroup>
    <description>Bridge Use</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>15 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>21 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>30 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>540 Days</fullName>
            </value>
            <value>
                <fullName>630 Days</fullName>
            </value>
            <value>
                <fullName>720 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maturity_Date_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date_Calculation_Type__c</fullName>
    <description>This controls when the Loan Maturity Date is set</description>
    <inlineHelpText>This controls when the Loan Maturity Date is set</inlineHelpText>
    <label>Maturity Date Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed at Closing</fullName>
            </value>
            <value>
                <fullName>Fixed at First Advance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Project_Strategy__c</fullName>
    <description>Bridge Use - Multifamily Light Lift: renovation loan is less than 50% of purchase price, Multifamily Heavy Lift: renovation loan is more than 50% of purchase price, Multifamily Lease-Up/No Rehab: no renovation funds given, Conversion to Multifamily: Converting a property into MF, Multifamily GUC: ground up construction for MF properties</description>
    <label>Project Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Fix and Flip</fullName>
            </value>
            <value>
                <fullName>Renovate and Rent</fullName>
            </value>
            <value>
                <fullName>Portfolio Acquisition</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Multifamily Light Lift</fullName>
            </value>
            <value>
                <fullName>Multifamily Heavy Lift</fullName>
            </value>
            <value>
                <fullName>Multifamily Lease-Up/No Rehab</fullName>
            </value>
            <value>
                <fullName>Conversion to Multifamily</fullName>
            </value>
            <value>
                <fullName>Multifamily GUC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reno_Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Reno_Funding_Type__c</fullName>
    <description>Bridge Use</description>
    <inlineHelpText>&quot;Reserves&quot; - The Reno Advance is sent to the Servicer and disbursed.  Sometimes this is referred to as a Dutch Loan. || 
&quot;Advances&quot; - CoreVest disburses the Reno Advance Fundings</inlineHelpText>
    <label>Reno Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Renovation_Funding__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advances</fullName>
            </value>
            <value>
                <fullName>Reserves</fullName>
            </value>
            <value>
                <fullName>Advances/Reserves</fullName>
                <isActive>false</isActive>
                <label>Advances/Reserves</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renovation_Funding__c.field-meta.xml
<CustomField>
    <fullName>Renovation_Funding__c</fullName>
    <description>Indicates if CoreVest will be funding the Renovation</description>
    <inlineHelpText>Indicates if CoreVest will be funding the Renovation</inlineHelpText>
    <label>Renovation Funding</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Sub_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stated_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Stated_Maturity_Date__c</fullName>
    <description>The Original Stated Loan Level Maturity Date</description>
    <inlineHelpText>The Original Stated Loan Level Maturity Date</inlineHelpText>
    <label>Original Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/classes/AdvanceDealTriggerTest.cls
@isTest
private class AdvanceDealTriggerTest {
  @TestVisible
  private static string statusValid = 'Completed';
  @TestVisible
  private static string statusInvalid = 'Pending';
  @isTest
  static void advanceDealTriggerTestInsert() {
    Test_Helper.createRate();
    Test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    Contact testContact = new Contact();
    testContact.FirstName = 'Test';
    testContact.LastName = 'Contact';
    testContact.Email = 'logins+cvest@mkpartners.com';
    testContact.AccountId = acc.Id;

    insert testContact;

    Opportunity testDeal = new Opportunity();
    testDeal.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
    ]
    .Id;
    testDeal.LOC_Loan_Type__c = 'Credit Line';
    testDeal.Active_States__c = 'Iowa;Ohio';
    testDeal.Product_Sub_Type__c = 'Renovation';
    testDeal.Renovation_Funding__c = 'Yes';
    testDeal.Reno_Funding_Type__c = 'Advances';
    testDeal.Project_Strategy__c = 'Renovate and Rent';
    testDeal.Name = 'Test Deal';
    testDeal.StageName = 'Loan Processing';
    testDeal.Contact__c = testContact.Id;
    testDeal.CloseDate = Date.today();
    testDeal.AccountId = acc.Id;
    testDeal.Stated_Maturity_Date__c = null;

    insert testDeal;

    //very picky picklist
    testDeal.Maturity_Date_Calculation_Type__c = 'Fixed at First Advance';

    update testDeal;

    testDeal.Advance_Period__c = 365;
    testDeal.LOC_Term__c = '540 Days';

    update testDeal;

    Deal_Contact__c testDealContact = new Deal_Contact__c(
      Contact__c = testContact.Id,
      Deal_Contact_Type__c = 'Individual',
      Entity_Type__c = 'Guarantor',
      Deal__c = testDeal.Id
    );

    insert testDealContact;

    Advance__c testAdvance = new Advance__c();
    testAdvance.Status__c = statusValid;
    testAdvance.Deal__c = testDeal.Id;
    testAdvance.Wire_Date__c = Date.today();
    testAdvance.Closing_Funds_Checklist__c = true;
    testAdvance.Manager_Approved__c = true;
    testAdvance.Evidence_of_Insurance_Approved__c = true;
    testAdvance.Flood_Certificate_Approved__c = true;

    Test.startTest();
    insert testAdvance;
    Integer emailInvocations = Limits.getEmailInvocations();
    Test.stopTest();

    Date expirationDate = Date.today().addDays(365);
    Date matDate = Date.today().addDays(540);

    Opportunity updatedDeal = [
      SELECT
        Id,
        Modified_Expiration_Date__c,
        Stated_Maturity_Date__c,
        Updated_Loan_Maturity_Date__c
      FROM Opportunity
      WHERE Id = :testDeal.Id
      LIMIT 1
    ];

    System.assertEquals(1, emailInvocations, 'An email should be sent.');

    System.assertEquals(
      matDate,
      updatedDeal.Stated_Maturity_Date__c,
      'Stated Maturity date should match'
    );
    System.assertEquals(
      matDate,
      updatedDeal.Updated_Loan_Maturity_Date__c,
      'Updated Loan Maturity date should match'
    );
    System.assertEquals(
      expirationDate,
      updatedDeal.Modified_Expiration_Date__c,
      'Expiration date should match'
    );
  }

  @isTest
  static void advanceDealTriggerTestUpdatePass() {
    Test_Helper.createRate();
    Test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    Contact testContact = new Contact();
    testContact.FirstName = 'Test';
    testContact.LastName = 'Contact';
    testContact.Email = 'logins+cvest@mkpartners.com';
    testContact.AccountId = acc.Id;

    insert testContact;

    Opportunity testDeal = new Opportunity();
    testDeal.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
    ]
    .Id;
    testDeal.LOC_Loan_Type__c = 'Credit Line';
    testDeal.Active_States__c = 'Iowa;Ohio';
    testDeal.Product_Sub_Type__c = 'Renovation';
    testDeal.Renovation_Funding__c = 'Yes';
    testDeal.Reno_Funding_Type__c = 'Advances';
    testDeal.Project_Strategy__c = 'Renovate and Rent';
    testDeal.Name = 'Test Deal';
    testDeal.StageName = 'Loan Processing';
    testDeal.Contact__c = testContact.Id;
    testDeal.CloseDate = Date.today();
    testDeal.AccountId = acc.Id;
    testDeal.Stated_Maturity_Date__c = null;

    insert testDeal;

    //very picky picklist
    testDeal.Maturity_Date_Calculation_Type__c = 'Fixed at First Advance';

    update testDeal;

    testDeal.Advance_Period__c = 365;
    testDeal.LOC_Term__c = '540 Days';

    update testDeal;

    Deal_Contact__c testDealContact = new Deal_Contact__c(
      Contact__c = testContact.Id,
      Deal_Contact_Type__c = 'Individual',
      Entity_Type__c = 'Guarantor',
      Deal__c = testDeal.Id
    );

    insert testDealContact;

    Advance__c testAdvance = new Advance__c();
    testAdvance.Status__c = statusInvalid;
    testAdvance.Deal__c = testDeal.Id;
    testAdvance.Wire_Date__c = Date.today();
    testAdvance.Closing_Funds_Checklist__c = true;
    testAdvance.Manager_Approved__c = true;
    testAdvance.Evidence_of_Insurance_Approved__c = true;
    testAdvance.Flood_Certificate_Approved__c = true;

    insert testAdvance;

    Advance__c updatedAdvance = new Advance__c();
    updatedAdvance.Id = testAdvance.Id;
    updatedAdvance.Status__c = statusValid;

    Test.startTest();
    update updatedAdvance;
    Integer emailInvocations = Limits.getEmailInvocations();
    Test.stopTest();

    Date expirationDate = Date.today().addDays(365);
    Date matDate = Date.today().addDays(540);

    Opportunity updatedDeal = [
      SELECT
        Id,
        Modified_Expiration_Date__c,
        Stated_Maturity_Date__c,
        Updated_Loan_Maturity_Date__c
      FROM Opportunity
      WHERE Id = :testDeal.Id
      LIMIT 1
    ];

    System.assertEquals(1, emailInvocations, 'An email should be sent.');

    System.assertEquals(
      expirationDate,
      updatedDeal.Modified_Expiration_Date__c,
      'Expiration date should match'
    );
    System.assertEquals(
      matDate,
      updatedDeal.Stated_Maturity_Date__c,
      'Stated Maturity date should match'
    );
    System.assertEquals(
      matDate,
      updatedDeal.Updated_Loan_Maturity_Date__c,
      'Updated Loan Maturity date should match'
    );
  }

  @isTest
  static void advanceDealTriggerTestUpdateFail() {
    Test_Helper.createRate();
    Test_Helper.createDealLoanNumber();
    Contact testContact = new Contact();
    testContact.FirstName = 'Test';
    testContact.LastName = 'Contact';

    insert testContact;

    Opportunity testDeal = new Opportunity();
    testDeal.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
    ]
    .Id;
    testDeal.LOC_Loan_Type__c = 'Credit Line';
    testDeal.Active_States__c = 'Iowa;Ohio';
    testDeal.Product_Sub_Type__c = 'Renovation';
    testDeal.Renovation_Funding__c = 'Yes';
    testDeal.Reno_Funding_Type__c = 'Advances';
    testDeal.Project_Strategy__c = 'Renovate and Rent';
    testDeal.Name = 'Test Deal';
    testDeal.StageName = 'Loan Processing';
    testDeal.Contact__c = testContact.Id;
    testDeal.CloseDate = Date.today();
    testDeal.Stated_Maturity_Date__c = null;

    insert testDeal;

    //very picky picklist
    testDeal.Maturity_Date_Calculation_Type__c = 'Fixed at First Advance';

    update testDeal;

    testDeal.Advance_Period__c = 365;
    testDeal.LOC_Term__c = '540 Days';

    update testDeal;

    Advance__c testAdvance = new Advance__c();
    testAdvance.Status__c = statusInvalid;
    testAdvance.Deal__c = testDeal.Id;
    testAdvance.Wire_Date__c = Date.today();

    insert testAdvance;

    Test.startTest();
    update testAdvance;
    Integer emailInvocations = Limits.getEmailInvocations();
    Test.stopTest();

    Date expirationDate = Date.today().addDays(365);
    Date matDate = Date.today().addDays(540);

    Opportunity updatedDeal = [
      SELECT
        Id,
        Modified_Expiration_Date__c,
        Stated_Maturity_Date__c,
        Updated_Loan_Maturity_Date__c
      FROM Opportunity
      WHERE Id = :testDeal.Id
      LIMIT 1
    ];

    System.assertEquals(0, emailInvocations, 'An email should not be sent.');

    System.assertNotEquals(
      expirationDate,
      updatedDeal.Modified_Expiration_Date__c,
      'Expiration date should not match'
    );
    System.assertNotEquals(
      matDate,
      updatedDeal.Stated_Maturity_Date__c,
      'Stated Maturity date should not match'
    );
    System.assertNotEquals(
      matDate,
      updatedDeal.Updated_Loan_Maturity_Date__c,
      'Updated Loan Maturity date should not match'
    );
  }
}