force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Loan Application Entity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Portal Access</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>EscrowAgent</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>TitleCompany</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/emailMessage_Helper.cls
public class emailMessage_Helper {

    public static Map<String, Schema.SObjectField> FIELD_MAP = Schema.SObjectType.EmailMessage.fields.getMap();

    /**
    * @name beforeInsert
    * @description
    * @param
    **/
    //public static void beforeInsert(List<EmailMessage> newList){
    //    for ( Integer i=0;i<newList.size();i++ ){

    //    }
    //}

    /**
    * @name afterInsert
    * @description
    * @param
    **/
    public static void afterInsert(List<EmailMessage> newList){
        //Set<Id> oppIds = new Set<Id>();
        //for ( EmailMessage e : newList){
        //    if(e.Subject == 'Welcome Email' && e.RelatedToId != null &&  e.RelatedToId.getSobjectType() == Schema.Opportunity.SObjectType ){
        //        oppIds.add(e.relatedToId);
        //    }
        //}

        //for(EmailMessage e : newList){

        //}

        //system.debug(oppIds);

        //Set<Id> contactIds = new Set<Id>();
        //for(Opportunity o : [SELECT Id, Contact__c, (SELECT Id, Contact__c FROM Deal_Contacts__r WHERE Contact__c != null AND Entity_Type__c='Portal Access') FROM Opportunity WHERE Id IN : oppIds]){
        //    system.debug(o);
        //    contactIds.add(o.Contact__c);
        //    if(o.Deal_Contacts__r != null){
        //        for(Deal_Contact__c c : o.Deal_Contacts__r){
        //            contactIds.add(c.Contact__c);
        //        }
        //    }
        //}

        //system.debug(contactIds);

        //List<User> portalUsers = new List<User>();
        //Profile p = [SELECT Id FROM Profile WHERE Name = 'Customer Portal User' LIMIT 1];

        //for(User u : [SELECT Id, ContactId FROM User WHERE ContactId IN : contactIds]){
        //    contactIds.remove(u.ContactId);
        //}

        //for(Contact c : [SELECT Id, Email, FirstName, LastName FROM Contact WHERE Id IN : contactIds]){
        //    User u = new User(ContactId=c.Id, username = c.Email, firstName = c.FirstName, lastName = c.LastName, email=c.Email, 
        //                        communityNIckName = c.LastName + '_' + c.FirstName, alias = string.valueof(c.FirstName.substring(0,1) + c.LastName.substring(0,1)), 
        //                        profileid = p.Id, emailencodingkey='UTF-8', languagelocalekey='en_US', localesidkey='en_US', timezonesidkey='America/Los_Angeles');

        //    portalUsers.add(u);
            

        //}

        //system.debug(portalUsers);

        //Database.DMLOptions dlo = new Database.DMLOptions();
        //    dlo.EmailHeader.triggerUserEmail = true;

        //    List<Database.saveResult> sr = Database.Insert(portalUsers, dlo);



    }

    /**
    * @name beforeUpdate
    * @description
    * @param
    **/
    //public static void beforeUpdate(List<EmailMessage> newList, List<EmailMessage> oldList){
    //    for ( Integer i=0;i<newList.size();i++ ){

    //    }
    //}

    /**
    * @name afterUpdate
    * @description
    * @param
    **/
    //public static void afterUpdate(List<EmailMessage> newList, List<EmailMessage> oldList){
    //    for ( Integer i=0;i<newList.size();i++ ){

    //    }
    //}

    /**
    * @name beforeDelete
    * @description
    * @param
    **/
    //public static void beforeDelete(List<EmailMessage> newList){
    //    for ( Integer i=0;i<newList.size();i++ ){

    //    }
    //}

    /**
    * @name afterDelete
    * @description
    * @param
    **/
    //public static void afterDelete(List<EmailMessage> newList, List<EmailMessage> oldList){
    //    for ( Integer i=0;i<newList.size();i++ ){

    //    }
    //}

    /**
    * @name afterUndelete
    * @description
    * @param
    **/
    //public static void afterUndelete(List<EmailMessage> oldList){
    //    for ( Integer i=0;i<oldList.size();i++ ){

    //    }
    //}

}