force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Loan Application Entity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Contact_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Pledgor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Portal Access</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>EscrowAgent</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>TitleCompany</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/Document_Information__c.object-meta.xml
<CustomObject>
    <description>Deal Document Information / Loan Status Tab etc...</description>
    <label>Document Information</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Document Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Information__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Information</relationshipLabel>
    <relationshipName>Document_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Doc_String__c.field-meta.xml
<CustomField>
    <fullName>Doc_String__c</fullName>
    <label>Doc String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Exclude_from_Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Loan_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude from Loan Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/External_Comments__c.field-meta.xml
<CustomField>
    <fullName>External_Comments__c</fullName>
    <label>External Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Folder__c.field-meta.xml
<CustomField>
    <fullName>Folder__c</fullName>
    <label>Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Is_Portal_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Portal_User__c</fullName>
    <formula>!ISBLANK( $User.ContactId )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Portal User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Bridge Product Type from the Deal.  Used in Apex</description>
    <formula>TEXT(Deal__r.LOC_Loan_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Bridge Product Type from the Deal.  Used in Apex</inlineHelpText>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Record Type of the Deal.  Used in Apex</description>
    <formula>Deal__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Required_for_Clear_to_Close__c.field-meta.xml
<CustomField>
    <fullName>Required_for_Clear_to_Close__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required for Clear to Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Information__c/fields/Set_to_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Set_to_Defaults__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <defaultValue>false</defaultValue>
    <description>This will set the Document Information settings to the default controlled by the Custom Meta Data Doc Structure</description>
    <label>Set to Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/Document_Structure__mdt.object-meta.xml
<CustomObject>
    <label>Document Structure</label>
    <pluralLabel>Document Structures</pluralLabel>
</CustomObject>

force-app/main/default/objects/Document_Structure__mdt/fields/Additional_Borrower_Checklist_Filtering__c.field-meta.xml
<CustomField>
    <fullName>Additional_Borrower_Checklist_Filtering__c</fullName>
    <label>Additional_Borrower Checklist Filtering</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/fields/C2C_Required_Filtering__c.field-meta.xml
<CustomField>
    <fullName>C2C_Required_Filtering__c</fullName>
    <label>C2C Required Filtering</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/fields/Default_Exclude_from_Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Default_Exclude_from_Loan_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Exclude from Loan Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/fields/Folder_Structure_String__c.field-meta.xml
<CustomField>
    <fullName>Folder_Structure_String__c</fullName>
    <label>Folder Structure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Structure__mdt/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>RecordType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LOC_Loan</fullName>
            </value>
            <value>
                <fullName>Term_Loan</fullName>
            </value>
            <value>
                <fullName>Single_Asset_Bridge_Loan</fullName>
            </value>
            <value>
                <fullName>Single_Asset_Loan</fullName>
            </value>
            <value>
                <fullName>Acquired_SAB_Loan_Active</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Investor_DSCR</fullName>
            </value>
            <value>
                <fullName>Term</fullName>
                <isActive>false</isActive>
                <label>Term</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>IF(  
 CONTAINS(RecordType.DeveloperName, &apos;LOC&apos;),
 &apos;Bridge&apos;,
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Term&apos;), 
 &apos;Term&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Loan&apos;), 
 &apos;Single Asset Rental&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Investor_DSCR&apos;), 
 &apos;Investor DSCR&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Bridge&apos;), 
 &apos;Bridge&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Acquired_Bridge_Loan&apos;), 
 &apos;Acquired Bridge Loan&apos;, 
 &apos;&apos;
 ) 
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Single_Asset_Bridge_Loan.recordType-meta.xml
<RecordType>
    <fullName>Single_Asset_Bridge_Loan</fullName>
    <active>true</active>
    <businessProcess>SAB Process</businessProcess>
    <label>Single Asset Bridge Loan</label>
</RecordType>

force-app/main/default/classes/DocumentInformationHelper.cls
public without sharing class DocumentInformationHelper {
  public static void beforeInsert(List<Document_Information__c> newList) {
    Map<String, Map<String, List<Document_Information__c>>> docInfoMap = new Map<String, Map<String, List<Document_Information__c>>>();

    for (Integer i = 0; i < newList.size(); i++) {
      if (String.isNotBlank(newList[i].Doc_String__c)) {
        List<String> splitString = newList[i].Doc_String__c.split('\\|');
        newList[i].Folder__c = splitString[0].replace(';', ' - ');
        if (splitString.size() > 1) {
          newList[i].Document_Type__c = splitString[1];
        }

        String recordType = newList[i].RecordType__c;
        if (
          recordType.contains('Bridge') &&
          recordType != 'Single_Asset_Bridge_Loan'
        ) {
          recordType = 'LOC_Loan';
        }

        if (!docInfoMap.containsKey(recordType)) {
          docInfoMap.put(
            recordType,
            new Map<String, List<Document_Information__c>>()
          );
        }

        if (!docInfoMap.get(recordType).containsKey(newList[i].Doc_String__c)) {
          docInfoMap.get(recordType)
            .put(newList[i].Doc_String__c, new List<Document_Information__c>());
        }

        docInfoMap.get(recordType)
          .get(newList[i].Doc_String__c)
          .add(newList[i]);
      }
    }

    if (docInfoMap.size() > 0) {
      setDefaults(docInfoMap);
    }
  }

  public static void beforeUpdate(
    List<Document_Information__c> newList,
    List<Document_Information__c> oldList
  ) {
    Map<String, Map<String, List<Document_Information__c>>> docInfoMap = new Map<String, Map<String, List<Document_Information__c>>>();
    for (Integer i = 0; i < newList.size(); i++) {
      if (String.isNotBlank(newList[i].Doc_String__c)) {
        List<String> splitString = newList[i].Doc_String__c.split('\\|');
        newList[i].Folder__c = splitString[0].replace(';', ' - ');
        if (splitString.size() > 1) {
          newList[i].Document_Type__c = splitString[1];
        }
      }

      if (newList[i].Set_to_Defaults__c) {
        newList[i].Set_to_Defaults__c = false;
        String recordType = newList[i].RecordType__c;
        if (
          recordType.contains('Bridge') &&
          recordType != 'Single_Asset_Bridge_Loan'
        ) {
          recordType = 'LOC_Loan';
        }

        if (!docInfoMap.containsKey(recordType)) {
          docInfoMap.put(
            recordType,
            new Map<String, List<Document_Information__c>>()
          );
        }

        if (!docInfoMap.get(recordType).containsKey(newList[i].Doc_String__c)) {
          docInfoMap.get(recordType)
            .put(newList[i].Doc_String__c, new List<Document_Information__c>());
        }

        docInfoMap.get(recordType)
          .get(newList[i].Doc_String__c)
          .add(newList[i]);
      }

      if (docInfoMap.size() > 0) {
        setDefaults(docInfoMap);
      }
    }

    if (docInfoMap.size() > 0) {
      setDefaults(docInfoMap);
    }
  }

  public static void afterUpdate(
    List<Document_Information__c> newList,
    List<Document_Information__c> oldList
  ) {
    Set<Id> emailsToSend = new Set<Id>();

    for (Integer i = 0; i < newList.size(); i++) {
      if (
        String.isNotBlank(newList[i].External_Comments__c) &&
        !newList[i].Is_Portal_User__c &&
        newList[i].External_Comments__c != oldList[i].External_Comments__c
      ) {
        emailsToSend.add(newList[i].Id);
      }
    }

    if (emailsToSend.size() > 0) {
      sendNotificationEmails(emailsToSend);
    }
  }

  public static void setDefaults(
    Map<String, Map<String, List<Document_Information__c>>> docInfoMap
  ) {
    Map<String, Map<String, Document_Structure__mdt>> docStructureMap = new Map<String, Map<String, Document_Structure__mdt>>();

    for (Document_Structure__mdt docStructure : [
      SELECT
        Id,
        Folder_Structure_String__c,
        Document_Type__c,
        RecordType__c,
        Required__c,
        C2C_Required_Filtering__c,
        Default_Exclude_from_Loan_Status__c,
        Additional_Borrower_Checklist_Filtering__c
      FROM Document_Structure__mdt
    ]) {
      if (!docStructureMap.containsKey(docStructure.RecordType__c)) {
        docStructureMap.put(
          docStructure.RecordType__c,
          new Map<String, Document_Structure__mdt>()
        );
      }

      docStructureMap.get(docStructure.RecordType__c)
        .put(
          docStructure.Folder_Structure_String__c +
          '|' +
          docStructure.Document_Type__c,
          docStructure
        );
    }

    for (String recordType : docInfoMap.keySet()) {
      for (String folderString : docInfoMap.get(recordType).keySet()) {
        for (
          Document_Information__c docInfo : docInfoMap.get(recordType)
            .get(folderString)
        ) {
          //
          //
          system.debug('doc info stuff');
          system.debug(recordType);
          system.debug(folderString);
          // system.debug(
          //   docStructureMap.get(recordType)
          //     .get(folderString)
          //     .C2C_Required_Filtering__c
          // );
          // system.debug(docStructureMap.get(recordType).get(folderString));
          if(!docStructureMap.containsKey(recordType) ||
          !docStructureMap.get(recordType)
            .containsKey(folderString)) {
              continue;
            }

          if (
            docStructureMap.get(recordType)
              .get(folderString)
              .C2C_Required_Filtering__c == null
          ) {
            docInfo.Required_for_Clear_to_Close__c = docStructureMap.get(
                recordType
              )
              .get(folderString)
              .Required__c;
          } else {
            // docInfo.Required_for_Clear_to_Close__c = docStructureMap.get(recordType).get(folderString).Default_Exclude_from_Loan_Status__c;
            Set<String> dealTypes = opportunity_Helper.compileDealType(
              new Opportunity(LOC_Loan_Type__c = docInfo.Product_Type__c)
            );

            String additionalFilters = docStructureMap.get(recordType)
              .get(folderString)
              .C2C_Required_Filtering__c;
            Set<String> filters = new Set<String>(additionalFilters.split(';'));
            system.debug(filters);
            dealTypes.retainAll(filters);
            if (dealTypes.size() > 0) {
              system.debug(dealTypes);
              docInfo.Required_for_Clear_to_Close__c = true;
            } else {
              docInfo.Required_for_Clear_to_Close__c = false;
            }
          }

          if (
            docStructureMap.get(recordType)
              .get(folderString)
              .Additional_Borrower_Checklist_Filtering__c == null
          ) {
            docInfo.Exclude_from_Loan_Status__c = docStructureMap.get(
                recordType
              )
              .get(folderString)
              .Default_Exclude_from_Loan_Status__c;
          } else {
            // docInfo.Required_for_Clear_to_Close__c = docStructureMap.get(recordType).get(folderString).Default_Exclude_from_Loan_Status__c;
            Set<String> dealTypes = opportunity_Helper.compileDealType(
              new Opportunity(LOC_Loan_Type__c = docInfo.Product_Type__c)
            );

            String additionalFilters = docStructureMap.get(recordType)
              .get(folderString)
              .Additional_Borrower_Checklist_Filtering__c;
            Set<String> filters = new Set<String>(additionalFilters.split(';'));
            system.debug(filters);
            dealTypes.retainAll(filters);
            if (dealTypes.size() > 0) {
              system.debug(dealTypes);
              docInfo.Exclude_from_Loan_Status__c = docStructureMap.get(
                  recordType
                )
                .get(folderString)
                .Default_Exclude_from_Loan_Status__c;
            } else {
              docInfo.Exclude_from_Loan_Status__c = false;
            }
          }
        }
      }
    }
  }

  @future
  public static void sendNotificationEmails(Set<Id> docInfoIds) {
    Id templateId = [
      SELECT Id
      FROM EmailTemplate
      WHERE
        DeveloperName = 'Communities_Loan_Status_External_Comment_Notification'
      LIMIT 1
    ]
    .Id;
    Id orgEmailId = [
      SELECT Id, Address
      FROM OrgWideEmailAddress
      WHERE Address = 'caf-apps@cvest.com'
      LIMIT 1
    ]
    .Id;

    Map<Id, List<Id>> docInfoMap = new Map<Id, List<Id>>();
    for (Document_Information__c docInfo : [
      SELECT Id, Deal__c
      FROM Document_Information__c
      WHERE Id IN :docInfoIds
    ]) {
      if (!docInfoMap.containsKey(docInfo.Deal__c)) {
        docInfoMap.put(docInfo.Deal__c, new List<Id>());
      }

      docInfoMap.get(docInfo.Deal__c).add(docInfo.Id);
    }

    Set<Id> contactIds = new Set<Id>();
    Map<Id, Deal_Contact__c> dealContactMap = new Map<Id, Deal_Contact__c>();
    for (Opportunity o : [
      SELECT
        Id,
        Contact__c,
        (
          SELECT Id, Contact__c, Deal__c
          FROM Deal_Contacts__r
          WHERE Contact__c != NULL AND Entity_Type__c = 'Portal Access'
        )
      FROM Opportunity
      WHERE Id IN :docInfoMap.keySet()
    ]) {
      contactIds.add(o.Contact__c);
      if (o.Deal_Contacts__r != null) {
        for (Deal_Contact__c c : o.Deal_Contacts__r) {
          contactIds.add(c.Contact__c);
          dealContactMap.put(c.Contact__c, c);
        }
      }
    }

    List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
    for (User u : [
      SELECT Id, ContactId, Contact.Email, Email
      FROM User
      WHERE ContactId IN :contactIds
    ]) {
      contactIds.remove(u.ContactId);

      if (dealContactMap.containsKey(u.ContactId)) {
        Deal_Contact__c jc = dealContactMap.get(u.ContactId);

        for (Id docId : docInfoMap.get(jc.Deal__c)) {
          Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
          email.setTemplateId(templateId);
          email.setTargetObjectId(u.ContactId);
          email.setWhatId(docId);
          email.setOrgWideEmailAddressId(orgEmailId);
          emails.add(email);
        }
      }
    }

    if (emails.size() > 0) {
      //system.debug(emails);
      List<Messaging.SendEMailResult> results = Messaging.sendEmail(emails);
    }
  }
}