force-app/main/default/objects/User/fields/Create_Operations_Portal_User__c.field-meta.xml
<CustomField>
    <fullName>Create_Operations_Portal_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Operations Portal User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_Id__c.field-meta.xml
<CustomField>
    <fullName>Portal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Portal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserHelper.cls
public without sharing class UserHelper {
  public static void afterUpdate(List<User> newList, List<User> oldList) {
    List<Id> userIds = new List<Id>();

    for (Integer i = 0; i < newList.size(); i++) {
      if (
        String.isBlank(newList[i].Portal_Id__c) &&
        newList[i].Create_Operations_Portal_User__c &&
        newList[i].Create_Operations_Portal_User__c !=
        oldList[i].Create_Operations_Portal_User__c
      ) {
        userIds.add(newList[i].Id);
      }
    }

    if (userIds.size() > 0) {
      system.enqueueJob(
        new UpdatePortalUserQueueable(userIds, 'createOperationsUser')
      );
    }
  }
}