force-app/main/default/objects/Integration_Mapping__c/Integration_Mapping__c.object-meta.xml
<CustomObject>
    <label>Integration Mapping</label>
    <nameField>
        <label>Integration Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Mapping__c/fields/Integration_Field__c.field-meta.xml
<CustomField>
    <fullName>Integration_Field__c</fullName>
    <label>Integration Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Integration_Object__c.field-meta.xml
<CustomField>
    <fullName>Integration_Object__c</fullName>
    <label>Integration Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <label>Salesforce Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>TermLoan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationMappingEdit_Tests.cls
@isTest
global class IntegrationMappingEdit_Tests {
	static testMethod void Integration_Mapping_UnitTest() {
		Test.startTest();
		Integration_Mapping__c accountMapping = new Integration_Mapping__c(Salesforce_Object__c='Account', Salesforce_Field__c='Id', Integration_Object__c='customer', Integration_Field__c='sf_id', Active__c=true, Required__c=false, Key__c='Account');
		Integration_Mapping__c accountMapping2 = new Integration_Mapping__c(Salesforce_Object__c='Account', Salesforce_Field__c='FAKE', Integration_Object__c='customer', Integration_Field__c='sf_id', Active__c=true, Required__c=false, Key__c='');
		Integration_Mapping__c accountMapping3 = new Integration_Mapping__c(Salesforce_Object__c='Account', Salesforce_Field__c='Name', Integration_Object__c='customer', Integration_Field__c='sf_id', Active__c=true, Required__c=false, Key__c='');
		insert accountMapping;
		insert accountMapping2;
		insert accountMapping3;
		IntegrationMappingEdit_Extension ext = new IntegrationMappingEdit_Extension();
		ext.selectedObject = 'Account';
		ext.selectedAdd = 'Name';
		//ext.addMapping();
		ext.selectedDelete = 'Id';
		ext.deleteMapping();
		ext.selectedDelete = 'FAKE';
		ext.deleteBadMapping();
		ext.doSave();
		ext.getObjectOptions();
		Test.stopTest();
	}
}