force-app/main/default/objects/Interest_Reserves__c/Interest_Reserves__c.object-meta.xml
<CustomObject>
    <label>Interest Reserve</label>
    <nameField>
        <displayFormat>IR-{00000}</displayFormat>
        <label>Interest Reserves Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Reserves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Reserves__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Interest Reserves</relationshipLabel>
    <relationshipName>Interest_Reserves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interest_Reserves__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Interest Reserves</relationshipLabel>
    <relationshipName>Interest_Reserves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Reserves__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reserves__c</fullName>
    <description>Bridge Use</description>
    <label>Interest Reserves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interest_Reserves__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reserves__c</fullName>
    <label>Current Interest Reserves Paid</label>
    <summarizedField>Interest_Reserves__c.Interest_Reserves_Payment__c</summarizedField>
    <summaryForeignKey>Interest_Reserves__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/interestReservesHandler.cls
public class interestReservesHandler {
    public static void beforeInsert(List<Interest_Reserves__c> newList){
        
        List<id> iRId = new List<id>();
        MAP<id, id> myMap = new MAP<id,id>();
        
        for(integer i = 0; i < newList.size(); i++){
            iRId.add(newList[i].Property__c);
        }
        
        for(Property__c prop : [SELECT id, Deal__r.id FROM Property__c WHERE id in: iRId]){
            myMap.put(prop.id, prop.Deal__r.id);
            system.debug('myMap'+myMap);
            system.debug('mapsize'+myMap.size());
        }
        
        for(integer i = 0; i < newList.size(); i++){
        	Date monthDate = newList[i].Date__c == null? System.today().toStartOfMonth():newList[i].Date__c;

            newList[i].Deal__c = myMap.get(newList[i].Property__c);
            newList[i].Date__c = monthDate;

            system.debug('value'+ myMap.get(newList[i].Property__c));
        }
        
    }
    public static void beforeUpdate(List<Interest_Reserves__c> newList, List<Interest_Reserves__c> oldList){
        List<id> iRId = new List<id>();
        MAP<id, id> myMap = new MAP<id,id>();
        
        
        for(integer i = 0; i < newList.size(); i++){
            system.debug (newList[i].Property__c );
                        system.debug (oldList[i].Property__c );

            iRId.add(newList[i].Property__c);
        }
        
        for(Property__c prop : [SELECT id, Deal__r.id FROM Property__c WHERE id in: iRId]){
            myMap.put(prop.id, prop.Deal__r.id);
            system.debug('myMap2'+myMap);
            system.debug('mapsize2'+myMap.size());
        }
        
        for(integer i = 0; i < newList.size(); i++){
            newList[i].Deal__c = myMap.get(newList[i].Property__c);
            system.debug('value2'+ myMap.get(newList[i].Property__c));
        }
    
    
    }   
}