force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <inlineHelpText>The Type of Approval Process</inlineHelpText>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Review</fullName>
            </value>
            <value>
                <fullName>Submission into UW</fullName>
            </value>
            <value>
                <fullName>GLC Approval</fullName>
            </value>
            <value>
                <fullName>Term Sheet Approval</fullName>
            </value>
            <value>
                <fullName>Approved By GLC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <label>Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Date_Acted__c.field-meta.xml
<CustomField>
    <fullName>Date_Acted__c</fullName>
    <label>Date Acted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Deal_Stage_At_Time_of_Submission__c.field-meta.xml
<CustomField>
    <fullName>Deal_Stage_At_Time_of_Submission__c</fullName>
    <description>This was the Stage of the Deal at the time of this Approval Submission</description>
    <inlineHelpText>This was the Stage of the Deal at the time of this Approval Submission</inlineHelpText>
    <label>Deal Stage At Time of Submission</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Data Tape Received</fullName>
            </value>
            <value>
                <fullName>Term Sheet Issued</fullName>
            </value>
            <value>
                <fullName>Term Sheet Signed/Deposit Collected</fullName>
            </value>
            <value>
                <fullName>Loan Processing</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Approved By Committee</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>UW Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Id__c</fullName>
    <label>Process Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Instance_Id__c</fullName>
    <label>Process Instance Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Name of the Approval Process Used</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Status_Text__c.field-meta.xml
<CustomField>
    <fullName>Status_Text__c</fullName>
    <label>Status Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Step_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Step_Item_Id__c</fullName>
    <label>Step Item Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Time_in_Approval__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Approval__c</fullName>
    <description>Time since Pricing Approval Submission</description>
    <formula>IF(Status__c != &apos;Approved&apos;,
      TEXT( Time_In_Approval_Initial__c - 1 ) &amp; &quot; days &quot;
      &amp; TEXT( ABS(FLOOR( MOD( (NOW() - CreatedDate) * 24, 24 ) ) )) &amp; &quot; hours &quot;
      &amp; TEXT( ABS (ROUND( MOD( (NOW() - CreatedDate) * 24 * 60, 60 ), 0 )) ) &amp; &quot; minutes&quot;,
  
      TEXT( Time_In_Approval_Completed__c -1 ) &amp; &quot; days &quot;
      &amp; TEXT( ABS(FLOOR( MOD( (Date_Acted__c - CreatedDate) * 24, 24 ) )) ) &amp; &quot; hours &quot;
      &amp; TEXT( ABS(ROUND( MOD( (Date_Acted__c - CreatedDate) * 24 * 60, 60 ), 0 ) )) &amp; &quot; minutes&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time in Approval</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Program_Type__c</fullName>
    <description>Bridge Use
Custom or Standard Pricing</description>
    <inlineHelpText>Indicates if the pricing is Standard or Custom</inlineHelpText>
    <label>Bridge Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <formula>Owner.FirstName &amp; &quot; &quot; &amp; Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IcReviewsLwcController.cls
public without sharing class IcReviewsLwcController {
  public static List<String> IC_PROCESS_NAMES = new List<String>{
    'Bridge IC Process',
    'Term Sub-IC Process',
    'Term IC Process',
    'Bridge Sub-IC Process',
    'Bridge Mini Sub-IC Process'
  };

  @AuraEnabled(cacheable=true)
  public static List<Map<String, Object>> getApprovalHistories() {
    List<Map<String, Object>> returnVal = new List<Map<String, Object>>();
    List<Approval_History__c> approvalHistories = [
      SELECT
        Id,
        Actor__c,
        Actor__r.Name,
        Name,
        Approver__c,
        Comments__c,
        Date_Acted__c,
        Time_in_Approval__c,
        Deal__c,
        Deal__r.Name,
        Deal__r.Type,
        Deal__r.Owner_Name__c,
        Deal__r.Amount,
        Deal__r.LOC_Loan_Type__c,
        Deal__r.Product_Sub_Type__c,
        Deal__r.LOC_Program_Type__c,
        Deal__r.RecordType.DeveloperName,
        Parent_Status__c,
        Process_Id__c,
        Process_Instance_Id__c,
        Status__c,
        Step_Item_Id__c,
        Status_Text__c,
        LastModifiedDate,
        Approval_Type__c,
        ProcessName__c,
        Deal_Stage_At_Time_of_Submission__c
      FROM Approval_History__c
      WHERE
        Parent_Status__c = 'Pending'
        AND Status__c = 'Pending'
        AND (ProcessName__c IN :IC_PROCESS_NAMES
        OR Approval_Type__c LIKE '%IC Memo%')
        AND Process_Id__c != NULL
      ORDER BY LastModifiedDate DESC
    ];

    Set<Id> wrkItemIds = new Set<Id>();
    for (Approval_History__c ah : approvalHistories) {
      Map<String, Object> ahMap = new Map<String, Object>{
        'id' => ah.Id,
        'opportunityName' => ah.Deal__r.Name,
        'opportunityUrl' => '/' + ah.Deal__c,
        'originator' => ah.Deal__r.Owner_Name__c,
        'loanAmount' => ah.Deal__r.Amount,
        'loanType' => ah.Deal__r.Type,
        'productType' => ah.Deal__r.LOC_Loan_Type__c,
        'stageTimeOfSub' => ah.Deal_Stage_At_Time_of_Submission__c,
        'dateSubmitted' => ah.Date_Acted__c,
        'timeSinceSub' => ah.Time_in_Approval__c,
        'subStatus' => ah.Status__c,
        'approvalType' => ah.ProcessName__c,
        'approvalUrl' => '/' + ah.Process_Id__c,
        'approvalName' => ah.Name,
        'processId' => ah.Process_Id__c
      };
      wrkItemIds.add((Id) ah.Process_Id__c);
      returnVal.add(ahMap);
    }

    Map<Id, ProcessInstanceWorkItem> processInstanceMap = new Map<Id, ProcessInstanceWorkItem>([
      SELECT Id, ActorId, Actor.Name, ProcessInstanceId
      FROM ProcessInstanceWorkItem
      WHERE Id IN :wrkItemIds
    ]);

    System.debug(JSON.serializePretty(returnVal));
    for(Map<String, Object> val: returnVal) {
      if(processInstanceMap.size() > 0 && processInstanceMap.containsKey((Id) val.get('processId'))) {
        String actorName  = processInstanceMap.get((Id) val.get('processId')).Actor.Name;
        val.put('approverName', actorName);
        val.put('approvalName', val.get('approvalName') + ' (' + actorName + ')');
      }
    }

    return returnVal;
  }
}