force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Id__c</fullName>
    <label>Process Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Instance_Id__c</fullName>
    <label>Process Instance Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Term_Sheet_Name__c.field-meta.xml
<CustomField>
    <fullName>Approved_Term_Sheet_Name__c</fullName>
    <label>Approved Term Sheet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Program_Type__c</fullName>
    <description>Bridge Use
Custom or Standard Pricing</description>
    <inlineHelpText>Indicates if the pricing is Standard or Custom</inlineHelpText>
    <label>Bridge Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DashboardPricing_Tests.cls
@isTest
private class DashboardPricing_Tests {

    static TestMethod void DashboardPricing_LightningController_UnitTest(){
        Account acc = test_Helper.createAccount();
        Contact cont = test_Helper.createContact( acc );
        Opportunity opp = test_Helper.createOpportunity( acc, cont );
        
        // Code Added By Trivikram : Start
        Id termLoanRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Term Loan').getRecordTypeId();
        Id bridgeLoanRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Bridge Loan').getRecordTypeId();
        
        opp.RecordTypeId = termLoanRecordTypeId;
        opp.LOC_Program_Type__c = 'Custom';
        opp.Approved_Term_Sheet_Name__c = null;
        update opp;
        
        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(opp.Id);
        Approval.ProcessResult result = Approval.process(req);
        Id processInstanceId = result.getInstanceId();
        // Code Added By Trivikram : End
        
        Approval_History__c testApprovalHistory = new Approval_History__c();
        testApprovalHistory.Process_Id__c = userInfo.getUserId();
        testApprovalHistory.Parent_Status__c = 'Pending';
        testApprovalHistory.Deal__c = opp.Id;
        testApprovalHistory.Process_Instance_Id__c = processInstanceId; // Code Added By Trivikram 
        insert testApprovalHistory;

        Test.startTest();
        DashboardPricing_LightningController.returnApprovals();

        DashboardPricing_LightningController.ahWrapper ahWrapper = new DashboardPricing_LightningController.ahWrapper();
        ahWrapper.oppName = 'Test';
        ahWrapper.lmd = system.now();
        ahWrapper.processStatus = 'Test';
        ahWrapper.processInstance = 'Test';

        DashboardPricing_LightningController.returnWRapper returnWrapper = new DashboardPricing_LightningController.returnWRapper(userInfo.getUserId(), new List<DashboardPricing_LightningController.ahWrapper>());

        Test.stopTest();
    }

}