force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <inlineHelpText>The Type of Approval Process</inlineHelpText>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Review</fullName>
            </value>
            <value>
                <fullName>Submission into UW</fullName>
            </value>
            <value>
                <fullName>GLC Approval</fullName>
            </value>
            <value>
                <fullName>Term Sheet Approval</fullName>
            </value>
            <value>
                <fullName>Approved By GLC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PricingReviewController.cls
global class PricingReviewController {
  global string recId { get; set; }

  global ProcessInstanceStep ApprovalProcess {
    get {
      if (recId == null) {
        return null;
      }

      String soqlQuery = 'SELECT Comments, Id, ActorId FROM ProcessInstanceStep WHERE ProcessInstance.TargetObjectId = :recId';
      soqlQuery += ' ORDER BY SystemModstamp DESC LIMIT 1';
      List<ProcessInstanceStep> steps = Database.query(soqlQuery);
      return steps.size() > 0 ? steps[0] : null;
    }
    private set;
  }

  global ProcessInstanceWorkItem WorkItem {
    get {
      if (recId == null) {
        return null;
      } else {
        List<ProcessInstanceWorkItem> workItems = [
          SELECT Id, OriginalActorId, OriginalActor.Name, ActorId, Actor.Name
          FROM ProcessInstanceWorkitem
          WHERE ProcessInstance.TargetObjectId = :recId
          ORDER BY SystemModstamp DESC
          LIMIT 1
        ];
        return workItems.size() > 0 ? workItems[0] : null;
      }
    } private set;
  }

  global String approvalComments {
    get {
      return ApprovalProcess != null ? ApprovalProcess.Comments : null;
    }
    private set;
  }

  global String approvalUrl {
    get {
      return WorkItem != null
        ? URL.getOrgDomainUrl().toExternalForm() + '/' + WorkItem.Id
        : null;
    }
    private set;
  }

  global String dealUrl {
    get {
      return recId == null
        ? null
        : URL.getOrgDomainUrl().toExternalForm() + '/' + recId;
    }
    private set;
  }

  global Integer repriceCount {
    get {
      return [
        SELECT COUNT()
        FROM Approval_History__c
        WHERE
          Parent_Status__c = 'Approved'
          AND Status__c LIKE '%Submitted'
          AND Deal__c = :recId
          AND Approval_Type__c LIKE 'Pricing%'
      ];
    }
    private set;
  }
}