force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Instance_Id__c</fullName>
    <label>Process Instance Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Loan_Number__c/Deal_Loan_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Deal Loan Number</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Deal_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Loan_Number__c</fullName>
    <description>This will replace the manual auto assignment</description>
    <displayFormat>{00000}</displayFormat>
    <label>Deal Loan Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/ConfirmationOfTermsEmailController.cls
public class ConfirmationOfTermsEmailController {
  public Id historyId { get; set; }
  public ConfirmationOfTermsController.Panels panels;

  public ConfirmationOfTermsController.SubmissionPanel submissionDetails;
  public ConfirmationOfTermsController.CurrentPanel currentDetails;
  public ConfirmationOfTermsController.Comments comments;
  public Opportunity deal;
  public ConfirmationOfTermsController.Panels getPanels() {
    if (this.historyId != null && this.panels == null) {
      Approval_History__c hist = [
        SELECT Id, Deal__c, Process_Instance_Id__c
        FROM Approval_History__c
        WHERE Id = :this.historyId
      ];
      Id dealId = hist.Deal__c;
      this.panels = (ConfirmationOfTermsController.Panels) JSON.deserialize(
        ConfirmationOfTermsController.getRecordDetails(
          dealId,
          hist.Process_Instance_Id__c
        ),
        ConfirmationOfTermsController.Panels.class
      );
    }

    return this.panels;
  }

  public Opportunity getDeal() {
    if (this.historyId != null && this.deal == null) {
      Approval_History__c hist = [
        SELECT Id, Deal__c
        FROM Approval_History__c
        WHERE Id = :this.historyId
      ];
      this.deal = [SELECT Id, Name, Deal_Loan_NUmber__c FROM Opportunity WHERE Id = :hist.Deal__c];
    }
    return this.deal;
  }
}