force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <inlineHelpText>The Type of Approval Process</inlineHelpText>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Review</fullName>
            </value>
            <value>
                <fullName>Submission into UW</fullName>
            </value>
            <value>
                <fullName>GLC Approval</fullName>
            </value>
            <value>
                <fullName>Term Sheet Approval</fullName>
            </value>
            <value>
                <fullName>Approved By GLC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <label>Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Date_Acted__c.field-meta.xml
<CustomField>
    <fullName>Date_Acted__c</fullName>
    <label>Date Acted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approval Histories</relationshipLabel>
    <relationshipName>Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Deal_Stage_At_Time_of_Submission__c.field-meta.xml
<CustomField>
    <fullName>Deal_Stage_At_Time_of_Submission__c</fullName>
    <description>This was the Stage of the Deal at the time of this Approval Submission</description>
    <inlineHelpText>This was the Stage of the Deal at the time of this Approval Submission</inlineHelpText>
    <label>Deal Stage At Time of Submission</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
            </value>
            <value>
                <fullName>Data Tape Received</fullName>
            </value>
            <value>
                <fullName>Term Sheet Issued</fullName>
            </value>
            <value>
                <fullName>Term Sheet Signed/Deposit Collected</fullName>
            </value>
            <value>
                <fullName>Loan Processing</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Approved By Committee</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>UW Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Final_Spread__c.field-meta.xml
<CustomField>
    <fullName>Final_Spread__c</fullName>
    <label>Final Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee__c</fullName>
    <description>The Origination Fee % at the time of submission or approval</description>
    <inlineHelpText>The Origination Fee % at the time of submission or approval</inlineHelpText>
    <label>Origination Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Id__c</fullName>
    <label>Process Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Process_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Instance_Id__c</fullName>
    <label>Process Instance Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Name of the Approval Process Used</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Spread__c.field-meta.xml
<CustomField>
    <fullName>Spread__c</fullName>
    <description>Spread at the time of submission or approval</description>
    <inlineHelpText>Spread at the time of submission or approval</inlineHelpText>
    <label>Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Status_Text__c.field-meta.xml
<CustomField>
    <fullName>Status_Text__c</fullName>
    <label>Status Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Tracking_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Status__c</fullName>
    <label>Tracking Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAF_Upfront_Fee__c.field-meta.xml
<CustomField>
    <fullName>CAF_Upfront_Fee__c</fullName>
    <description>Term and Bridge Use</description>
    <label>Origination Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Sponsor_Tier__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Sponsor_Tier__c</fullName>
    <description>Estimated Credit Tier based on credit score, liquidity and number of projects</description>
    <inlineHelpText>Estimated Credit Tier based on credit score, liquidity and number of projects</inlineHelpText>
    <label>Estimated Credit Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Sponsor_Tier__c.field-meta.xml
<CustomField>
    <fullName>Final_Sponsor_Tier__c</fullName>
    <description>Final Credit Tier based on credit score, liquidity and number of projects</description>
    <inlineHelpText>Final Credit Tier determined during the Underwriting process and based on credit score, liquidity and number of projects</inlineHelpText>
    <label>Final Credit Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Spread__c.field-meta.xml
<CustomField>
    <fullName>Final_Spread__c</fullName>
    <description>Term Use</description>
    <label>Final Spread</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee__c</fullName>
    <label>Origination Fee Entry</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IcReviewsControllerTest.cls
@isTest
private class IcReviewsControllerTest {
  @isTest
  static void IcReviewsControllerTest() {
    Id userId = UserInfo.getUserId();
    String approvalType = 'Bridge IC';
    String processName = 'Bridge_IC_Approval';
    Account testAcct = Test_Helper.createAccount();
    Contact testContact = Test_Helper.createContact(testAcct);
    Opportunity testDeal = Test_Helper.createBridgeDeal(testAcct, testContact);
    testDeal.StageName = 'Underwriting';
    testDeal.Amount = 245000;
    testDeal.Estimated_Sponsor_Tier__c = 'Tier 1';
    testDeal.Final_Sponsor_Tier__c = 'Tier 1';
    update testDeal;
    Id recordId = testDeal.Id;
    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
    req.setObjectId(recordId);
    req.setSubmitterId(userId);
    req.setSkipEntryCriteria(true);
    req.setProcessDefinitionNameOrId(processName);
    Approval.ProcessResult result = Approval.process(req);
    Id processInstanceId = result.getInstanceId();
    String status = result.getInstanceStatus();
    List<Id> workItemIds = result.getNewWorkitemIds();

    Opportunity deal = IcApprovalController.queryOpportunity(recordId);

    String dealStage = deal.StageName;

    String ahProcessName = approvalType != 'Term Sub-IC'
      ? approvalType + ' Process'
      : approvalType;
    List<Approval_History__c> ahList = new List<Approval_History__c>();
    Approval_History__c ahc = new Approval_History__c(
      Process_Instance_Id__c = processInstanceId,
      Parent_Status__c = status,
      Deal__c = recordId,
      Name = 'Approval Request: ' + deal.Name.left(50),
      ProcessName__c = ahProcessName,
      Approver__c = UserInfo.getName(),
      Actor__c = UserInfo.getUserId(),
      Role__c = 'Submitter',
      Date_Acted__c = System.now(),
      Status__c = 'Submitted',
      Status_Text__c = 'Submitted',
      Approval_Type__c = 'IC Memo',
      Tracking_Status__c = 'Closer',
      Deal_Stage_At_Time_of_Submission__c = dealStage
    );

    ahc.Spread__c = deal.Final_Spread__c;
    if (ahc.Spread__c != null) {
      ahc.Spread__c *= 100;
    }

    ahc.Origination_Fee__c = deal.CAF_Upfront_Fee__c;

    ahList.add(ahc);

    for (ProcessInstanceWorkitem workItem : [
      SELECT Id, ActorId, Actor.Name
      FROM ProcessInstanceWorkItem
      WHERE Id IN :workItemIds
    ]) {
      Approval_History__c a = new Approval_History__c(
        Process_Instance_Id__c = processInstanceId,
        Process_Id__c = workItem.Id,
        ProcessName__c = ahProcessName,
        Actor__c = workItem.ActorId,
        Parent_Status__c = status,
        Deal__c = recordId,
        Name = 'Approval Request: ' + deal.Name.left(50),
        Approver__c = workItem.Actor.Name, // actor.name
        Status__c = 'Pending',
        Status_Text__c = 'Pending: Committee Review',
        Date_Acted__c = System.now(),
        Approval_Type__c = 'IC Memo',
        Deal_Stage_At_Time_of_Submission__c = dealStage,
        Tracking_Status__c = 'Committee'
      );

      a.Spread__c = deal.Final_Spread__c;
      if (a.Spread__c != null) {
        a.Spread__c *= 100;
      }

      ahList.add(a);
    }
    insert ahList;
    Test.startTest();
        List<Map<String, Object>> approvalHistories = IcReviewsLwcController.getApprovalHistories();
        System.assertEquals(true, approvalHistories.size() > 0, 'Some approval histories should have been returned.');
    Test.stopTest();
  }
}