force-app/main/default/objects/Lead/fields/Account_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Account_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Converted Into</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account Converted Into)</relationshipLabel>
    <relationshipName>Leads_Converted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Conference_Year__c.field-meta.xml
<CustomField>
    <fullName>Conference_Year__c</fullName>
    <description>Conference year</description>
    <label>Conference Year</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Subsource__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Contact_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Converted Into</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact Converted Into)</relationshipLabel>
    <relationshipName>Lead_Converted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Notes__c.field-meta.xml
<CustomField>
    <fullName>Contact_Notes__c</fullName>
    <label>Contact Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Deal_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Deal_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Converted Into</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads_Converted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Existing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Existing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Existing Contact)</relationshipLabel>
    <relationshipName>Existing_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Touch_checkbox__c.field-meta.xml
<CustomField>
    <fullName>First_Touch_checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Touch checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Introduction_Source__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Source__c</fullName>
    <inlineHelpText>If the introduction source is Website Chat Bot, please review the past activities to view the conversation in Drift.</inlineHelpText>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>CA Realtors Expo</fullName>
                <label>California Realtors Expo</label>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>CREFC</fullName>
            </value>
            <value>
                <fullName>CRELC</fullName>
            </value>
            <value>
                <fullName>Crittenden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_touch_Checkbox__c.field-meta.xml
<CustomField>
    <fullName>Last_touch_Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Last touch Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Product_s__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product_s__c</fullName>
    <label>Loan Product(s)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent Complete</fullName>
            </value>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Fix and Flip Credit Line</fullName>
            </value>
            <value>
                <fullName>Freddie Mac Loan</fullName>
            </value>
            <value>
                <fullName>Ground Up Construction Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Construction Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Term Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily Loan</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Rental Aggregation Credit Line</fullName>
            </value>
            <value>
                <fullName>Rental Portfolio Loan</fullName>
            </value>
            <value>
                <fullName>Single Asset Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Single Project Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Single Property Rental Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Property Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/True_source__c.field-meta.xml
<CustomField>
    <fullName>True_source__c</fullName>
    <defaultValue>true</defaultValue>
    <label>True source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/utm_Campaign_Medium__c.field-meta.xml
<CustomField>
    <fullName>utm_Campaign_Medium__c</fullName>
    <label>utm Campaign Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Lead Source Tracking</description>
    <label>Source</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Account_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Account_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Converted Into</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Source (Account)</relationshipLabel>
    <relationshipName>Source1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Conference_Year__c.field-meta.xml
<CustomField>
    <fullName>Conference_Year__c</fullName>
    <label>Conference Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/fields/Contact_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Contact_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Source (Contact Converted Into)</relationshipLabel>
    <relationshipName>Source1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Contact_Notes__c.field-meta.xml
<CustomField>
    <fullName>Contact_Notes__c</fullName>
    <label>Contact Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Deal_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Deal_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Converted Into</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Source</relationshipLabel>
    <relationshipName>Source</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Existing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Existing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Source (Existing Contact)</relationshipLabel>
    <relationshipName>SourceDelete</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/first_Touch_checkbox__c.field-meta.xml
<CustomField>
    <fullName>first_Touch_checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates that this Source was the first time this person interacted with CoreVest</description>
    <inlineHelpText>This indicates that this Source was the first time this person interacted with CoreVest</inlineHelpText>
    <label>First Touch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/last_touch_Checkbox__c.field-meta.xml
<CustomField>
    <fullName>last_touch_Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates that this Source was the last time this person interacted with CoreVest</description>
    <inlineHelpText>This indicates that this Source was the last time this person interacted with CoreVest</inlineHelpText>
    <label>Last Touch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Requested_Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Requested_Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/True_source__c.field-meta.xml
<CustomField>
    <fullName>True_source__c</fullName>
    <defaultValue>false</defaultValue>
    <label>True Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/utm_Campaign_Content__c.field-meta.xml
<CustomField>
    <fullName>utm_Campaign_Content__c</fullName>
    <label>utm Campaign Content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateSourceFromLeadBatch.cls
public class CreateSourceFromLeadBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        system.debug('start:::');
        string leadQuery = 'SELECT id,FirstName,LastName,Email,Phone,MobilePhone,Company,Loan_Product_s__c,Introduction_Source__c,Introduction_Subsource__c,Account_Converted_Into__c,Contact_Converted_Into__c,Deal_Converted_Into__c,Status,Conference_Year__c,Requested_Loan_Size__c,first_Touch_checkbox__c,last_Touch_checkbox__c,True_source__c,Contact_Notes__c,Existing_Contact__c,utm_Campaign_Content__c,utm_Campaign_Medium__c,utm_Campaign_Name__c,utm_Campaign_Source__c,utm_Campaign_Term__c from lead where id NOT IN (select Lead__c from Source__c) LIMIT 1';
        system.debug('leadQuery:::'+leadQuery);
        return  Database.getQueryLocator(leadQuery);
    }
    public void execute(Database.BatchableContext bc, List<lead> leadList){
        system.debug('leadList:::'+leadList);
        if(leadList != null && leadList.size() > 0){
            lead_Helper.CreateSource(leadList);
        }
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        system.debug('createSourceFromLeadBatch:::finish:::');
    }
}