force-app/main/default/objects/Lead/fields/Account_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Account_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Converted Into</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account Converted Into)</relationshipLabel>
    <relationshipName>Leads_Converted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Conference_Year__c.field-meta.xml
<CustomField>
    <fullName>Conference_Year__c</fullName>
    <description>Conference year</description>
    <label>Conference Year</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Subsource__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Contact_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Converted Into</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact Converted Into)</relationshipLabel>
    <relationshipName>Lead_Converted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Notes__c.field-meta.xml
<CustomField>
    <fullName>Contact_Notes__c</fullName>
    <label>Contact Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Deal_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Deal_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Converted Into</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads_Converted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Existing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Existing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Existing Contact)</relationshipLabel>
    <relationshipName>Existing_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Touch_checkbox__c.field-meta.xml
<CustomField>
    <fullName>First_Touch_checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Touch checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Product_s__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product_s__c</fullName>
    <label>Loan Product(s)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent Complete</fullName>
            </value>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Fix and Flip Credit Line</fullName>
            </value>
            <value>
                <fullName>Freddie Mac Loan</fullName>
            </value>
            <value>
                <fullName>Ground Up Construction Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Construction Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Term Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily Loan</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Rental Aggregation Credit Line</fullName>
            </value>
            <value>
                <fullName>Rental Portfolio Loan</fullName>
            </value>
            <value>
                <fullName>Single Asset Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Single Project Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Single Property Rental Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Property Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referring Brokerage, Vendor or Client Account</description>
    <inlineHelpText>Referring Brokerage, Vendor or Client Account</inlineHelpText>
    <label>Referral Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Lead Source Tracking</description>
    <label>Source</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Account_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Account_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Converted Into</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Source (Account)</relationshipLabel>
    <relationshipName>Source1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Conference_Year__c.field-meta.xml
<CustomField>
    <fullName>Conference_Year__c</fullName>
    <label>Conference Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/fields/Contact_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Contact_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Source (Contact Converted Into)</relationshipLabel>
    <relationshipName>Source1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Contact_Notes__c.field-meta.xml
<CustomField>
    <fullName>Contact_Notes__c</fullName>
    <label>Contact Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/CTM_Ring_Time__c.field-meta.xml
<CustomField>
    <fullName>CTM_Ring_Time__c</fullName>
    <label>CTM Ring Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Deal_Converted_Into__c.field-meta.xml
<CustomField>
    <fullName>Deal_Converted_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Converted Into</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Source</relationshipLabel>
    <relationshipName>Source</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Lead email Address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Existing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Existing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Source (Existing Contact)</relationshipLabel>
    <relationshipName>SourceDelete</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/first_Touch_checkbox__c.field-meta.xml
<CustomField>
    <fullName>first_Touch_checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates that this Source was the first time this person interacted with CoreVest</description>
    <inlineHelpText>This indicates that this Source was the first time this person interacted with CoreVest</inlineHelpText>
    <label>First Touch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/IsConvertedLead__c.field-meta.xml
<CustomField>
    <fullName>IsConvertedLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConvertedLead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Source</relationshipLabel>
    <relationshipName>Source</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/lead_id__c.field-meta.xml
<CustomField>
    <fullName>lead_id__c</fullName>
    <label>Lead ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Lead Phone Number</description>
    <inlineHelpText>Lead Phone Number</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Primary_Lead_status__c.field-meta.xml
<CustomField>
    <fullName>Primary_Lead_status__c</fullName>
    <label>Primary Lead status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/fields/Primary_Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Primary_Loan_Product__c</fullName>
    <description>Loan Products Interested in</description>
    <label>Primary Loan Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single Project Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Build to Rent Complete</fullName>
            </value>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Fix and Flip Credit Line</fullName>
            </value>
            <value>
                <fullName>Freddie Mac Loan</fullName>
            </value>
            <value>
                <fullName>Ground Up Construction Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Construction Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily-CRE Term Loan</fullName>
            </value>
            <value>
                <fullName>Multifamily Loan</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Rental Aggregation Credit Line</fullName>
            </value>
            <value>
                <fullName>Rental Portfolio Loan</fullName>
            </value>
            <value>
                <fullName>Single Asset Bridge Loan</fullName>
            </value>
            <value>
                <fullName>Single Property Rental Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Property Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/fields/Primary_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Source__c</fullName>
    <label>Primary Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SourceToLeadBatch.cls
public class SourceToLeadBatch implements Database.Batchable<sObject> {
  public static final Map<String, String> fieldMapping = new Map<String, String>{
    'Account_Converted_Into__c' => 'Account_Converted_Into__c',
    'Company' => 'Company__c',
    'Conference_Year__c' => 'Conference_Year__c',
    'Contact_Converted_Into__c' => 'Contact_Converted_Into__c',
    'Contact_Notes__c' => 'Contact_Notes__c',
    'CreatedById' => 'CreatedById',
    'CreatedDate' => 'CreatedDate',
    'CTM_Ring_Time__c' => 'CTM_Ring_Time__c',
    'Deal_Converted_Into__c' => 'Deal_Converted_Into__c',
    'Email' => 'Email__c',
    'Existing_Contact__c' => 'Existing_Contact__c',
    'First_Touch_checkbox__c' => 'first_Touch_checkbox__c',
    'IsConverted' => 'IsConvertedLead__c',
    'IsDeleted' => 'IsDeleted__c',
    // 'LastModifiedDate' => 'LastModifiedDate',
    // 'LastActivityDate' => 'LastActivityDate',
    // 'LastModifiedById' => 'LastModifiedById',
    // 'LastReferencedDate' => 'LastReferencedDate',
    // 'LastViewedDate' => 'LastViewedDate',
    'Id' => 'lead_id__c',
    'FirstName' => 'Lead_First_Name__c',
    'LastName' => 'Lead_Last_Name__c',
    'Full_Name__c' => 'Lead_Name__c',
    'Status' => 'Primary_Lead_status__c',
    'Loan_Product_s__c' => 'Primary_Loan_Product__c',
    'MobilePhone' => 'Mobile__c',
    'Phone' => 'Phone__c',
    'Source__c' => 'Primary_Source__c',
    'Referral_Source__c' => 'Referral_Source__c',
    'Referral_Source_Contact__c' => 'Referral_Source_Contact__c',
    'Referring_URL__c' => 'Referring_URL__c',
    'Requested_Loan_Size__c' => 'Requested_Loan_Size__c',
    // 'SystemModstamp' => 'SystemModstamp',
    'True_source__c' => 'True_source__c',
    'utm_Campaign_Content__c' => 'utm_Campaign_Content__c',
    'utm_Campaign_Medium__c' => 'utm_Campaign_Medium__c',
    'utm_Campaign_Name__c' => 'utm_Campaign_Name__c',
    'utm_Campaign_Source__c' => 'utm_Campaign_Source__c',
    'utm_Campaign_Term__c' => 'utm_Campaign_Term__c'
  };

  public Database.QueryLocator start(Database.BatchableContext BC) {
    List<String> fieldsList = new List<String>();
    fieldsList.addAll(fieldMapping.keySet());
    String fields = String.join(fieldsList, ',');

    String q =
      'SELECT ' +
      fields +
      ' FROM Lead WHERE Id NOT IN (SELECT Lead__c FROM Source__c)';
    // String q = 'SELECT ' + fields + ' FROM Lead WHERE Id = \'00Q0a00000lqxn5EAA\' ';
    // String q = 'SELECT ' + fields + ' FROM Lead WHERE Id NOT IN (SELECT Lead__c FROM Source__c) AND CALENDAR_MONTH(CreatedDate) IN (3) AND CALENDAR_YEAR(CreatedDate) IN (2015)';

    return Database.getQueryLocator(q);
  }

  public void execute(Database.BatchableContext BC, List<Lead> scope) {
    List<Source__c> convertedSources = new List<Source__c>();

    for (Lead s : scope) {
      convertedSources.add(createSourceRecord(s));
    }

    try {
      if (Test.isRunningTest() && scope[0].FirstName == 'EXCEPTION') {
        throw new DmlException('Test Exception');
      }
      upsert convertedSources;
    } catch (Exception err) {
      String a = [
        SELECT a.Name, a.Id
        FROM ApexClass a
        WHERE a.Name LIKE 'source%' AND (NOT a.Name LIKE '%test%')
        LIMIT 1
      ]
      .Id;

      List<AsyncApexJob> jobs = [
        SELECT Id, createddate
        FROM AsyncApexJob
        WHERE ApexClassID = :a AND status != 'completed' AND status != 'aborted'
      ];

      for (AsyncApexJob j : jobs) {
        System.abortJob(j.Id);
      }

      Integer remainingRecords = scope.size() * jobs.size();

      sendExceptionEmails(err, jobs.size(), remainingRecords);
    }
  }

  public void finish(Database.BatchableContext BC) {
    String a = [
      SELECT a.Name, a.Id
      FROM ApexClass a
      WHERE a.Name LIKE 'source%' AND (NOT a.Name LIKE '%test%')
      LIMIT 1
    ]
    .Id;

    List<AsyncApexJob> jobs = [
      SELECT
        Id,
        status,
        createddate,
        NumberOfErrors,
        JobItemsProcessed,
        TotalJobItems
      FROM AsyncApexJob
      WHERE
        ApexClassID = :a
        AND completeddate > :Datetime.now().addMinutes(-2)
        AND Status IN ('Aborted', 'Completed')
      ORDER BY createddate DESC
      LIMIT 1
    ];

    if (jobs.size() > 0) {
      sendCompletedEmail(jobs[0]);
    }
  }

  public static Source__c createSourceRecord(Lead l) {
    Source__c s = new Source__c();
    s.Lead__c = l.Id;
    for (String key : fieldMapping.keySet()) {
      s.put(fieldMapping.get(key), l.get(key));
    }

    return s;
  }

  public static void sendExceptionEmails(
    Exception ex,
    Integer jobCount,
    Integer remainingRecords
  ) {
    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

    email.setToAddresses(new List<String>{ 'ldecastro@mkpartners.com','integrations@cvest.com', 'jonathan.lay@cvest.com' });
    OrgWideEmailAddress owea = new OrgWideEmailAddress();
    owea = [
      SELECT Id, Address, DisplayName
      FROM OrgWideEmailAddress
      WHERE DisplayName = 'Integrations User'
    ];
    String body = '';
    body += 'Line Number: ' + ex.getLineNumber();
    body += '\nStacktrace: ' + ex.getStackTraceString();
    body += '\nType: ' + ex.getTypeName();
    body += '\nMessage:  ' + ex.getMessage();
    body += '\nAborted Job Count: ' + jobCount;
    body += '\nRemaining Records (Approx.): ' + remainingRecords;

    if ( owea != null) {
      email.setOrgWideEmailAddressId(owea.Id);
    }
    email.setPlainTextbody(body);
    email.setSubject('Lead to Source Batch Error');

    Messaging.sendEmail(new List<Messaging.SIngleEmailMessage>{ email });
  }

  public static void sendCompletedEmail(AsyncApexJob job) {
    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

    email.setToAddresses(new List<String>{ 'ldecastro@mkpartners.com','integrations@cvest.com', 'jonathan.lay@cvest.com' });
    OrgWideEmailAddress owea = new OrgWideEmailAddress();
    owea = [
      SELECT Id, Address, DisplayName
      FROM OrgWideEmailAddress
      WHERE DisplayName = 'Integrations User'
    ];

    String body = 'Batch ' + job.Status + '.\n';
    body += '\nTotal Job Items: ' + job.TotalJobItems;
    body += '\nJob Items Processed: ' + job.JobItemsProcessed;
    body += '\nNumber of Errors: ' + job.NumberOfErrors;
    body += '\nStatus: ' + job.Status;

    if (job.NumberOfErrors > 0) {
      body += '\n\nPlease refer to separate email with details about the error.';
    }
    if ( owea != null) {
      email.setOrgWideEmailAddressId(owea.Id);
    }

    email.setPlainTextbody(body);
    email.setSubject('Lead to Source Batch ' + job.Status);

    Messaging.sendEmail(new List<Messaging.SIngleEmailMessage>{ email });
  }
}