force-app/main/default/objects/Lead/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <label>Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Bad Contact Info</fullName>
            </value>
            <value>
                <fullName>Bankruptcy / Foreclosure</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Lack of Experience</fullName>
            </value>
            <value>
                <fullName>Low Fico</fullName>
            </value>
            <value>
                <fullName>Low Income</fullName>
            </value>
            <value>
                <fullName>Low Liquidity</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Not Investor/Broker</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Spam / Solicitation</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <isActive>false</isActive>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>Current Credit Issue</fullName>
                <isActive>false</isActive>
                <label>Current Credit Issue</label>
            </value>
            <value>
                <fullName>DO NOT CALL</fullName>
                <isActive>false</isActive>
                <label>DO NOT CALL</label>
            </value>
            <value>
                <fullName>Left Message / Sent Email</fullName>
                <isActive>false</isActive>
                <label>Left Message / Sent Email</label>
            </value>
            <value>
                <fullName>Non-Borrower</fullName>
                <isActive>false</isActive>
                <label>Non-Borrower</label>
            </value>
            <value>
                <fullName>Seeking Non-CAF Loan</fullName>
                <isActive>false</isActive>
                <label>Seeking Non-CAF Loan</label>
            </value>
            <value>
                <fullName>Seeking Non-CAF Product</fullName>
                <isActive>false</isActive>
                <label>Seeking Non-CAF Product</label>
            </value>
            <value>
                <fullName>Seeking Personal Loan</fullName>
                <isActive>false</isActive>
                <label>Seeking Personal Loan</label>
            </value>
            <value>
                <fullName>Set Appointment</fullName>
                <isActive>false</isActive>
                <label>Set Appointment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Introduction_Source__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Source__c</fullName>
    <inlineHelpText>If the introduction source is Website Chat Bot, please review the past activities to view the conversation in Drift.</inlineHelpText>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Round_Robin_Value__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Value__c</fullName>
    <label>Round Robin Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Leads.recordType-meta.xml
<RecordType>
    <fullName>Leads</fullName>
    <active>true</active>
    <businessProcess>Leads</businessProcess>
    <description>CAF Leads</description>
    <label>Leads</label>
</RecordType>

force-app/main/default/objects/Lead_Settings__c/Lead_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Lead Assignment Settings</label>
</CustomObject>

force-app/main/default/objects/Lead_Settings__c/fields/Round_Robin_Max__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Max__c</fullName>
    <label>Round Robin Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Settings__c/fields/Round_Robin_Value__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Value__c</fullName>
    <label>Round Robin Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Source__c/Master_Source__c.object-meta.xml
<CustomObject>
    <label>Master Source</label>
    <nameField>
        <label>Master Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master source</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Lead Source Tracking</description>
    <label>Source</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Master_Source__c.field-meta.xml
<CustomField>
    <fullName>Master_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Source</label>
    <referenceTo>Master_Source__c</referenceTo>
    <relationshipLabel>Source</relationshipLabel>
    <relationshipName>Source</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateSourceFromLeadBatchTest.cls
@isTest
public class CreateSourceFromLeadBatchTest{
	
	@testSetup static void methodName() {
		Lead_Settings__c setting = new Lead_Settings__c(Name='CAF Website', Round_Robin_Max__c = 6, Round_Robin_Value__c = 1);
        insert setting;
        
        Lead l = new Lead(FirstName = 'Test1', LastName = 'Tester',
               Company='Test Company1', Email = 'test111@test.com', Phone = '5555555555', MobilePhone = '5555555555', 
               Introduction_Source__c = 'Event',OwnerId = UserInfo.getUserId());
        Lead l2 = new Lead(FirstName = 'Test2', LastName = 'Tester1', Company='None',Email = 'test222@test.com',
                  Introduction_Source__c = 'Event',OwnerId = UserInfo.getUserId());

        Lead l3 = new Lead(FirstName = 'Test3', LastName = 'Tester3', email = 'test@tester.com',
               Company='Test Company3',
               Introduction_Source__c = 'Event',OwnerId = UserInfo.getUserId());

        List<Lead> leads = new List<Lead>{l};
        insert leads;
        
        Lead testLead4 = new Lead(FirstName = 'Test4', LastName = 'Tester',
               Company='Test Company', Email = 'test111@test.com',
               Introduction_Source__c = 'Event',OwnerId = UserInfo.getUserId());
        insert testLead4;
        testLead4.Phone = '6666666666';
        testLead4.MobilePhone = 'Call: 88888888888888888888';
        testLead4.Status = 'Unqualified';
        testLead4.Disposition__c = 'Low Fico';
        update testLead4;
        
        delete [SELECT id from Master_Source__c LIMIT 10];
        delete [SELECT id from Source__c  LIMIT 10];
	}
	
	static TestMethod void lead_Tests_UnitTest(){
		Test.startTest();
		Database.executeBatch(new CreateSourceFromLeadBatch(),100);
        Test.stopTest();
	}
}