force-app/main/default/objects/Lead/fields/Introduction_Source__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Source__c</fullName>
    <inlineHelpText>If the introduction source is Website Chat Bot, please review the past activities to view the conversation in Drift.</inlineHelpText>
    <label>Introduction Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Introduction_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Subsource__c</fullName>
    <label>Introduction Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Introduction_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS  East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>CA Realtors Expo</fullName>
                <label>California Realtors Expo</label>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>CREFC</fullName>
            </value>
            <value>
                <fullName>CRELC</fullName>
            </value>
            <value>
                <fullName>Crittenden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Owner_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Owner_Timezone__c</fullName>
    <formula>IF(TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Los_Angeles&quot; ||TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Tijuana&quot;, &quot;PST&quot;, 

IF(TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Denver&quot; || TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Phoenix&quot; , &quot;MST&quot;, 

IF(TEXT(Owner:User.TimeZoneSidKey)= &quot;America/New_York&quot; || TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Panama&quot; || TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Indiana/Indianapolis&quot;, &quot;EST&quot;,
 
IF(TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Chicago&quot;, &quot;CST&quot;,
IF(TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Anchorage&quot;, &quot;AST&quot;,
IF(TEXT(Owner:User.TimeZoneSidKey)= &quot;America/Adak&quot;, &quot;Hawaii-Aleutian Standard Time&quot;,



&quot;N/A&quot;))))))</formula>
    <label>Owner Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Leads.recordType-meta.xml
<RecordType>
    <fullName>Leads</fullName>
    <active>true</active>
    <businessProcess>Leads</businessProcess>
    <description>CAF Leads</description>
    <label>Leads</label>
</RecordType>

force-app/main/default/classes/LeadsLeftOpenEndofDayReportEst.cls
global class LeadsLeftOpenEndofDayReportEst implements Schedulable{
    global void execute(SchedulableContext SC) {
        string reportLink = 'https://cvest--qa.my.salesforce.com/a17/o' ;
       list<id> leadOwner =new list<id>();
       list<user> ignoreUser = new list<user>([SELECT id FROM user WHERE Full_Name__c = 'Andrea Reed' 
                                                OR Full_Name__c = 'Tuan Pham'
                                                OR Full_Name__c = 'Brad Chmura'
                                                OR Full_Name__c = 'Tom Basmajian'
                                                OR Full_Name__c = 'Liz Roling']);

        //Lead Created Dates Start 3PM CA time to 3PM CA Time
        list<lead> leadList = new list<lead>([SELECT OwnerId FROM lead WHERE Status = 'Open' 
                                              AND Introduction_Source__c != 'Imported Leads'
                                              AND Introduction_Source__c != 'Imported List'
                                              AND Introduction_Source__c != 'Event'
                                              AND Introduction_Source__c != 'Referral'
                                              AND Introduction_Source__c != 'Non-Database'
                                              AND Introduction_Source__c != null
                                              AND  Owner_Timezone__c	!= 'PST'
                                              AND CreatedDate <=: System.now()
                                              AND CreatedDate >=: System.now()-7
                                              AND (NOT Introduction_Subsource__c like '%Tower List%')
                                              AND OwnerId Not IN:ignoreUser
                                             ]); 
        if(leadList.size() > 0){
            for(Lead l : leadList){
                leadOwner.add(l.ownerId);
                    }
        }
        if(leadOwner.size() > 0){
   	sendMail(leadOwner);
        }
    }
    public void sendMail(list<id> leadOwner){
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE developerName = 'Leads_Left_Open_Report' LIMIT 1];

        list <id> usersToEmail = new list<id>();
        set <Id> listDedupe = new set<id>();
        listDedupe.addAll(leadOwner);
        usersToEmail.addAll(listDedupe);
        
    Messaging.MassEmailMessage reportEmail = new Messaging.MassEmailMessage(); 
	reportEmail.setTargetObjectIds(usersToEmail);
    reportEmail.setTemplateId(et.id);
    reportEmail.setSenderDisplayName('CoreVest');
    reportEmail.saveAsActivity = false;
    Messaging.sendEmail(new Messaging.MassEmailMessage[] {reportEmail});    
    }
}