force-app/main/default/objects/Opportunity/fields/Advance_Period__c.field-meta.xml
<CustomField>
    <fullName>Advance_Period__c</fullName>
    <description>Bridge Use</description>
    <label>Advance Period Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IC_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>IC_Approval_Date__c</fullName>
    <description>Date of Investment Committee Approval</description>
    <inlineHelpText>Date of Investment Committee Approval</inlineHelpText>
    <label>IC Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Effective_Date__c</fullName>
    <description>Bridge Use</description>
    <label>Loan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Term__c.field-meta.xml
<CustomField>
    <fullName>LOC_Term__c</fullName>
    <businessOwnerGroup>Bridge_Ops</businessOwnerGroup>
    <description>Bridge Use</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>15 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>21 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>30 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>540 Days</fullName>
            </value>
            <value>
                <fullName>630 Days</fullName>
            </value>
            <value>
                <fullName>720 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Loc_BatchableTest.cls
@isTest
private class Loc_BatchableTest {
  @testSetup
  static void setup() {
    List<Account> testAccts = new List<Account>();
    for (Integer i = 0; i < 2; i++) {
      testAccts.add(
        new Account(
          Name = 'TestAcct' + i,
          BillingCountry = 'United States',
          BillingState = 'California',
          Phone = '1122334455'
        )
      );
    }
    //insert testAccts;
  }

  static testMethod void testMethod1() {
    test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);

    Id termLoanRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get('Bridge Loan')
      .getRecordTypeId();
    opp.RecordTypeId = termLoanRecordTypeId;
    update opp;
    opp.IC_Approval_Date__c = System.today() - 5;
    opp.StageName = 'Closed Won';
    opp.Loan_Effective_Date__c = System.today() - 5;
    opp.Advance_Period__c = 3;
    opp.LOC_Term__c = '12 Months';
    update opp;

    Test.startTest();
    loc_Batchable.reschedule(10);
    List<String> listTestOpportunityId = new List<String>();
    listTestOpportunityId.add(opp.Id);
    loc_Batchable.processIds(listTestOpportunityId);
    Database.executeBatch(new loc_Batchable());
    Test.stopTest();
  }
}