force-app/main/default/objects/Opportunity/fields/Advance_Period__c.field-meta.xml
<CustomField>
    <fullName>Advance_Period__c</fullName>
    <description>Bridge Use</description>
    <label>Advance Period Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Term__c.field-meta.xml
<CustomField>
    <fullName>LOC_Term__c</fullName>
    <businessOwnerGroup>Bridge_Ops</businessOwnerGroup>
    <description>Bridge Use</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>15 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>21 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>30 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>540 Days</fullName>
            </value>
            <value>
                <fullName>630 Days</fullName>
            </value>
            <value>
                <fullName>720 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maturity_Date_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date_Calculation_Type__c</fullName>
    <description>This controls when the Loan Maturity Date is set</description>
    <inlineHelpText>This controls when the Loan Maturity Date is set</inlineHelpText>
    <label>Maturity Date Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed at Closing</fullName>
            </value>
            <value>
                <fullName>Fixed at First Advance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Modified_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Modified_Expiration_Date__c</fullName>
    <description>This Date is populated when a Loan Modification is completed/approved.  This date will populate the Expiration Date via a formula</description>
    <inlineHelpText>This Date is populated when a Loan Modification is completed/approved</inlineHelpText>
    <label>Modified Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stated_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Stated_Maturity_Date__c</fullName>
    <description>The Original Stated Loan Level Maturity Date</description>
    <inlineHelpText>The Original Stated Loan Level Maturity Date</inlineHelpText>
    <label>Original Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Updated_Loan_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Updated_Loan_Maturity_Date__c</fullName>
    <description>This is used to override the Loan Maturity Date for overrides and Loan Modifications</description>
    <label>Current Loan Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DealBatchable.cls
global class DealBatchable implements Database.Batchable<sObject> {
  global final string templateDevName = 'Maturity_Date_Set_90_Days_From_Closing_1629747499258';

  global Database.QueryLocator start(Database.BatchableContext context) {
    Date dateLimit = Date.today().addDays(-90);
    return Database.getQueryLocator(
      ('SELECT Id, LOC_Term__c, Advance_Period__c' +
      ' FROM Opportunity' +
      ' WHERE' +
      ' Maturity_Date_Calculation_Type__c = \'Fixed at First Advance\'' +
      ' AND Stated_Maturity_Date__c = NULL' +
      ' AND CloseDate <= ' +
      Datetime.newInstance(dateLimit.year(), dateLimit.month(), dateLimit.day())
        .format('yyy-MM-dd'))
    );
  }

  public void execute(
    Database.BatchableContext context,
    List<Opportunity> deals
  ) {
    List<Opportunity> updatedDeals = new List<Opportunity>();
    List<Id> dealIds = new List<Id>();

    System.debug('Scheduled process starts here with deals : ' + deals);
    for (Opportunity deal : deals) {
      Opportunity updDeal = new Opportunity();
      Integer locTerm = Integer.valueOf(deal.LOC_Term__c.split(' ')[0]);
      updDeal.Id = deal.Id;
      updDeal.Stated_Maturity_Date__c = deal.CloseDate.addDays(locTerm);
      updDeal.Updated_Loan_Maturity_Date__c = deal.CloseDate.addDays(locTerm);
      updDeal.Modified_Expiration_Date__c = deal.CloseDate
        .addDays(Integer.valueOf(deal.Advance_Period__c));
      dealIds.add(deal.Id);
      updatedDeals.add(updDeal);
    }

    update updatedDeals;

    EmailTemplate tpl = [
      SELECT Id
      FROM EmailTemplate
      WHERE DeveloperName = :templateDevName
      LIMIT 1
    ];

    for (Opportunity deal : updatedDeals) {
      System.debug('Scheduled process loops through email method here.');
      AdvanceDealTriggerHelper.sendEmailForDealTrigger(deal.Id, tpl.Id);
    }

    System.debug('Scheduled process ends here');
  }

  public void finish(Database.BatchableContext context) {
    system.debug('Scheduled process success');
  }
}