force-app/main/default/objects/Opportunity/fields/Apex_Context__c.field-meta.xml
<CustomField>
    <fullName>Apex_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for development work only</description>
    <label>Apex Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Sub_Source__c</fullName>
    <label>Deal Intro Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deal_Intro_Source__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>5Arch</fullName>
                <label>5arch</label>
            </value>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>ABS East</fullName>
            </value>
            <value>
                <fullName>ABS West</fullName>
            </value>
            <value>
                <fullName>ACOF</fullName>
            </value>
            <value>
                <fullName>ADC Roadshow</fullName>
            </value>
            <value>
                <fullName>Americatalyst</fullName>
            </value>
            <value>
                <fullName>Answering Service</fullName>
            </value>
            <value>
                <fullName>Anthony Elgort Sourced</fullName>
            </value>
            <value>
                <fullName>Asset Based Lending</fullName>
            </value>
            <value>
                <fullName>BiggerPockets</fullName>
            </value>
            <value>
                <fullName>BiggerPockets Conference</fullName>
            </value>
            <value>
                <fullName>Boris Zhuravel Sourced</fullName>
            </value>
            <value>
                <fullName>Brad Chmura Sourced</fullName>
            </value>
            <value>
                <fullName>Brady Regier Sourced</fullName>
            </value>
            <value>
                <fullName>Brandon Turk Sourced</fullName>
            </value>
            <value>
                <fullName>Brendan Hamilton Sourced</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker+</fullName>
            </value>
            <value>
                <fullName>California Mortgage Expo</fullName>
            </value>
            <value>
                <fullName>California Realtors Expo</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Churchill Real Estate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Collective Genius</fullName>
            </value>
            <value>
                <fullName>Colony AF</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>CoreVest MSA</fullName>
            </value>
            <value>
                <fullName>Correspondent</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Draw_Period__c.field-meta.xml
<CustomField>
    <fullName>Draw_Period__c</fullName>
    <description>Bridge model pricing request field for Draw Period Term,</description>
    <inlineHelpText>Requested Advance Period = &apos;Draw Period&apos; in Pricing Model</inlineHelpText>
    <label>Requested Advance Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <description>Bridge Use</description>
    <inlineHelpText>CAF Retained Fee *Broker Fee is taken out of the Advance Fee*</inlineHelpText>
    <label>Advance Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Line_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Line_Expiration__c</fullName>
    <description>Bridge model pricing request field for Line Expiration</description>
    <inlineHelpText>Requested Term = &apos;Line Expiration&apos;&apos; in Pricing Model</inlineHelpText>
    <label>Requested Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maturity_Date_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date_Calculation_Type__c</fullName>
    <description>This controls when the Loan Maturity Date is set</description>
    <inlineHelpText>This controls when the Loan Maturity Date is set</inlineHelpText>
    <label>Maturity Date Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed at Closing</fullName>
            </value>
            <value>
                <fullName>Fixed at First Advance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Repayment_Period__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Period__c</fullName>
    <description>Bridge model pricing request field for Repayment Period</description>
    <label>Requested Repayment Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Draw_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Draw_Fee__c</fullName>
    <description>Bridge model pricing request field for Draw Fee
Requested Advance Fee = &apos;Draw Fee&apos; in Pricing Model</description>
    <inlineHelpText>This is the Advance Fee reflected in a Term Sheet</inlineHelpText>
    <label>Requested Advance Fee</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Draw_Fee_Cap__c.field-meta.xml
<CustomField>
    <fullName>Requested_Draw_Fee_Cap__c</fullName>
    <description>Bridge model pricing request values for Draw Fee Cap</description>
    <inlineHelpText>Requested Advance Fee Cap = &apos;Draw Fee Cap&apos; in Pricing Model</inlineHelpText>
    <label>Requested Advance Fee Cap</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Initial Line Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Exit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Exit_Fee__c</fullName>
    <description>Bridge model pricing request field for Exit Fee</description>
    <label>Requested Exit Fee</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>Requested_Interest_Type__c</fullName>
    <description>Bridge model pricing request values for Requested Interest Type</description>
    <label>Requested Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_LTC_Max__c.field-meta.xml
<CustomField>
    <fullName>Requested_LTC_Max__c</fullName>
    <description>Bridge model pricing request field for Requested LTC Max</description>
    <label>Requested Initial LTC</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_LTV_Max__c.field-meta.xml
<CustomField>
    <fullName>Requested_LTV_Max__c</fullName>
    <description>Bridge model pricing request field for Requested LTV Max</description>
    <label>Requested Initial LTV</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Origination_Fee__c</fullName>
    <description>Bridge model pricing request field for Origination Fees</description>
    <label>Requested Origination Fee</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Rate_1_9_Months__c.field-meta.xml
<CustomField>
    <fullName>Requested_Rate_1_9_Months__c</fullName>
    <description>Bridge model pricing request values for Requested Rates</description>
    <label>Requested Rate</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Revolving__c.field-meta.xml
<CustomField>
    <fullName>Requested_Revolving__c</fullName>
    <description>Bridge model pricing request values for Requesting Revolvoing t</description>
    <label>Requested Revolving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Acquired_Bridge_Loan.recordType-meta.xml
<RecordType>
    <fullName>Acquired_Bridge_Loan</fullName>
    <active>true</active>
    <businessProcess>Acquired Bridge Business Process</businessProcess>
    <description>Acquired Bridge Loan</description>
    <label>Acquired Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/globalValueSets/LOC_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6 Months</fullName>
    </customValue>
    <customValue>
        <fullName>9 Months</fullName>
    </customValue>
    <customValue>
        <fullName>12 Months</fullName>
    </customValue>
    <customValue>
        <fullName>15 Months</fullName>
    </customValue>
    <customValue>
        <fullName>18 Months</fullName>
    </customValue>
    <customValue>
        <fullName>20 Months</fullName>
    </customValue>
    <customValue>
        <fullName>21 Months</fullName>
    </customValue>
    <customValue>
        <fullName>24 Months</fullName>
    </customValue>
    <customValue>
        <fullName>30 Months</fullName>
    </customValue>
    <customValue>
        <fullName>36 Months</fullName>
    </customValue>
    <customValue>
        <fullName>540 Days</fullName>
    </customValue>
    <customValue>
        <fullName>630 Days</fullName>
    </customValue>
    <customValue>
        <fullName>720 Days</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>33 Months</fullName>
        <isActive>false</isActive>
        <label>33 Months</label>
    </customValue>
    <customValue>
        <fullName>27 Months</fullName>
        <isActive>false</isActive>
        <label>27 Months</label>
    </customValue>
    <customValue>
        <fullName>3 Months</fullName>
        <isActive>false</isActive>
        <label>3 Months</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <description>Terms for LOC Loans</description>
    <masterLabel>LOC Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DrawAdvanceProcessHandlerTest.cls
@isTest
public class DrawAdvanceProcessHandlerTest {
@testsetup
  static void datasetup() {
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    List<Opportunity> oppList = new List<Opportunity>();
    Opportunity opp = new Opportunity();
    Opportunity opp1 = new Opportunity();
    opp.Name = 'test';
    opp.CloseDate = System.today();
    opp.StageName = 'Initial Review';
    opp.Loan_Size__c = 2000000;
    opp.AccountId = acc.Id;
    opp.Contact__c = cont.Id;
    opp.Deal_Intro_Source__c = 'Hotline';
    opp.Deal_Intro_Sub_Source__c = 'Main';
    opp.Apex_Context__c = true;
    opp.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
    ]
    .Id;
    opp.Apex_Context__c = true;
    opp.StageName = 'Hold';
    //opp.Draw_Period__c = '12 Months';
    //opp.Repayment_Period__c = '9 Months';
    opp.LOC_Loan_Type__c = 'Credit Line';
    opp.Loan_Size__c = 3000000;
    opp.Maturity_Date_Calculation_Type__c = 'Fixed at Closing';
    //opp.Line_Expiration__c = '18 Months';
    opp.Requested_LTC_Max__c = 70;
    opp.Requested_LTV_Max__c = 80;
    opp.Requested_Origination_Fee__c = 0;
    opp.Requested_Draw_Fee__c = 2;
    opp.Requested_Exit_Fee__c = 0;
    opp.Requested_Interest_Type__c = 'Fixed';
    opp.Requested_Rate_1_9_Months__c = 10;
    opp.Requested_Revolving__c = 'Yes';
    opp.Requested_Draw_Fee_Cap__c = 'None';
    opp.Product_Sub_Type__c = 'No Renovation';
    opp.Interest_Rate_Type__c = 'Floating';
    opp.Index__c = '1M LIBOR';
    opp.Commission_Type__c = 'Internal';
   // opp.Index_Floor__c = '1.00%';
    opp.Index_Margin__c = 1.50;
    opp.Deal_Intro_Source__c = 'Hotline';
    opp.Deal_Intro_Sub_source__c = 'Direct Mail';
    opp.Fee__c = 2;
    opp.Warehouse_Line__c = 'MS3';
      
    opp1.Name = 'test1';
    opp1.CloseDate = System.today();
    opp1.StageName = 'Initial Review';
    opp1.Loan_Size__c = 2000000;
    opp1.AccountId = acc.Id;
    opp1.Contact__c = cont.Id;
    opp1.Deal_Intro_Source__c = 'Hotline';
    opp1.Deal_Intro_Sub_Source__c = 'Main';
    opp1.Apex_Context__c = true;
    opp1.AccountId = acc.id;
    opp1.Contact__c = cont.id;
    opp1.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Acquired_Bridge_Loan'
    ]
    .Id;
    opp1.StageName = 'Loan Processing';
    //opp1.Draw_Period__c = '12 Months';
    //opp1.Repayment_Period__c = '9 Months';
    opp1.LOC_Loan_Type__c = 'Credit Line';
    opp1.Loan_Size__c = 3000000;
    opp1.Maturity_Date_Calculation_Type__c = 'Fixed at Closing';
    //opp1.Line_Expiration__c = '18 Months';
    opp1.Requested_LTC_Max__c = 70;
    opp1.Requested_LTV_Max__c = 80;
    opp1.Requested_Origination_Fee__c = 0;
    opp1.Requested_Draw_Fee__c = 2;
    opp1.Requested_Exit_Fee__c = 0;
    opp1.Requested_Interest_Type__c = 'Fixed';
    opp1.Requested_Rate_1_9_Months__c = 10;
    opp1.Requested_Revolving__c = 'Yes';
    opp1.Requested_Draw_Fee_Cap__c = 'None';
    opp1.Product_Sub_Type__c = 'No Renovation';
    opp1.Interest_Rate_Type__c = 'Floating';
    opp1.Index__c = '1M LIBOR';
    opp1.Warehouse_Line__c = 'MS3';
    opp1.Commission_Type__c = 'Internal';
    //opp1.Index_Floor__c = '1.00%';
    opp1.Index_Margin__c = 1.50;
    opp1.Deal_Intro_Source__c = 'Hotline';
    opp1.Deal_Intro_Sub_source__c = 'Direct Mail';
    opp1.Fee__c = 2;
    opp1.Aggregate_Funding__c = 55000000;
    opp1.Loan_Effective_Date__c = system.today().addDays(-3);
    opp1.CloseDate = system.today().addDays(-3);
    oppList.add(opp);
    oppList.add(opp1);
    insert oppList;
      
    property__c property = new Property__c();
    property.Name = 'Test1';
    property.Deal__c = oppList[0].Id;
    property.Escrow_Company_text__c = 'ESCROW';
    property.Insurance_Company_text__c = 'INSURANCE';
    property.Status__c = 'Closing';
    property.Override_Origination_Fee__c = 1000;
    property.Acquisition_Price__c = 600000;
    property.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE
        sobjecttype = 'Property__c'
        AND DeveloperName = 'Bridge_No_Renovation'
    ]
    .Id;
    insert property;
 	Advance__c adv = new Advance__c(Deal__c = opp1.Id);
    insert adv;      
      
  }
    
public static testMethod void DrawAdvanceProcessHandler_UnitTest1() {
    
    Test.startTest();
    List<opportunity> opp = [select id,Deal_Loan_Number__c from opportunity where Name = 'test'];
    List<opportunity> opp1 = [select id,Deal_Loan_Number__c from opportunity where Name = 'test1'];
    List<Advance__c> adv = [select Advance_Num__c from Advance__c where deal__c = :opp1[0].id];
    
      Messaging.InboundEmail email = new Messaging.InboundEmail() ;
      Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
       
      email.subject = 'Create Task';
      email.fromAddress = 'support@cvest.com';
      email.plainTextBody = 'Test Task Creation';
      
      String fileBody = 'Loan ID,Loan Name,MortgageLoan Initial Funded Amount,Origination Date,Monthly Debt Service,Interest Rate,Origination Date,First Payment Date,Initial Maturity Date,Borrower Name,Sponsor _name';
      fileBody = fileBody + '\r\n' + opp[0].Deal_Loan_Number__c + ',Test Loan1,"1,000",6/3/2022,1000,0.999,6/3/2022,3/9/2022,1/1/2000,Test Borrower1,Test Sponser Name 1';
      Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
      attachment.body = blob.valueOf(fileBody);
      attachment.fileName = 'Term.csv';
      attachment.mimeTypeSubType = 'text/plain';
      
      String fileBody1 = 'Loan ID,SF Asset ID,Loan Name,Address (Street),City,State,Zip,County,Advance #,,Loan ID,Loan Name,LOC Closing Date,LOC Commitment';
      fileBody1 = fileBody1 + '\r\n' + opp1[0].Deal_Loan_Number__c + ',123456,Testing Name,123 testing address,testing,ca,33209,test,' + adv[0].Advance_Num__c + ',,38553,LJ Phoenician Properties LLC,12/9/2021,1000';
      Messaging.InboundEmail.BinaryAttachment attachment1 = new Messaging.InboundEmail.BinaryAttachment();
      attachment1.body = blob.valueOf(fileBody1);
      attachment1.fileName = 'Bridge.csv';
      attachment1.mimeTypeSubType = 'text/plain';
      
      email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment,attachment1 };
      
 
      /*Messaging.InboundEmail.TextAttachment attachmenttext = new Messaging.InboundEmail.TextAttachment();
      attachmenttext.body = 'Create Task';
      attachmenttext.fileName = 'Term.csv';
      attachmenttext.mimeTypeSubType = 'texttwo/plain';
      email.textAttachments =   new Messaging.inboundEmail.TextAttachment[] { attachmenttext };*/
      
      
      // call the email service class and test it with the data in the testMethod
      DrawAdvanceProcessHandler testInbound = new DrawAdvanceProcessHandler();
      testInbound.handleInboundEmail(email, env);
    Test.stopTest();
  }
public static testMethod void DrawAdvanceProcessHandler_UnitTest2() {
    
    Test.startTest();
    List<opportunity> opp = [select id,Deal_Loan_Number__c from opportunity where Name = 'test'];
    List<opportunity> opp1 = [select id,Deal_Loan_Number__c from opportunity where Name = 'test1'];
    List<Advance__c> adv = [select Advance_Num__c from Advance__c where deal__c = :opp1[0].id];
    
      Messaging.InboundEmail email = new Messaging.InboundEmail() ;
      Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
       
      email.subject = 're:Create Task';
      email.fromAddress = 'support@cvest.com';
      email.plainTextBody = 'Test Task Creation';
      
      String fileBody = 'Load ID,Loan Name,MortgageLoan Initial Funded Amount,Origination Date,Monthly Debt Service,Interest Rate,Origination Date,First Payment Date,Initial Maturity Date,Borrower Name,Sponsor _name';
      fileBody = fileBody + '\r\n' + opp[0].Deal_Loan_Number__c + ',Test Loan1,1000,6/3/2022,1000,0.999,6/3/2022,3/9/2022,1/1/2000,Test Borrower1,Test Sponser Name 1';
      Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
      attachment.body = blob.valueOf(fileBody);
      attachment.fileName = 'Term.csv';
      attachment.mimeTypeSubType = 'text/plain';
      
      String fileBody1 = 'Loan ID,SF Asset ID,Loan Name,Address (Street),City,State,Zip,County,Advance #,,Loan ID,Loan Name,LOC Closing Date,LOC Commitment';
      fileBody1 = fileBody1 + '\r\n' + opp1[0].Deal_Loan_Number__c + ',123456,Testing Name,123 testing address,testing,ca,33209,test,' + adv[0].Advance_Num__c + ',,38553,LJ Phoenician Properties LLC,12/9/2021,1000';
      Messaging.InboundEmail.BinaryAttachment attachment1 = new Messaging.InboundEmail.BinaryAttachment();
      attachment1.body = blob.valueOf(fileBody1);
      attachment1.fileName = 'Bridge.csv';
      attachment1.mimeTypeSubType = 'text/plain';
      
      email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment,attachment1 };
      
 
      /*Messaging.InboundEmail.TextAttachment attachmenttext = new Messaging.InboundEmail.TextAttachment();
      attachmenttext.body = 'Create Task';
      attachmenttext.fileName = 'Term.csv';
      attachmenttext.mimeTypeSubType = 'texttwo/plain';
      email.textAttachments =   new Messaging.inboundEmail.TextAttachment[] { attachmenttext };*/
      
      
      // call the email service class and test it with the data in the testMethod
      DrawAdvanceProcessHandler testInbound = new DrawAdvanceProcessHandler();
      testInbound.handleInboundEmail(email, env);
    Test.stopTest();
  }    
}