force-app/main/default/objects/Opportunity/fields/Apex_Context__c.field-meta.xml
<CustomField>
    <fullName>Apex_Context__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for development work only</description>
    <label>Apex Context</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Intro_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Intro_Source__c</fullName>
    <description>This is the introduction source at the deal if it is different from the original intro source</description>
    <inlineHelpText>Enter the introduction Source of the deal</inlineHelpText>
    <label>Deal Intro Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email Blast</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hotline</fullName>
            </value>
            <value>
                <fullName>Imported List</fullName>
            </value>
            <value>
                <fullName>Non-Database</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Draw_Period__c.field-meta.xml
<CustomField>
    <fullName>Draw_Period__c</fullName>
    <description>Bridge model pricing request field for Draw Period Term,</description>
    <inlineHelpText>Requested Advance Period = &apos;Draw Period&apos; in Pricing Model</inlineHelpText>
    <label>Requested Advance Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>Secured Overnight Financing Rate (SOFR)</description>
    <label>Index</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Rate_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1M SOFR</fullName>
            </value>
            <value>
                <fullName>3M SOFR</fullName>
            </value>
            <value>
                <fullName>6M SOFR</fullName>
            </value>
            <value>
                <fullName>1Y SOFR</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Index_Margin__c.field-meta.xml
<CustomField>
    <fullName>Index_Margin__c</fullName>
    <description>Floating Index Margin field set back to percentage, user who enters basis points will need to use percent instead.</description>
    <label>Margin</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <label>Interest Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Line_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Line_Expiration__c</fullName>
    <description>Bridge model pricing request field for Line Expiration</description>
    <inlineHelpText>Requested Term = &apos;Line Expiration&apos;&apos; in Pricing Model</inlineHelpText>
    <label>Requested Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Maturity_Date_Calculation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Size__c.field-meta.xml
<CustomField>
    <fullName>Loan_Size__c</fullName>
    <label>Requested Loan Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Loan_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Line</fullName>
            </value>
            <value>
                <fullName>Single Asset (1-4 Unit)</fullName>
            </value>
            <value>
                <fullName>Single Asset (5-10 Unit)</fullName>
            </value>
            <value>
                <fullName>Multifamily/CRE</fullName>
            </value>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Model Home Lease</fullName>
            </value>
            <value>
                <fullName>Purchased Bridge</fullName>
            </value>
            <value>
                <fullName>Term Loan</fullName>
            </value>
            <value>
                <fullName>Single Rental Loan</fullName>
            </value>
            <value>
                <fullName>Investor DSCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Repayment_Period__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Period__c</fullName>
    <description>Bridge model pricing request field for Repayment Period</description>
    <label>Requested Repayment Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOC_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Draw_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Draw_Fee__c</fullName>
    <description>Bridge model pricing request field for Draw Fee
Requested Advance Fee = &apos;Draw Fee&apos; in Pricing Model</description>
    <inlineHelpText>This is the Advance Fee reflected in a Term Sheet</inlineHelpText>
    <label>Requested Advance Fee</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Draw_Fee_Cap__c.field-meta.xml
<CustomField>
    <fullName>Requested_Draw_Fee_Cap__c</fullName>
    <description>Bridge model pricing request values for Draw Fee Cap</description>
    <inlineHelpText>Requested Advance Fee Cap = &apos;Draw Fee Cap&apos; in Pricing Model</inlineHelpText>
    <label>Requested Advance Fee Cap</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Initial Line Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Exit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Exit_Fee__c</fullName>
    <description>Bridge model pricing request field for Exit Fee</description>
    <label>Requested Exit Fee</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>Requested_Interest_Type__c</fullName>
    <description>Bridge model pricing request values for Requested Interest Type</description>
    <label>Requested Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_LTC_Max__c.field-meta.xml
<CustomField>
    <fullName>Requested_LTC_Max__c</fullName>
    <description>Bridge model pricing request field for Requested LTC Max</description>
    <label>Requested Initial LTC</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_LTV_Max__c.field-meta.xml
<CustomField>
    <fullName>Requested_LTV_Max__c</fullName>
    <description>Bridge model pricing request field for Requested LTV Max</description>
    <label>Requested Initial LTV</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Requested_Origination_Fee__c</fullName>
    <description>Bridge model pricing request field for Origination Fees</description>
    <label>Requested Origination Fee</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Rate_1_9_Months__c.field-meta.xml
<CustomField>
    <fullName>Requested_Rate_1_9_Months__c</fullName>
    <description>Bridge model pricing request values for Requested Rates</description>
    <label>Requested Rate</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Revolving__c.field-meta.xml
<CustomField>
    <fullName>Requested_Revolving__c</fullName>
    <description>Bridge model pricing request values for Requesting Revolvoing t</description>
    <label>Requested Revolving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/LOC_Loan.recordType-meta.xml
<RecordType>
    <fullName>LOC_Loan</fullName>
    <active>true</active>
    <businessProcess>Bridge Process</businessProcess>
    <label>Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Term_Loan.recordType-meta.xml
<RecordType>
    <fullName>Term_Loan</fullName>
    <active>true</active>
    <businessProcess>Term Process</businessProcess>
    <label>Term Loan</label>
</RecordType>

force-app/main/default/globalValueSets/LOC_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6 Months</fullName>
    </customValue>
    <customValue>
        <fullName>9 Months</fullName>
    </customValue>
    <customValue>
        <fullName>12 Months</fullName>
    </customValue>
    <customValue>
        <fullName>15 Months</fullName>
    </customValue>
    <customValue>
        <fullName>18 Months</fullName>
    </customValue>
    <customValue>
        <fullName>20 Months</fullName>
    </customValue>
    <customValue>
        <fullName>21 Months</fullName>
    </customValue>
    <customValue>
        <fullName>24 Months</fullName>
    </customValue>
    <customValue>
        <fullName>30 Months</fullName>
    </customValue>
    <customValue>
        <fullName>36 Months</fullName>
    </customValue>
    <customValue>
        <fullName>540 Days</fullName>
    </customValue>
    <customValue>
        <fullName>630 Days</fullName>
    </customValue>
    <customValue>
        <fullName>720 Days</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>33 Months</fullName>
        <isActive>false</isActive>
        <label>33 Months</label>
    </customValue>
    <customValue>
        <fullName>27 Months</fullName>
        <isActive>false</isActive>
        <label>27 Months</label>
    </customValue>
    <customValue>
        <fullName>3 Months</fullName>
        <isActive>false</isActive>
        <label>3 Months</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <description>Terms for LOC Loans</description>
    <masterLabel>LOC Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DealFieldValidationTests.cls
@isTest
private class DealFieldValidationTests {
  static testMethod void test1() {
    Test_Helper.createRate();
    Test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
    opp.Apex_Context__c = true;
    opp.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'LOC_Loan'
    ]
    .Id;
    opp.StageName = 'Hold';
    opp.Draw_Period__c = '12 Months';
    opp.Repayment_Period__c = '9 Months';
    opp.LOC_Loan_Type__c = 'Credit Line';
    opp.Loan_Size__c = 3000000;
    opp.Line_Expiration__c = '18 Months';
    opp.Requested_LTC_Max__c = 70;
    opp.Requested_LTV_Max__c = 80;
    opp.Requested_Origination_Fee__c = 0;
    opp.Requested_Draw_Fee__c = 2;
    opp.Requested_Exit_Fee__c = 0;
    opp.Requested_Interest_Type__c = 'Fixed';
    opp.Requested_Rate_1_9_Months__c = 10;
    opp.Requested_Revolving__c = 'Yes';
    opp.Requested_Draw_Fee_Cap__c = 'None';
    opp.Product_Sub_Type__c = 'Renovation';
    opp.Interest_Rate_Type__c = 'Floating';
    opp.Index__c = '1M LIBOR';
    opp.Floor__c = 1.00;
    opp.Index_Margin__c = 1.50;
    opp.Deal_Intro_Source__c = 'Hotline';
    opp.Deal_Intro_Sub_source__c = 'Main';

    update opp;

    List<Property__c> property = new List<Property__c>();
    for (Integer i = 0; i < 20; i++) {
      property.add(
        new Property__c(
          Name = 'Test + ' + i,
          Property_Name__c = 'Test + ' + i,
          Deal__c = opp.Id,
          Escrow_Company_text__c = 'ESCROW',
          Insurance_Company_text__c = 'INSURANCE',
          Status__c = 'Active'
        )
      );
    }

    property[0].Status__c = 'Inactive';
    property[1].Status__c = 'Inactive';
    property[2].Payoff_Received_Date__c = system.today();
    insert property;

    // update opp;

    // opp.Record_Type_Name__c = 'LOC_Loan';

    Opportunity queriedOpp = (Opportunity) util.queryRecordAllFields(opp.Id);
    queriedOpp.StageName = 'Underwriting';

    Opportunity opp2 = queriedOpp.clone(true, false, false, false);
    opp2.StageName = 'Approved by Committee';

    Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>(
      new List<Opportunity>{ queriedOpp }
    );

    Map<Id, Opportunity> newMap = new Map<Id, Opportunity>(
      new List<Opportunity>{ opp2 }
    );

    Map<Id, List<Property__c>> dealPropertyMap = new Map<Id, List<Property__c>>();
    dealPropertyMap.put(queriedOpp.Id, property);
    Map<Id, List<Business_Entity__c>> businessEntityMap = new Map<Id, List<Business_Entity__c>>();
    Map<Id, List<Deal_Document__c>> dealDocumentMap = new Map<Id, List<Deal_Document__c>>();

    Test.startTest();
    String errorMessage = DealFieldValidationHelper.validateDeals(
      oldMap,
      newMap,
      dealPropertyMap,
      businessEntityMap,
      dealDocumentMap
    );
    Test.stopTest();
  }

  static testMethod void test2() {
    Test_Helper.createRate();
    Test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    acc.Alternate_Phone__c = '7777777777';
    update acc;
    Contact cont = test_Helper.createContact(acc);
    cont.MobilePhone = '2222222222';
    cont.Phone = '9999999999';
    Opportunity topp1 = test_Helper.createOpportunity(acc, cont);
    topp1.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE sobjecttype = 'Opportunity' AND DeveloperName = 'Term_Loan'
    ]
    .Id;
    topp1.StageName = 'Underwriting';
    topp1.Deal_Intro_Source__c = 'Email';
    topp1.Bridge_Borrower__c = 'No';
    topp1.Are_Assets_Coming_Off_Bridge_Line__c = 'No';
    topp1.Term_Sheet_Signed__c = system.today();
    topp1.Term_Sheet_Issued__c = system.today();
    update topp1;

    Opportunity queriedOpp = (Opportunity) util.queryRecordAllFields(topp1.Id);
    queriedOpp.StageName = 'Underwriting';

    Opportunity opp2 = queriedOpp.clone(true, false, false, false);
    opp2.StageName = 'Approved by Committee';

    Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>(
      new List<Opportunity>{ queriedOpp }
    );

    Map<Id, Opportunity> newMap = new Map<Id, Opportunity>(
      new List<Opportunity>{ opp2 }
    );

    Map<Id, List<Property__c>> dealPropertyMap = new Map<Id, List<Property__c>>();
    Map<Id, List<Business_Entity__c>> businessEntityMap = new Map<Id, List<Business_Entity__c>>();
    Map<Id, List<Deal_Document__c>> dealDocumentMap = new Map<Id, List<Deal_Document__c>>();

    Test.startTest();
    String errorMessage = DealFieldValidationHelper.validateDeals(
      oldMap,
      newMap,
      dealPropertyMap,
      businessEntityMap,
      dealDocumentMap
    );
    Test.stopTest();
  }
}