force-app/main/default/objects/Opportunity/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Closer on this Deal</description>
    <label>Closer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Closer</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Closer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Closer)</relationshipLabel>
    <relationshipName>Deals2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Term and Bridge Use</description>
    <label>Underwriter</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Bridge Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Term Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>SAB Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Underwriter)</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PortalAPIChecklist.cls
@RestResource(urlMapping='/portal/checklist/*')
global without sharing class PortalAPIChecklist {
  public static Id recordId;
  public static Opportunity deal;
  @HttpGet
  global static void doGet() {
    RestRequest req = RestContext.request;
    RestResponse res = Restcontext.response;

    List<String> params = Restcontext.request.requestURI.split('/');

    if (params[3] == 'milestones') {
      recordId = params[4];
      deal = [
        SELECT Id, Owner.Name, Underwriter__r.Name, Closer__r.Name, Type
        FROM Opportunity
        WHERE Id = :recordId
      ];

      Checklist checklist = new Checklist();

      if (deal.Type == 'Term Loan') {
        checklist.milestones = createTermMilestone();
      } else {
        checklist.milestones = createBridgeMilestone();
      }

      res.addHeader('Content-Type', 'application/json');
      res.responseBody = Blob.valueOf(JSON.serialize(checklist));
    }
  }

  public static List<Milestone> createTermMilestone() {
    List<Milestone> milestones = new List<Milestone>();
    milestones.add(
      new Milestone(
        'Initial Screening and Diligence',
        deal.Owner.Name,
        system.today(),
        true
      )
    );
    milestones.add(
      new Milestone(
        'Term Sheet Signed/Deposit Collected',
        deal.Owner.Name,
        null,
        false
      )
    );
    milestones.add(
      new Milestone(
        'Submission to Underwriting',
        deal.Owner.Name,
        system.today(),
        true
      )
    );
    milestones.add(
      new Milestone('Kick-Off', deal.Underwriter__r.Name, null, false)
    );
    milestones.add(
      new Milestone('In Due Diligence', deal.Underwriter__r.Name, null, false)
    );
    milestones.add(
      new Milestone('In Underwriting', deal.Underwriter__r.Name, null, false)
    );
    milestones.add(
      new Milestone('In Closing', deal.Closer__r.Name, null, false)
    );
    milestones.add(
      new Milestone('Wire Scheduled', deal.Closer__r.Name, null, false)
    );
    milestones.add(
      new Milestone('Loan Funded/Closed Loan', deal.Closer__r.Name, null, false)
    );

    return milestones;
  }

  public static List<Milestone> createBridgeMilestone() {
    List<Milestone> milestones = new List<Milestone>();
    milestones.add(
      new Milestone(
        'Initial Screening and Diligence',
        deal.Owner.Name,
        system.today(),
        true
      )
    );
    milestones.add(
      new Milestone(
        'Term Sheet Signed/Deposit Collected',
        deal.Owner.Name,
        null,
        false
      )
    );
    milestones.add(
      new Milestone('Submission to Underwriting', deal.Owner.Name, null, false)
    );
    milestones.add(
      new Milestone('Kick-Off', deal.Underwriter__r.Name, null, false)
    );
    milestones.add(
      new Milestone('In Due Diligence', deal.Underwriter__r.Name, null, false)
    );
    milestones.add(
      new Milestone('In Underwriting', deal.Underwriter__r.Name, null, false)
    );
    milestones.add(
      new Milestone('In Closing', deal.Closer__r.Name, null, false)
    );
    milestones.add(
      new Milestone('Loan Funded/Closed Loan', deal.Closer__r.Name, null, false)
    );

    return milestones;
  }

  public class Checklist {
    List<Milestone> milestones;

    Checklist() {
      milestones = new List<Milestone>();
    }
  }

  public class Milestone {
    String milestone;
    String teamMember;
    Date completedDate;
    Boolean completed;

    Milestone(
      String milestone,
      String teamMember,
      Date completedDate,
      Boolean completed
    ) {
      this.milestone = milestone;
      this.teamMember = teamMember;
      this.completedDate = completedDate;
      this.completed = completed;
    }
  }
}