force-app/main/default/objects/Opportunity/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <description>Current Stage for the Deal</description>
    <formula>text(StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_Locked__c.field-meta.xml
<CustomField>
    <fullName>Rate_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Rate on this Loan has been locked</description>
    <inlineHelpText>Indicates that the Rate on this Loan has been locked</inlineHelpText>
    <label>Rate Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>IF(  
 CONTAINS(RecordType.DeveloperName, &apos;LOC&apos;),
 &apos;Bridge&apos;,
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Term&apos;), 
 &apos;Term&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Loan&apos;), 
 &apos;Single Asset Rental&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Investor_DSCR&apos;), 
 &apos;Investor DSCR&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Bridge&apos;), 
 &apos;Bridge&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Acquired_Bridge_Loan&apos;), 
 &apos;Acquired Bridge Loan&apos;, 
 &apos;&apos;
 ) 
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Swap_Rate__c.field-meta.xml
<CustomField>
    <fullName>Swap_Rate__c</fullName>
    <label>Swap Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Term_Loan_Type__c</fullName>
    <label>Term Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 Year</fullName>
            </value>
            <value>
                <fullName>5 Year</fullName>
            </value>
            <value>
                <fullName>7 Year</fullName>
            </value>
            <value>
                <fullName>10 Year</fullName>
            </value>
            <value>
                <fullName>30 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/Swap_Rate__c.object-meta.xml
<CustomObject>
    <label>Rates</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Swap_Rate__c/fields/Five_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Five_Year_Swap__c</fullName>
    <label>5 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/fields/Seven_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Seven_Year_Swap__c</fullName>
    <label>7 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/fields/Ten_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Ten_Year_Swap__c</fullName>
    <label>10 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/fields/Thirty_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Thirty_Year_Swap__c</fullName>
    <label>30 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/dealSwapRateUpdate.cls
public class dealSwapRateUpdate implements Database.Batchable<sObject>{

     public Database.QueryLocator start(Database.BatchableContext BC){
     String query = 'Select Swap_Rate__c,RecordType__c, Rate_Locked__c, Floor__c, Term_Loan_Type__c,Current_Stage__c from Opportunity where RecordType__c = \'Term\' and Rate_Locked__c = false and Current_Stage__c not in (\'Withdrawn\', \'Rejected\') and id in ((\'0065b00000rqrTLAAY\',\'006j000000OXCPcAAP\',\'0065b00000ruoA6AAI\'))';
     //String query = 'Select Swap_Rate__c,RecordType__c, Rate_Locked__c, Floor__c, Term_Loan_Type__c,Current_Stage__c from Opportunity where RecordType__c = \'Term\' and Rate_Locked__c = false and Current_Stage__c not in (\'Withdrawn\', \'Rejected\')';
     return Database.getQueryLocator(query);
   }
     
     public void execute(Database.BatchableContext BC, List<opportunity> processingDeals){
     

	List<opportunity> dealsToUpdate = new List<opportunity>();
	Boolean updateOpportunity = false; 
	Swap_Rate__c SwapRate = [select Five_Year_Swap__c,Seven_Year_Swap__c,Ten_Year_Swap__c,Thirty_Year_Swap__c from Swap_Rate__c where CreatedDateTime__c != null order by CreatedDateTime__c desc limit 1];                           
     for(opportunity Oppor : processingDeals){
     
       System.debug('RS123 Oppor.id :' +Oppor.id);
       system.debug('RS345 Oppor.Term_Loan_Type__c : ' +Oppor.Term_Loan_Type__c);
       system.debug('RS345 Oppor.Floor__c : ' +Oppor.Floor__c);         
       system.debug('RS345 SwapRate.Five_Year_Swap__c : ' +SwapRate.Five_Year_Swap__c);
       system.debug('RS345 SwapRate.Seven_Year_Swap__c : ' +SwapRate.Seven_Year_Swap__c);
       system.debug('RS345 SwapRate.Ten_Year_Swap__c : ' +SwapRate.Ten_Year_Swap__c);         
       system.debug('RS345 SwapRate.Thirty_Year_Swap__c : ' +SwapRate.Thirty_Year_Swap__c);   
         
       switch on Oppor.Term_Loan_Type__c {
       when '5 Year' {
           if (SwapRate.Five_Year_Swap__c > Oppor.Floor__c)
           {
               Oppor.Swap_Rate__c = SwapRate.Five_Year_Swap__c;
               updateOpportunity = True;
           }
           else
           {
               Oppor.Swap_Rate__c = Oppor.Floor__c;
               updateOpportunity = True;
           }
       }
       when '7 Year' {
           if (SwapRate.Seven_Year_Swap__c > Oppor.Floor__c)
           {
               Oppor.Swap_Rate__c = SwapRate.Seven_Year_Swap__c;
               updateOpportunity = True;
           }
           else
           {
               Oppor.Swap_Rate__c = Oppor.Floor__c;
               updateOpportunity = True;
           }
       }
       when '10 Year' {
           if (SwapRate.Ten_Year_Swap__c > Oppor.Floor__c)
           {
               Oppor.Swap_Rate__c = SwapRate.Ten_Year_Swap__c;
               updateOpportunity = True;
           }
           else
           {
               Oppor.Swap_Rate__c = Oppor.Floor__c;
               updateOpportunity = True;
           }
       }
       when '30 Year' {
           if (SwapRate.Thirty_Year_Swap__c > Oppor.Floor__c)
           {
               Oppor.Swap_Rate__c = SwapRate.Thirty_Year_Swap__c;
               updateOpportunity = True;
           }
           else
           {
               Oppor.Swap_Rate__c = Oppor.Floor__c;
               updateOpportunity = True;
           }
       }           
	  } //switch 
      if (updateOpportunity)
      {
        System.debug('RS999 Add to update Oppor.id :' +Oppor.id);
       system.debug('RS999 Oppor.Term_Loan_Type__c : ' +Oppor.Term_Loan_Type__c);
       system.debug('RS999 Oppor.Floor__c : ' +Oppor.Floor__c); 
       system.debug('RS999 Oppor.Swap_Rate__c : ' +Oppor.Swap_Rate__c);          
     	dealsToUpdate.add(Oppor);
     	updateOpportunity = False;
      }
     } //for

       system.debug('RS345 dealsToUpdate :' +dealsToUpdate);
                    
	if (dealsToUpdate.size() > 0)
	{
        try 
        {
        update dealsToUpdate;
        } 
        catch (DmlException e)
        {
        System.debug( 'Error updating Swap Rates on deal' + e.getMessage());
        }                
	}
	} //method

   public void finish(Database.BatchableContext BC){
              system.debug('RS345 finish:' );
   }
    
}