force-app/main/default/objects/Opportunity/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <description>Current Stage for the Deal</description>
    <formula>text(StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_Locked__c.field-meta.xml
<CustomField>
    <fullName>Rate_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Rate on this Loan has been locked</description>
    <inlineHelpText>Indicates that the Rate on this Loan has been locked</inlineHelpText>
    <label>Rate Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>IF(  
 CONTAINS(RecordType.DeveloperName, &apos;LOC&apos;),
 &apos;Bridge&apos;,
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Term&apos;), 
 &apos;Term&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Loan&apos;), 
 &apos;Single Asset Rental&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Investor_DSCR&apos;), 
 &apos;Investor DSCR&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Single_Asset_Bridge&apos;), 
 &apos;Bridge&apos;, 
IF(
 CONTAINS(RecordType.DeveloperName, &apos;Acquired_Bridge_Loan&apos;), 
 &apos;Acquired Bridge Loan&apos;, 
 &apos;&apos;
 ) 
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data</inlineHelpText>
    <label>Basic Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Swap_Rate__c.field-meta.xml
<CustomField>
    <fullName>Swap_Rate__c</fullName>
    <label>Swap Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Term_Loan_Type__c</fullName>
    <label>Term Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 Year</fullName>
            </value>
            <value>
                <fullName>5 Year</fullName>
            </value>
            <value>
                <fullName>7 Year</fullName>
            </value>
            <value>
                <fullName>10 Year</fullName>
            </value>
            <value>
                <fullName>30 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/Swap_Rate__c.object-meta.xml
<CustomObject>
    <label>Rates</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Swap_Rate__c/fields/Five_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Five_Year_Swap__c</fullName>
    <label>5 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/fields/Seven_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Seven_Year_Swap__c</fullName>
    <label>7 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/fields/Ten_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Ten_Year_Swap__c</fullName>
    <label>10 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Swap_Rate__c/fields/Thirty_Year_Swap__c.field-meta.xml
<CustomField>
    <fullName>Thirty_Year_Swap__c</fullName>
    <label>30 Year Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Update_swap_rates.cls
public class Update_swap_rates {
    
	public Id opportunityId;
    
    public Update_swap_rates(ApexPages.standardController standardController)
    {
        opportunityId = standardController.getId();
       
    }

    public void UpdateRate() {
         Opportunity Oppor= [Select Swap_Rate__c,RecordType__c, Rate_Locked__c, Floor__c, Term_Loan_Type__c,Current_Stage__c 
                       from Opportunity where id = :opportunityId and RecordType__c = 'Term' and Rate_Locked__c = false];
		Swap_Rate__c SwapRate = [select Five_Year_Swap__c,Seven_Year_Swap__c,Ten_Year_Swap__c,Thirty_Year_Swap__c 
                         from Swap_Rate__c order by CreatedDate desc limit 1];
		System.Debug('RS123 SwapRate :' +SwapRate);
        System.Debug('RS Oppor :' +Oppor);
        System.Debug('RS123 Oppor.Term_Loan_Type__c :' +Oppor.Term_Loan_Type__c);
        System.Debug('RS123 Oppor.Floor__c :' +Oppor.Floor__c);
         System.Debug('RS123 SwapRate.Five_Year_Swap__c :' +SwapRate.Five_Year_Swap__c);
        
        if (Oppor.Term_Loan_Type__c == '5 Year')
        {
            if (SwapRate.Five_Year_Swap__c > Oppor.Floor__c)
            {
                Oppor.Swap_Rate__c = SwapRate.Five_Year_Swap__c;
            }
            else
            {
               Oppor.Swap_Rate__c = Oppor.Floor__c;
            }
        }
		update Oppor;        
    }

}