force-app/main/default/objects/Opportunity/fields/Current_UPB__c.field-meta.xml
<CustomField>
    <fullName>Current_UPB__c</fullName>
    <description>Data comes from Servicer</description>
    <label>Current UPB</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Extension_Fee__c.field-meta.xml
<CustomField>
    <fullName>Extension_Fee__c</fullName>
    <label>Extension Fee</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>0.00%</fullName>
            </value>
            <value>
                <fullName>0.25%</fullName>
            </value>
            <value>
                <fullName>0.50%</fullName>
            </value>
            <value>
                <fullName>0.75%</fullName>
            </value>
            <value>
                <fullName>1.00%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Fee__c.field-meta.xml
<CustomField>
    <fullName>Legal_Fee__c</fullName>
    <label>Legal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payoff_Date__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Date__c</fullName>
    <description>Date Drawn Amount was repaid in full (blank for Draw Amounts still outstanding)</description>
    <inlineHelpText>Date Drawn Amount was repaid in full</inlineHelpText>
    <label>Payoff Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Securitized__c.field-meta.xml
<CustomField>
    <fullName>Securitized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate the deal has been securitized in a portfolio</description>
    <label>Securitized?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Appraised_Value_Amount__c.field-meta.xml
<CustomField>
    <fullName>Appraised_Value_Amount__c</fullName>
    <description>Most recent Appraised As Is Value</description>
    <inlineHelpText>Most recent Appraised As Is Value</inlineHelpText>
    <label>Current Appraised As-Is Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/BPO_Appraisal_Date__c.field-meta.xml
<CustomField>
    <fullName>BPO_Appraisal_Date__c</fullName>
    <description>Date of the most recent Appraisal</description>
    <inlineHelpText>Date of the most recent Appraisal</inlineHelpText>
    <label>Current Appraisal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Current_UPB__c.field-meta.xml
<CustomField>
    <fullName>Current_UPB__c</fullName>
    <description>From Servicer</description>
    <inlineHelpText>Updated by Statebridge Servicer Integration.</inlineHelpText>
    <label>Current UPB</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Days_To_Resolve__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Resolve__c</fullName>
    <description>If Extension exists then Payoff Received Date - Extension Completed Date. If no Extension then Payoff Received Date - 60 days prior to Original Asset Maturity Date (use Current Asset Maturity Date if Payoff Received Date &gt; Original Asset Maturity Date).</description>
    <formula>IF( 
   AND(NOT(ISBLANK(Newest_Property_Extension__c)), NOT(ISBLANK(Newest_Property_Extension__r.Extension_Date__c)))
 , Payoff_Received_Date__c - Newest_Property_Extension__r.Extension_Date__c,
      IF(Payoff_Received_Date__c &gt; Asset_Maturity_Date__c
      , Payoff_Received_Date__c -  ( Current_Asset_Maturity_Date__c - 60 )
      ,Payoff_Received_Date__c - ( Asset_Maturity_Date__c  - 60 )
      )
   )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Extension exists then Payoff Received Date - Extension Completed Date. If no Extension then Payoff Received Date - 60 days prior to Original Asset Maturity Date (use Current Asset Maturity Date if Payoff Received Date &gt; Original Asset Maturity Date).</inlineHelpText>
    <label>Days To Resolve</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Payoff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Amount__c</fullName>
    <label>Payoff Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Payoff_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Received_Date__c</fullName>
    <description>The Date that the Property was paid off.  Provided by the servicer</description>
    <label>Payoff Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <description>Date that this Property became Real Estate Owned</description>
    <inlineHelpText>Date that this Property became Real Estate Owned</inlineHelpText>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Securitized__c.field-meta.xml
<CustomField>
    <fullName>Securitized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator of whether or not a property is part of a securitized portfolio.</description>
    <label>Securitized?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Extension__c/Property_Extension__c.object-meta.xml
<CustomObject>
    <label>Property Extension</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Property Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Extension__c/fields/Days_To_Resolve__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Resolve__c</fullName>
    <description>If first extension then calculated as Completed Extension Date - 60 days prior to Original Asset Maturity Date. If the Property Extension Created Date &lt; 60 days prior to Original Asset Maturity Date then use Extension Created Date. Any extension after first calculated as Extension Completed Date - Previous Asset Maturity Date. If Property Extension Created Date &lt; Previous Asset Maturity Date then use Property Extension Created Date.</description>
    <formula>IF(Is_First__c
, IF(DATEVALUE(CreatedDate) &lt; (Original_Asset_Maturity_Date_Formula__c - 60),
Extension_Date__c - DATEVALUE(CreatedDate)
,Extension_Date__c - (Original_Asset_Maturity_Date_Formula__c - 60)
), 
IF(NOT(ISNULL(Previous_Asset_Maturity_Date__c)) &amp;&amp; Previous_Asset_Maturity_Date__c &gt; DATEVALUE(CreatedDate),
Extension_Date__c - DATEVALUE(CreatedDate),
Extension_Date__c - Previous_Asset_Maturity_Date__c
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If first extension then calculated as Completed Extension Date - 60 days prior to Original Asset Maturity Date. If the Property Extension Created Date &lt; 60 days prior to Original Asset Maturity Date then use Extension Created Date. Any extension after first calculated as Extension Completed Date - Previous Asset Maturity Date. If Property Extension Created Date &lt; Previous Asset Maturity Date then use Property Extension Created Date.</inlineHelpText>
    <label>Days To Resolve</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_Extension__c/fields/Extension_Fee__c.field-meta.xml
<CustomField>
    <fullName>Extension_Fee__c</fullName>
    <label>Extension Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/Property_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Property Snapshot</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Property Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Snapshot__c/fields/Current_UPB__c.field-meta.xml
<CustomField>
    <fullName>Current_UPB__c</fullName>
    <label>Current UPB</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Current_Valuation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Valuation_Amount__c</fullName>
    <label>Current Valuation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Current_Valuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Valuation_Date__c</fullName>
    <label>Current Valuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Days_To_Resolve__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Resolve__c</fullName>
    <label>Days To Resolve</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Extension_Fee__c.field-meta.xml
<CustomField>
    <fullName>Extension_Fee__c</fullName>
    <label>Extension Fee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Legal_Fee__c.field-meta.xml
<CustomField>
    <fullName>Legal_Fee__c</fullName>
    <label>Legal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Maturity_Default_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Default_Transfer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Maturity Default Transfer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Payoff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Amount__c</fullName>
    <label>Payoff Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Payoff_Date__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Date__c</fullName>
    <label>Payoff Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Realized_Loss_Severity__c.field-meta.xml
<CustomField>
    <fullName>Realized_Loss_Severity__c</fullName>
    <label>Realized Loss Severity %</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/REO_Sell_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Sell_Date__c</fullName>
    <label>REO Sell Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Resolved_Date__c.field-meta.xml
<CustomField>
    <fullName>Resolved_Date__c</fullName>
    <label>Resolved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Securitized_at_Time_of_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Securitized_at_Time_of_Resolution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Securitized at Time of Resolution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Snapshot__c/fields/Total_Broker_Commissions_Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Broker_Commissions_Fees_Paid__c</fullName>
    <label>Total Broker Commissions &amp; Fees Paid</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/Special_Asset__c.object-meta.xml
<CustomObject>
    <description>When a Property becomes a Special Asset, this record is created and related to the Property.</description>
    <label>Special Asset</label>
    <nameField>
        <label>Special Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Asset__c/fields/Days_To_Resolve__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Resolve__c</fullName>
    <description>Created Date - Resolved Date</description>
    <formula>Resolved_Date__c -  DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Created Date - Resolved Date</inlineHelpText>
    <label>Days To Resolve</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Maturity_Default_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Default_Transfer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Maturity Default Transfer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Realized_Loss_Severity__c.field-meta.xml
<CustomField>
    <fullName>Realized_Loss_Severity__c</fullName>
    <label>Realized Loss Severity %</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/REO_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Date__c</fullName>
    <description>Date that this Property became Real Estate Owned</description>
    <inlineHelpText>Date that this Property became Real Estate Owned</inlineHelpText>
    <label>REO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/REO_Sell_Date__c.field-meta.xml
<CustomField>
    <fullName>REO_Sell_Date__c</fullName>
    <label>REO Sell Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Resolved_Date__c.field-meta.xml
<CustomField>
    <fullName>Resolved_Date__c</fullName>
    <label>Resolved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Special_Asset__c/fields/Total_Broker_Commissions_Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Broker_Commissions_Fees_Paid__c</fullName>
    <label>Total Broker Commissions &amp; Fees Paid</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PropertySnapshotHelper.cls
public without sharing class PropertySnapshotHelper {
  private static final Map<String, String> PROPERTY_GENERAL_FIELD_MAP = new Map<String, String>{
    'Current_UPB__c' => 'Current_UPB__c',
    'Appraised_Value_Amount__c' => 'Current_Valuation_Amount__c',
    'BPO_Appraisal_Date__c' => 'Current_Valuation_Date__c',
    'Payoff_Amount__c' => 'Payoff_Amount__c',
    'Payoff_Received_Date__c' => 'Payoff_Date__c'
  };

  private static final Map<String, String> DEAL_FIELD_MAP = new Map<String, String>{
    'Legal_Fee__c' => 'Legal_Fee__c',
    'Extension_Fee__c' => 'Extension_Fee__c',
    'Securitized__c' => 'Securitized_at_Time_of_Resolution__c'
  };

  private static final Map<String, String> SNAPSHOT_TO_PROP_MAP_ASSETPAIDOFF = new Map<String, String>{
    'Resolved_Date__c' => 'Payoff_Received_Date__c',
    'Start_Date__c' => 'Payoff_Received_Date__c',
    'Days_To_Resolve__c' => 'Days_To_Resolve__c'
  };

  private static final Map<String, String> SNAPSHOT_TO_SPEC_ASSET_RESOLVED = new Map<String, String>{
    'Start_Date__c' => 'CreatedDate',
    'Resolved_Date__c' => 'Resolved_Date__c',
    'Days_To_Resolve__c' => 'Days_To_Resolve__c',
    'REO_Sell_Date__c' => 'REO_Sell_Date__c',
    'REO_Date__c' => 'REO_Date__c',
    'Realized_Loss_Severity__c' => 'Realized_Loss_Severity__c',
    'Total_Broker_Commissions_Fees_Paid__c' => 'Total_Broker_Commissions_Fees_Paid__c',
    'Maturity_Default_Transfer__c' => 'Maturity_Default_Transfer__c',
    'Days_to_Resolve_REO_to_REO_Sold__c' => 'Days_to_Resolve_REO_to_REO_Sold__c',
    'Net_Proceeds__c' => 'Net_Proceeds__c',
    'Resolution_Type__c' => 'Resolution_Type__c'
  };

  private static final Map<String, String> SNAPSHOT_TO_EXT_COMPLETED = new Map<String, String>{
    'Start_Date__c' => 'CreatedDate',
    'Resolved_Date__c' => 'Extension_Date__c',
    'Days_To_Resolve__c' => 'Days_To_Resolve__c',
    'New_Asset_Maturity_Date__c' => 'New_Asset_Maturity_Date__c',
    'Original_Asset_Maturity_Date__c' => 'Original_Asset_Maturity_Date_Formula__c',
    'Previous_Asset_Maturity_Date__c' => 'Previous_Asset_Maturity_Date__c'
  };

  private static final String PROP_EVENT_NAME_PAID = 'Asset Paid Off';

  private static final String PROP_EVENT_NAME_SOLD = 'Asset Sold';

  private static final List<String> PROPERTY_EVENT_TYPES = new List<String>{
    PROP_EVENT_NAME_PAID,
    PROP_EVENT_NAME_SOLD
  };

  private static final String PROP_EXT_EVENT_NAME = 'Extension Completed';

  private static final String SPEC_ASSET_EVENT_NAME = 'Special Asset Resolved';

  // changed to 'Asset Sold in the record but it now causes duplicate keys in the map so i will just programatically change it below

  private static final Map<String, Map<String, String>> FIELD_MAPPING_BY_EVENT = new Map<String, Map<String, String>>{
    PROP_EVENT_NAME_PAID => SNAPSHOT_TO_PROP_MAP_ASSETPAIDOFF,
    PROP_EXT_EVENT_NAME => SNAPSHOT_TO_EXT_COMPLETED,
    SPEC_ASSET_EVENT_NAME => SNAPSHOT_TO_SPEC_ASSET_RESOLVED,
    PROP_EVENT_NAME_SOLD => SNAPSHOT_TO_PROP_MAP_ASSETPAIDOFF
  };

  private static final Map<String, Schema.SObjectField> PROPERTY_FIELD_MAP = Schema.SObjectType.Property__c.fields.getMap();
  private static final Map<String, Schema.SObjectField> OPPORTUNITY_FIELD_MAP = Schema.SObjectType.Opportunity.fields.getMap();
  private static final Map<String, Schema.SObjectField> SNAPSHOT_FIELDMAP = Schema.SObjectType.Property_Snapshot__c.fields.getMap();

  public static void createPropertySnapshot(
    Map<String, Map<Id, sObject>> eventTypeMap
  ) {
    List<Property_Snapshot__c> propSnapshots = new List<Property_Snapshot__c>();
    Set<Id> dealIds = new Set<Id>();
    Set<Id> propIds = new Set<Id>();

    Map<Id, Property__c> propMap = new Map<Id, Property__c>();
    Map<Id, Opportunity> dealMap = new Map<Id, Opportunity>();

    for (String key : eventTypeMap.keySet()) {
      if (key == PROP_EXT_EVENT_NAME || key == SPEC_ASSET_EVENT_NAME) {
        for (sObject obj : eventTypeMap.get(key).values()) {
          System.debug(obj.get('Property__c'));
          if (obj.get('Property__c') != null) {
            propIds.add((Id) obj.get('Property__c'));
          }
        }
      } else {
        for (sObject obj : eventTypeMap.get(key).values()) {
          if (obj.get('Deal__c') != null) {
            dealIds.add((Id) obj.get('Deal__c'));
          }
        }
      }
    }

    Set<String> dealFields = Schema.SObjectType.Opportunity.fields.getMap().keySet();
    Set<String> propFields = Schema.SObjectType.Property__c.fields.getMap().keySet();


    if (dealIds.size() > 0) {
      String dealQuery =
        'SELECT ' +
        String.join(new List<String>(dealFields), ',') +
        ' FROM Opportunity WHERE Id IN :dealIds';
      dealMap = new Map<Id, Opportunity>(
        (List<Opportunity>) Database.query(dealQuery)
      );
    } 
    System.debug(propIds.size());
    if (propIds.size() > 0) {
      String propQuery =
        'SELECT ' +
        String.join(
          new List<String>(propFields),
          ','
        ) +
        ', Deal__r.' +
        String.join(new List<String>(dealFields), ', Deal__r.') +
        ' FROM Property__c WHERE Id IN :propIds';
      System.debug(propQuery);
      propMap = new Map<Id, Property__c>(
        (List<Property__c>) Database.query(propQuery)
      );
    }

    for (String key : eventTypeMap.keySet()) {
      Property_Snapshot__c propSnapshot = new Property_Snapshot__c(
        Event_Type__c = key
      );

        Map<String, String> fieldMapping = FIELD_MAPPING_BY_EVENT.get(key);

        if (fieldMapping == null || fieldMapping.size() < 1) {
          continue;
        }

        for (sObject obj : eventTypeMap.get(key).values()) {
          if (PROP_EXT_EVENT_NAME == key) {
            propSnapshot.Property_Extension__c = (Id) obj.get('Id');
            propSnapshot.Property__c = (Id) obj.get('Property__c');
          } else if (SPEC_ASSET_EVENT_NAME == key) {
            propSnapshot.Special_Asset__c = (Id) obj.get('Id');
            propSnapshot.Property__c = (Id) obj.get('Property__c');
          if(obj.get('REO_Sell_Date__c') != null) {
              propSnapshot.Event_Type__c = 'Asset Sold';
            }
          } else {
            propSnapshot.Property__c = (Id) obj.get('Id');
          }
          for (String fld : fieldMapping.keySet()) {
            Schema.SObjectField field = SNAPSHOT_FIELDMAP.get(fld);
            if (field != null) {
              if (fieldMapping.get(fld) == 'CreatedDate') {
                propSnapshot.put(
                  field,
                  date.valueOf((DateTime) obj.get('CreatedDate'))
                );
              } else {
                propSnapshot.put(field, obj.get(fieldMapping.get(fld)));
              }
            }
          }

          if (
            key == SPEC_ASSET_EVENT_NAME &&
            obj.get('Special_Asset_Reason__c') != null &&
            obj.get('Special_Asset_Reason__c') == 'Bankruptcy'
          ) {
            propSnapshot.In_BK_at_Time_of_Resolution__c = true;
          }

          for (String propFld : PROPERTY_GENERAL_FIELD_MAP.keySet()) {
            Schema.SObjectField field = SNAPSHOT_FIELDMAP.get(
              PROPERTY_GENERAL_FIELD_MAP.get(propFld)
            );
            if (propMap.size() > 0) {
              Property__c prop = propMap.get((Id) obj.get('Property__c'));
              if (prop != null) {
                if (propFld == 'Current_UPB__c') {
                  Decimal upb = prop.Current_UPB__c != null &&
                    prop.Current_UPB__c > 0
                    ? prop.Current_UPB__c
                    : prop.UPB_Before_Payoff__c != null
                        ? prop.UPB_Before_Payoff__c
                        : 0;
                  propSnapshot.put(field, upb);
                } else {
                  propSnapshot.put(field, prop.get(propFld));
                }
              }
            } else if(PROPERTY_EVENT_TYPES.contains(key)) {
              if (propFld == 'Current_UPB__c') {
                Property__c prop = (Property__c) obj;
                Decimal upb = prop.Current_UPB__c != null &&
                  prop.Current_UPB__c > 0
                  ? prop.Current_UPB__c
                  : prop.UPB_Before_Payoff__c != null
                      ? prop.UPB_Before_Payoff__c
                      : 0;
                propSnapshot.put(field, upb);
              } else {
                propSnapshot.put(field, obj.get(propFld));
              }
            }
          }

          for (String dealFld : DEAL_FIELD_MAP.keySet()) {
            Schema.SObjectField field = SNAPSHOT_FIELDMAP.get(
              DEAL_FIELD_MAP.get(dealFld)
            );
            if (dealMap.size() > 0) {
              Opportunity deal = dealMap.get((Id) obj.get('Deal__c'));
              if (deal != null) {
                propSnapshot.put(field, deal.get(dealFld));
              }
            } else {
              Property__c prop = propMap.get((Id) obj.get('Property__c'));
              if (prop != null) {
                propSnapshot.put(
                  field,
                  prop.getSobject('Deal__r').get(dealFld)
                );
              }
            }
          }
        }
      // } else if (key == SA_ASSIGNED) {
      //   /* 
      //   The Days to Resolve on the property snapshot should be calculated as 
      //   Special Asset Created Date - (Original Asset Maturity Date [Asset_Maturity_Date__c] - 60). 
      //   If the Current Asset Maturity Date [Current_Asset_Maturity_Date__c] exists 
      //   then use Current Asset Maturity Date instead of Original Asset Maturity Date.
      //   All the fields that populate from the property to the property snapshot should persist when the property snapshot gets created.
      //   */
      //   for (sObject obj : eventTypeMap.get(key).values()) {
      //     Property__c prop = propMap.get((Id) obj.get('Property__c'));
      //     propSnapshot.Property__c = prop.Id;
      //     propSnapshot.Special_Asset__c = (Id) obj.get('Id');
      //     if(prop.Asset_Maturity_Date__c != null) {
      //       Integer daysToResolve = prop.Asset_Maturity_Date__c.daysBetween(Date.valueOf((DateTime) obj.get('CreatedDate'))) - 60;
  
      //       if(prop.Current_Asset_Maturity_Date__c != null) {
      //         daysToResolve = prop.Current_Asset_Maturity_Date__c.daysBetween(Date.valueOf((DateTime) obj.get('CreatedDate'))) - 60;
      //       }
      //       propSnapshot.Days_To_Resolve__c = Decimal.valueOf(daysToResolve);
      //     } 
      //   }

        
      // }

      propSnapshots.add(propSnapshot);
    }

    if (propSnapshots.size() > 0) {
      Database.insert(propSnapshots);
    }
  }
}