force-app/main/default/objects/Opportunity/fields/Include_3_Months_Min_Interest__c.field-meta.xml
<CustomField>
    <fullName>Include_3_Months_Min_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will make the 3 Month Minimum Interest verbiage show up on a Term Sheet</description>
    <label>Include 3 Months Min Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Include_Assumption__c.field-meta.xml
<CustomField>
    <fullName>Include_Assumption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Assumption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Include_Prop_Sub_Text__c.field-meta.xml
<CustomField>
    <fullName>Include_Prop_Sub_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Property Substitution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NY_Counsel_Required__c.field-meta.xml
<CustomField>
    <fullName>NY_Counsel_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NY Counsel Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Multi-unit (5+)</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
                <default>true</default>
                <label>SFR</label>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Condo - Detached</fullName>
            </value>
            <value>
                <fullName>Condo - High Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Low Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Mid Rise</fullName>
            </value>
            <value>
                <fullName>Condo - NonWarrantable</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>Multi-unit (1-4)</fullName>
                <isActive>false</isActive>
                <label>Multi-unit (1-4)</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
                <isActive>false</isActive>
                <label>Student Housing</label>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
                <isActive>false</isActive>
                <label>Vacation Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Loan_Type_Months__c.field-meta.xml
<CustomField>
    <fullName>Term_Loan_Type_Months__c</fullName>
    <description>Term Use</description>
    <inlineHelpText>In Months</inlineHelpText>
    <label>Term Loan Type Months</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>60 months</fullName>
            </value>
            <value>
                <fullName>84 months</fullName>
            </value>
            <value>
                <fullName>120 months</fullName>
            </value>
            <value>
                <fullName>360 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Sheet_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet_Expiration_Date__c</fullName>
    <label>Term Sheet Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Single_Asset_Bridge_Loan.recordType-meta.xml
<RecordType>
    <fullName>Single_Asset_Bridge_Loan</fullName>
    <active>true</active>
    <businessProcess>SAB Process</businessProcess>
    <label>Single Asset Bridge Loan</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label># of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <label>Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>ZIP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TermSheetPDF_Controller.cls
public with sharing class TermSheetPDF_Controller {
  public Opportunity record { get; set; }
  public Integer month { get; set; }
  public Integer day { get; set; }
  public Integer year { get; set; }
  public Integer todayMonth { get; set; }
  public Integer todayDay { get; set; }
  public Integer todayYear { get; set; }
  public String intStr { get; set; }
  public String base64Image { get; set; }
  public Opportunity dupeRecord { get; set; }

  public Boolean includeBrokerFee { get; set; }
  public Boolean includeCOBroker { get; set; }

  public String numPropertyText { get; set; }
  public String numPropertyTextCapitalized { get; set; }
  public String totalPropertiesText { get; set; }

  public String formattedStates { get; set; }

  public Property__c sabProperty { get; set; }
  public List<Property__c> allProperties { get; set; }
    

  public Integer numTermLoanMonths {
    get {
      Integer monthsVal = null;
      if(this.record != null) {
        String loanTermMonths = this.record.Term_Loan_Type_Months__c;
        if(String.isNotEmpty(loanTermMonths)) {
          monthsVal = Integer.valueOf(loanTermMonths.substringBefore(' months'));
        }
      }
      return monthsVal;
  }
  private set;
  }

  public TermSheetPDF_Controller(
    ApexPages.standardController standardController
  ) {
    // <!-- application/msword#{!Opportunity.Name}_TermSheetv_{!intStr}.doc -->

    this.record = (Opportunity) standardController.getRecord();
    // this.dupeRecord = new Opportunity();
    if (record.Id != null) {
      List<StaticResource> sr = [
        SELECT Body
        FROM StaticResource
        WHERE Name = 'corevestLogo'
      ];

      // Opportunity dupeRecord = [SELECT Id, Term_Sheet_Expiration_Date__c, Include_Assumption__c, Include_Prop_Sub_Text__c, NY_Counsel_Required__c, Include_3_Months_Min_Interest__c
      // 							FROM Opportunity where Id =: record.Id LIMIT 1];
      // this.record.Term_Sheet_Expiration_Date__c = updatedOpp.Term_Sheet_Expiration_Date__c;

      if (sr.size() > 0) {
        base64Image = EncodingUtil.base64Encode(sr[0].Body);
      }
      record = (Opportunity) util.queryRecord(record.Id);
      month = Integer.valueOf(
        ApexPages.currentPage().getParameters().get('month')
      );
      day = Integer.valueOf(ApexPages.currentPage().getParameters().get('day'));
      year = Integer.valueOf(
        ApexPages.currentPage().getParameters().get('year')
      );
      todayMonth = Integer.valueOf(
        ApexPages.currentPage().getParameters().get('todaymonth')
      );
      todayDay = Integer.valueOf(
        ApexPages.currentPage().getParameters().get('todayday')
      );
      todayYear = Integer.valueOf(
        ApexPages.currentPage().getParameters().get('todayyear')
      );
      intStr = ApexPages.currentPage().getParameters().get('version');
      String strUrl = ApexPages.currentPage().getUrl();
      system.debug(strUrl);
      if (strUrl.contains('Doc')) {
        system.debug('in here');
        Apexpages.currentPage()
          .getHeaders()
          .put(
            'Content-Disposition',
            'attachment; filename="' +
            record.Name +
            '_Termsheetv_' +
            intStr +
            '.doc"'
          );
      }

      this.dupeRecord = [
        SELECT
          Id,
          Term_Sheet_Expiration_Date__c,
          Include_Assumption__c,
          Include_Prop_Sub_Text__c,
          NY_Counsel_Required__c,
          Include_3_Months_Min_Interest__c,
          RecordType.DeveloperName
        FROM Opportunity
        WHERE Id = :record.Id
        LIMIT 1
      ];

      if (
        this.dupeRecord.RecordType.DeveloperName == 'Single_Asset_Bridge_Loan'
      ) {
        List<Property__c> props = [
          SELECT
            Id,
            Property_Name__c,
            Name,
            City__c,
            State__c,
            ZipCode__c,
            Property_Type__c,
            County__c,
            Number_of_Units__c
          FROM Property__c
          WHERE
            Deal__c = :record.Id
            AND Status__c NOT IN ('Cancelled', 'Inactive')
          LIMIT 1
        ];
        system.debug(props);
        if (props.size() > 0) {
          this.sabProperty = props[0];
          system.debug('here');
        } else {
          this.sabProperty = new Property__c();
        }
      }

      List<Property__c> properties = new List<Property__c>();
      for (Property__c property : [
        SELECT
          Id,
          Property_Name__c,
          Name,
          City__c,
          State__c,
          ZipCode__c,
          Property_Type__c,
          County__c,
          Number_of_Units__c,
          Is_Parent__c,
          Is_Sub_Unit__c
        FROM Property__c
        WHERE
          Deal__c = :record.Id
          AND Status__c NOT IN ('Cancelled', 'Inactive')
      ]) {
        if (
          property.Property_Type__c == '2-4 Unit' ||
          property.Property_Type__c == 'Multifamily' ||
          property.Property_Type__c == 'Mixed Use'
        ) {
          if (property.Is_Sub_Unit__c == false) {
            properties.add(property);
          }
        } else {
          properties.add(property);
        }
      }

      this.allProperties = properties;

      if (ApexPages.currentPage().getParameters().containsKey('s')) {
        String str = ApexPages.currentPage().getParameters().get('s');
        Map<String, String> s = (Map<String, String>) JSON.deserialize(
          EncodingUtil.base64Decode(str).toString(),
          Map<String, String>.class
        );

        if (s.containsKey('Term_Sheet_Expiration_Date__c')) {
          this.dupeRecord.Term_Sheet_Expiration_Date__c = Date.valueOf(
            s.get('Term_Sheet_Expiration_Date__c')
          );
        }

        if (s.containsKey('Include_Assumption__c')) {
          this.dupeRecord.Include_Assumption__c = Boolean.valueOf(
            s.get('Include_Assumption__c')
          );
        }

        if (s.containsKey('Include_Prop_Sub_Text__c')) {
          this.dupeRecord.Include_Prop_Sub_Text__c = Boolean.valueOf(
            s.get('Include_Prop_Sub_Text__c')
          );
        }

        if (s.containsKey('NY_Counsel_Required__c')) {
          this.dupeRecord.NY_Counsel_Required__c = Boolean.valueOf(
            s.get('NY_Counsel_Required__c')
          );
        }

        if (s.containsKey('Include_3_Months_Min_Interest__c')) {
          this.dupeRecord.Include_3_Months_Min_Interest__c = Boolean.valueOf(
            s.get('Include_3_Months_Min_Interest__c')
          );
        }

        if (s.containsKey('Include_Broker_Fee__c')) {
          //this.dupeRecord.Include_Broker_Fee__c = Boolean.valueOf(s.get('Include_Broker_Fee__c'));
          this.includeBrokerFee = Boolean.valueOf(
            s.get('Include_Broker_Fee__c')
          );
        }

        if (s.containsKey('Include_CO_Broker_Text__c')) {
          //this.dupeRecord.Include_CO_Broker_Text__c = Boolean.valueOf(s.get('Include_CO_Broker_Text__c'));
          this.includeCOBroker = Boolean.valueOf(
            s.get('Include_CO_Broker_Text__c')
          );
        }
      }

      if (
        null != record.Number_of_Properties__c &&
        0 != record.Number_of_Properties__c
      ) {
        numPropertyTextCapitalized = formatCurrencyString(
          record.Number_of_Properties__c
        );
        //numPropertyTextCapitalized = numPropertyText.capitalize();
      } else {
        numPropertyText = 'zero';
      }

      if (
        null != record.Total_Properties__c &&
        0 != record.Total_Properties__c
      ) {
        totalPropertiesText = formatCurrencyString(record.Total_Properties__c);
      } else {
        totalPropertiesText = 'zero';
      }

      if (String.isNotBlank(record.Active_States__c)) {
        this.formattedStates = multiSelectToText(record.Active_States__c);
      }
    }
  }

  public Map<Integer, String> thousandsMap = new Map<Integer, String>{
    1 => 'one thousand,',
    2 => 'two thousand,',
    3 => 'three thousand,',
    4 => 'four thousand,',
    5 => 'five thousand,',
    6 => 'six thousand,',
    7 => 'seven thousand,',
    8 => 'eight thousand,',
    9 => 'nine thousand,',
    10 => 'ten thousand,'
  };

  public Map<Integer, String> hundredsMap = new Map<Integer, String>{
    1 => 'one hundred and',
    2 => 'two hundred and',
    3 => 'three hundred and',
    4 => 'four hundred and',
    5 => 'five hundred and',
    6 => 'six hundred and',
    7 => 'seven hundred and',
    8 => 'eight hundred and',
    9 => 'nine hundred and'
  };

  public Map<Integer, String> tensMap = new Map<Integer, String>{
    2 => 'twenty',
    3 => 'thirty',
    4 => 'forty',
    5 => 'fifty',
    6 => 'sixty',
    7 => 'seventy',
    8 => 'eighty',
    9 => 'ninety'
  };

  public Map<Integer, String> tensOneMap = new Map<Integer, String>{
    10 => 'ten',
    11 => 'eleven',
    12 => 'twelve',
    13 => 'thirteen',
    14 => 'fourteen',
    15 => 'fifteen',
    16 => 'sixteen',
    17 => 'seventeen',
    18 => 'eighteen',
    19 => 'nineteen'
  };

  public Map<Integer, String> onesMap = new Map<Integer, String>{
    0 => 'zero',
    1 => 'one',
    2 => 'two',
    3 => 'three',
    4 => 'four',
    5 => 'five',
    6 => 'six',
    7 => 'seven',
    8 => 'eight',
    9 => 'nine'
  };

  public Integer getMonth() {
    return month;
  }

  public Integer getDay() {
    return day;
  }

  public Integer getYear() {
    return year;
  }

  public Integer todayMonth() {
    return todayMonth;
  }

  public Integer todayDay() {
    return todayDay;
  }

  public Integer todayYear() {
    return todayYear;
  }

  public String convertText(Decimal d) {
    Integer total = d.intValue();
    String intStr = '';
    System.debug('this is the total: ' + total);

    Integer thousandsCnt = loopPosition(total, 1000);
    total -= thousandsCnt * 1000;

    System.debug('this is the total: ' + total);
    System.debug('this is thousandsCnt: ' + thousandsCnt);

    Integer hundredsCnt = loopPosition(total, 100);
    total -= hundredsCnt * 100;

    System.debug('this is the total: ' + total);
    System.debug('this is hundredsCnt: ' + hundredsCnt);

    Integer tensCnt = loopPosition(total, 10);
    total -= tensCnt * 10;

    System.debug('this is the total: ' + total);
    System.debug('this is tensCnt: ' + tensCnt);

    Integer onesCnt = total;
    System.debug('this is onesCnt: ' + onesCnt);

    intStr += thousandsCnt > 0 ? thousandsMap.get(thousandsCnt) + ' ' : '';
    System.debug('this is intStr: ' + intStr);

    intStr += hundredsCnt > 0 ? hundredsMap.get(hundredsCnt) + ' ' : '';
    System.debug('this is intStr: ' + intStr);

    if (tensCnt > 1) {
      intStr += tensMap.get(tensCnt);
      intStr += onesCnt > 0 ? ' ' + onesMap.get(onesCnt) : '';
      System.debug('this is intStr: ' + intStr);
    } else if (tensCnt == 1) {
      System.debug('inside tenCnt is 1');
      Integer sum = (tensCnt * 10) + onesCnt;
      intStr += tensOneMap.get(sum);
      System.debug('this is intStr: ' + intStr);
    } else if (tensCnt == 0) {
      intStr += onesCnt > 0 ? onesMap.get(onesCnt) : '';
      System.debug('this is intStr: ' + intStr);
    }

    return intStr;
  }

  public Integer loopPosition(Integer i, Integer unit) {
    Integer cnt = 0;
    for (Integer j = i; j >= unit; j -= unit) {
      cnt += 1;
    }
    // System.debug(cnt);
    return cnt;
  }

  public PageReference save() {
    upsert record;
    if (!ApexPages.hasMessages()) {
      return new ApexPages.standardController(record).view().setRedirect(true);
    }
    return null;
  }

  public static string formatCurrencyString(Decimal n) {
    Integer nn = Integer.valueOf(n);
    String val = String.valueOf(nn);
    List<String> units;
    List<String> tens;
    List<String> scales;
    Integer start;
    Integer endl;
    List<String> chunks;
    Integer chunksLen;
    Integer chunk;
    List<Integer> ints;
    Integer i;
    String word;
    List<String> words;
    String andS = 'and';

    // val = val.replace('/[, ]/g', '');
    val = val.replaceAll(' ', '');
    val = val.replaceAll(',', '');

    if (Decimal.valueOf(val) == 0) {
      return 'zero';
    }

    units = new List<String>{
      '',
      'one',
      'two',
      'three',
      'four',
      'five',
      'six',
      'seven',
      'eight',
      'nine',
      'ten',
      'eleven',
      'twelve',
      'thirteen',
      'fourteen',
      'fifteen',
      'sixteen',
      'seventeen',
      'eighteen',
      'nineteen'
    };

    tens = new List<String>{
      '',
      '',
      'twenty',
      'thirty',
      'forty',
      'fifty',
      'sixty',
      'seventy',
      'eighty',
      'ninety'
    };

    scales = new List<String>{
      '',
      'thousand',
      'million',
      'billion',
      'trillion',
      'quadrillion',
      'quintillion',
      'sextillion',
      'septillion',
      'octillion',
      'nonillion',
      'decillion',
      'undecillion',
      'duodecillion',
      'tredecillion',
      'quatttuor-decillion',
      'quindecillion',
      'sexdecillion',
      'septen-decillion',
      'octodecillion',
      'novemdecillion',
      'vigintillion',
      'centillion'
    };

    start = val.length();
    chunks = new List<String>();

    while (start > 0) {
      endl = start;
      start = Math.max(0, start - 3);
      chunks.add(val.substring(start, endl));
    }

    chunksLen = chunks.size();
    if (chunksLen > scales.size()) {
      return '';
    }

    words = new List<String>();

    for (i = 0; i < chunksLen; i++) {
      chunk = Integer.valueOf(chunks[i]);

      if (chunk != null) {
        ints = new List<Integer>();
        List<String> intsTemp = chunks[i].split('');
        system.debug(intsTemp);
        for (Integer j = intsTemp.size() - 1; j >= 0; j--) {
          system.debug(j);
          ints.add(Integer.valueOf(intsTemp[j]));
        }

        try {
          if (ints[1] == 1) {
            ints[0] += 10;
          }
        } catch (Exception e) {
        }

        try {
          word = scales[i];
          words.add(word);
        } catch (Exception e) {
        }

        try {
          word = units[ints[0]];
          words.add(word);
        } catch (Exception e) {
        }

        try {
          word = tens[ints[1]];
          words.add(word);
        } catch (Exception e) {
        }

        try {
          if (ints[0] > 0 || ints[1] > 0) {
            if (ints[2] > 0 || (i == 0 && chunksLen > 0)) {
              words.add(andS);
            }
          }
        } catch (Exception e) {
        }

        try {
          word = units[ints[2]];
          words.add(word + ' hundred');
        } catch (Exception e) {
        }
      }
    }
    String res = '';
    for (i = words.size() - 1; i >= 0; i--) {
      res += words[i] + ' ';

      if (
        words[i] != '' &&
        tens.contains(words[i]) &&
        i != 0 &&
        words[i - 1] != ''
      ) {
        res = res.substringBeforeLast(' ') + '-';
      }
    }

    return res;
  }

  public static String multiSelectToText(String value) {
    String textValue = '';
    List<String> splitValues = value.split(';');

    if (splitValues.size() == 1) {
      textValue = splitValues[0];
    } else if (splitValues.size() == 2) {
      textValue = splitValues[0] + ' and ' + splitValues[1];
    } else {
      for (Integer i = 0; i < splitValues.size(); i++) {
        if (i == splitValues.size() - 1) {
          textValue =
            textValue.substringBeforeLast(',') +
            ' and ' +
            splitValues[i];
        } else {
          textValue += splitValues[i] + ', ';
        }
      }
    }

    return textValue;
  }
}