force-app/main/default/objects/Opportunity/fields/Loss_Mitigation_Associate__c.field-meta.xml
<CustomField>
    <fullName>Loss_Mitigation_Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Loss Mitigation Associate working with the Borrower</description>
    <inlineHelpText>The Loss Mitigation Associate working with the Borrower</inlineHelpText>
    <label>Loss Mitigation Associate</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Loss Mitigation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Deals3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payoff_Date__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Date__c</fullName>
    <description>Date Drawn Amount was repaid in full (blank for Draw Amounts still outstanding)</description>
    <inlineHelpText>Date Drawn Amount was repaid in full</inlineHelpText>
    <label>Payoff Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Date__c</fullName>
    <description>Term Use
Date the Property is set to Inactive</description>
    <label>Inactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Loss_Mitigation_Associate__c.field-meta.xml
<CustomField>
    <fullName>Loss_Mitigation_Associate__c</fullName>
    <description>Loss Mitigation Associate is a user lookup on Deal object
The Loss Mitigation Associate working with the Borrower</description>
    <formula>Deal__r.Loss_Mitigation_Associate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Loss Mitigation Associate working with the Borrower</inlineHelpText>
    <label>Loss Mitigation Associate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityMethods.cls
public without sharing class OpportunityMethods {
  private static final String LOSS_MITIGATION_ROLE = 'Loss Mitigation Associate';

  public static void updatePaidOffProperties(Map<Id, Opportunity> dealMap) {
    List<Property__c> propertiesForUpdate = [
      SELECT Id, Status__c, Deal__c, Inactive_Date__c
      FROM Property__c
      WHERE Deal__c IN :dealMap.keySet() AND Status__c = 'Active'
      FOR UPDATE
    ];

    if (propertiesForUpdate.size() > 0) {
      for (Property__c p : propertiesForUpdate) {
        p.Status__c = 'Paid Off';
        p.Inactive_Date__c = dealMap.get(p.Deal__c).Payoff_Date__c;
      }

      update propertiesForUpdate;
    }
  }

  public static void reassignLossMitUser(Map<Id, Opportunity> dealMap) {
    Map<Id, Account> acctMap = new Map<Id, Account>(
      [
        SELECT
          Id,
          (
            SELECT AccountId, UserId,TeamMemberRole
            FROM AccountTeamMembers
          )
        FROM Account
        WHERE
          Id IN (
            SELECT AccountId
            FROM Opportunity
            WHERE Id IN :dealMap.keySet()
          )
      ]
    );

    List<AccountTeamMember> updatedAccTeamMembers = new List<AccountTeamMember>();
    List<AccountTeamMember> forDeletion = new List<AccountTeamMember>();
    for (Opportunity o : dealMap.values()) {
      Account acctRecord = acctMap.get(o.AccountId);
      if (
        acctRecord.AccountTeamMembers == null ||
        acctRecord.AccountTeamMembers.size() == 0
      ) {
        updatedAccTeamMembers.add(
          new AccountTeamMember(
            TeamMemberRole = LOSS_MITIGATION_ROLE,
            AccountId = o.AccountId,
            UserId = o.Loss_Mitigation_Associate__c
          )
        );
      } else {
        AccountTeamMember newAtm = new AccountTeamMember();
        Boolean shouldUpdate = false;
        Boolean userFound = false;
        for (AccountTeamMember atm : acctRecord.AccountTeamMembers) {
           if(atm.userId == o.Loss_Mitigation_Associate__c) {
               userFound = true;
           }
           if (atm.UserId == o.Loss_Mitigation_Associate__c && atm.TeamMemberRole != LOSS_MITIGATION_ROLE) {
            shouldUpdate = true;
            newAtm.Id = atm.Id;
            newAtm.TeamMemberRole = LOSS_MITIGATION_ROLE;
          } else if (atm.TeamMemberRole == LOSS_MITIGATION_ROLE && atm.UserId != o.Loss_Mitigation_Associate__c) {
            shouldUpdate = true;
            newAtm.UserId = o.Loss_Mitigation_Associate__c;
            newAtm.AccountId = o.AccountId;
            newAtm.TeamMemberRole = LOSS_MITIGATION_ROLE;
            forDeletion.add(atm);
          }
        }

        if(!userFound){
            shouldUpdate = true;
            newAtm.UserId = o.Loss_Mitigation_Associate__c;
            newAtm.AccountId = o.AccountId;
            newAtm.TeamMemberRole = LOSS_MITIGATION_ROLE;
        }

        if (shouldUpdate) {
          updatedAccTeamMembers.add(newAtm);
        }
      }
    }

    if (updatedAccTeamMembers.size() > 0) {
      upsert updatedAccTeamMembers;
    }

    if(forDeletion.size() > 0) {
      delete forDeletion;
    }
  }
}