force-app/main/default/objects/Contact/fields/Borrowed_on_Bridge_Loans__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_on_Bridge_Loans__c</fullName>
    <description>Total amount borrowed through Bridge and Single Asset Bridge Loans</description>
    <label>Borrowed on Bridge Loans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Borrowed_on_Term_Loans__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_on_Term_Loans__c</fullName>
    <description>Total amount borrowed through Term Loans</description>
    <label>Borrowed on Term Loans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cash_Equivalent__c.field-meta.xml
<CustomField>
    <fullName>Cash_Equivalent__c</fullName>
    <label>Cash Equivalent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cash_Position__c.field-meta.xml
<CustomField>
    <fullName>Cash_Position__c</fullName>
    <label>Cash Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CurrentPayoffAmount__c.field-meta.xml
<CustomField>
    <fullName>CurrentPayoffAmount__c</fullName>
    <label>Current Payoff Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Deliquency_History__c.field-meta.xml
<CustomField>
    <fullName>Deliquency_History__c</fullName>
    <label>Deliquency History</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Occurrence</fullName>
            </value>
            <value>
                <fullName>Episodic</fullName>
            </value>
            <value>
                <fullName>Severe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Est_Payoff_Amt_by_Lender_LR__c.field-meta.xml
<CustomField>
    <fullName>Est_Payoff_Amt_by_Lender_LR__c</fullName>
    <description>LR = Loan Request</description>
    <label>Est Payoff Amt by Lender</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Number of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Liquidity__c</fullName>
    <label>Liquidity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Middle_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Middle_Credit_Score__c</fullName>
    <description>Middle number of Experian, Equifax, &amp; TransUnion credit scores</description>
    <formula>IF(  
    OR ( AND( Experian__c &gt;= Equifax__c, TransUnion__c &lt;= Equifax__c ) , AND( TransUnion__c &gt;= Equifax__c, Experian__c &lt;= Equifax__c) ),
    Equifax__c,
    IF(
       OR ( AND( Equifax__c &gt;= Experian__c, TransUnion__c &lt;= Experian__c ) , AND( TransUnion__c &gt;= Experian__c, Equifax__c &lt;= Experian__c) ),
       Experian__c,
       TransUnion__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Middle number of Experian, Equifax, &amp; TransUnion credit scores</inlineHelpText>
    <label>Middle Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>Net_Worth__c</fullName>
    <label>Net Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rental_Units_Owned__c.field-meta.xml
<CustomField>
    <fullName>Rental_Units_Owned__c</fullName>
    <label>Rental Units Owned</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Repeat_Borrower__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Borrower__c</fullName>
    <formula>Account.Repeat_Borrower__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Repeat Borrower</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsor_Tier__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Tier__c</fullName>
    <description>Bridge Use</description>
    <label>Sponsor Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/Deal_Contact__c.object-meta.xml
<CustomObject>
    <label>Deal Contact</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Deal Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Contact__c/fields/Account_Entity__c.field-meta.xml
<CustomField>
    <fullName>Account_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Deals and Accounts</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Annual_Income_Last_Year__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_Last_Year__c</fullName>
    <label>Annual Income Last Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Cash_Equivalent__c.field-meta.xml
<CustomField>
    <fullName>Cash_Equivalent__c</fullName>
    <label>Cash Equivalent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Cash_Position__c.field-meta.xml
<CustomField>
    <fullName>Cash_Position__c</fullName>
    <label>Cash Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Roles on Deals</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName + &apos; &apos; + Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Contacts</relationshipLabel>
    <relationshipName>Deal_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <description>Number of Projects</description>
    <label>Number of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Liquidity__c</fullName>
    <label>Liquidity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Middle_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Middle_Credit_Score__c</fullName>
    <description>Middle number of Experian, Equifax, &amp; TransUnion credit scores</description>
    <formula>IF(  
    OR ( AND( Experian__c &gt;= Equifax__c, TransUnion__c &lt;= Equifax__c ) , AND( TransUnion__c &gt;= Equifax__c, Experian__c &lt;= Equifax__c) ),
    Equifax__c,
    IF(
       OR ( AND( Equifax__c &gt;= Experian__c, TransUnion__c &lt;= Experian__c ) , AND( TransUnion__c &gt;= Experian__c, Equifax__c &lt;= Experian__c) ),
       Experian__c,
       TransUnion__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Middle number of Experian, Equifax, &amp; TransUnion credit scores</inlineHelpText>
    <label>Middle Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>Net_Worth__c</fullName>
    <label>Net Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Rental_Units_Owned__c.field-meta.xml
<CustomField>
    <fullName>Rental_Units_Owned__c</fullName>
    <label>Rental Units Owned</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Sponsor_Tier__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Tier__c</fullName>
    <description>Bridge Use</description>
    <label>Sponsor Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Contact__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <formula>Contact__r.Years_of_Experience__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Years of Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact this Document is related to</description>
    <inlineHelpText>Contact this Document is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal Contact record that this Document is related to</description>
    <inlineHelpText>Deal Contact record that this Document is related to</inlineHelpText>
    <label>Deal Contact</label>
    <referenceTo>Deal_Contact__c</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExecSummaryController.cls
public with sharing class ExecSummaryController {
  private static final List<String> IC_TYPES = new List<String>{
    'Draft IC Memo',
    'Committee Memo'
  };
  // @AuraEnabled(cacheable=true)
  // public static String queryChildrenRecords(Id recordId) {
  //   Map<String, List<Object>> resMap = new Map<String, List<Object>>();

  //   List<Deal_Contact__c> sponsors = [
  //     SELECT
  //       Id,
  //       Account_Entity__c,
  //       Contact_Name__c,
  //       Net_Worth__c,
  //       Liquidity__c,
  //       Rental_Units_Owned__c,
  //       Middle_Credit_Score__c,
  //       Cash_Equivalent__c,
  //       Cash_Position__c,
  //       Years_of_Experience__c,
  //       Annual_Income_Last_Year__c,
  //       Contact__r.Sponsor_Tier__c,
  //       Contact__r.Repeat_Borrower__c,
  //       Contact__r.Borrowed_on_Bridge_Loans__c,
  //       Contact__r.Borrowed_on_Term_Loans__c,
  //       Contact__r.CurrentPayoffAmount__c,
  //       Contact__r.Deliquency_History__c,
  //       Contact__r.Est_Payoff_Amt_by_Lender_LR__c
  //     FROM Deal_Contact__c
  //     WHERE Deal__c = :recordId AND entity_type__c = 'sponsor'
  //   ];
  //   resMap.put('Sponsors', sponsors);

  //   List<Deal_Contact__c> guarantors = [
  //     SELECT
  //       Id,
  //       Contact__c,
  //       Name,
  //       Contact_Name__c,
  //       Rental_Units_Owned__c,
  //       Cash_Equivalent__c,
  //       Cash_Position__c,
  //       Net_Worth__c,
  //       Annual_Income_Last_Year__c,
  //       Annual_Income_2_Years_Ago__c,
  //       Middle_Credit_Score__c,
  //       Contact__r.Middle_Credit_Score__c,
  //       Contact__r.Name,
  //       Contact__r.Phone,
  //       Contact__r.Email,
  //       Contact__r.Experience__c,
  //       Contact__r.Liquidity__c,
  //       Contact__r.Sponsor_Tier__c,
  //       Contact__r.Deliquency_History__c,
  //       Contact__r.Years_of_Experience__c,
  //       Years_of_Experience__c,
  //       Contact__r.Repeat_Borrower__c
  //     FROM Deal_Contact__c
  //     WHERE Deal__c = :recordId AND entity_type__c = 'Guarantor'
  //     ORDER BY Percentage_Owned__c DESC, Middle_Credit_Score__c DESC
  //   ];
  //   resMap.put('Guarantors', guarantors);

  //   List<AggregateResult> propertyTypes = [
  //     SELECT Count(Id) ct, Property_Type__c
  //     FROM Property__c
  //     WHERE Deal__c = :recordId
  //     GROUP BY Property_Type__c
  //   ];

  //   Deal_Document__c dealDoc = [
  //     SELECT ContentVersion_Id__c, Attachment_Id__c
  //     FROM Deal_Document__c
  //     WHERE
  //       Document_Type__c IN :IC_TYPES
  //       AND Deal__c = :recordId
  //       AND File_Name__c LIKE '%.pdf'
  //     ORDER BY CreatedDate DESC
  //     LIMIT 1
  //   ];

  //   ContentVersion cv = [
  //     SELECT VersionData
  //     FROM ContentVersion
  //     WHERE Id = :dealDoc.ContentVersion_Id__c
  //   ];
  //   String fileLink =
  //     'data:application/pdf;base64,' +
  //     EncodingUtil.base64Encode(cv.VersionData);

  //   resMap.put('FileLink', new List<Object>{ fileLink });

  //   List<Map<String, Object>> propTypes = new List<Map<String, Object>>();
  //   for (AggregateResult p : propertyTypes) {
  //     Map<String, Object> pT = new Map<String, Object>{
  //       'Type' => p.get('Property_Type__c'),
  //       'Count' => p.get('ct')
  //     };
  //     propTypes.add(pT);
  //   }
  //   resMap.put('PropTypes', propTypes);
  //   resMap.put('FileId', new List<Object>{ dealDoc.Attachment_Id__c });

  //   AggregateResult floodZone = [
  //     SELECT Count(Id) ct
  //     FROM Property__c
  //     WHERE Deal__c = :recordId AND Flood_Coverage_Needed__c = 'Yes'
  //   ];
  //   resMap.put('FloodZone', new List<Object>{ floodZone.get('ct') });

  //   return JSON.serialize(resMap);
  // }

  @AuraEnabled(cacheable=true)
  public static String getFileId(Id recordId) {
    List<Deal_Document__c> dealDoc = [
      SELECT ContentVersion_Id__c, Attachment_Id__c
      FROM Deal_Document__c
      WHERE
        Document_Type__c IN :IC_TYPES
        AND Deal__c = :recordId
        AND File_Name__c LIKE '%.pdf'
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    return dealDoc.size() > 0 && String.isNotEmpty(dealDoc[0].Attachment_Id__c) ? dealDoc[0].Attachment_Id__c : '';
  }
}