force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Primary person at account to receive correspondence</description>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Covenant__c/Covenant__c.object-meta.xml
<CustomObject>
    <description>Loan Milestones</description>
    <label>Covenant</label>
    <nameField>
        <label>Covenants Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covenant__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Covenants</relationshipLabel>
    <relationshipName>Covenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Contact__r.FirstName  &amp; &quot; &quot;  &amp;  Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>General Task</description>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/CovenantRecurringEmailTest.cls
@isTest
private class CovenantRecurringEmailTest {
  @isTest
  static void CovenantRecurringEmailAlertTest() {
      

test_Helper.createDealLoanNumber();
    account acc = new account();
    acc.name = 'testacc';

    insert acc;

    contact con = new contact();
    con.FirstName = 'test contact';
    con.LastName = 'test cont';
    con.Email = 'email@email.com';
    con.Primary_Contact__c = true;
    con.AccountId = acc.Id;
    con.MailingCity = 'test city';
    con.MailingCountry = 'United States';

    insert con;

    System.debug(con.FirstName);
    System.debug(con.LastName);

    opportunity opp = new opportunity();
    opp.name = 'testopp';
    opp.StageName = 'Initial Review';
    opp.CloseDate = date.today();
    opp.AccountId = acc.Id;
    opp.ContactId = con.id;
    opp.Contact__c = con.id;

    insert opp;

    covenant__c cov = new covenant__c();
    cov.Name = 'testcov';
    cov.Deal__c = opp.id;
    cov.Due_Date__c = system.today();

    insert cov;

    task tsk = new task();
    tsk.Subject = 'Financial Covenants';
    tsk.Priority = 'Normal';
    tsk.Status = 'Open';
    tsk.Type = 'Financial Covenants';
    tsk.WhatId = cov.Id;
    task t = new task();
    t.type = 'Financial Covenants';
    t.X10_Day_Email_Sent__c = true;
    t.Status = 'Open';
    t.Covenant_Milestones__c = false;
    t.Subject = 'Financial Covenants';
    t.WhatId = cov.id;

    insert t;

    test.starttest();
    CovenantRecurringEmailAlert myClass = new CovenantRecurringEmailAlert();
    String chron = '0 0 23 * * ?';
    system.schedule('Test Sched', chron, myClass);
    System.debug(myClass);
    test.stopTest();
  }
}