force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Primary person at account to receive correspondence</description>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/Deal_Document__c.object-meta.xml
<CustomObject>
    <label>Deal Document</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Deal Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Closer from the related Deal</description>
    <inlineHelpText>Closer from the related Deal</inlineHelpText>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact this Document is related to</description>
    <inlineHelpText>Contact this Document is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_Id__c</fullName>
    <label>ContentVersion Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Documents</relationshipLabel>
    <relationshipName>Deal_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Document_Loaded__c.field-meta.xml
<CustomField>
    <fullName>Document_Loaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Loaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Loan_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Coordinator from the related Deal</description>
    <inlineHelpText>Loan Coordinator from the related Deal</inlineHelpText>
    <label>Loan Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please use the &quot;Update Folder&quot; button to make changes to the Folder and Document Type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Diligence</fullName>
            </value>
            <value>
                <fullName>Background and Credit Information</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Information</fullName>
            </value>
            <value>
                <fullName>Corporate Entity Documents</fullName>
            </value>
            <value>
                <fullName>Diligence Documents</fullName>
            </value>
            <value>
                <fullName>DS Funding Package</fullName>
            </value>
            <value>
                <fullName>IC Memo</fullName>
            </value>
            <value>
                <fullName>Insurance Information</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Loan Document</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Models</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Title Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Document__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Underwriter from the related Deal</description>
    <inlineHelpText>Underwriter from the related Deal</inlineHelpText>
    <label>Underwriter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Documents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Closer on this Deal</description>
    <label>Closer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Closer</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Closer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Closer)</relationshipLabel>
    <relationshipName>Deals2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Updated via Apex - When an &quot;Insurance Review&quot; Deal Contact is created, the Account is populated</description>
    <inlineHelpText>Insurance Review from the Vendor Entities Section</inlineHelpText>
    <label>Insurance Review</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals (Insurance)</relationshipLabel>
    <relationshipName>Deals_as_Insurance_Review</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Internal_Referral__c.field-meta.xml
<CustomField>
    <fullName>Internal_Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the CoreVest employee that referred this Deal</inlineHelpText>
    <label>Internal Referral</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Loan_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Loan Coordinator</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Loan Coordinator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Loan Coordinator)</relationshipLabel>
    <relationshipName>Deals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Program_Type__c</fullName>
    <description>Bridge Use
Custom or Standard Pricing</description>
    <inlineHelpText>Indicates if the pricing is Standard or Custom</inlineHelpText>
    <label>Bridge Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Contact__r.FirstName  &amp; &quot; &quot;  &amp;  Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOC_Loan_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Build to Rent</fullName>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>No Renovation</fullName>
                <default>true</default>
                <label>No Renovation</label>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Condo Development</fullName>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Adaptive Reuse</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Land Development</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Long Term Loan</fullName>
            </value>
            <value>
                <fullName>Fixed Rate Short Term Loan</fullName>
            </value>
            <value>
                <fullName>Floating Rate Term Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <businessOwnerGroup>System_Admins</businessOwnerGroup>
    <description>Used in Apex Classes and other Meta Data</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used in Apex Classes and other Meta Data.  Record Type Developer Name</inlineHelpText>
    <label>Record Type Developer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Updated via Apex - When an &quot;Title and Escrow&quot; Deal Contact is created, the Account is populated</description>
    <inlineHelpText>Title and Escrow from the Vendor Entities Section</inlineHelpText>
    <label>Title</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals (Title and Escrow)</relationshipLabel>
    <relationshipName>Deals_as_Title</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Term and Bridge Use</description>
    <label>Underwriter</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Bridge Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Term Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Term Underwriter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>SAB Loan</value>
        </filterItems>
        <filterItems>
            <field>User.For_Lookup_Filters__c</field>
            <operation>contains</operation>
            <value>Bridge Underwriter</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Deals (Underwriter)</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TermSheetBypassController.cls
public without sharing class TermSheetBypassController {

    // Opportunity.OwnerId, CAF Originator (Lookup on User)
    // Opportunity.Closer__c, Closer (Lookup on User)
    // Opportunity.Guarantor__c, Guarantor (Lookup on Contact)
    // Opportunity.Internal_Referral__c, Internal Referral (Lookup on User)
    // Opportunity.Loan_Coordinator__c, Loan Coordinator (Lookup on User)
    // Opportunity.Primary_Contact__c, Primary Contact (Lookup on Contact)
    // Opportunity.Underwriter__c, Underwriter (Lookup on User)

    // Opportunity.Counsel__c, Counsel (Lookup on Account)
    // Opportunity.Insurance__c, Insurance__c (Lookup on Account)
    // Opportunity.Title__c, Title__c (Lookup on Account)
    // Opportunity.PNC__c (Lookup on Account)

    // public static final String emailAddress = 'dealapprovalhandler@1rcof8n96wj6plns2owu5ajq75yd8wlpy914j3zbt9jk5bfree.2f-crgzuas.cs91.apex.sandbox.salesforce.com';

    // public static final String emailAddress = 'deal_approval_handler@1-2ubmvsr19x7o406nnymb5zkfzbl7wsflro23z72qyy25g7hr6z.5c-8jnxuay.cs62.apex.sandbox.salesforce.com';

    // public static final String BRIDGE_LIST = 'caf.test@cvest.com';
    // public static final String TERM_LIST = 'caf.test@cvest.com';



    // public static final String termDistList = m.get('Term Sheet Request').Email_Address__c;
    // public static final String bridgeDistList = m.get('Bridge Term Sheet Request').Email_Address__c;

    // public static Map<String,Email_Addresses__c> m = Email_Addresses__c.getAll();
    // public static final String emailAddress = m.get('dealApprovalHandler').Value__c;
    // public static final String termDistList = m.get('Term Sheet Request').Value__c;
    // public static final String bridgeDistList = m.get('Bridge Term Sheet Request').Value__c;
    //
    // User userBeth = [
    //     SELECT Id,Email
    //     FROM User
    //     WHERE Name = 'Beth O\'Brien'
    //     LIMIT 1
    // ];
    //
    // User userRyan = [
    //     SELECT Id,Email
    //     FROM User
    //     WHERE Name = 'Ryan McBride'
    //     LIMIT 1
    // ];
    // public static final String BETH = userBeth.Email;
    // public static final String RYAN = userRyan.Email;

    public static List<String> fields = new List<String>{
        // 'Opportunity.OwnerId',
        // 'Opportunity.Closer__c',
        // 'Opportunity.Internal_Referral__c',
        // 'Opportunity.Loan_Coordinator__c',
        // 'Opportunity.Contact__c',
        // 'Opportunity.Underwriter__c',

        'Opportunity.Owner.Email',
        // 'Opportunity.Closer__r.Email',
        // 'Opportunity.Internal_Referral__r.Email',
        // 'Opportunity.Loan_Coordinator__r.Email',
        // 'Opportunity.Contact__r.Email',
        // 'Opportunity.Underwriter__r.Email',

        // 'Opportunity.Owner.Name',
        // 'Opportunity.Closer__r.Name',
        // 'Opportunity.Internal_Referral__r.Name',
        // 'Opportunity.Loan_Coordinator__r.Name',
        // 'Opportunity.Contact__r.Name',
        // 'Opportunity.Underwriter__r.Name',
        'Name',
        'Record_Type_Name__c',
        'LOC_Program_Type__c',
        'Product_Sub_Type__c'
    };

    // public static Map<String,String> loansToTemplate = new Map<String,String>{
    //     'Term Loan' => 'TERM_Term_Sheet_Request',
    //     'LOC Loan Outside Guidelines' => 'BRIDGE_Term_Sheet_Request',
    //     'LOC Loan Within Guidelines' => 'BRIDGE_Term_Sheet_Request_Within_Pricing_Guidelines'
    // };


    @AuraEnabled
    public static String returnDeal(Id recordId){
        Map<String,Object> m = new Map<String,List<Object>>();
        String qs = 'SELECT ';
        qs += String.join(fields,', ');
        qs += ' FROM Opportunity WHERE Id = :recordId';

        List<sObject> oList = Database.query(qs);
        Opportunity o;


        Integer versionNumber = 0;
        List<Deal_Document__c> ddList = [
            SELECT ContentVersion_Id__c,Attachment_Id__c,Type__c
            FROM Deal_Document__c
            WHERE Deal__c = :recordId
            AND File_Name__c LIKE '%.pdf'
            AND ContentVersion_Id__c != null
            AND Document_Loaded__c = true
            AND Is_Deleted__c = false
            AND Type__c = 'Term Sheet'
        ];

        List<Id> ddCvIds = new List<Id>();
        if (null != ddList && ddList.size() > 0){
            for (Deal_Document__c ddc : ddList){
                if ('Term Sheet' == ddc.Type__c){
                    versionNumber += 1;
                }
                if (null != ddc.ContentVersion_Id__c){
                    ddCvIds.add(ddc.ContentVersion_Id__c);
                }
            }
        }


        //
        // System.debug('this is ddList');
        // System.debug(ddList);
        // System.debug('these are ddCvIds');
        // System.debug(ddCvIds);
        //
        // List<ContentVersion> compiledCv = new List<ContentVersion>();
        List<ContentVersion> cvList = [
            SELECT Id,PathOnClient
            FROM ContentVersion
            WHERE Id IN :ddCvIds
        ];

        if (versionNumber == 0){
            // m.put('Error', new List<String>{'true'});
            m.put('TermSheetError', new List<String>{'true'});
            return JSON.serialize(m, true);
        }

        // }

        //m.put('ContentVersions', cvList);
        return JSON.serialize(m, true);
    }

    @AuraEnabled
    public static String bypassDeal(String recordId){
        try{
            Deal_Document__c termSheet = [
                SELECT ContentVersion_Id__c,Attachment_Id__c,Type__c, File_Name__c
                FROM Deal_Document__c
                WHERE Deal__c = :recordId
                AND File_Name__c LIKE '%.pdf'
                AND ContentVersion_Id__c != null
                AND Document_Loaded__c = true
                AND Is_Deleted__c = false
                AND Type__c = 'Term Sheet'
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];

            Attachment a = createAttachmentFromCv(termSheet.ContentVersion_Id__c);
            a.ParentId = recordId;
            insert a;

            Opportunity o = new Opportunity(Id = recordId, Bypass_To_Underwriting__c = true, 
                                            Approved_Term_Sheet__c = termSheet.ContentVersion_Id__c, 
                                            Approved_Term_Sheet_Name__c = termSheet.File_Name__c);

            update o;
            



            return 'This record has successfully been bypassed';
        }catch(DmlException e){
            throw new AuraException(e.getMessage());
        }
    }

    public static Attachment createAttachmentFromCV(Id contentVersionId){
        
        ContentVersion cv = [SELECT Id, PathOnClient, VersionData  FROM ContentVersion WHERE Id =: contentVersionId];

        return new Attachment(Name = cv.PathOnClient, Body = cv.VersionData);

    }

    // close Return the Deal

}