force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Primary person at account to receive correspondence</description>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Covenant__c/Covenant__c.object-meta.xml
<CustomObject>
    <description>Loan Milestones</description>
    <label>Covenant</label>
    <nameField>
        <label>Covenants Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Covenant__c/fields/Covenant_Details__c.field-meta.xml
<CustomField>
    <fullName>Covenant_Details__c</fullName>
    <label>Covenant Details</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Covenant__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Covenants</relationshipLabel>
    <relationshipName>Covenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Covenant__c/fields/Milestones__c.field-meta.xml
<CustomField>
    <fullName>Milestones__c</fullName>
    <label>Milestones</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Construction milestone pending</fullName>
            </value>
            <value>
                <fullName>Financial covenant pending</fullName>
            </value>
            <value>
                <fullName>Sale or leasing milestone pending</fullName>
            </value>
            <value>
                <fullName>Mandatory principal payment covenant pending</fullName>
            </value>
            <value>
                <fullName>Other Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals (Primary Contact)</relationshipLabel>
    <relationshipName>Deals_As_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Contact__r.FirstName  &amp; &quot; &quot;  &amp;  Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>General Task</description>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/CovenantTriggerTest.cls
@isTest
private class CovenantTriggerTest {
  @isTest
  static void CovTriggerTest() {
    Id recordTypeId = Schema.SObjectType.task.getRecordTypeInfosByDeveloperName()
      .get('Task')
      .getRecordTypeId();


test_Helper.createDealLoanNumber();
    account acc = new account();
    acc.name = 'testacc';

    insert acc;

    contact con = new contact();
    con.FirstName = 'test contact';
    con.LastName = 'test cont';
    con.Email = 'email@email.com';
    con.Primary_Contact__c = true;
    con.AccountId = acc.Id;

    insert con;

    opportunity opp = new opportunity();
    opp.name = 'testopp';
    opp.StageName = 'Term sheet Issued';
    opp.CloseDate = date.today();
    opp.AccountId = acc.Id;
    opp.Contact__c = con.id;
    opp.ContactId = con.id;

    insert opp;

    covenant__c cov = new covenant__c();
    cov.Name = 'testcov';
    cov.Deal__c = opp.id;

    insert cov;

    task tsk = new task();
    tsk.Subject = cov.Name;
    tsk.Priority = 'Normal';
    tsk.Status = 'Open';
    tsk.Type = 'Financial Covenants';
    tsk.WhatId = cov.Id;
    tsk.RecordTypeId = recordTypeId;

    insert tsk;
    system.assertEquals('Open', tsk.Status);

    cov.Milestones__c = 'Construction milestone pending';

    update cov;
    task updatedTask = [SELECT status FROM task WHERE id = :tsk.id];
    system.assertEquals('Completed', updatedTask.Status);
  }
  @isTest
  static void CovTriggerTestDueDate() {
    Id recordTypeId = Schema.SObjectType.task.getRecordTypeInfosByDeveloperName()
      .get('Task')
      .getRecordTypeId();
    account acc = new account();
    acc.name = 'testacc';

    insert acc;

    contact con = new contact();
    con.FirstName = 'test contact';
    con.LastName = 'test cont';
    con.Email = 'email@email.com';
    con.Primary_Contact__c = true;
    con.AccountId = acc.Id;

    insert con;


test_Helper.createDealLoanNumber();
    opportunity opp = new opportunity();
    opp.name = 'testopp';
    opp.StageName = 'Term sheet Issued';
    opp.CloseDate = date.today();
    opp.AccountId = acc.Id;
    opp.Contact__c = con.id;
    opp.ContactId = con.id;

    insert opp;

    covenant__c cov = new covenant__c();
    cov.Name = 'testcov';
    cov.Deal__c = opp.id;
    cov.Covenant_Details__c = 'test comments';
    cov.Due_Date__c = date.today();

    insert cov;

    task tsk = new task();
    tsk.Subject = cov.Name;
    tsk.Priority = 'Normal';
    tsk.Status = 'Open';
    tsk.Type = 'Financial Covenants';
    tsk.WhatId = cov.Id;
    tsk.RecordTypeId = recordTypeId;
    tsk.ActivityDate = cov.Due_Date__c;
    tsk.IsReminderSet = true;
    tsk.ReminderDateTime = cov.Due_Date__c - 15;

    insert tsk;
    system.assertEquals('Open', tsk.Status);

    cov.Milestones__c = 'Construction milestone pending';

    update cov;

    task updatedTask = [SELECT status FROM task WHERE id = :tsk.id];
    system.assertEquals('Completed', updatedTask.Status);
  }
}