force-app/main/default/objects/Contact/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>Property Details Section</description>
    <label>Property Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Multi-unit (5+)</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
                <default>true</default>
                <label>SFR</label>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Condo - Detached</fullName>
            </value>
            <value>
                <fullName>Condo - High Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Low Rise</fullName>
            </value>
            <value>
                <fullName>Condo - Mid Rise</fullName>
            </value>
            <value>
                <fullName>Condo - NonWarrantable</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>Multi-unit (1-4)</fullName>
                <isActive>false</isActive>
                <label>Multi-unit (1-4)</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
                <isActive>false</isActive>
                <label>Student Housing</label>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
                <isActive>false</isActive>
                <label>Vacation Rental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Escrow_Company_text__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Company_text__c</fullName>
    <label>Escrow Company text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Insurance_Company_text__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_text__c</fullName>
    <label>Insurance Company text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label># of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Payoff_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Payoff_Received_Date__c</fullName>
    <description>The Date that the Property was paid off.  Provided by the servicer</description>
    <label>Payoff Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <label>Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-4 Unit</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Land/Lot</fullName>
            </value>
            <value>
                <fullName>Manufactured Housing</fullName>
            </value>
            <value>
                <fullName>Mixed Use</fullName>
            </value>
            <value>
                <fullName>Modular</fullName>
            </value>
            <value>
                <fullName>Multifamily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>SFR</fullName>
            </value>
            <value>
                <fullName>Townhome</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>1 - 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1 - 4 Unit</label>
            </value>
            <value>
                <fullName>1- 4 Unit</fullName>
                <isActive>false</isActive>
                <label>1- 4 Unit</label>
            </value>
            <value>
                <fullName>1-4</fullName>
                <isActive>false</isActive>
                <label>1-4</label>
            </value>
            <value>
                <fullName>1-4  Unit</fullName>
                <isActive>false</isActive>
                <label>1-4  Unit</label>
            </value>
            <value>
                <fullName>1-4 UNITS</fullName>
                <isActive>false</isActive>
                <label>1-4 UNITS</label>
            </value>
            <value>
                <fullName>1-4 Unit</fullName>
                <isActive>false</isActive>
                <label>1-4 Unit</label>
            </value>
            <value>
                <fullName>1-4 Unt</fullName>
                <isActive>false</isActive>
                <label>1-4 Unt</label>
            </value>
            <value>
                <fullName>1-4Unit</fullName>
                <isActive>false</isActive>
                <label>1-4Unit</label>
            </value>
            <value>
                <fullName>1-Family</fullName>
                <isActive>false</isActive>
                <label>1-Family</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>2 Unit</fullName>
                <isActive>false</isActive>
                <label>2 Unit</label>
            </value>
            <value>
                <fullName>2 family</fullName>
                <isActive>false</isActive>
                <label>2 family</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Refinance_Acquisition__c.field-meta.xml
<CustomField>
    <fullName>Refinance_Acquisition__c</fullName>
    <label>Refinance Acquisition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/recordTypes/Bridge_No_Renovation.recordType-meta.xml
<RecordType>
    <fullName>Bridge_No_Renovation</fullName>
    <active>true</active>
    <label>Bridge No Renovation</label>
</RecordType>

force-app/main/default/classes/CommunityFundingTests.cls
@isTest
public with sharing class CommunityFundingTests {
  @testSetup
  static void setup() {
      

test_Helper.createDealLoanNumber();
    Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createBridgeDeal(acc, cont);
    opp.StageName = 'Underwriting';
    update opp;

    List<Property__c> property = new List<Property__c>();
    Id recordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE
        sobjecttype = 'Property__c'
        AND DeveloperName = 'Bridge_No_Renovation'
    ]
    .Id;
    for (Integer i = 0; i < 20; i++) {
      property.add(
        new Property__c(
          Name = 'Test + ' + i,
          Property_Name__c = 'Test + ' + i,
          Deal__c = opp.Id,
          Escrow_Company_text__c = 'ESCROW',
          Insurance_Company_text__c = 'INSURANCE',
          Status__c = 'Pending',
          Property_Type__c = 'SFR',
          Number_of_Units__c = 1,
          RecordTypeId = recordTypeId
        )
      );
    }

    property[0].Status__c = 'Due Diligence';
    property[1].Status__c = 'Active';
    property[2].Payoff_Received_Date__c = system.today();
    property[0].Refinance_Acquisition__c = 'Refinance';
    insert property;
  }

  @IsTest
  static void insertTests() {
    Id oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
    List<Property__c> property = new List<Property__c>();
    Id recordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE
        sobjecttype = 'Property__c'
        AND DeveloperName = 'Bridge_No_Renovation'
    ]
    .Id;
    for (Integer i = 0; i < 20; i++) {
      property.add(
        new Property__c(
          Name = 'Test + ' + i,
          Property_Name__c = 'Test + ' + i,
          Deal__c = oppId,
          Escrow_Company_text__c = 'ESCROW',
          Insurance_Company_text__c = 'INSURANCE',
          Status__c = 'Pending',
          Property_Type__c = 'SFR',
          Number_of_Units__c = 1,
          RecordTypeId = recordTypeId
        )
      );
    }

    property[0].Status__c = 'Active';
    property[0].Refinance_Acquisition__c = 'Refinance';
    property[1].Status__c = 'Active';
    property[2].Payoff_Received_Date__c = system.today();
    Test.startTest();
    try {
      CommunityFundingController.insertProperties(
        oppId,
        JSON.serialize(property)
      );
    } catch (Exception ex) {
    }
    Test.stopTest();
  }

  @isTest
  static void initTest() {
    List<Property__c> props = [
      SELECT Id, Refinance_Acquisition__c
      FROM Property__c
      WHERE Refinance_Acquisition__c = 'Refinance'
      LIMIT 1
    ];
    // if (props != null && !props.isEmpty()) {
    //   props[0].Refinance_Acquisition__c = 'Refinance';
    //   update props[0];
    // }
    test.startTest();

    Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];
    CommunityFundingController.getFundingsInProcess(o.Id);
    CommunityFundingController.getFundingsInProcess('');
    CommunityFundingController.getLOCChartData(o.Id);
    CommunityFundingController.getClosedFundings(o.Id);
    CommunityFundingController.getLoanFundings(o.Id);
    CommunityFundingController.getLOCChartData(null);
    CommunityFundingController.getClosedFundings(null);
    CommunityFundingController.getLoanFundings(null);
    CommunityFundingController.initMatrixScreen(props[0].Id);
    CommunityFundingController.updateRecord(o);
    test.stopTest();
  }
}