force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Vehicle__c/Funding_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Funding Vehicle</label>
    <nameField>
        <label>Funding Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Vehicle__c/fields/Securitization__c.field-meta.xml
<CustomField>
    <fullName>Securitization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Securitization</label>
    <referenceTo>Securitization__c</referenceTo>
    <relationshipLabel>Funding Vehicles</relationshipLabel>
    <relationshipName>Funding_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Securitization__c.field-meta.xml
<CustomField>
    <fullName>Securitization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Securitization</label>
    <referenceTo>Securitization__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Securitized__c.field-meta.xml
<CustomField>
    <fullName>Securitized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate the deal has been securitized in a portfolio</description>
    <label>Securitized?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Securitization__c/Securitization__c.object-meta.xml
<CustomObject>
    <label>Securitization</label>
    <nameField>
        <label>Securitization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securitizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Securitization__c/fields/Funding_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funding Vehicle</label>
    <referenceTo>Funding_Vehicle__c</referenceTo>
    <relationshipLabel>Securitizations</relationshipLabel>
    <relationshipName>Securitizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Securitization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this Securitization</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/securitizationHelperTest.cls
@isTest
public with sharing class securitizationHelperTest {
    @isTest
    public static void testMethod1() {
        Account testAcc = Test_Helper.createBrokerAccount();
        Contact testCtc = Test_Helper.createContact(testAcc);
        Opportunity testDeal = Test_Helper.createTermDeal(testAcc, testCtc);
        testDeal.Securitization__c = null;
        update testDeal;

        Securitization__c testSc = Test_Helper.createSecuritization(); 
        Funding_Vehicle__c testFv = [SELECT Id FROM Funding_Vehicle__c WHERE Securitization__c = :testSc.Id];
        testDeal.Securitized__c = true;
        testDeal.Securitization__c = testSc.Id;

        Test.startTest();
        update testDeal;
        Test.stopTest();


        testSc.Status__c = 'Redeemed';
        testSc.Close_Date__c = (Date) system.today();

        update testSc;

        Opportunity returnedDeal = [SELECT Securitization__c, Securitized__c FROM Opportunity WHERE Id = :testDeal.Id LIMIT 1];
        
    }
}