force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of this Contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Experience</fullName>
            </value>
            <value>
                <fullName>Future Prospect - FICO</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Income</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Liquidity</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Product Type</fullName>
            </value>
            <value>
                <fullName>Future Prospect - Short Term Rental</fullName>
            </value>
            <value>
                <fullName>Deceased/ Not Reachable</fullName>
            </value>
            <value>
                <fullName>Moved/Changed Contact Info</fullName>
            </value>
            <value>
                <fullName>Retired/Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interest_Reserves__c/Interest_Reserves__c.object-meta.xml
<CustomObject>
    <label>Interest Reserve</label>
    <nameField>
        <displayFormat>IR-{00000}</displayFormat>
        <label>Interest Reserves Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Reserves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Reserves__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Interest Reserves</relationshipLabel>
    <relationshipName>Interest_Reserves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interest_Reserves__c/fields/Interest_Reserves_Payment__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reserves_Payment__c</fullName>
    <label>Interest Reserves Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Interest_Reserves__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Interest Reserves</relationshipLabel>
    <relationshipName>Interest_Reserves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Reserves__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reserves__c</fullName>
    <description>Bridge Use</description>
    <label>Interest Reserves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Escrow_Company_text__c.field-meta.xml
<CustomField>
    <fullName>Escrow_Company_text__c</fullName>
    <label>Escrow Company text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Insurance_Company_text__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_text__c</fullName>
    <label>Insurance Company text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Interest_Reserves__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reserves__c</fullName>
    <label>Current Interest Reserves Paid</label>
    <summarizedField>Interest_Reserves__c.Interest_Reserves_Payment__c</summarizedField>
    <summaryForeignKey>Interest_Reserves__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Override_Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>Override_Origination_Fee__c</fullName>
    <label>Override Origination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of this Property/Asset</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Foreclosure</fullName>
            </value>
            <value>
                <fullName>Real Estate Owned</fullName>
            </value>
            <value>
                <fullName>Decision Required</fullName>
            </value>
            <value>
                <fullName>Key Updates Available</fullName>
            </value>
            <value>
                <fullName>On Active NOD List</fullName>
            </value>
            <value>
                <fullName>On Pre-Foreclosure List</fullName>
            </value>
            <value>
                <fullName>Other Special Assets</fullName>
            </value>
            <value>
                <fullName>Redemption Period</fullName>
            </value>
            <value>
                <fullName>Title Claim</fullName>
            </value>
            <value>
                <fullName>Trustee&apos;s Sale Date Set</fullName>
            </value>
            <value>
                <fullName>Rescinded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Caancelled</fullName>
                <isActive>false</isActive>
                <label>Caancelled</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cancelled`</fullName>
                <isActive>false</isActive>
                <label>Cancelled`</label>
            </value>
            <value>
                <fullName>Canelled</fullName>
                <isActive>false</isActive>
                <label>Canelled</label>
            </value>
            <value>
                <fullName>Due Dilligence</fullName>
                <isActive>false</isActive>
                <label>Due Dilligence</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>REO</fullName>
                <isActive>false</isActive>
                <label>REO</label>
            </value>
            <value>
                <fullName>Rent Deposit Bank</fullName>
                <isActive>false</isActive>
                <label>Rent Deposit Bank</label>
            </value>
            <value>
                <fullName>v</fullName>
                <isActive>false</isActive>
                <label>v</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/recordTypes/Bridge_No_Renovation.recordType-meta.xml
<RecordType>
    <fullName>Bridge_No_Renovation</fullName>
    <active>true</active>
    <label>Bridge No Renovation</label>
</RecordType>

force-app/main/default/classes/interestReservesTest.cls
@isTest

private class interestReservesTest {
    @isTest static void interestReservesTest1(){
        test_Helper.createDealLoanNumber();
 Account acc = test_Helper.createAccount();
    Contact cont = test_Helper.createContact(acc);
    Opportunity opp = test_Helper.createOpportunity(acc, cont);
system.debug('deal created'+opp.id);
        
    Property__c property = new Property__c();
    property.Name = 'Test1';
    property.Deal__c = opp.Id;
    property.Escrow_Company_text__c = 'ESCROW';
    property.Insurance_Company_text__c = 'INSURANCE';
    property.Status__c = 'Pending';
    property.Override_Origination_Fee__c = 1000;
    property.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE
        sobjecttype = 'Property__c'
        AND DeveloperName = 'Bridge_No_Renovation'
    ]
    .Id;

    insert property;
    system.debug('prop1 created'+property.id);

    
        Test.startTest();
    Interest_Reserves__c ir = new Interest_Reserves__c();
    				 ir.Property__c = property.id;
    				 ir.Date__c = system.today();
    				 ir.Interest_Reserves_Payment__c = 1000;
    insert ir;
    system.debug('ir created'+ir.id);
        
   Property__c property2 = new Property__c();
    property2.Name = 'Test123';
    property2.Deal__c = opp.Id;
    property2.Escrow_Company_text__c = 'ESCROW';
    property2.Insurance_Company_text__c = 'INSURANCE';
    property2.Status__c = 'Pending';
    property2.Override_Origination_Fee__c = 1000;
    property2.RecordTypeId = [
      SELECT Id
      FROM RecordType
      WHERE
        sobjecttype = 'Property__c'
        AND DeveloperName = 'Bridge_No_Renovation'
    ]
    .Id;

    insert property2;
        
    system.debug('prop2 created'+property2.id);
   Interest_Reserves__c irToUpdate = [SELECT ID, Property__c FROM Interest_Reserves__c WHERE Id =:ir.Id ];
        system.debug('irToUpdate'+irToUpdate.id);
    irToUpdate.Property__c = property2.id;
    update irToUpdate;
test.stopTest();
    }
}