force-app/main/default/objects/Draw__c/Draw__c.object-meta.xml
<CustomObject>
    <description>Renovation draws against the Renovation Holdback</description>
    <label>Draw</label>
    <nameField>
        <label>Renovation Draw #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Draws</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Draw__c/fields/Draw_Number__c.field-meta.xml
<CustomField>
    <fullName>Draw_Number__c</fullName>
    <formula>VALUE(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draw Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Draw__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Bridge Reno Use</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Draws</relationshipLabel>
    <relationshipName>Draws</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DrawHelper.cls
public class DrawHelper {

    public static Map<String, Schema.SObjectField> FIELD_MAP = Schema.SObjectType.Draw__c.fields.getMap();

    /**
    * @author MK Partners, Inc.
    * @date
    * @group
    * @group-content
    * @name beforeInsert
    * @description
    * @param {List<Draw__c>} newList
    * @return void
    **/
    public static void beforeInsert(List<Draw__c> newList){
        Map<Id, List<Draw__c>> propertyMap = new Map<Id, List<Draw__c>>();

        for ( Integer i=0;i<newList.size();i++ ){
            if(!propertyMap.containsKey(newList[i].Property__c)){
                propertyMap.put(newList[i].Property__c, new List<Draw__c>());
            }

            propertyMap.get(newList[i].Property__c).add(newList[i]);

        }

        for(Property__c property : [SELECT Id, (SELECT Id, Draw_Number__c FROM Draws__r WHERE Draw_Number__c != null Order BY Draw_Number__c desc) FROM Property__c WHERE Id IN : propertyMap.keySet()]){
            for(Draw__c draw : propertyMap.get(property.Id)){
                if(String.isBlank(draw.Name)){
                    if(property.Draws__r.size() > 0){
                        draw.Name = String.valueOf(property.Draws__r[0].Draw_Number__c + 1);
                    }else{
                        draw.Name = '1';
                    }
                }
            }
        }

    }

    /**
    * @author MK Partners, Inc.
    * @date
    * @group
    * @group-content
    * @name afterInsert
    * @description
    * @param {List<Draw__c>} newList
    * @return void
    **/
    public static void afterInsert(List<Draw__c> newList){
        for ( Integer i=0;i<newList.size();i++ ){

        }
    }


}